import json
from pathlib import Path
p=Path('work/research-2026');rows=json.loads((p/'general-round76-input.json').read_text());dest=p/'round76-root-incremental-evidence.json';data=json.loads(dest.read_text())
def add(i,description,website,kind,ownership,notes,sources,featured=False):
 r=rows[i];assert r['id'] not in data
 data[r['id']]={'name':r['name'],'description':description,'website':website,'kind':kind,'ownership':ownership,'notes':notes,'review_outcome':'partial' if ownership=='Unknown' else 'confirmed','featured':featured,'sources':[{'url':u,'claim':c} for u,c in sources]}
add(70,'Lancium develops power infrastructure and large data-center campuses for AI computing.','https://lancium.com/','Energy and data-center infrastructure developer','Unknown','Official privacy policy includes Lancium LLC alongside Lancium Inc and affiliates. This verifies the group website but does not establish the exact LLC ownership chain.',[('https://lancium.com/about-us/','Official about page describes power and AI infrastructure business.'),('https://lancium.com/privacy-policy/','Official legal policy explicitly names Lancium LLC as one of covered entities.')])
add(71,'Land O’Lakes is a member-owned agricultural cooperative with businesses spanning farm inputs and consumer foods.','https://www.landolakesinc.com/','Agricultural cooperative','Private company','Member-owned by individual farmers and other cooperatives. The private category denotes member ownership; this is specifically a cooperative. Distinguish it from the separate nonprofit Venture37.',[('https://www.landolakesinc.com/our-impact/investors/structure-governance/','Official governance page states member-owned cooperative and identifies individual farmers and cooperatives as members.')],True)
add(72,'Land Trust Alliance supports land conservation organizations through training, resources and policy advocacy.','https://landtrustalliance.org/','Land conservation association','Nonprofit / tax-exempt','IRS record identifies Land Trust Alliance Incorporated, EIN 04-2751357, as a section 501(c)(3) organization. Distinguish the alliance from its member land trusts.',[('https://landtrustalliance.org/why-land-matters/land-conservation/about-land-trusts','Official site describes land trusts and alliance membership.'),('https://www.irs.gov/pub/irs-soi/eo2.csv','IRS entry EIN 042751357 identifies Land Trust Alliance Incorporated, Washington DC, subsection 03.'),('https://a.storyblok.com/f/120093/x/90cecd6ccc/2021-alliance-990-pd-signed.pdf','Organization Form 990 identifies Land Trust Alliance Inc and charitable activities.')])
add(73,'Lander County is the county government serving communities including Battle Mountain in Nevada.','https://www.landercountynv.org/','County government','Government body','County government, not a city municipality; Nevada jurisdiction confirmed by state employer directory.',[('https://emrb.nv.gov/uploadedFiles/emrbnvgov/content/Directories/Employee_Organizations/2023%20Employer%20Data.pdf','Nevada state directory identifies Lander County government, Battle Mountain address and official domain.')])
add(75,'Landry’s is a privately owned restaurant, hospitality and entertainment group operating multiple brands through subsidiaries and affiliates.','https://www.landrysinc.com/','Restaurant and hospitality group','Private company','Official company description explicitly contrasts its former public listing with current private ownership. Individual restaurant brands and affiliates should retain their legal distinctions.',[('https://www.landrysinc.com/about-us','Official company page describes business, subsidiaries and current privately owned status.')],True)
add(76,'The Lane Construction Corporation builds transportation and civil infrastructure in the United States.','https://www.laneconstruct.com/','Infrastructure construction company','Subsidiary','Official company history identifies Lane as a wholly owned subsidiary of Webuild U.S. Do not label the subsidiary itself publicly traded based on the global parent.',[('https://www.laneconstruct.com/who-we-are/','Official company page identifies infrastructure business and wholly owned Webuild U.S. subsidiary relationship.')])
add(77,'Lane County is the county government providing public services in Lane County, Oregon.','https://www.lanecounty.org/','County government','Government body','Separate from Lane Transit District and similarly named counties outside Oregon.',[('https://www.lanecounty.org/government','Official county government page lists commissioners, administration, health, public works and other public departments.')])
add(78,'Lane Transit District provides public transportation in the Eugene-Springfield area and surrounding communities in Oregon.','https://www.ltd.org/','Public transit district','Government body','Special-purpose district enacted by Oregon; seven-member board appointed by the governor. Separate from Lane County government.',[('https://www.ltd.org/about/board-of-directors/','Official district page establishes statutory district status, governor-appointed board and service-area governance.')])
dest.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('Saved',len(data),'evidence profiles')
