import json
from pathlib import Path
p=Path('work/research-2026');rows=json.loads((p/'general-round76-input.json').read_text());dest=p/'round76-root-incremental-evidence.json';data=json.loads(dest.read_text())
def add(i,description,website,kind,ownership,notes,sources):
 r=rows[i];assert r['id'] not in data
 data[r['id']]={'name':r['name'],'description':description,'website':website,'kind':kind,'ownership':ownership,'notes':notes,'review_outcome':'partial' if ownership=='Unknown' else 'confirmed','featured':False,'sources':[{'url':u,'claim':c} for u,c in sources]}
sec='https://www.sec.gov/Archives/edgar/data/1521036/000119312526336795/lnth-20260630.htm'
merger='https://investor.lantheus.com/node/17091'
add(82,'Lantheus is a radiopharmaceutical and diagnostic-imaging business headquartered in Massachusetts.','https://www.lantheus.com/','Radiopharmaceutical business','Unknown','The short filing name does not distinguish Lantheus Holdings Inc from its operating subsidiaries. SEC uses Lantheus as a collective group term; do not merge with the exact Holdings or Medical Imaging entities without filing-level evidence.',[(sec,'SEC quarterly report distinguishes collective Lantheus references from exact parent and subsidiaries.'),(merger,'Official announcement identifies radiopharmaceutical business, headquarters and corporate website.')])
add(83,'Lantheus Holdings, Inc. is the publicly traded parent of a radiopharmaceutical and diagnostic-imaging group.','https://www.lantheus.com/','Radiopharmaceutical holding company','Public company','Nasdaq LNTH. An August 2026 agreement with Curium anticipates closing in the first half of 2027; the announcement expressly says Lantheus remains publicly traded until closing. Do not mark the proposed acquisition completed.',[(sec,'June 2026 quarterly report identifies exact public parent and its subsidiaries.'),(merger,'August 3 2026 announcement states Nasdaq listing, proposed acquisition and expected 2027 closing.')])
add(84,'Lantheus Medical Imaging, Inc. is an operating subsidiary of Lantheus Holdings involved in the group’s medical-imaging business.','https://www.lantheus.com/','Medical imaging company','Subsidiary','June 2026 SEC report explicitly identifies Lantheus Medical Imaging Inc as wholly owned by Lantheus Holdings. The subsidiary is not itself the Nasdaq-listed company. Shared group website.',[(sec,'SEC report explicitly identifies exact subsidiary and wholly owned relationship to Lantheus Holdings.'),('https://www.lantheus.com/contact/','Official group contact page provides medical-imaging product and corporate contacts.')])
for i in [87,88]:
 add(i,'Large Urology Group Practice Association (LUGPA) is a nonprofit trade association representing independent urology practices in the United States.','https://www.lugpa.org/','Medical practice trade association','Nonprofit / tax-exempt','Official source explicitly expands LUGPA to the full name. Two directory name groups appear to identify the same association; compare source filing identities before merging their records.',[('https://www.lugpa.org/media-contacts','Official media page expands acronym and explicitly identifies nonprofit urology trade association.'),('https://www.lugpa.org/about-lugpa','Official about page identifies nonprofit association and mission.')])
dest.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');(p/'round76-lugpa-dedupe-followup.json').write_text(json.dumps({'indices':[87,88],'ids':[rows[i]['id'] for i in [87,88]],'finding':'Official association name and acronym establish strong duplicate candidate. Filing identity comparison and actual merge still pending.'},indent=2)+'\n');print('Saved',len(data),'evidence profiles')
