import json
from pathlib import Path
p=Path('work/research-2026');rows=json.loads((p/'general-round76-input.json').read_text());dest=p/'round76-root-incremental-evidence.json';data=json.loads(dest.read_text())
def add(i,description,website,kind,ownership,notes,sources,featured=False):
 r=rows[i];assert r['id'] not in data
 data[r['id']]={'name':r['name'],'description':description,'website':website,'kind':kind,'ownership':ownership,'notes':notes,'review_outcome':'partial' if ownership=='Unknown' else 'confirmed','featured':featured,'sources':[{'url':u,'claim':c} for u,c in sources]}
add(95,'LaSalle General Hospital provides hospital and related healthcare services in Jena, Louisiana, as part of Hospital Service District No. 2 of LaSalle Parish.','https://www.lasallegeneralhospital.com/','Public district hospital','Government body','The official board page identifies the hospital and nursing home as names used by Hospital Service District #2. They operate as separate enterprise funds within one governmental unit.',[('https://www.lasallegeneralhospital.com/about/','Official history describes district creation and governmental structure.'),('https://www.lasallegeneralhospital.com/board-meeting-remote-access-request/','Official board information explicitly links hospital name to public hospital district.'),('https://ldh.la.gov/directory/detail/1845','Louisiana health department verifies hospital and Jena address.')])
add(96,'Laser Marking Technologies, LLC makes industrial laser marking, engraving and cutting equipment in Caro, Michigan.','https://lasermarktech.com/','Industrial laser equipment manufacturer','Unknown','Official website establishes exact LLC and manufacturing location. American-owned wording does not establish private versus subsidiary ownership; exact ownership remains unverified. Distinguish from Lasertechnics Marking Corporation.',[('https://lasermarktech.com/about/','Official about page identifies exact LLC, equipment and Caro headquarters.'),('https://lasermarktech.com/lmt-connect-privacy-policy/','July 2026 legal policy identifies Laser Marking Technologies LLC as service operator.')])
add(97,'Laser Shot develops firearm-training simulators and live-fire training facilities for military, law enforcement and commercial customers.','https://lasershot.com/','Training simulation equipment company','Unknown','Official source identifies Texas engineering operations and simulation business. Current ownership is unverified; do not confuse with the UK Lasershot clay-shooting business.',[('https://lasershot.com/about-us/','Official company page describes customers, simulators and Sugar Land Texas engineering facility.')])
add(98,'Lash OpCo, LLC operates under the Performance Beauty Group name, investing in and supporting beauty and personal-care brands.','https://performance-beauty.com/','Beauty brand investment and operating company','Unknown','Canadian government trademark journal identifies Lash Opco LLC as applicant for Performance Beauty Group. Exact current ownership chain remains unverified; do not substitute a single portfolio brand or infer ownership from a lender investment.',[('https://publications.gc.ca/collections/collection_2025/opic-cipo/RG42-2-72-3671-eng.pdf','Government trademark journal page 1638 links Lash Opco LLC to Performance Beauty Group mark and beauty-industry business services.'),('https://performance-beauty.com/','Official group site describes investment and support for beauty brands and Frisco Texas contact.')])
add(99,'Lasko Products, LLC makes and sells home-comfort products including portable fans, heaters and air-treatment equipment.','https://lasko.com/','Home appliance manufacturer','Unknown','Official privacy policy establishes exact LLC. The business began family-owned, but that history does not establish current ownership. Comvest announced a 2016 acquisition of Lasko Holdings; the present LLC ownership chain remains unverified.',[('https://lasko.com/pages/privacy-policy','Official legal policy explicitly names Lasko Products LLC.'),('https://lasko.com/pages/careers','Official page describes home-comfort business, brands and locations.'),('https://comvestprivateequity.com/comvest-partners-acquires-lasko-holdings/','Investor announcement documents historical 2016 Lasko Holdings acquisition, not proof of current exact LLC ownership.')],True)
dest.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('Saved',len(data),'evidence profiles')
