import json
from pathlib import Path
p=Path('work/research-2026'); rows=json.loads((p/'general-round76-input.json').read_text()); dest=p/'round76-root-incremental-evidence.json'; data=json.loads(dest.read_text())
def add(i,description,website,kind,ownership,notes,sources):
 r=rows[i];assert r['id'] not in data
 data[r['id']]={'name':r['name'],'description':description,'website':website,'kind':kind,'ownership':ownership,'notes':notes,'review_outcome':'partial' if ownership=='Unknown' else 'confirmed','featured':False,'sources':[{'url':u,'claim':c} for u,c in sources]}
add(56,'Lake Area Technical College, formerly Lake Area Technical Institute, is a public technical college in Watertown, South Dakota.','https://www.lakeareatech.edu/','Public technical college','Government body','The institution changed its name on July 1, 2020. Preserve the historical filing name; distinguish the college from its fundraising foundation.',[('https://www.lakeareatech.edu/lake-area-tech-officially-becomes-a-college/','Official announcement explicitly links Institute and College names, effective July 1, 2020.'),('https://www.lakeareatech.edu/governor-daugaard-signs-tech-school-board-bill/','Official announcement describes state legislation and governor-appointed board overseeing technical colleges.')])
add(57,'Lake Carriers’ Association represents operators of U.S.-flag cargo vessels on the Great Lakes.','https://lcaships.com/','Shipping trade association','Nonprofit / tax-exempt','IRS EIN 34-0347260 matches the official Westlake, Ohio address at 25651 Detroit Road. Trade association, not an individual shipping operator.',[('https://lcaships.com/about/history/','Official history describes represented fleet, membership and Westlake address.'),('https://www.irs.gov/pub/irs-soi/eo2.csv','IRS exempt organizations record for EIN 340347260 identifies Lake Carriers Association at matching street and city; subsection 06.')])
add(59,'Lake Charles Harbor & Terminal District operates the Port of Lake Charles, a Louisiana deepwater port with marine terminals and industrial properties.','https://portlc.com/','Port authority','Government body','Port of Lake Charles is the public-facing name of this Louisiana public district; it is not a privately owned terminal company.',[('https://portlc.com/our-port/','Official port page states exact district name, public-body status and operations.'),('https://wwwcfprd.doa.louisiana.gov/boardsandcommissions/viewBoard.cfm?board=115','State directory identifies district as local political subdivision and links official port website.')])
add(60,'Lake Charles Methanol II, LLC is developing a proposed natural-gas-to-methanol manufacturing project in Lake Charles, Louisiana.','https://www.lakecharlesmethanol.com/','Industrial project developer','Unknown','The company explicitly distinguishes itself from Lake Charles Methanol, LLC, which has different ownership. Do not merge the two. Production and construction targets are company plans, not evidence of an operating plant. Exact ownership remains unverified.',[('https://www.lakecharlesmethanol.com/','Project website describes planned methanol facility and future construction target.'),('https://www.lakecharlesmethanol.com/new-page-1','Company correction specifies exact LLC name and warns that Lake Charles Methanol, LLC is a separate entity with different ownership.')])
add(61,'Lake Charles Regional Airport provides commercial air service for southwest Louisiana and is governed by the Airport Authority of Airport District No. 1 of Calcasieu Parish.','https://flylakecharles.com/','Public airport','Government body','Official authority page describes five unpaid members appointed by the Calcasieu Parish Police Jury. Distinguish from Chennault International Airport.',[('https://flylakecharles.com/airport-authority-board/','Official airport page establishes governing district, parish appointment process and commercial air service.')])
dest.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('Saved',len(data),'evidence profiles')
