import json
from pathlib import Path
p=Path('work/research-2026');rows=json.loads((p/'general-round76-input.json').read_text());dest=p/'round76-root-incremental-evidence.json';data=json.loads(dest.read_text())
def add(i,description,website,kind,ownership,notes,sources,featured=False):
 r=rows[i];assert r['id'] not in data
 data[r['id']]={'name':r['name'],'description':description,'website':website,'kind':kind,'ownership':ownership,'notes':notes,'review_outcome':'partial' if ownership=='Unknown' else 'confirmed','featured':featured,'sources':[{'url':u,'claim':c} for u,c in sources]}
add(1,'KPMG is a professional-services organization providing audit, tax and advisory services through independent member firms.','https://kpmg.com/','Professional services network','Unknown','The abbreviated filing name does not establish the exact member firm. KPMG LLP in the U.S. is a Delaware partnership; KPMG International Limited is a separate English company. Do not assume the global network is one corporation or transfer one member firm’s ownership to the unspecified client.',[('https://kpmg.com/kpmg-us/content/dam/kpmg/pdf/2026/2025-eu-supplement.pdf','Current KPMG legal-governance supplement identifies independent member-firm arrangement and separate U.S. firm.'),('https://kpmg.com/kpmg-us/content/dam/kpmg/pdf/2023/2022-kpmgllp-transparency-report.pdf','U.S. firm report describes audit tax advisory services and partner ownership of that specific firm.')],True)
add(25,'Kymera International develops and manufactures specialty metal powders, advanced materials and surface coatings for industrial applications.','https://kymerainternational.com/','Specialty materials manufacturer','Private company','Company sources identify ownership by affiliates of Palladium Equity Partners since 2018; a July 2026 company announcement confirms the continuing Palladium relationship. Distinguish from Kymeta satellite antennas.',[('https://kymerainternational.com/kymera-to-acquire-fiven/','Company acquisition announcement explicitly identifies Palladium affiliate ownership and materials business.'),('https://kymerainternational.com/kymera-international-appoints-willson-ropp-as-chief-executive-officer/','July 2026 company announcement identifies materials business and ongoing work with Palladium leadership.')])
add(51,'LAC Management LLC provides management services for Lithium Americas’ Thacker Pass lithium development project.','https://www.lithiumamericas.com/','Lithium project management company','Subsidiary','Nevada LLC listed as wholly owned by Lithium Americas in its 2025 year-end corporate structure. The public LAC ticker belongs to the parent, not this LLC. Website is the parent group site.',[('https://www.sec.gov/Archives/edgar/data/1966983/000119312526207573/lac-10k-ars-2026.pdf','2026 annual report lists LAC Management LLC Nevada as 100% owned subsidiary.'),('https://www.sec.gov/Archives/edgar/data/1966983/000119312524283702/d875462dex992.htm','Executed management services agreement identifies exact LLC and role on Thacker Pass.'),('https://www.lithiumamericas.com/','Official parent group site identifies lithium development business.')])
dest.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('Saved',len(data),'evidence profiles')
