import json
from pathlib import Path
p=Path('work/research-2026');rows=json.loads((p/'general-round76-input.json').read_text());dest=p/'round76-root-incremental-evidence.json';data=json.loads(dest.read_text())
def add(i,description,website,kind,ownership,notes,sources):
 r=rows[i];assert r['id'] not in data
 data[r['id']]={'name':r['name'],'description':description,'website':website,'kind':kind,'ownership':ownership,'notes':notes,'review_outcome':'partial' if ownership=='Unknown' else 'confirmed','featured':False,'sources':[{'url':u,'claim':c} for u,c in sources]}
add(46,'Laboratory Corporation of America is a filing name associated with Labcorp’s laboratory testing business.','https://www.labcorp.com/','Laboratory testing business','Unknown','The abbreviated name needs exact-entity resolution. Since the May 2024 reorganization, Labcorp Holdings Inc is the public parent and Laboratory Corporation of America Holdings is its subsidiary. Do not infer the short name is the current listed parent or merge it automatically.',[('https://www.labcorp.com/compliance/privacy/privacy-notice','Current official legal notice distinguishes Labcorp Holdings Inc and Laboratory Corporation of America Holdings.'),('https://www.sec.gov/Archives/edgar/data/920148/000092014824000063/lh-20240517.htm','SEC filing documents completed holding company reorganization.')])
add(47,'Laboratory Corporation of America Holdings is a Labcorp laboratory-services subsidiary beneath Labcorp Holdings Inc.','https://www.labcorp.com/','Laboratory services company','Subsidiary','Previously the public parent; became wholly owned by newly formed Labcorp Holdings Inc on May 17, 2024. NYSE LH now belongs to Labcorp Holdings Inc. Retain exact legal identity and historical filing name.',[('https://www.sec.gov/Archives/edgar/data/920148/000092014824000063/lh-20240517.htm','Completed reorganization filing establishes exact former parent as subsidiary of new listed parent.'),('https://www.labcorp.com/compliance/privacy/privacy-notice','Current company legal notice retains Laboratory Corporation of America Holdings within controlled subsidiaries.'),('https://www.sec.gov/Archives/edgar/data/920148/000092014826000175/lh-20260630.htm','2026 quarterly report identifies current reporting entity and LCAH abbreviation.')])
add(85,'LANXESS develops and manufactures specialty chemicals, with German headquarters and U.S. operations headquartered in the Pittsburgh area.','https://lanxess.com/','Specialty chemicals business','Unknown','The filing name omits legal form. LANXESS AG and LANXESS Corporation are distinct parent and U.S. entities; do not label the unspecified client publicly traded until the exact contracting entity is established.',[('https://lanxess.com/en-us/media/press-releases/2026/02/lanxess-to-retain-regional-hq-in-pittsburgh','Current company release describes specialty chemicals business and distinguishes LANXESS AG from LANXESS Corporation.'),('https://lanxess.com/en/company/organization/locations/locations-worldwide','Official location directory names operating entities and regional headquarters.')])
dest.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('Saved',len(data),'evidence profiles')
