import json
from pathlib import Path
p=Path('work/research-2026');rows=json.loads((p/'general-round76-input.json').read_text());dest=p/'round76-root-incremental-evidence.json';data=json.loads(dest.read_text())
def add(i,description,website,kind,ownership,notes,sources):
 r=rows[i];assert r['id'] not in data
 data[r['id']]={'name':r['name'],'description':description,'website':website,'kind':kind,'ownership':ownership,'notes':notes,'review_outcome':'confirmed','featured':False,'sources':[{'url':u,'claim':c} for u,c in sources]}
add(86,'Laramide Resources Ltd. explores and develops uranium projects in the United States and Australia.','https://laramide.com/','Uranium exploration and development company','Public company','Official investor page lists TSX and ASX ticker LAM and U.S. OTCQX trading. Development assets should not be described as currently producing mines without project-specific evidence.',[('https://laramide.com/about/about-us/','Official company page identifies uranium project portfolio.'),('https://laramide.com/investors/investor-centre/','Official investor page identifies stock exchange listings.')])
add(89,'Larimer County is the county government providing public services in northern Colorado.','https://www.larimer.gov/','County government','Government body','Colorado jurisdiction; county is a constitutional subdivision of state government.',[('https://www.larimer.gov/about-larimer-county/county-structure-organizational-chart','Official county page explains legal structure and statutory public responsibilities.'),('https://www.larimer.gov/departments','Official department list explicitly identifies Larimer County Colorado.')])
add(91,'Las Vegas Convention and Visitors Authority promotes southern Nevada tourism and conventions and oversees convention facilities.','https://www.lvcva.com/','Tourism and convention authority','Government body','Public authority funded in part by room taxes, not a private tourism trade association. Preserve distinction from individual hotels and casino operators.',[('https://www.lvcva.com/governance/funding-finance/','Official authority finance page provides public financial reporting and convention-center financing information.'),('https://res.cloudinary.com/simpleview/image/upload/v1/clients/lasvegas/FY_2015_PAFR_8f522ae4-31fc-4b9e-a37b-ee8610632f36.pdf','Authority annual report identifies government agency established by state law, room-tax funding and autonomous board.')])
add(93,'Las Vegas Valley Water District is a public water utility supplying the Las Vegas Valley in Nevada.','https://www.lvvwd.com/','Public water district','Government body','Governed by Clark County Commissioners. Its not-for-profit utility description does not mean it is a private charitable nonprofit; distinguish from Southern Nevada Water Authority and other districts it operates.',[('https://www.lvvwd.com/about/water-district/index.html','Official history identifies district, water service and state legislation enabling its creation.'),('https://www.lvvwd.com/about/board/index.html','Official governance page identifies Clark County Commissioners as district board.')])
add(94,'Las Virgenes–Triunfo Joint Powers Authority manages shared wastewater and recycled-water infrastructure for two water districts in southern California.','https://www.lvmwd.gov/the-district','Joint powers water authority','Government body','Joint authority of Las Virgenes Municipal Water District and Triunfo Water & Sanitation District. Website is hosted by a member district; do not merge their separate lobbying records or transfer the member logo automatically.',[('https://www.lvmwd.gov/the-district','Member district official site identifies joint authority established in 1964.'),('https://www.lvmwd.gov/january-15-2026-las-virgenes-triunfo-joint-powers-authority-sets-leadership-for-2026','Current official announcement confirms joint authority, member districts and leadership.'),('https://www.ventura.lafco.ca.gov/wp-content/uploads/2022/02/TWSD-MSR-2022-02-16.pdf','Government service review explains authority ownership and operation of shared wastewater infrastructure.')])
dest.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('Saved',len(data),'evidence profiles')
