import json
from pathlib import Path
p=Path('work/research-2026');rows=json.loads((p/'general-round76-input.json').read_text());dest=p/'round76-root-incremental-evidence.json';data=json.loads(dest.read_text())
def add(i,description,website,kind,ownership,notes,sources,featured=False):
 r=rows[i];assert r['id'] not in data
 data[r['id']]={'name':r['name'],'description':description,'website':website,'kind':kind,'ownership':ownership,'notes':notes,'review_outcome':'partial' if ownership=='Unknown' else 'confirmed','featured':featured,'sources':[{'url':u,'claim':c} for u,c in sources]}
add(62,'Lake Erie Tobacco Company manufactures tobacco products; a 2025 California regulator notice identifies its Natural Harvest cigarette brand.','','Tobacco manufacturer','Unknown','Independent government records support the manufacturer identity. Current official website and ownership remain unverified; do not assign the similarly named Seneca Foods or a general Seneca brand website.',[('https://oag.ca.gov/system/files/media/directory-added-notice-01172025.pdf','California Attorney General notice identifies Lake Erie Tobacco Company as manufacturer of Natural Harvest cigarette styles.')])
add(63,'Lake Providence Port Commission governs a public Mississippi River port in East Carroll Parish, Louisiana.','http://www.lakeprovidenceport.com','Port authority','Government body','State law establishes the commission and local government appointments. The website is listed in the state transportation department’s public-port directory; present availability requires checking.',[('https://legis.la.gov/legis/Law.aspx?d=91891','Louisiana statute creates exact commission with parish and town appointed members.'),('https://dotd.la.gov/media/qqdkbe0t/2024-lla-profiles-of-public-ports.pdf','State port profile identifies authority, location and official domain.')])
add(64,'Lakeland Regional Health is a nonprofit healthcare system based in Lakeland, Florida, providing hospital and outpatient care.','https://www.mylrh.org/','Health system','Nonprofit / tax-exempt','Distinguish the operating health system from its fundraising foundation and from the former Spectrum Health Lakeland in Michigan. Florida regulator identifies the medical center licensee and its health-system parent.',[('https://www.mylrh.org/service-to-the-community/','Official system page explicitly states not-for-profit status.'),('https://www.mylrh.org/about-us/','Official history and services establish Lakeland Florida health system.'),('https://quality.healthfinder.fl.gov/Facility-Provider/Profile/?LID=9956','Florida regulator lists nonprofit licensee Lakeland Regional Medical Center Inc and controlling organization Lakeland Regional Health Systems Inc.')])
add(66,'St. Louis Lambert International Airport is the City of St. Louis-owned airport serving the St. Louis region in Missouri.','https://www.flystl.com/','Public airport','Government body','Normalize the display spelling while retaining Lambert-st Louis International Airport as the filing name. City ownership is stated in a recent public bond hearing notice.',[('https://www.stlouis-mo.gov/events/eventdetails.cfm?Event_ID=55079','City public notice states airport is owned and operated by the city and provides Lambert Boulevard address.'),('https://www.flystl.com/about/history/curtiss-wright-aeroplane-factory/history/','Official airport history establishes Lambert identity and city acquisition.')])
add(67,'Lancaster Airport Authority owns and operates Lancaster Airport in Lititz, Pennsylvania, serving general aviation and commercial air travel.','https://lancasterairport.com/','Airport authority','Government body','Joint municipal authority of Lancaster city and county in Pennsylvania, not a Lancaster airport in another state.',[('https://www.cityoflancasterpa.gov/boards-commissions-and-authorities/airport-authority/','City confirms joint authority, airport responsibilities and official domain.'),('https://lancasterairport.com/contact-us/','Official authority site matches 500 Airport Road Suite G Lititz address.')])
add(68,'The Marzetti Company, formerly Lancaster Colony Corporation, manufactures specialty foods including dressings, dips, frozen breads and noodles.','https://www.marzetticompany.com/','Food manufacturer','Public company','Renamed July 1, 2025; current Nasdaq ticker MZTI replaces LANC. Preserve Lancaster Colony as historical filing alias. Distinguish the listed parent from subsidiaries carrying the T. Marzetti name.',[('https://s206.q4cdn.com/621856538/files/doc_news/2025/Jul/01/MZTI-7-1-25.pdf','Company announcement links Lancaster Colony to new Marzetti name and ticker.'),('https://www.sec.gov/Archives/edgar/data/57515/000005751526000019/mzti-20260630.htm','Fiscal 2026 SEC annual report identifies The Marzetti Company and Nasdaq MZTI listing.'),('https://www.marzetticompany.com/','Official corporate website identifies current company and products.')],True)
add(69,'Lancaster County is the county government serving Lincoln and surrounding communities in Nebraska.','https://www.lancaster.ne.gov/','County government','Government body','Nebraska jurisdiction; distinguish from Lancaster County in Pennsylvania and other states.',[('https://www.lancaster.ne.gov/commiss/index.htm','Official county board page identifies Nebraska legislative priorities and governmental budget, tax and property responsibilities.'),('https://www.lancaster.ne.gov/','Official Lancaster County Nebraska website.')])
dest.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('Saved',len(data),'evidence profiles')
