import json,pathlib,copy
r=pathlib.Path('work/research-2026');site=pathlib.Path('lobbying-map');original={x['id']:x for x in json.load(open(r/'root-next-40.json'))};out={}
for k,name,desc,url in [('0ef3eadadc2b7ee2','FWC2026 US, Inc. — FIFA World Cup','FIFA’s U.S. subsidiary supporting operations for the 2026 World Cup.','https://www.fifa.com/'),('0f67309eb86c9563','Odyssey House Louisiana','Provides substance-use treatment, primary and behavioral healthcare, and housing support in Louisiana.','https://www.ohlinc.org/')]:
 x=original[k];d=x['tax_evidence'];v={'name':name,'description':desc,'kind':'Nonprofit / initiative','ownership':'FIFA subsidiary' if k=='0ef3eadadc2b7ee2' else 'Not applicable','website':url,'website_status':'verified','review_outcome':'confirmed','status':'sourced','as_of':'2026-09-05','checked_at':'2026-09-05','featured':k=='0ef3eadadc2b7ee2','legal_form':'','logo_url':'','logo_kind':'','logo_source_url':'','logo_status':'unresolved','sources':copy.deepcopy(x['registry_profile']['sources']),'notes':'','identity_evidence':'EIN '+d['ein']+'; filed legal name '+d['organization_name']+'. Original lobbying/registry identity evidence retained; official sources establish the activity.'}
 v['sources'].append({'label':'Form 990 identity','url':d['source_url'],'claim':'Return identifies '+d['organization_name']+' with EIN '+d['ein']+'.'})
 if k=='0ef3eadadc2b7ee2':
  v['sources'] += [{'label':'FIFA 2026 privacy notice','url':'https://fanspotlight.fifa.com/privacy-notice','claim':'FIFA identifies FWC2026, US, Inc. as its subsidiary in the United States for the 2026 World Cup.'},{'label':'FIFA subsidiary ownership — 2022 report','url':'https://publications.fifa.com/en/annual-report-2022/finances/finance/notes-2022/35-consolidated-subsidiaries-2022/','claim':'FIFA listed FWC2026 US, Inc. as a 100%-owned service company at December 31, 2022. This percentage is historical.'}]
  v['notes']='This is the U.S. World Cup operating entity, not the entire FIFA organization. The displayed icon is FIFA group branding. Highlighted because of its recognizable World Cup role.';a=json.load(open(r/'website-cache'/f'{k}.json'))
  for field in ['logo_url','logo_kind','logo_source_url']:v[field]=a[field]
  v['logo_status']='official_site_asset'
 else:
  v['sources'] += [{'label':'Odyssey House official services','url':'https://www.ohlinc.org/services','claim':'Lists substance-use treatment, primary and behavioral healthcare, and housing services.'},{'label':'Odyssey House official mission','url':'https://www.ohlinc.org/our-mission','claim':'Identifies Odyssey House Louisiana and its continuum of healthcare and recovery services.'}]
  v['notes']='The tax return points to additional mission detail; the description is sourced from the official services and mission pages.'
 out[k]=v
(r/'resolved-two-profiles.json').write_text(json.dumps(out,indent=2)+'\n')
p=json.load(open(r/'reviewed.json'));v=p['5015797740422e34'];v['description']='Patient financial-assistance nonprofit that announced a merger with Patient Advocate Foundation in March 2026.';v['notes']='The combined organization operates under the Patient Advocate Foundation name. The original lobbying identity and filings are preserved; these records have not been merged with another directory entity.';v['website_status']='verified';v['review_outcome']='confirmed';v['sources'].append({'label':'Official PAN and PAF merger announcement','url':'https://www.patientadvocate.org/article/patient-advocate-foundation-and-pan-foundation-announce-merger-to-create-nations-most-comprehensive-nonprofit-dedicated-to-helping-patients-navigate-access-and-afford-care/','claim':'Announces the merger and identifies the combined organization as Patient Advocate Foundation.'});v['sources'].append({'label':'PAN Foundation — March 2026 merger','url':'https://www.panfoundation.org/about-us','claim':'Confirms the merger announcement date and explains the transition of patient-support programs.'})
for v in p.values():
 if 'static.parastorage.com/client/pfavico.ico' in v.get('logo_url',''):
  v.update(logo_url='',logo_kind='',logo_source_url='',logo_status='unresolved');v['sources']=[s for s in v['sources'] if s.get('label') not in ['Official website branding','Official website icon']]
for f in [r/'reviewed.json',site/'research/reviewed-2026.json']:f.write_text(json.dumps(p,indent=2)+'\n')
