from pathlib import Path
p=Path('work/research-2026/research31c_root.py');s=p.read_text();tail="""
add(1,'CCMA, LLC','Trades and distributes metals, ores, alloys and related raw materials.','https://www.ccmallc.com/',sources=[('https://lda.gov/api/v1/clients/70612/?format=json','New York client reports materials and metals trading.'),('https://scalca.blob.core.windows.net/2024/CCMA%2C_LLC_2024_CzZglC.pdf','Company supply-chain report identifies privately owned Getzville trading house.')],notes='Company report supports identity; current website fetch blocked. Specific current owners not verified.',legal='LLC')
add(6,'Cecile Buonocore and other American victims of the Rome airport attack','Individuals represented in lobbying concerning relief for victims of the Rome airport attack.','',kind='Represented individuals',own='Not applicable',notes='Filing names individuals and a represented group, not a company. No separate organization website or logo verified.',outcome='partial')
add(8,'Cedar Lake','Kentucky nonprofit providing residential and community services for adults with intellectual and developmental disabilities.','https://cedarlake.org/',kind='Disability services nonprofit',own='Nonprofit / tax-exempt',sources=[('https://cedarlake.org/about-us/','Official history identifies nonprofit faith-based Kentucky service organization.'),('https://lda.gov/api/v1/clients/70876/?format=json','LDA identifies Kentucky client Cedar Lake.')],notes='Exact legal entity among Cedar Lake Lodge and related service entities remains unresolved.',outcome='partial')
add(9,'Cedar Port Navigation and Improvement District','Texas district sponsoring navigation infrastructure and a proposed channel-deepening project serving Cedar Port.','https://www.cedarportchannelproject.com/home',kind='Navigation district',own='Government body',sources=[('https://www.cedarportchannelproject.com/home','District project site identifies district sponsor and proposed feasibility study.'),('https://mdswater.com/districts/chambers-county-id-1/','District service provider identifies district and public services.')],notes='Project website linked; proposed deep-water connection is not described as completed. Project or contractor logo held.')
add(10,'Cedar Valley Medical Specialists, P.C.','Physician practice providing specialty medical care in Waterloo and surrounding Cedar Valley communities in Iowa.','https://cedarvalleymedical.com/',kind='Medical practice',own='Private company',sources=[('https://cedarvalleymedical.com/about/','Official profile explicitly states locally owned and physician-owned independent practice.')],notes='Not the similarly named Utah medical clinic.',legal='Professional corporation')
for i in [12,14]:
 add(i,'Cedars-Sinai' if i==12 else 'Cedars-Sinai Medical Center','Nonprofit healthcare organization providing patient care, medical research and professional education in Los Angeles.','https://www.cedars-sinai.org/',kind='Nonprofit healthcare organization',own='Nonprofit / tax-exempt',sources=[('https://www.cedars-sinai.org/about.html','Official profile identifies nonprofit medical center and healthcare services.')],notes='Broad Cedars-Sinai label is not automatically merged across the health system, medical center and medical foundation.' if i==12 else 'Medical Center label kept separate from other health-system legal entities.',outcome='partial' if i==12 else 'confirmed',featured=True)
add(15,'CEDIA','Association providing advocacy, training, standards and certification for smart-home technology professionals.','https://cedia.org/',kind='Trade association',sources=[('https://cedia.org/smart-home-professionals/about-us/','Official association page describes smart-home professionals and industry services.')],notes='Distinct from the European agronomists association also abbreviated CEDIA. Exact tax classification unverified.')
add(16,'Cedrus Bank S.A.L.','Lebanese bank providing banking services to individual and business customers.','https://www.cedrusbank.com/',kind='Bank',own='Subsidiary',sources=[('https://www.cedrusbank.com/shareholders-cedrus-bank-lebanon','Bank shareholder page identifies Cedrus Invest Bank SAL as majority shareholder.'),('https://www.cedrusbank.com/Sub.aspx?lang=1&pageid=28','Official bank history and services.')],notes='Majority shareholder is Cedrus Invest Bank; other shareholders remain. Website disclosure lacks a clear effective date, so percentages are not presented as independently current.',legal='S.A.L.')
add(20,'Cellcube Energy Systems (filing label)','Energy-storage client associated with CellCube vanadium-flow battery systems.','https://www.cellcube.com/',sources=[('https://lda.gov/api/v1/clients/71635/?format=json','Colorado client reports energy storage systems.'),('https://www.cellcube.com/about-us/','Official brand describes long-duration flow battery systems.'),('https://www.cellcube.com/legal-information/','Legal notice identifies Energy Storage entities rather than exact Energy Systems label.')],notes='Exact legal connection to current CellCube operating entities remains unresolved; brand logo held.')
add(21,'Cellebrite Federal Solutions, Inc.','Provides digital forensic and investigative technology to U.S. federal government customers.','https://www.cellebritefsi.com/',own='Subsidiary',sources=[('https://www.cellebritefsi.com/about-us/','Official company profile identifies federal subsidiary and services.'),('https://www.sec.gov/Archives/edgar/data/1854587/000162828026013790/cele-20251231.htm','Annual report identifies ownership by Cellebrite Inc.')],notes='Separate from Cellebrite Inc and publicly listed Cellebrite DI Ltd; no parent ticker assigned.')
add(22,'Cellebrite Inc.','U.S. subsidiary providing digital investigative and intelligence technology.','https://cellebrite.com/',own='Subsidiary',sources=[('https://www.sec.gov/Archives/edgar/data/1854587/000162828026013790/cele-20251231.htm','Annual report lists Delaware subsidiary and its federal-solutions subsidiary.')],notes='Not the publicly listed Israeli parent Cellebrite DI Ltd. Group website linked; parent logo held.')
add(23,'Celligence LLC','Develops AI-enabled mortgage and financial-services technology, including AngelAi.','https://celligence.com/',sources=[('https://www.celligence.com/privacy','Official privacy policy identifies Celligence LLC as service provider.'),('https://lda.gov/api/v1/clients/73527/?format=json','Puerto Rico fintech LLC client.')],notes='Founder and management titles do not establish equity ownership.',legal='LLC')
add(24,'CelLink Corporation','Develops flexible electrical circuits and interconnects for vehicle wiring, batteries and other power applications.','https://www.cellinktechnologies.com/',sources=[('https://lda.gov/api/v1/clients/63560/?format=json','California client describes flexible harnesses for automotive and battery industries.'),('https://www.cellinktechnologies.com/','Official CelLink Technologies site describes corresponding products.')],notes='Not the bioprinting business CELLINK. Exact current relationship between Corporation and Technologies branding remains partial; logo held.')
add(27,'Celltrion USA, Inc.','U.S. pharmaceutical subsidiary commercializing biologic medicines.','https://www.celltrionusa.com/',own='Subsidiary',sources=[('https://www.celltrionusa.com/aboutus/philosophy/','Current company overview explicitly identifies Celltrion U.S. subsidiary.')],notes='Separate from listed Korean parent; no parent ticker assigned. Historical 2023 ownership notice predates group restructuring.')
add(28,'Celonis, Inc.','Provides process-intelligence software that helps organizations analyze and improve business operations.','https://www.celonis.com/',sources=[('https://www.celonis.com/faqs','Official FAQ describes process-intelligence software and privately held group.'),('https://careers.celonis.com/legal/privacy-notice','Official notice identifies Celonis Inc separately from other group entities.')],notes='Group is privately held; exact Inc ownership chain not established by reviewed sources. Group website linked; parent logo held.',featured=True)
"""
s=s.replace("(r/'general-round31c-root-draft.json').write_text",tail+"\nassert len(p)==30\n(r/'general-round31c-root-draft.json').write_text");p.write_text(s)
