import pathlib,json
r=pathlib.Path('work/research-2026')
exec((r/'research32b_root.py').read_text())
add(15,'City of Centerville, Utah','Municipal government serving Centerville in Davis County, Utah.','https://www.centervilleutah.gov/',kind='Municipal government',own='Government body',sources=[('https://www.centervilleutah.gov/living-here/about-centerville/','Official city website identifies Centerville, Utah and city offices.')],notes='Not the similarly named city in Ohio.')
for i in [17,18]:
 add(i,'CentraCare','Minnesota health system providing hospital, clinic and other healthcare services.','https://www.centracare.com/',kind='Health system',own='Nonprofit / tax-exempt',sources=[('https://www.centracare.com/about-us/','Official system website identifies Minnesota healthcare services.'),('https://www.pbs.org/video/centracare-ceo-road-show-2026-fjcywv/','2026 interview with CentraCare CEO describes private nonprofit 501(c)(3) healthcare organization.')],notes='CentraCare system branding; individual hospitals and affiliated legal entities remain distinct.',outcome='partial')
add(19,'Central Admixture Pharmacy Services (CAPS)','Provides patient-specific compounded sterile medications through a network of pharmacies.','https://www.capspharmacy.com/en.html',kind='Compounding pharmacy company',own='Subsidiary',sources=[('https://www.capspharmacy.com/en.html','Current site identifies CAPS and its shift away from 503B toward 503A compounding.'),('https://www.bbraun.de/de/ueber-uns/unternehmen/stories/wir-kuemmern-uns/individuelle_ernaehrungsloesungen.html','B. Braun identifies CAPS as a subsidiary.')],notes='B. Braun subsidiary; no parent stock ticker assigned to CAPS.')
add(22,'Central Arizona Irrigation and Drainage District','Arizona public district delivering irrigation water to agricultural users.','',kind='Public irrigation district',own='Government body',sources=[('https://usbr.gov/watersmart/swep/docs/2022/SWEP_142_Central_AZ_Irrigation_and_Drainage_District_508.pdf','Federal government-hosted district proposal identifies political subdivision and irrigation district.'),('https://www.azwater.gov/sites/default/files/2022-07/irrigationdistricts.pdf','Arizona water agency map identifies the district.')],notes='Official standalone website not established; distinct from Central Arizona Water Conservation District.',outcome='partial')
add(25,'Central Association for the Blind and Visually Impaired','Provides vision rehabilitation, support services and employment opportunities for blind and visually impaired people in central New York.','https://cabvi.org/',kind='Vision services organization',sources=[('https://cabvi.org/about/','Official site identifies full organization name, Utica address and vision rehabilitation and manufacturing activities.')],notes='Utica, New York organization; not similarly abbreviated California or Cincinnati organizations. Tax status not yet independently verified.')
add(28,'Central Florida Regional Transportation Authority (LYNX)','Public transportation authority operating LYNX bus and related transit services in the Orlando region.','https://www.golynx.com/',kind='Public transit authority',own='Government body',sources=[('https://www.golynx.com/corporate-info/facts-glance.stml','Official history connects LYNX name with Central Florida Regional Transportation Authority.'),('https://www.golynx.com/core/fileparse.php/97365/urlt/Transportation-Network-Company-Alternative-Transportation-for-Paratransit-Services-RFP-18-R14.pdf','Authority procurement document identifies agency of the State of Florida created by legislature.')])
(r/'general-round32b-root-draft.json').write_text(json.dumps(p,indent=2)+'\n')
print(len(p),'drafts saved')
h=json.load(open(r/'latest-handoff.json'));h['next_batch']='Round32B:17 root drafts; five agent research active; remaining evidence in round32b-agent-evidence.md';h['next_actions'].insert(0,'5744 confirmed live. Use filing_evidence.py latest_filing across all members. Complete32B, validate websites/logos and integrate; no32B integration yet.');(r/'latest-handoff.json').write_text(json.dumps(h,indent=2)+'\n')
