import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));ids=['d4f9d66d7b2f6d8d','70f82d8dfea39e13','6aea7b6912a96350','de25008a6234191f','55ed32e838c55b95','b938f26654dc9481'];f=r/'featured284-before.json';assert not f.exists();f.write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n')
q=p[ids[0]];q.update(name='City of Yuma, Arizona',review_outcome='confirmed',website_status='verified',ownership='Government body',legal_form='Municipal government',checked_at='2026-09-14');q['notes']='The official government page was read in a rendered browser on September 14, 2026. It identifies City of Yuma, AZ, its municipal departments, and City Hall at 1 City Plaza, Yuma, AZ 85364. This matches the municipal client registration. Earlier automated access-denied responses were access limitations.';q['sources'].append({'url':'https://www.yumaaz.gov/government','label':'Rendered official municipal website','claim':'Browser page names City of Yuma, AZ and lists municipal departments, City Hall and 1 City Plaza address.'})
q=p[ids[1]];q.update(review_outcome='confirmed',ownership='Subsidiary',legal_form='Corporation',checked_at='2026-09-14');q['notes']='A 2025 South Dakota PUC filing identifies Zayo Education, Inc., formerly Education Networks of America, Inc., as owned by ENA Holding Corporation, through Commodore Holdco, LLC and Zayo Group, LLC. The chart states all depicted ownership percentages are 100%. It separately shows Zayo Education, LLC below the Inc. entity; the two legal entities are not collapsed.';q['sources'].append({'url':'https://puc.sd.gov/commission/dockets/telecom/2025/TC25-032/ExhB.pdf','label':'2025 regulator-filed ownership chart','claim':'Chart 1 names Zayo Education, Inc., its former name, ENA Holding Corporation and the Zayo group ownership chain; all ownership percentages are 100%. Chart visually inspected September 14, 2026.'})
q=p[ids[2]];q.update(review_outcome='confirmed',legal_form='LLC',checked_at='2026-09-14');q['notes']='Current LDA client 66339 names Zixi LLC. The official software terms explicitly name Zixi, LLC as the software licensor, confirming this exact filed entity. A separate registration uses Zixi Inc.; no conversion or merger between those legal forms is inferred. Ownership remains unknown.';q['sources'].append({'url':'https://zixi.com/zixi-software-terms-of-use/','label':'Official software terms','claim':'The terms explicitly identify Zixi, LLC as software licensor; read September 14, 2026.'})
q=p[ids[3]];q['checked_at']='2026-09-14';q['notes']='The current disclosure uses Zeteo Tech FKA BioFlyte. Official Zeteo evidence instead describes licensing its digitalMALDI technology to BioFlyte, Inc. Zeteo’s own identity is established, but the disclosure’s former-name relationship remains unverified. This record remains partial and is not merged with BioFlyte.'
q=p[ids[4]];q.update(checked_at='2026-09-14',website='https://www.myzinghealth.com/about-us',website_status='partial');q['notes']='The official Zing Health page describes health-plan services but does not name the filed Zing Health Holdings, Inc. entity. The group website is retained as a partial match; the exact holding-company relationship and ownership remain unverified.'
for s in q['sources']:
 if s['url']=='https://www.zinghealth.com/':s['claim']='Earlier group website reference; it does not establish the exact Zing Health Holdings, Inc. legal entity.'
q['sources'].append({'url':'https://www.myzinghealth.com/about-us','label':'Official group activity evidence','claim':'Page describes Zing Health health-plan services; exact Holdings Inc. entity is not named.'})
q=p[ids[5]];q.update(checked_at='2026-09-14',description='The 2020 lobbying registration describes research and treatment development for endophthalmitis. Current operating status is unverified.');q['notes']='Original registration 301154794 names Zions Therapeutics. The supplied domain currently fails DNS resolution, so no current official operating body was verified. A third-party reference to Zion Therapeutics, LLC is not treated as proof that it is the same entity.'
for s in q['sources']:
 if s['url']=='https://zionstherapeutics.com/':s['claim']='Supplied website reference currently fails DNS resolution; it does not establish current activity.'
for i in ids:p[i]['identity_evidence']=p[i]['notes']
(r/'featured284-decisions.json').write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n');(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');print('Six profiles saved: three confirmations and three evidence qualifications.')
