import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));before={};dec=[]
assert not (r/'featured96-before.json').exists()
rows=json.load(open(r/'featured96-first10.json'))+json.load(open(r/'featured96-middle10.json'));follow={x['id']:x for part in ['first','middle'] for x in json.load(open(r/f'featured96-{part}-followup.json'))}
names=['Unified Patents, LLC','Unilever','Unilever United States, Inc.','Union Pacific Corporation','Union Pacific Railroad','Union Pacific Railroad Company','Uniper Global Commodities North America LLC','Uniswap Labs','Unit Finance, Inc.','UNIT Solutions, Inc.','Unite Us','United Aerial Firefighters Association','United Airlines, Inc.','United Energy Workers Healthcare and Four Corners Healthcare','United HealthCare Services, Inc.','United Philanthropy Forum','Numotion (United Seating and Mobility, LLC)','United States Association of Reptile Keepers','US Cannabis Roundtable','United States Coast Guard Academy Alumni Association']
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for idx,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));e=follow.get(i,d);v=e.get('proposed_fields',d);f=dict(name=names[idx],description=v['description'],kind=v['kind'],ownership='Unknown',review_outcome='confirmed',notes='Official organization evidence confirms identity and activity. Ownership remains unknown unless separately supported.',website=v['website'],website_status='verified',status='sourced',checked_at='2026-09-13',as_of='2026-09-13');s=[src(e['official_url'],e['evidence'])]
 if idx==0:s.append(src(d['official_url'],'Official FAQ describes the membership organization and patent-quality work.'))
 if idx==1:f.update(ownership='Public company',website='https://www.unilever.com/',description='Unilever makes and sells beauty, wellbeing, personal-care, home-care and food products.');s=[src('https://www.unilever.com/files/unilever-annual-report-and-accounts-2025.pdf','Current annual report identifies Unilever PLC as the listed group parent and describes its continuing consumer-goods businesses.')]
 if idx==2:
  f.update(ownership='Subsidiary',kind='Consumer-goods holding company',description='Unilever United States, Inc. holds U.S. operating and financing subsidiaries within the Unilever consumer-goods group.');s=[src('https://www.unilever.com/files/unilever-united-states-financial-statements-december-2025.pdf','2025 audited financial statements identify exact Unilever United States Inc., its parent UNUS Holding BV, ultimate parent Unilever PLC and subsidiaries Conopco and Unilever Capital Corporation.')]
 if idx in [3,4,5]:
  f.update(ownership='Public company' if idx==3 else 'Subsidiary',kind='Railroad holding company' if idx==3 else 'Freight railroad',website='https://www.up.com/');s=[src('https://www.sec.gov/Archives/edgar/data/100885/000010088526000037/unp-20251231.htm','2025 Form 10-K identifies Union Pacific Corporation as NYSE UNP and Union Pacific Railroad Company as its principal operating subsidiary, also called UPRR or the Railroad.')];f['notes']='Public parent remains separate from the operating railroad. Existing verified merge covers the two railroad name variants; no new merge added.'
  if idx==3:f['description']='Union Pacific Corporation is the publicly traded parent of Union Pacific Railroad Company, which provides freight rail transportation across the western United States.'
 if idx==6:
  f['ownership']='Subsidiary';s=[src('https://www.uniper.energy/procurement/suppliers/invoicing-information','Current official company invoicing directory names Uniper Global Commodities North America LLC in Chicago.'),src('https://www.uniper.energy/sites/default/files/2024-04/Annual%20Report%202023.pdf','2023 audited group shareholding schedule names the exact Chicago entity at 100 percent. Historical ownership evidence, supplemented by current group directory.')];f['notes']='Exact LLC confirmed in current group invoicing directory and historical subsidiary schedule. Rejected unsupported claim that 2025 report names it in Houston.'
 if idx==7:f['notes']='Confirmed software-development organization; the Uniswap protocol, token community and independent Foundation are not treated as the same legal entity.'
 if idx==8:s=[src('https://www.unit.co/privacy-policy','Official policy explicitly identifies Unit Finance Inc. as a technology service provider to banks and program partners.')];f['description']='Unit Finance, Inc. provides technology that lets businesses offer accounts, payments and cards through partner banks.'
 if idx==9:
  s=[src('https://unitsolutions.com/pages/unit-solutions-terms-of-use','Official legal terms explicitly identify UNIT Solutions Inc., a California company.'),src('https://unitsolutions.com/','Official product site describes firearms-training equipment.')];f['description']='UNIT Solutions makes simulated firearms and ammunition systems for military, law-enforcement and civilian training.'
 if idx==10:f['website']='https://uniteus.com/'
 if idx==11:
  f['kind']='Aerial firefighting industry association';s=[src('https://www.uafa.org/','Official site identifies the United Aerial Firefighters Association and its member companies.'),src('https://www.uafa.org/about','Official about page describes aerial-firefighting safety, advocacy and industry representation.')];f['notes']='Association identity confirmed; nonprofit tax classification not established by the reviewed primary pages.'
 if idx==12:f.update(ownership='Subsidiary',kind='Passenger airline',website='https://www.united.com/');f['notes']='Current combined SEC 10-K explicitly identifies United Airlines Inc. as the wholly owned airline subsidiary of United Airlines Holdings Inc.; parent listing not assigned to subsidiary.'
 if idx==13:
  f.update(website='https://uewhealth.com/',description='United Energy Workers Healthcare and its Four Corners Healthcare affiliate provide in-home care for eligible former energy and uranium workers.',kind='Home healthcare group');s=[src('https://uewhealth.com/locations/wyoming','Official Wyoming page explicitly names Four Corners Healthcare as an affiliate of United Energy Workers Healthcare.'),src('https://fchchealth.com/','Four Corners official site describes itself as part of the United Energy Workers Healthcare family.')];f['notes']='Combined provider-and-affiliate filing scope established directly by both official sites. No legal rename inferred.'
 if idx==14:
  f['description']='United HealthCare Services, Inc. operates services within the UnitedHealthcare health-benefits business, including its broker-service portal.';f['kind']='Health-benefits services company';f['notes']='Exact legal name established by official UHC broker portal. Ownership and insurance-underwriting status are not inferred from the portal copyright.'
 if idx==15:f['kind']='Philanthropy network';f['notes']='Organization identity and philanthropy-network activity confirmed. Tax classification remains unknown rather than borrowed from member organizations.'
 if idx==16:
  f['website']='https://www.numotion.com/';s=[src('https://lmnnavigator.numotion.com/Numotion_Platform_Terms_of_Use_Last_Updated_02122025.pdf','Official 2025 platform terms name United Seating and Mobility LLC doing business as Numotion.')];f['notes']='Exact LLC and DBA bridge confirmed. Other Numotion-family legal entities are not merged.'
 if idx==18:f['notes']='Official site describes the early-2025 combination of National Cannabis Roundtable and US Cannabis Council; this explains organization history without treating every predecessor as a legal rename.'
 if idx==19:f['ownership']='Nonprofit';f['notes']='Official donor FAQ identifies tax-exempt Delaware nonprofit and EIN 06-1354978, distinct from the federal academy itself.'
 f['identity_evidence']=f['notes'];p[i].update(f);bad={d['official_url'],e['official_url']}-{x['url'] for x in s};byurl={x['url']:x for x in p[i].get('sources',[]) if x['url'] not in bad}
 for x in s:byurl[x['url']]=x
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes'],sources=s))
(r/'featured96-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured96-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()));print('Status changes',[(i,b.get('status'),p[i]['status']) for i,b in before.items() if b.get('status')!=p[i]['status']])
