import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured103-first10.json'));before={};dec=[];assert not (r/'featured103-before.json').exists()
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for k,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));f=dict(name=before[i]['name'],description=d['description'],kind=d['kind'],ownership='Unknown',review_outcome='confirmed',notes=d['evidence'],website=before[i]['website'],website_status='verified',status='sourced',checked_at='2026-09-13',as_of='2026-09-13');s=[src(d['official_url'],d['evidence'])];bad=set()
 if k==0:f['notes']='Official privacy notice names exact Clarios LLC and affiliates. Battery-manufacturing identity confirmed; exact current ownership chain remains Unknown.'
 if k==1:
  f.update(ownership='Public company',name='CLEAR');f['notes']='Official member terms define CLEAR as Clear Secure Inc. and subsidiaries. Current issuer investor page confirms NYSE YOU. Unsuffixed filing is described at group-brand scope; no operating subsidiary is assigned public status.';s.append(src('https://ir.clearme.com/','Current official investor page identifies Clear Secure Inc., YOU, and identity services.'))
 if k==2:
  f.update(review_outcome='partial',description='CN is a freight railway group. This lobbying record uses the label “CN f/k/a Grand Trunk Corporation”; Grand Trunk Corporation is separately listed as a CN subsidiary.');f['notes']='Original2026 report uses CN f/k/a Grand Trunk Corporation. CN2025Form40-F separately lists Grand Trunk Corporation as wholly owned. These establish the group relationship but do not prove the reported legal rename; exact client scope remains partial.';s=[src(d['official_url'],'2025Form40-F lists Grand Trunk Corporation among wholly owned principal subsidiaries; it does not prove a rename to CN.'),src('https://lda.gov/filings/public/filing/27f91145-050d-4595-b23d-1709097801d1/print/','Original2026report lists Public Strategies Washington as registrant and CN f/k/a Grand Trunk Corporation as client.')];bad.add('https://www.sec.gov/Archives/edgar/data/16868/000110465926000352/tm261145d1_40f.htm')
 if k==3:
  f.update(review_outcome='partial',description='Coach USA is a passenger bus business providing commuter and intercity transportation. Selected operating lines and assets transferred to a Renco affiliate in 2024.');f['notes']='Company completion announcement identifies transferred operating lines and Bus Company Holdings US LLC. This asset transaction does not establish that the historical Coach USA Inc. lobbying entity itself became that buyer; exact post-bankruptcy legal continuity remains unresolved.';s=[src('https://www.coachusa.com/node/679','October31,2024 company announcement confirms completed transaction with Renco affiliate, specifying bus lines and assets.')];bad.add(d['official_url'])
 if k==4:
  f.update(name='CoAspire, LLC',description='CoAspire develops and manufactures cruise missiles and other defense systems for U.S. and allied government customers.',kind='Defense and missile contractor',ownership='Private company');f['notes']='Navy small-business directory names exact CoAspire LLC. Current company news describes missile manufacturing and private founder ownership. Rejected draft healthcare description.';s=[src('https://www.navair.navy.mil/osbp/node/2816','Navy directory independently identifies exact CoAspire LLC and defense/naval-aviation business.'),src('https://www.coaspire.com/news','Current official company news describes cruise-missile manufacturing and privately owned founder business.')]
 if k==5:
  f.update(review_outcome='partial',description='Cohere US, Inc. is the U.S.-named lobbying client associated with Cohere’s enterprise artificial-intelligence models and software.');f['notes']='Original filing names Cohere US Inc. Official Cohere terms identify Cohere Inc.; exact corporate bridge and ownership of the filed U.S. entity remain unresolved. Distinct from Cohere Health and Cohere Technologies.'
 if k==6:
  f.update(name='Coinbase, Inc.',ownership='Subsidiary',description='Coinbase, Inc. operates cryptocurrency services within the Coinbase group.',kind='Cryptocurrency services subsidiary');f['notes']='Coinbase Global2025annual report confirms exact Coinbase Inc. became its wholly owned subsidiary in2014. The publicly traded issuer is Coinbase Global, not this operating subsidiary.';s=[src('https://www.sec.gov/Archives/edgar/data/1679788/000167978826000015/coin-20251231.htm','2025annual report Note1 names exact Coinbase Inc. and wholly owned relationship to Coinbase Global.')];bad.add(d['official_url'])
 if k==7:
  f.update(name='CoinFlip',description='CoinFlip operates cryptocurrency ATMs and services for buying and selling digital assets.');f['notes']='Current CoinFlip site describes ATMs and trading services and names GPD Holdings LLC in its footer. Unsuffixed brand identity confirmed; no ownership percentages assigned.';s=[src('https://www.coinflip.tech/',f['notes'])]
 if k==8:
  f.update(review_outcome='partial',ownership='Subsidiary',description=before[i]['description'],kind='Medical-products subsidiary');f['notes']='Filed Convatec Inc. f/k/a Triad Life Sciences label is retained. Patent history distinguishes a Triad-to-Convatec Triad name change from a later assignment to Convatec Inc.; patent reassignment does not itself prove that second step was a corporate rename. Exact full legal continuity remains unresolved.';s=[src('https://patents.google.com/patent/US20230310707A1/en','Patent history mirror labels2022Triad-to-Convatec Triad event CHANGE OF NAME, but2023transfer to Convatec Inc. ASSIGNMENT OF ASSIGNORS INTEREST. Does not prove a full corporate rename chain.')]
 if k==9:
  f.update(name='American Gaming Association (via Cornerstone Government Affairs)',description='The American Gaming Association represents the casino gaming industry. This client record names Cornerstone acting on its behalf; DiNino Associates filed the lobbying report.',kind='Gaming trade association / represented-client record');f['notes']='Original2026LD2 names DiNino Associates LLC as registrant, Cornerstone Government Affairs obo American Gaming Association as client. All three roles retained. Ownership classification remains Unknown for this represented-client record.';s=[src('https://lda.gov/filings/public/filing/4b97cbd4-c7ab-496b-b66b-861a9a0abfb9/print/',f['notes'])];bad.add('https://lda.gov/')
 f['identity_evidence']=f['notes'];p[i].update(f)
 byurl={x['url']:x for x in p[i].get('sources',[]) if x['url'] not in bad}
 for x in s:byurl[x['url']]=x
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes'],sources=s))
(r/'featured103-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured103-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False))
print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()));print('Status changes',[(i,b.get('status'),p[i]['status']) for i,b in before.items() if b.get('status')!=p[i]['status']])
