import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));xs=json.load(open(r/'sec-remaining118-last63-review.json'));b={};ds=[]
notes={6:'The SEC subsidiary exhibit names exact Restaurant Brands International US Services LLC. It is kept separate from the listed parent; the subsidiary evidence is historical.',10:'RMR’s SEC report explicitly includes RMR Aggregates Inc. among its wholly or majority owned subsidiaries and describes the aggregates business. No unsupported 100% ownership percentage is assigned.',20:'SAP’s SEC 20-F lists exact SAP National Security Services Inc., Newtown Square, among its significant wholly owned or controlled subsidiaries. It remains separate from SAP SE.',27:'Southern Company’s 2025 annual report explicitly defines Southern Company Services Inc. as its wholly owned system service company. The parent and service company remain separate.',28:'A November 2012 SEC filing explicitly names Southwest Convenience Stores LLC in a fuel-supply contract and calls it a subsidiary at that date. Current ownership and website remain unverified.',38:'Targa’s SEC annual report explicitly includes Targa Resources Partners LP among its subsidiaries. The partnership is distinct from the publicly listed Targa Resources Corp.',40:'A November 12, 2021 SEC-filed credit agreement identifies exact The North American Coal Corporation as borrower. This confirms historical corporate identity; current continuity with similarly named LLCs remains unverified.',44:'SEC staff’s January 12, 2026 meeting memorandum names USIG Digital and records discussion of crypto-asset regulation. Attached company materials describe its collateral infrastructure. Meeting participation is not regulatory endorsement; ownership remains unverified.',46:'Valero’s 2025 subsidiary exhibit explicitly names exact Delaware Valero Services Inc. The exhibit supports group identity, but does not detail the subsidiary’s precise operating function.',47:'Vertex Energy’s December 31, 2023 subsidiary exhibit explicitly lists Texas Vertex Energy Operating LLC as wholly owned. This is historical ownership evidence; current ownership is not established by this review.',48:'Vertiv’s SEC subsidiary exhibit names exact Delaware Vertiv Group Corporation. The entity remains separate from the listed parent Vertiv Holdings Co.',51:'Vistra’s SEC-filed subsidiary-guarantor schedule explicitly names Vistra Corporate Services Company. This confirms the subsidiary identity, not any purported rename into the listed parent.',58:'SEC Form D identifies WellSense Inc., formerly Enhanced Surface Dynamics Inc., with a Birmingham, Michigan address. This is the medical-technology business, distinct from the New England WellSense insurance plan; current ownership remains unverified.'}
assert not (r/'featured118-extra-before.json').exists()
for n,note in notes.items():
 x=xs[n];i=x['id'];assert p[i]['name']==x['original_name'];assert p[i]['review_outcome']!='confirmed';b[i]=json.loads(json.dumps(p[i]));own='Unknown' if n in [28,40,44,47,58] else x['ownership'];desc=x['description']
 if n==46:desc='Valero Services, Inc. is a Delaware entity within the Valero Energy group; its precise operating role is not detailed in the subsidiary exhibit.'
 p[i].update(description=desc,ownership=own,review_outcome='confirmed',notes=note,identity_evidence=note,checked_at='2026-09-13',as_of='2026-09-13');ds.append(dict(id=i,notes=note,fetched_evidence=x['fetched_evidence']))
logos=json.load(open(r/'sec117-logo-candidates.json'))['candidates']
for x in logos:
 if x['status']!='candidate':continue
 i=x['id'];b[i]=json.loads(json.dumps(p[i]));p[i].update(logo_url=x['logo_url'],logo_source_url=x['source_page'],logo_kind='logo',logo_status='official_site_asset',logo_background='light');p[i]['notes']+=' Logo shown is the shared parent/group brand, not a distinct subsidiary logo.'
 ds.append(dict(id=i,logo=x['logo_url'],source_page=x['source_page'],notes='Downloaded official asset and root visually inspected; shared group mark.'))
(r/'featured118-extra-before.json').write_text(json.dumps(b,indent=2)+'\n');(r/'featured118-extra-decisions.json').write_text(json.dumps(ds,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('13 identities and3 visually checked shared group logos saved')
