import json,pathlib,copy
from bs4 import BeautifulSoup
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));xs=json.load(open(r/'verified-sites164-next100-review.json'));before={};dec=[]
assert not (r/'featured166-before.json').exists()
accepted=[0, 2, 5, 6, 8, 11, 13, 14, 16, 19, 20, 22, 29, 33]
fix={0: 'Develops satellite remote-sensing and orbital computing services, and provides Major Tom software for satellite ground operations.', 2: 'Provides military satellite communications and satellite radar-imaging services.', 6: 'Manufactures components for small aerospace engines, including lubrication systems, fuel systems and turbine air starters.', 11: 'Provides human-resources management, acquisition support and technology services to federal agencies.', 14: 'Provides sexual-assault counseling and advocacy, childcare, affordable housing and community education in Lancaster, Pennsylvania.'}
special={0: 'Official Xplore body describes remote sensing, orbital computing and satellite-operations software; image copyright names Xplore Inc. Planned constellation scale and performance are not established deployed results.', 2: 'Official XTAR body describes X-band military satellite communications and radar imaging. Advertised compatibility and combat performance are not independently established.', 5: 'Official Zotec Partners body describes healthcare revenue-cycle management, coding and patient payments. Claimed financial improvements are not independently established.', 6: 'Official Zulu Pods body and Inc. footer identify its aerospace components. The description now reflects activities beyond ZPOD lubrication; displayed logos explicitly do not imply affiliation or endorsement.', 8: 'Official Y Combinator press page describes seed funding and its accelerator program. Conflicting aggregate portfolio valuations on the page are omitted. Featured is an editorial recognizability selection, not a lobbying-volume ranking.', 11: 'Official YRCI body identifies federal human-capital, acquisition and technology services. Government customers do not establish government ownership.', 13: 'Official Yummy Acai body describes smoothie-bowl-base manufacturing for food-service, retail and consumer-product brands.', 14: 'Official YWCA Lancaster body identifies specific counseling, childcare, housing and community programs; address and EIN 23-1352609 identify the local organization. National YWCA identity is not substituted for the local entity.', 16: 'Official Zayo body describes fiber and network services and names Zayo Group LLC. Group branding does not independently establish ownership of every regional entity.', 19: 'Official Zekelman Holocaust Center body identifies the Farmington Hills museum, memorial exhibits and educational activities.', 20: 'Official Zelim body describes maritime detection, recovery systems and an unmanned rescue vessel; footer identifies Zelim Ltd. Performance and standards compliance are not independently verified.', 22: 'Official ZenaDrone body and Inc. footer describe drones and explicitly identify it as a subsidiary of ZenaTech Inc. The parent ticker is not assigned as a separate public listing for the subsidiary.', 29: 'Official Zinus storefront displays mattresses, bed frames and furnishings; footer explicitly identifies Zinus Inc. Product health, comfort and sustainability claims are not independently verified.', 33: 'Official Zonos body describes cross-border commerce software, duty calculations and classification. Automated classifications and compliance claims are not treated as authoritative legal determinations.'}
for n in accepted:
 v=xs[n];i=v['id'];assert p[i]['name']==v['original_name'] and p[i]['review_outcome']!='confirmed';before[i]=copy.deepcopy(p[i]);note=special.get(n,'Official organization body identifies this organization and supports its stated services. Existing ownership evidence is retained; advertised outcomes are not independently verified.')
 p[i].update(description=fix.get(n,v['description']),notes=note,identity_evidence=note,review_outcome='confirmed',checked_at='2026-09-13',as_of='2026-09-13')
 if n==22:p[i]['ownership']='Subsidiary'
 if n==8:p[i]['featured']=True
 e=v['fetched_evidence'][0];assert e['http_status']==200
 s=BeautifulSoup(open(e['cache_path']).read(),'html.parser')
 for t in s(['script','style','nav','header']):t.decompose()
 ss={s['url']:s for s in p[i]['sources']};ss[e['url']]={'url':e['url'],'label':'Official organization evidence','claim':note};p[i]['sources']=list(ss.values());dec.append(dict(id=i,name=p[i]['name'],decision='confirmed',notes=note,fetched_evidence=v['fetched_evidence'],reviewed_body=' '.join(s.stripped_strings)))
for name,value in [('before',before),('decisions',dec),('deferred',[])]:
 (r/f'featured166-{name}.json').write_text(json.dumps(value,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print(len(dec),'identity confirmations saved')
