import json,pathlib,copy
from bs4 import BeautifulSoup
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));xs=json.load(open(r/'verified-sites143-next100-review.json'));before={};dec=[]
assert not (r/'featured141-before.json').exists()
fix={25:'Develops AI tools for dispute resolution and claims administration.',37:'Develops interceptor and missile systems, including flight-test demonstrators.',45:'An Indigenous community organization representing Gabrielino/Tongva people in the Los Angeles Basin.',57:'A pharmaceutical company focused on reproductive healthcare, including mifepristone and misoprostol products.',59:'Develops industrial chemical production using agricultural feedstocks and existing industrial facilities.',96:'Develops helicopter health and usage monitoring software and sensors.',99:'A tribal organization based along the Grand River in southwest Michigan, including the Grand Rapids and Muskegon areas.'}
special={11:'The official risk-management fund page identifies Florida sheriffs as its members and owners and describes shared coverage and risk services.',16:'The site explicitly distinguishes Forest Landowners Association from Forest Landowners Foundation; this entry concerns the association.',18:'The official page names Forge Group LLC and its Reston address, matching the consulting business rather than another Forge brand.',19:'The substantive official body describes Fortem Technologies radar and counter-drone systems. Advertised interception performance is not independently established.',25:'The official page identifies Fourth Party AI and its claims/dispute tools. Claims of neutrality, fairness and lack of bias are not independently verified.',36:'The alliance site describes wildfire-policy advocacy; the advocacy alliance is distinct from the federal commission discussed on the page.',37:'The official site names Furientis Inc. and describes interceptor development and flight-test demonstrators. Planned production scale is not treated as current output.',39:'The official site identifies Future Defense USA and its Virginia-built vessel offerings. Unsinkability, ballistic protection and sea-state marketing are not independently validated.',45:'The community’s own site identifies Gabrielino/Tongva Nation and its Los Angeles Basin homelands. This identity check does not establish federal recognition or exclusive authority relative to other Tongva organizations.',57:'Corrected an unsupported sterile-injectables description. GenBioPro’s official site identifies its reproductive-health mission and mifepristone/misoprostol products.',58:'GeneCapture’s official site describes infection-diagnostics development. Advertised pathogen counts and testing speed are not independently established.',61:'The official site explicitly names General Radar Corp. and describes phased-array radar development.',71:'The official Glas Inc. site describes nicotine devices and pods. Product marketing is not treated as a health or safety finding.',76:'The Nozin About page explicitly identifies Global Life Technologies Corp. as maker of Nozin brand products.',81:'The official payment-security site names GM Sectec Corp. in its footer.',86:'The official Goldco site identifies precious-metal purchasing and retirement-account services. Celebrity endorsements and investment claims are not adopted as advice.',96:'The monitoring-technology site explicitly names GPMS International, Inc. in its footer and describes helicopter monitoring.',97:'The official board site explicitly identifies Grand Bay, Alabama water service and a limited wastewater-service area.',99:'The official site identifies Grand River Bands of Ottawa Indians and its southwest Michigan community. This confirms the named organization without merging related source labels or making a federal-recognition finding.'}
for n,v in enumerate(xs):
 if v['decision']!='confirmed' or n==44:continue
 i=v['id'];assert p[i]['name']==v['original_name'] and p[i]['review_outcome']!='confirmed';before[i]=copy.deepcopy(p[i]);note=special.get(n,'Official organization body text identifies this organization and supports the activity summarized. Existing ownership evidence is retained without inferring additional ownership from its name.')
 p[i].update(description=fix.get(n,v['description']),notes=note,identity_evidence=note,review_outcome='confirmed',checked_at='2026-09-13',as_of='2026-09-13')
 if n==57:
  p[i]['kind']='Pharmaceutical company'
  for src in p[i]['sources']:
   if 'sterile' in src.get('claim','').lower():src['claim']='Prior sterile-injectables description was incorrect; official site describes reproductive-health pharmaceutical products.'
 e=v['fetched_evidence'][0];assert e['http_status']==200
 s=BeautifulSoup(open(e['cache_path']).read(),'html.parser')
 for t in s(['script','style','nav','header']):t.decompose()
 body=' '.join(s.stripped_strings)
 ss={s['url']:s for s in p[i]['sources']};ss[e['url']]={'url':e['url'],'label':'Official organization evidence','claim':note};p[i]['sources']=list(ss.values());dec.append(dict(id=i,name=p[i]['name'],decision='confirmed',notes=note,fetched_evidence=v['fetched_evidence'],reviewed_body=body))
(r/'featured141-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured141-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
(r/'featured141-deferred.json').write_text(json.dumps([dict(id=xs[44]['id'],name=xs[44]['original_name'],reason='The filing labels an individual while the website describes a construction company; the exact legal relationship needs resolution.')],indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print(len(dec),'identity confirmations saved')
