import json,pathlib
b=pathlib.Path('work/research-2026');p=b/'reviewed.json';x=json.loads(p.read_text())
d={
'b6fa284bd9393b10':('501(c)(4) nonprofit','https://amac.us/action/','Official action page identifies AMAC Action as the 501(c)(4) advocacy affiliate of AMAC.','AMAC Action is the separate advocacy affiliate; this classification does not apply to all AMAC entities.'),
'2c3984a3a2f8978c':('Nonprofit professional membership organization','https://www.aaap.org/american-academy-of-addiction-psychiatry-awarded-joint-accreditation-status/','Official accreditation announcement identifies the American Academy of Addiction Psychiatry as a nonprofit professional membership organization.','Nonprofit status is supported by the academy itself. A specific federal tax subsection has not been established from this source.'),
'ece13fcd85f8c18c':('Nonprofit medical organization','https://asmbs.org/wp-content/uploads/2024/06/ASMBS-Fact-Sheet2024.pdf','The society\'s 2024 fact sheet identifies ASMBS as a nonprofit medical organization dedicated to metabolic and bariatric surgery.','The society itself is identified as nonprofit; no tax subsection or separate foundation status is inferred.'),
'468eb22673f91aa9':('501(c)(3) nonprofit','https://www.nalms.org/nalms-financials/','Official financial disclosures explicitly identify NALMS as a 501(c)(3) tax-exempt nonprofit organization.','Official financial disclosure establishes nonprofit tax status for the society itself.'),
'400055f3854a6add':('501(c)(3) nonprofit','https://www.ncdmm.org/privacy-policy/','Official privacy policy identifies the National Center for Defense Manufacturing and Machining and lists 699 Scalp Avenue, Johnstown, matching the IRS record.','IRS EIN 76-0727663 matches the exact organization and its privacy-policy address at 699 Scalp Avenue. Current contact information lists headquarters at 125 Donald Lane, Suite 2; the historical address is an identity cross-check. NCDMM is a subsidiary of Manufacturing Technology Deployment Group; its own IRS status supports this classification.')}
backup=b/'five-primary-status-before.json';assert not backup.exists();backup.write_text(json.dumps({i:x[i] for i in d},indent=2)+'\n')
for i,(legal,url,claim,note) in d.items():
 v=x[i];assert v['ownership']=='Unknown';v.update(ownership='Nonprofit',legal_form=legal,notes=note,review_outcome='confirmed',checked_at='2026-09-09',as_of='2026-09-09',identity_evidence='Original filing identity and official organization evidence retained; additional primary evidence establishes organizational status. '+note)
 v['sources'].append({'url':url,'label':'Official organizational status evidence','claim':claim})
x['400055f3854a6add']['sources'] += [{'url':'https://www.irs.gov/pub/irs-soi/eo2.csv','label':'IRS exempt organization record','claim':'EIN 760727663, exact organization name and 699 Scalp Avenue address; subsection 03 and exemption status 01 in the August 2026 extract.'},{'url':'https://www.ncdmm.org/contact-us/','label':'Current official contact and parent disclosure','claim':'Lists Johnstown headquarters at 125 Donald Lane, Suite 2, and identifies NCDMM as a subsidiary of Manufacturing Technology Deployment Group.'}]
p.write_text(json.dumps(x,indent=2)+'\n');pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(x,separators=(',',':'))+'\n');pathlib.Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(x,indent=2)+'\n')
f=b/'publication.json';pub=json.loads(f.read_text());pub={k:v for k,v in pub.items() if not k.startswith('pending_')};pub.update(local_changes_pending=True,pending_source_pushed=False,pending_change_summary='Seven sourced organizational status updates: Highmark, US Rice Producers, AMAC Action, AAAP, ASMBS, NALMS and NCDMM');f.write_text(json.dumps(pub,indent=2)+'\n');print('Five organization statuses saved')
