import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured111-input.json'));before={};dec=[]
assert not (r/'featured111-before.json').exists()
a=[
('confirmed','Unknown','CoinFlip (GPD Holdings LLC)','CoinFlip operates cryptocurrency kiosks and related buying and selling services.','https://coinflip.tech/terms/privacy-policy','The current official privacy policy explicitly identifies GPD Holdings LLC DBA CoinFlip as a kiosk operator. Exact entity and brand are confirmed; current ownership remains unknown.'),
('confirmed','Public company','GRAIL (filed as GRAIL LLC)','GRAIL develops blood tests for detecting multiple types of cancer, including its Galleri test.','https://www.sec.gov/Archives/edgar/data/1699031/000169903125000041/gral-20241231.htm','The 2024 SEC10-K documents GRAIL LLC converting to a corporation June21,2024 and separating from Illumina June24,2024 as an independent public entity, Nasdaq GRAL. The old LLC filing label is retained as historical; the former wholly owned Illumina classification no longer applies.'),
('confirmed','Unknown','Grayscale Investments LLC (historical entity)','The historical Grayscale Investments LLC managed cryptocurrency investment funds. Its business was reorganized into other Grayscale entities.','https://www.sec.gov/Archives/edgar/data/1729997/000119312526381861/gdlc-20260630.htm','The September3,2026 SEC10-K identifies Grayscale Investments LLC as the former manager and predecessor merged into Grayscale Operating LLC. It was a DCG consolidated subsidiary. Do not equate this historical LLC with the separately incorporated Grayscale Investments Inc. or current Sponsors LLC; current ownership of an extant LLC is not asserted.'),
('confirmed','Unknown','Great American Outdoors Group, LLC','Great American Outdoors Group is associated with the Bass Pro Shops and Cabela’s outdoor-retail businesses.','https://courts.delaware.gov/Opinions/Download.aspx?id=368430','The corrected September30,2024 Delaware Superior Court opinion independently names exact Great American Outdoors Group LLC alongside Cabela’s, BPS Direct and Great Outdoors Group. Exact identity is established; the source does not prove a current ownership chain or equivalence between those entities.'),
('confirmed','Unknown','Greystar Management Services, LLC','Greystar Management Services LLC provides real-estate management services within the Greystar business.','https://www.greystar.com/disclosures-and-licenses','Greystar’s official license disclosures name exact Greystar Management Services LLC, including Minnesota entity license40216761 and its responsible broker. Group brand association is confirmed; exact ownership is not independently established.'),
('confirmed','Subsidiary','Groupe SEB USA','Groupe SEB USA is a US household-appliance and cookware business within Groupe SEB.','https://www.groupeseb.com/sites/default/files/2026-04/SEB_DEU_2025_FR%201.pdf','The officially indexed 2025 consolidated-company table lists exact Groupe SEB USA in the United States with100% voting rights and interest. The direct PDF open failed in this review; indexed primary table corroborates subsidiary identity. Official legal notices separately identify its Delaware registered office.'),
('confirmed','Unknown','Grundfos Americas Corporation','Grundfos Americas Corporation supplies pumps and water-handling technology for buildings, industry and utilities.','https://www.grundfos.com/us/about-us/grundfos-in-the-usa','Grundfos’s official US page names exact Grundfos Americas Corporation at856 Koomey Road, Brookshire, Texas77423 and describes its water-technology activity. Parent-group ownership statements are not substituted for an exact ownership chain.'),
('partial','Unknown','GRVTY (filed as formerly Royce Geo)','GRVTY provides defense and intelligence technology services. The filing’s former-name link to Royce Geo remains unresolved.','https://www.grvty.com/newsroom/grvty-launches-advisory-board-with-phil-root-and-dave-sterling-as-founding-advisors','The official GRVTY announcement identifies Royce Geo’s founder as an adviser but does not establish a corporate rename. Keep this filed former-name label separate from GRVTY Inc. until continuity is documented.'),
('confirmed','Unknown','GRVTY, Inc.','GRVTY provides technology and support services for defense and intelligence work.','https://www.grvty.com/careers/listings/facility-security-officer-nuaibxko','The official hiring page explicitly names GRVTY Inc. and describes its classified defense-contracting environment. This confirms the exact corporation’s operating identity. Private-sector wording alone is not proof of private ownership.'),
('confirmed','Nonprofit','GTI Energy','GTI Energy researches energy technologies and trains industry professionals, including work on natural gas, infrastructure and energy efficiency.','https://cmicseeatcalc.gti.energy/About','The officially indexed GTI tool About page describes GTI Energy as an Illinois not-for-profit corporation, tax-exempt under501(c)(3), at1700 South Mount Prospect Road, Des Plaines. The page now redirects to CMIC; indexed official text supplies the explicit legal form.')]
for row,v in zip(rows,a):
 i=row['id'];before[i]=json.loads(json.dumps(p[i]));out,own,name,desc,url,note=v;p[i].update(name=name,description=desc,ownership=own,review_outcome=out,notes=note,identity_evidence=note,status='sourced',checked_at='2026-09-13',as_of='2026-09-13')
 if out=='confirmed':p[i]['website_status']='verified'
 ss={s['url']:s for s in p[i].get('sources',[])};ss[url]=dict(url=url,label='Primary identity evidence',claim=note);p[i]['sources']=list(ss.values());dec.append(dict(**row,decision=out,evidence=note,sources=[ss[url]]))
(r/'featured111-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured111-first10.json').write_text(json.dumps(dec,indent=2)+'\n');(r/'featured111-middle10.json').write_text('[]\n');(r/'featured111-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False))
print('9 confirmed')
