import json,pathlib,copy,collections
root=pathlib.Path(__file__).resolve().parents[2];base=root/'work/research-2026/identity-wave40-bulk';path=root/'work/research-2026/reviewed.json';p=json.loads(path.read_text());m=json.loads((base/'matches.json').read_text());holds={57:'Trajector group page does not identify Trajector Medical subsidiary.',62:'Official contact identifies Travois Inc, not filed Travois Holdings Inc.',66:'Filed Inc conflicts with official LLC; legal continuity not established.',70:'Exact Corporation legal identity not corroborated by cached pages.',73:'Tribal government homepage does not identify the Economic Development Authority.',77:'Exact Type One Energy Group Inc legal identity remains uncorroborated.',80:'Exact LLC legal identity remains uncorroborated.',81:'Exact Corporation identity remains uncorroborated.',84:'UC Health brand does not establish exact LLC and affiliates identity.'};decisions=[];backup={}
for i in range(44,88):
 x=m[i];id=x['id'];profile=p[id];backup[id]=copy.deepcopy(profile);a=x['matches'][0];r=a['registration'];proof=f"Official organization name, activity and address corroborate the registration: {r['client_name']}, {r['address']}, {r['city']}, {r['state']}. Source: {r['archive']} / {r['member']}.";decision={'id':id,'decision':'hold' if i in holds else 'confirm','evidence':holds.get(i,proof),'url':a['page_url']};decisions.append(decision)
 if i in holds:continue
 assert profile['review_outcome']=='partial'
 profile.update(status='sourced',review_outcome='confirmed',website_status='verified',checked_at='2026-09-12',as_of='2026-09-12');old=profile.get('identity_evidence','');profile['identity_evidence']=(old if isinstance(old,str) else json.dumps(old))+' '+proof
 profile['sources'] += [{'url':a['page_url'],'label':'Official identity and registration-address corroboration','claim':proof},{'url':r['source_url'],'label':'House registration archive: '+r['member'],'claim':proof}]
 if i==85:profile['notes']=profile.get('notes','')+' Filing jointly names UGT Renewables/Sun Africa. UGT official site identifies Sun Africa as a sister company; this record is retained as the disclosed joint label, not proof the two companies are one legal entity.'
(base/'local44-before.json').write_text(json.dumps(backup,indent=2,ensure_ascii=False));(base/'local44-decisions.json').write_text(json.dumps(decisions,indent=2,ensure_ascii=False))
for f,pretty in [(path,True),(root/'lobbying-map/research/reviewed-2026.json',False),(root/'outputs/2026-research-trial/profiles.json',True)]:f.write_text(json.dumps(p,indent=2 if pretty else None,ensure_ascii=False))
print(collections.Counter(d['decision'] for d in decisions))
