import json,copy
from pathlib import Path
p=Path('work/research-2026');d=json.load(open(p/'reviewed.json')); inp=json.load(open(p/'featured65-input.json'));before={x['id']:copy.deepcopy(d[x['id']]) for x in inp};rows=[
('6b14a93a6901ce4e','https://ir.hilton.com/investor-resources/faqs','Official investor FAQ identifies Hilton Worldwide Holdings Inc. and NYSE ticker HLT. Filed unsuffixed Hilton Worldwide brand and hospitality activity match. Hilton Grand Vacations is kept distinct.','Public company (NYSE: HLT)'),
('4279e1fd2fe9d7f6','https://hippy-international.org/about/','Official About page identifies HIPPY International as a company founded in 2019 providing home-based early-childhood education curriculum and parent support. Confirm the unsuffixed brand; no nonprofit status or specific legal entity is inferred.','Unknown'),
('56ce7ff7d2e348f8','https://hcnglobal.com/','Official HCN Global site explicitly names Hispanic Communications Network in its footer and describes multicultural communications and Spanish-language media campaigns, matching the filed brand and activity. Ownership is not established.','Unknown'),
('7ee87de68c6111a2','https://www.aana.org/','Official AANA site expands the name to Arthroscopy Association of North America and describes arthroscopy education. The original registration explicitly expands AANA to this association. Hither Creek Strategies LLC remains the disclosed intermediary; website and activity describe the represented organization.','Unknown'),
('3d499323c35e8e97','https://www.hntb.com/kansas-city-office/','Official HNTB page names HNTB Corporation and describes it as an employee-owned infrastructure firm, matching original HNTB/HNTB Corporation aliases and engineering activity.','Employee-owned company'),
('82d869563893eaea','https://www.hntb.com/wp-content/uploads/2019/10/Expert_Mendes_2019.pdf','Official HNTB publication uses The HNTB Companies branding. Original filing is the unsuffixed group label and architecture/engineering activity; confirm the brand scope without equating every group company with HNTB Corporation. Ownership at exact group scope is left unknown.','Unknown'),
('fb7f15e6f8e91d62','https://hobaspipe.com/','Official homepage explicitly names Hobas Pipe USA, Inc. and its fiberglass-pipe manufacturing business. Official contact page lists 1413 E. Richey Road, Houston, matching original filing context. Current ownership is not established.','Unknown'),
('0b9c64705d75aba0','https://hoeckerenergy.com/','Official James Hoecker professional site lists Principal, Hoecker Energy Law and Policy PLLC, from 2005 onward, establishing the exact firm name and energy-policy practice. No ownership share is inferred.','Unknown'),
('3df20fc660831800','https://www.wharfdc.com/business-directory/hoffman-associates/','The Wharf official business directory identifies Hoffman & Associates and links hoffman-dev.com, matching the original 760 Maine Avenue SW Washington address and real-estate development activity. Previous hoffmanassociates.com website was unsupported and is replaced.','Unknown')]
for i,u,e,o in rows:
 x=d[i];assert x['review_outcome']!='confirmed';x.update(review_outcome='confirmed',ownership=o,identity_evidence=e,notes=e,checked_at='2026-09-13',as_of='2026-09-13',website_status='verified',status='sourced');x['sources']=[s for s in x.get('sources',[]) if s.get('label')=='Original lobbying disclosure']+[{'url':u,'label':'Primary identity evidence','claim':e}]
d['0b9c64705d75aba0'].update(website='https://hoeckerenergy.com/',description='Energy-law and policy practice led by former Federal Energy Regulatory Commission chairman James Hoecker.',kind='Law firm')
d['3df20fc660831800']['website']='https://www.hoffman-dev.com/'
d['4279e1fd2fe9d7f6'].update(kind='Education company',description='HIPPY International develops home-based early-childhood curricula and supports parents in preparing preschool children for school.')
(p/'featured65-before.json').write_text(json.dumps(before,indent=2,ensure_ascii=False)+'\n');(p/'featured65-root-decisions.json').write_text(json.dumps(rows,indent=2,ensure_ascii=False)+'\n')
for f,indent,nl in [(p/'reviewed.json',2,True),(Path('lobbying-map/research/reviewed-2026.json'),None,False),(Path('outputs/2026-research-trial/profiles.json'),2,True)]:f.write_text(json.dumps(d,ensure_ascii=False,indent=indent)+ ('\n' if nl else ''))
print('Saved',len(rows))
