import json,pathlib,copy
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));assert not (r/'featured222-before.json').exists();before={};dec=[]
items={
'00176ec7111fb81b':('Outpost Space (Outpost Technologies)', 'The 2026 Outpost Space registration lists 1601 Colorado Avenue, Santa Monica. SEC Form D identifies Outpost Technologies Corp at the same address, with Jason Dunn as an officer; Outpost’s current company page identifies the same business and founder and names Outpost Technologies Corporation in its footer. The operating identity is confirmed; this does not imply current ownership from an old securities filing.', [('https://www.sec.gov/Archives/edgar/data/1947241/000194724122000001/xslFormDX08/primary_doc.xml','SEC issuer identity and matching address'),('https://disclosurespreview.house.gov/data/LD/2026_Registrations_XML.zip','Original registration 301843969.xml: Outpost Space at 1601 Colorado Avenue.'),('https://www.outpost.space/company','Official current company identity and founder')]),
'b1f937efb3181131':('Clearspeed','The SBIR portfolio identifies AC Global Risk Inc. and explicitly links clearspeed.com; its award describes Clearspeed voice analytics. Clearspeed’s historical company brochure identifies its former name as AC Global Risk. That brochure was available in a cached primary-source retrieval, while the current URL returned 404. Current official website material confirms the Clearspeed operating business. Ownership remains unknown; no legal conversion or merger is inferred.',[('https://www.sbir.gov/portfolio/1560277','Federal identity bridge to AC Global Risk Inc.'),('https://www.clearspeed.com/wp-content/uploads/2020/06/Clearspeed-CS_Energy-Company-Philippines_060820.pdf','Historical official brochure, cached retrieval: former operating name AC Global Risk; current URL unavailable.'),('https://www.clearspeed.com/privacy-policy/','Current official Clearspeed website')])}
for i,(name,n,ss) in items.items():
 v=p[i];before[i]=copy.deepcopy(v);v.update(name=name,review_outcome='confirmed',website_status='verified',checked_at='2026-09-13',notes=n,identity_evidence=n);v['sources'].extend(dict(url=u,label=l,claim=n) for u,l in ss);dec.append(dict(id=i,notes=n,sources=ss))
for k,v in [('before',before),('decisions',dec)]: (r/f'featured222-{k}.json').write_text(json.dumps(v,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('2 identities, 1 website confirmed')
