import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));ids=['f19c35f1531a135e','060367a3531ad111','80a414f13217ec7d'];f=r/'featured300-before.json';assert not f.exists();f.write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n')
rows=[('https://www.caracol-am.com/wp-content/uploads/2024/05/PR_Caracol-Impac-Systems-Engineering-Partnership-2024_EN.pdf','The May 9, 2024 official release was downloaded and visually inspected. Its footer explicitly names Caracol Inc., 18919 N Heatherwilde Blvd Suite 125, Pflugerville, Texas, and links caracol-am.com. The body describes robotic additive manufacturing and the US production facility. The exact US identity is confirmed; current ownership percentages are unknown. The full official Caracol wordmark was separately retrieved and visually checked.'),('https://grassociation.org/board-of-directors/','Alan Knapp’s professional-association board biography explicitly names CareeResilient, LLC and describes it as a third-party administrator and employee-benefits business focused on professional development and career-protection benefits. This supports the exact operating identity independently of its lobbying filing. His founder/CEO role does not establish current ownership. The supplied company domain remains a partial website match because live retrieval encountered a TLS failure.'),('https://www.cps.ht/','The official CPS website names Caribbean Port Services and describes cargo handling and logistics at Port-au-Prince, Haiti, matching the disclosed terminal operator. Operating identity is confirmed. The company is distinguished from Haiti’s public port authority, with which the site describes a partnership. Current ownership remains unknown.')]
for i,(u,n) in zip(ids,rows):
 q=p[i];q.update(review_outcome='confirmed',checked_at='2026-09-14',notes=n,identity_evidence=n);q['sources'].append({'url':u,'label':'Primary identity evidence reviewed September 14, 2026','claim':n})
p[ids[0]].update(legal_form='Corporation',website_status='verified',logo_url='https://www.caracol-am.com/wp-content/themes/default-theme/img/logo-w.svg',logo_kind='logo',logo_status='official_site_asset',logo_source_url='https://www.caracol-am.com/')
p[ids[2]]['website_status']='verified'
(r/'featured300-decisions.json').write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n');(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');print('Three identities and one full logo saved.')
