import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));batch=json.load(open(r/'identity311-batch.json'))['records']
before=r/'featured312-before.json';assert not before.exists();before.write_text(json.dumps({q['id']:p[q['id']] for q in batch},ensure_ascii=False,indent=2)+'\n')
notes={
'8c38127e2e6c14fb':'The official About body explicitly identifies the American Cochlear Implant Alliance as a not-for-profit membership organization and describes research, education and access advocacy. Its history names the American Cochlear Implant (ACI) Alliance Foundation incorporated in 2011. Operating identity is confirmed; the brand is not asserted to be a separate corporation. Indexed official body inspected; direct retrieval was blocked.',
'477e48aab55549ce':'The official ACMG About body identifies the American College of Medical Genetics and Genomics and its professional membership in clinical genetics, laboratory genetics and genetic counseling. The shorter reported name is retained in the underlying filing record. Operating identity is confirmed; no unverified ownership or tax subsection is assigned.',
'5919eba2ef6504a2':'The official About body explicitly names the American Concrete Pumping Association, describes its 1974 founding and its concrete-pumping safety, education, advocacy and operator-certification work. This independently confirms the exact operating association. Current legal ownership and tax status remain unknown.',
'2b4b7edaa1a2c209':'The official company profile explicitly identifies American Textile & Apparel Inc. as a privately owned corporation in Davie, Florida, supplying apparel and private-label manufacturing. The indexed official body was inspected; live direct retrieval returned a database error. Private-company classification follows the explicit company statement, not an inference from the corporate suffix; current shareholders are not identified.',
'e5413bf5e7f53c2a':'The official AmeriQual About body names AmeriQual Group and describes its food manufacturing for branded-food customers, the US military and humanitarian relief. The group operating identity is confirmed. The website does not independently establish the filed LLC suffix or current controlling ownership, so no legal-entity merge or ownership inference is made.',
'f0f525b5f3cde6f5':'The official ADCES About body explicitly documents the January 22, 2020 change from American Association of Diabetes Educators to Association of Diabetes Care & Education Specialists. It describes diabetes-care education, member resources and policy advocacy. Identity and the reported former-name relationship are confirmed; tax status remains unverified.',
'14bc43e3b1f2e663':'ApolloMD’s official current body describes a private, independent medical group with no outside ownership and a 2025 clinician/senior-employee ownership model. This establishes the group description but does not resolve the filing parenthetical Americans for Fair Health Care or prove that a separate ApolloMD Partners, Inc. entity is the disclosed client. Exact filing identity remains partial; group ownership is not assigned across the unresolved relationship.',
'43bb1d455acc8edb':'The official Blackwatch International contact body independently names the business and its headquarters at 1430 Spring Hill Road, Suite 205, McLean, Virginia, with a California field office. Its official technology materials describe IT and cybersecurity work. Operating identity is confirmed; no legal suffix, parent relationship or current ownership is inferred.',
'fe151e27976c37cc':'The official Bravo Ordnance website names the business and describes design, prototyping and manufacture of warheads, explosives and defense components using additive manufacturing. This confirms the operating identity. Production-speed and performance statements remain company claims; no legal suffix or current ownership is inferred.',
'd3fba4769f8e4b85':'The official Emergency Care Partners About body identifies the emergency-medicine management platform, its clinical-group support and its formation in 2018. Operating identity is confirmed. The current page does not independently establish the filed LLC suffix or the present ownership percentages, and regional partner groups are not silently merged into this record.'}
for q in batch:
 i=q['id'];note=notes[i];z=p[i];z.update(review_outcome='partial' if i=='14bc43e3b1f2e663' else 'confirmed',checked_at='2026-09-14',notes=note,identity_evidence=note)
 if i!='14bc43e3b1f2e663':z.update(website=q['website'],website_status='verified',description=q['description'])
 for s in q['sources']:z['sources'].append({'url':s['url'],'label':'Primary organization evidence inspected September 14, 2026','claim':note})
p['8c38127e2e6c14fb']['ownership']='Nonprofit'
p['2b4b7edaa1a2c209'].update(ownership='Private company',legal_form='Corporation')
(r/'featured312-decisions.json').write_text(json.dumps({q['id']:p[q['id']] for q in batch},ensure_ascii=False,indent=2)+'\n')
(r/'reviewed.json').write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
print('Nine identities confirmed; one ambiguous filing relationship retained and annotated.')
