import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));ids=['266357fb5266ad04','56d2808ce6605803','f4aed698bd7db74f','9bcf0d6ed47cc42d'];f=r/'featured299-before.json';assert not f.exists();f.write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n')
rows=[('https://www.carlyle.com/sites/default/files/2025-08/Carlyle_Investment_Management_LLC_CIM_ADV_2A_Brochure_March_31_2025.pdf','The March 31, 2025 official adviser brochure explicitly identifies Carlyle Investment Management L.L.C., a Delaware LLC formed in 1996, providing investment advice to Carlyle-sponsored funds and accounts. It describes direct and indirect ownership/control by Carlyle-affiliated entities. This exact LLC is confirmed; the public parent ticker and the separate Inc. filing label are not assigned to it.'),('https://www.carolinawest.com/whats-happening/','The official Carolina West Wireless notice announces an agreement to transition its network to Verizon and discontinue its wireless services. The current homepage says service and customer account access end September 30. Operating identity is confirmed; this transition does not independently establish a change in legal ownership.'),('https://www.carsoncity.gov/our-city/history','The official city history explicitly identifies the Consolidated Municipality of Carson City, Nevada. This confirms the municipal government’s operating identity. It is distinct from Carson, California.'),('https://www.cnh.com/-/media/CNHi/cnhicorporate/Investor-relation/financial_information/annual_reports/2021/CNHI_Annual_report_2021.pdf?rev=-1','The official 2021 annual report lists Case New Holland Industrial Inc., Wilmington, USA, with 100% ownership through CNH Industrial U.S. Holdings Inc. The exact subsidiary is identified. Ownership is historical evidence as of December 31, 2021; the listed public parent and its ticker are not assigned to this subsidiary.')]
for i,(u,n) in zip(ids,rows):
 q=p[i];q.update(review_outcome='confirmed',checked_at='2026-09-14',notes=n,identity_evidence=n);q['sources'].append({'url':u,'label':'Primary identity evidence reviewed September 14, 2026','claim':n})
p[ids[0]].update(legal_form='LLC',ownership='Subsidiary')
p[ids[1]].update(website_status='verified',description='Regional wireless carrier that has announced it will discontinue service and transition its network to Verizon. Its current notice gives September 30 as the service cutoff.')
p[ids[2]].update(website_status='verified',ownership='Government body',kind='Municipal government',legal_form='Consolidated municipality')
p[ids[3]].update(legal_form='Corporation',ownership='Subsidiary')
(r/'featured299-decisions.json').write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n');(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');print('Four confirmations saved; Carolina West operating status clarified.')
