import json,pathlib,copy
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));assert not (r/'featured220-before.json').exists();before={};dec=[]
items={
'd7df59cb91f2ed5a':('https://www.bostonmetal.com/terms-of-use/','Boston Metal’s official website terms identify Boston Electrometallurgical Corporation as the business behind the Boston Metal website. The SBIR record uses that same legal name and domain. Ownership remains unknown.'),
'22f6f4577a534702':('https://www.gts.us.com/about-global-technical-systemscorporate-information/','GTS’s official corporate information states that its SAM registration is Management Services Group, Inc., doing business as Global Technical Systems. It describes the Virginia business as privately held. The matching federal award domain and defense-engineering activity corroborate this identity.'),
'57c1df21e64403b4':('https://www.gts.us.com/about-global-technical-systemscorporate-information/','GTS’s official corporate information states that its SAM registration is Management Services Group, Inc., doing business as Global Technical Systems. It describes the Virginia business as privately held. The matching federal award domain and defense-engineering activity corroborate this identity.'),
'b5ef316f1cf8ca98':('https://omnifederal.com/terms-of-use/','Omni Federal’s official terms name Omni Fed LLC as the website operator, matching the SBIR awardee OMNI FED LLC and domain. The current footer uses Omni Federal, LLC. The operating identity is confirmed; the sources do not establish a formal legal rename or ownership.'),
'f8ea61671a360192':('https://www.earthsciencesystems.com/wp-content/uploads/2026/01/concrete2-web.pdf','The official 2026 concrete-scanner brochure names Earth Science Systems, LLC, its Wheat Ridge location and earthsciencesystems.com domain together. It describes ground-penetrating radar equipment, confirming the operating identity. Ownership remains unknown.'),
'5616882e9336e9e2':('https://disclosurespreview.house.gov/data/LD/2021_Registrations_XML.zip','Original registration 301324434.xml names Human System Integration, Inc., a wearable-technology business at 153 Washington Street, Walpole, Massachusetts; its House ID 353650445 continues in the 2026 report. The SBIR record and official website identify Human Systems Integration Inc. at the matching address with matching wearable-electronics activity. The singular filing spelling is retained as an original alias; ownership remains unknown.'),
'798ca157270f93d1':('https://disclosurespreview.house.gov/data/LD/2026_Registrations_XML.zip','Original registration 301847858.xml names United Protective Technology at 142 Cara Court, Locust, North Carolina and describes military gear coatings. The federal award identifies United Protective Technologies, LLC at exactly that address and links upt-usa.com, whose footer gives the same plural legal name and coating activity. This corroborates the filing spelling variant; ownership remains unknown.')}
for i,(url,n) in items.items():
 v=p[i];before[i]=copy.deepcopy(v);v.update(review_outcome='confirmed',website_status='verified',checked_at='2026-09-13',notes=n,identity_evidence=n);v['sources'].append(dict(url=url,label='Primary entity identity evidence',claim=n))
 if i in ['22f6f4577a534702','57c1df21e64403b4']:v['ownership']='Private company'
 if i=='5616882e9336e9e2':v['name']='Human Systems Integration, Inc.';v['kind']='Wearable electronics company'
 if i=='798ca157270f93d1':v['name']='United Protective Technologies'
 dec.append(dict(id=i,url=url,notes=n))
for k,v in [('before',before),('decisions',dec)]: (r/f'featured220-{k}.json').write_text(json.dumps(v,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('7 identities, 1 website, 2 sourced ownership classifications')
