import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));before={};dec=[];assert not (r/'featured101-before.json').exists()
rows=json.load(open(r/'featured101-first10.json'));names=['Cann Inc.','Canon Medical Systems USA [Image Safely 360]','Cantor Fitzgerald, L.P.','ASCAP (represented through Capitol Dome Advocacy)','CareFirst BlueCross BlueShield','Cedars-Sinai','Changpeng Zhao','CHAOS Industries','The Charles Schwab Corporation','Chattem, Inc. (Opella)']
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for idx,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));f=dict(name=names[idx],description=d['description'],kind=d['kind'],ownership='Unknown',review_outcome='confirmed',notes=d['evidence'],website=d['website'],website_status='verified',status='sourced',checked_at='2026-09-13',as_of='2026-09-13');s=[src(d['official_url'],d['evidence'])]
 if idx==0:
  f.update(description='Cann Inc. is described in its 2026 lobbying registration as an alternative adult beverage company based in Oakland, California.',kind='Beverage company',review_outcome='partial',website=before[i].get('website',''),website_status='partial',notes='Rejected inactive Florida namesakes: original 2026 registration names an Oakland beverage company. Drinkcann terms identify SOCALI Manufacturing Inc.; legal bridge to filed Cann Inc. remains unresolved.');s=[src('https://disclosurespreview.house.gov/data/LD/2026_Registrations_XML.zip','Original member301847942.xml names Cann Inc., Oakland, and alternative adult beverage activity.'),src('https://drinkcann.com/pages/terms-conditions','Cann brand terms identify SOCALI Manufacturing Inc. as site owner, so exact filed Inc. identity is not assumed.')]
 if idx==1:
  f['ownership']='Subsidiary';f['notes']='Official Canon group directory names Canon Medical Systems USA Inc. Filed Image Safely360 qualifier is retained verbatim without asserting it is a separate legal company or verified campaign name.';s=[src(d['official_url'],'Official Canon group directory lists Canon Medical Systems USA Inc. and its medical imaging business.'),src('https://lda.senate.gov/filings/public/filing/400d5786-41eb-4a19-9909-9fb612729dac/print/','Original2026 report retains Canon Medical Systems USA [IMAGE SAFELY360] filing label.')]
 if idx==2:
  f['description']='Cantor Fitzgerald, L.P. is a financial-services group whose businesses provide investment banking, brokerage and related services.';f['notes']='Current company statement names exact Cantor Fitzgerald LP and its subsidiaries. Distinct Cantor Fitzgerald & Co., Securities and Income Trust entities are not merged.';s=[src('https://www.cantor.com/official-statement-by-cantor-fitzgerald-l-p-regarding-a-lawsuit-between-western-alliance-bank-and-cantor-group-v-llc/','October2025 official statement explicitly names Cantor Fitzgerald LP and its subsidiaries, disclaims affiliation with unrelated Cantor Group V LLC.'),src('https://www.cantor.com/media-center/','Current official media center describes investment banking and financial services businesses.')]
 if idx==3:
  f.update(description='ASCAP represents music creators and publishers in performance-rights licensing. This record names Capitol Dome Advocacy acting on ASCAP’s behalf.',kind='Music rights organization / represented-client record',website='https://www.ascap.com/');f['notes']='Original2026 LD2 names Capitol Dome Advocacy as registrant and ASCAP as client, with performance-rights licensing and copyright issues. Both roles retained; no automatic merge with another ASCAP record.'
 if idx==4:
  f['ownership']='Nonprofit';f['notes']='Current official careers page identifies CareFirst BlueCross BlueShield as a not-for-profit healthcare company. Brand scope retained without merging individual licensees.';s=[src('https://www.carefirst.com/careers',f['notes'])]
 if idx==5:
  f['ownership']='Nonprofit';f['notes']='Official giving FAQ explicitly identifies Cedars-Sinai as a nonprofit academic healthcare organization. Unsuffixed filing brand confirmed; no exact legal suffix added.';s=[src('https://www.cedars-sinai.org/giving/faqs.html',f['notes'])]
 if idx==6:
  f.update(description='Changpeng Zhao, also known as CZ, is the founder of cryptocurrency exchange Binance. This is an individual lobbying-client record.',kind='Individual',ownership='Not applicable',website='',website_status='unresolved');f['notes']='Original2026 registration identifies a cryptocurrency exchange entrepreneur. DOJ primary case record independently identifies exact Changpeng Zhao as Binance founder. Historical founder identity only; no current executive role or company ownership assigned.';s=[src('https://disclosurespreview.house.gov/data/LD/2026_Registrations_XML.zip','Original member301901824.xml identifies Changpeng Zhao as cryptocurrency exchange entrepreneur.'),src('https://www.justice.gov/criminal/case/united-states-v-changpeng-zhao','Primary DOJ record identifies Changpeng Zhao as founder of Binance; used for identity, not a claim of current office.')]
 if idx==7:
  f['notes']='Canadian Intellectual Property Office application2439364 identifies Chaos Industries Inc. in Hawthorne and radar/sensor threat-detection goods and services. This matches original advanced-defense business; registration pending is not described as a granted trademark.';s.append(src('https://ised-isde.canada.ca/cipo/trademark-search/pdf/2439364?lang=eng',f['notes']))
 if idx==8:
  f.update(ownership='Public company',website='https://www.aboutschwab.com/');f['notes']='Current2026 official investor page identifies exact Charles Schwab Corporation and NYSE SCHW. Operating brokerage and bank subsidiaries remain distinct.';s=[src('https://www.aboutschwab.com/investor-relations',f['notes'])]
 if idx==9:
  f['description']='Chattem, Inc. is a U.S. consumer-health business within Opella, which supplies nonprescription healthcare products.';f['notes']='Current Opella privacy center lists Chattem Inc. among its legal entities. Replaced dead Sanofi affiliate-list URL; no current Sanofi control or exact ownership percentage inferred. Filed DBA wording remains available among original aliases.';s=[src('https://www.opella.com/en/privacy-center/documents/workers-privacy-notice',f['notes']),src('https://www.actoralcare.com/en-us/contact','Official ACT oral-care product contact page names Chattem Inc.')]
 f['identity_evidence']=f['notes'];p[i].update(f);bad={d['official_url']}-{x['url'] for x in s};byurl={x['url']:x for x in p[i].get('sources',[]) if x['url'] not in bad}
 for x in s:byurl[x['url']]=x
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes'],sources=s))
(r/'featured101-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured101-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()));print('Status changes',[(i,b.get('status'),p[i]['status']) for i,b in before.items() if b.get('status')!=p[i]['status']])
