import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured108-first10.json'));supp={x['id']:x for x in json.load(open(r/'featured108-supplement.json'))};before={};dec=[]
assert not (r/'featured108-before.json').exists()
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for k,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));f=dict(name=p[i]['name'],description=d['description'],kind=d['kind'],ownership='Unknown',review_outcome=d['decision'],notes=d['evidence'],website=d['website'],website_status='verified',status='sourced',checked_at='2026-09-13',as_of='2026-09-13');s=[]
 if i in supp:
  v=supp[i];f.update(review_outcome=v['decision'],notes=v['evidence']);s=[src(v['official_url'],v['evidence'])]
 if k==0:
  f.update(name='Empower Retirement LLC (filed as formerly Great-West Life & Annuity)',website_status='partial',description='This retirement-services filing combines Empower Retirement LLC with a former insurer name. Official records show they are different legal entities.');f['notes']='Empower’s official 2022 notice maps Great-West Life & Annuity Insurance Company to Empower Annuity Insurance Company of America and explicitly says Empower Retirement, LLC was not renamed. The filing’s FKA label conflicts with that legal history, so its exact scope remains incomplete.';s=[src('https://www.empower.com/name-change',f['notes'])]
 if k==1:
  f.update(name='Enbridge (U.S.) Inc.',ownership='Subsidiary',description='Enbridge (U.S.) Inc. is a U.S. subsidiary within Enbridge’s energy-infrastructure group.');f['notes']='The 2025 Enbridge SEC Exhibit 21.1 lists exact Enbridge (U.S.) Inc. as a Delaware subsidiary. The original 2026 report names the same entity as both registrant and client; this record does not cover every Enbridge U.S. affiliate.';s=[src('https://www.sec.gov/Archives/edgar/data/895728/000119312526049810/enb-ex21_1.htm',f['notes'])]
 if k==2:
  f.update(name='ENSCO, Inc.',ownership='Private company');f['notes']='ENSCO’s July 20, 2026 official rail-contract announcement names exact ENSCO, Inc. and explicitly describes it as privately owned, with engineering and technology operations across defense, transportation, aerospace and intelligence. This is not the offshore-drilling namesake.';s=[src('https://www.ensco.com/news-media/press-releases/ensco-rail-awarded-contract-to-supply-ultrasonic-rail-flaw-detection-systems-urfs-for-taiwan-rail-project',f['notes'])]
 if k==3:
  f.update(name='Envision Healthcare (filed as formerly EmCare Inc.)',website_status='partial',description='Envision Healthcare provides clinical services. The filing also names EmCare Inc.; the exact legal relationship behind that former-name label remains unresolved.');f['notes']='Official Envision website establishes the healthcare business but does not establish the filed EmCare Inc. to Envision legal rename. No ownership or parent merger is inferred.';s=[src('https://www.envisionhealth.com/',f['notes'])]
 if k==4:
  f.update(name='Enviva LLC (filed as formerly Enviva LP)',website_status='partial',description='An Enviva wood-pellet business named in lobbying filings as Enviva LLC, formerly Enviva LP. Its exact legal-name history remains unresolved.');f['notes']='The official January 2022 announcement documents Enviva Partners, LP converting to Enviva Inc. on December 31, 2021. It does not establish the filed LLC/LP transition. The continuing wood-pellet activity is retained without promotional sustainability claims or inferred current ownership.';s=[src('https://www.envivabiomass.com/enviva-completes-corporate-conversion/',f['notes'])]
 if k==5:
  f.update(name='EssilorLuxottica (filed as formerly Essilor of America)',website_status='partial',description='A vision-care lobbying client filed as EssilorLuxottica, formerly Essilor of America, Inc. The precise legal entity behind this combined label remains unresolved.');f['notes']='The official 2024 URD subsidiary table lists Essilor of America, Inc. and EssilorLuxottica USA Inc. separately. The filing’s FKA wording is not independently established as a rename into the French public parent.';s=[src('https://www.essilorluxottica.com/cap/content/247586/?_iframe=true',f['notes'])]
 if k==6:
  f.update(name='EssilorLuxottica USA Inc.',ownership='Subsidiary',description='EssilorLuxottica USA Inc. is a U.S. company within the EssilorLuxottica eyewear and vision-care group.');f['notes']='Official 2024 URD, PDF page299, lists exact EssilorLuxottica USA Inc. as a fully consolidated U.S. subsidiary with 100% interest. The separate Essilor of America, Inc. row is preserved as a distinct entity; no French-parent stock listing is assigned.';s=[src('https://www.essilorluxottica.com/cap/content/247586/?_iframe=true',f['notes'])]
 if k==7:
  f.update(name='Farmers Group, Inc.',ownership='Subsidiary',kind='Insurance administration company',description='Farmers Group, Inc. provides administrative services to the Farmers insurance exchanges. Zurich owns this management company; policyholders own the exchanges.');f['notes']='Zurich’s August 6, 2026 results explicitly identify Farmers Group, Inc. as a wholly owned subsidiary and state Zurich has no ownership interest in the Farmers Exchanges. Farmers’ own companies page explains the administrative attorney-in-fact role.';s=[src('https://www.zurich.com/media/news-releases/2026/2026-0806-01',f['notes']),src('https://www.farmers.com/companies/','Official separation of Farmers Group administrative services from policyholder-owned Exchanges.')]
 if k==8:
  f.update(ownership='Subsidiary',description='FCA US LLC is the U.S. automaker within Stellantis, associated with brands including Chrysler, Dodge, Jeep and Ram.');f['notes']='The original 2026 LDA report explicitly identifies Stellantis and intermediate parent entities. Stellantis’ official 2022 release independently names exact FCA US LLC as its wholly owned subsidiary; the filed entity is kept distinct from the public parent.';s=[src(d['sources'][0]['url'],'2026 filing names FCA US LLC and explicitly identifies its parent entities.'),src('https://www.media.stellantis.com/em-en/corporate/press/fca-us-llc-reaches-agreement-with-u-s-attorney-s-office-to-resolve-diesel-emissions-investigation','Official Stellantis release names exact FCA US LLC as a wholly owned subsidiary.')]
 if k==9:
  f.update(name='Fenix International Limited (OnlyFans)',ownership='Private company',legal_form='UK private company limited by shares',description='Fenix International Limited operates OnlyFans, a subscription platform where creators sell access to their content.',logo_url='https://static2.onlyfans.com/static/prod/f/202609111149-a636f6190f/icons/android-chrome-192x192.png',logo_source_url='https://www.onlyfans.com/terms',logo_kind='site_icon',logo_status='official_site_asset',logo_background='light');f['notes']='OnlyFans terms name Fenix International Limited as operator. UK company10354575 is active and private limited; the current PSC register records Yekaterina Chudnovsky with at least75% shares and votes, notified March20,2026. The earlier Leonid Radvinsky control entry is ceased. Official site icon was fetched and visually verified.';s=[src('https://www.onlyfans.com/terms','Official terms identify Fenix International Limited as operator and link the verified site icon.'),src('https://find-and-update.company-information.service.gov.uk/company/10354575','Exact active UK private limited company.'),src('https://find-and-update.company-information.service.gov.uk/company/10354575/persons-with-significant-control','Current register lists Yekaterina Chudnovsky with75%or more shares and votes; earlier controller ceasedMarch2026.')]
 f['identity_evidence']=f['notes'];p[i].update(f);byurl={v['url']:v for v in p[i].get('sources',[])}
 for v in s:byurl[v['url']]=v
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes'],sources=s))
(r/'featured108-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured108-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()))
