import json,datetime,collections
from pathlib import Path
w=Path('work/research-2026');p=json.loads((w/'reviewed.json').read_text());ids=['6774eb6f24553e29','f317fa62cb7153e9','f023766070a945f4']
(w/'healthcare-followup-before.json').write_text(json.dumps({k:p[k] for k in ids},indent=2)+'\n')
def source(k,u,c):p[k]['sources'].append({'url':u,'label':'Primary ownership and identity evidence','claim':c})
k=ids[0];r=p[k];r.update(description='Renal Care 360 partners with health systems and physician practices to coordinate kidney and chronic-disease care, including patient education and early detection.',website='https://renalcare360.com/',website_status='verified',kind='Kidney and chronic care management company',ownership='Private company',review_outcome='confirmed',status='sourced')
r['identity_evidence']='The Tennessee LDA client description matches the mission statement on the official website. Pharos lists Renal Care 360 as a current Pharos IV investment, begun in 2022.';r['notes']='Privately backed by Pharos Capital. Exact ownership percentages are not disclosed in the cited portfolio page. Official logo remains unverified; direct site retrieval returned HTTP 403.'
source(k,'https://renalcare360.com/about-us/','Company mission, services, and Franklin, Tennessee address corroborate the LDA identity.')
source(k,'https://www.pharosfunds.com/portfolio/renal-care-360','Current Pharos IV investment, investment year 2022, company activity and website.')
k=ids[1];r=p[k];r.update(ownership='Subsidiary / operating company',kind='Medical aesthetics company',review_outcome='confirmed');r['identity_evidence']='Tiger Aesthetics Medical LLC announced its acquisition of Revelle Aesthetics Inc on November 8, 2024, identifying the company and its Avéli device.';r['notes']='Acquired by Tiger Aesthetics, a division of Tiger BioSciences, in November 2024. The release does not specify the surviving legal ownership chain or ownership percentages; historical venture backing is not presented as current ownership.'
source(k,'https://tiger-aesthetics.com/about/news/tiger-aesthetics-acquires-revelle-aesthetics-and-aveli-cellulite-reduction-device/','November 8, 2024 acquisition announcement identifies Revelle Aesthetics Inc and Avéli, and names Tiger Aesthetics Medical LLC as acquirer.')
k=ids[2];r=p[k];r.update(ownership='Private company',review_outcome='confirmed');r['identity_evidence']='Bain Capital Private Equity lists US Renal Care in its current investment portfolio, with its dialysis business and official website. The company announced a private investor-group transaction in 2019.';r['notes']='Current Bain Capital portfolio company. The 2019 company announcement also named management, Summit Partners, Revelstoke and Mark Caputo; present ownership percentages and continued participation of every historical investor are not established here.'
source(k,'https://baincapitalprivateequity.com/portfolio','Current investments include US Renal Care, a US dialysis operator; investment year 2019.')
source(k,'https://www.usrenalcare.com/press-releases/u-s-renal-care-to-be-acquired-by-investor-group/','Historical 2019 private investor-group transaction announcement; not used alone to establish current ownership.')
for k in ids:p[k]['checked_at']='2026-09-09'
for path,compact in [(w/'reviewed.json',False),(Path('lobbying-map/research/reviewed-2026.json'),True),(Path('outputs/2026-research-trial/profiles.json'),False)]:path.write_text(json.dumps(p,ensure_ascii=False,**({'separators':(',',':')} if compact else {'indent':2}))+'\n')
pub=json.loads((w/'publication.json').read_text());pub={k:v for k,v in pub.items() if not k.startswith('pending_')};pub.update(local_changes_pending=True,pending_source_pushed=False,pending_change_summary='Yubico, ZeroFox and three healthcare organization identity and ownership corrections')
(w/'publication.json').write_text(json.dumps(pub,indent=2)+'\n')
a=json.loads((w/'full-corpus-coverage-audit.json').read_text());a.update(as_of=datetime.datetime.now(datetime.timezone.utc).isoformat(),publication=pub,publication_stage='local_changes_pending',local_changes_pending=True)
for key,field in [('outcomes','review_outcome'),('websites','website_status'),('logos','logo_status'),('ownership','ownership')]:a[key]=dict(collections.Counter(v.get(field,'Unknown') for v in p.values()))
(w/'full-corpus-coverage-audit.json').write_text(json.dumps(a,indent=2)+'\n');print(a['outcomes'])
