import json,pathlib,copy
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));assert not (r/'featured185-before.json').exists();before={};dec=[]
rows=[('26bd286943f19fef','https://www.brimstone.com/privacy-policy','Official privacy policy explicitly identifies Brimstone Energy, Inc. as the operator of the Brimstone website. Identity is confirmed; ownership remains Unknown.',None),('4cea2a1485eab70e','https://brincdrones.com/lunch-and-learn-rsvp-landing-page/','Official event page discusses drone solutions for agencies and its footer explicitly names BRINC Drones Inc. at its Seattle address. This confirms the operating identity; ownership remains Unknown.',None),('068cd9605810276e','https://bridgerpipeline.com/wp-content/uploads/sites/5/2025/12/FERC26.23.0.pdf','Official tariff FERC26.23.0, effective January 1, 2026, names Bridger Pipeline LLC and covers petroleum transportation through its pipelines. It establishes the operating identity but not ownership.',None),('769a1ae1c9622df6','https://buhleryarn.com/about','Current official About page names Buhler Quality Yarns Corp., identifies its Jefferson, Georgia manufacturing site and describes technical and flame-resistant yarns. The old /about-our-company path returns404. Samil Spinning is described as a sister production facility; exact legal ownership remains Unknown.','Manufactures technical and flame-resistant yarns for protective apparel, as well as cotton yarns, at its Jefferson, Georgia facility.')]
for i,u,n,d in rows:
 v=p[i];before[i]=copy.deepcopy(v);v.update(review_outcome='confirmed',status='sourced',website_status='verified',checked_at='2026-09-13',identity_evidence=n,notes=n)
 if d:v.update(description=d,website=u)
 v['sources'].append(dict(url=u,label='Primary organization identity',claim=n));dec.append(dict(id=i,decision='confirmed',notes=n))
for name,value in [('before',before),('decisions',dec)]: (r/f'featured185-{name}.json').write_text(json.dumps(value,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('4 identities saved; Buhler website and description corrected')
