import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));ids=['6a6ecd34812b7679','087b73c2be4de158','a3d17478b9d61caa','a0c7fe1c2bb3c8b5','4d716e42b4e14088','cc3877c124df006c'];f=r/'featured296-before.json';assert not f.exists();f.write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n')
rows=[('https://capiopartners.com/','The readable official website explicitly names Capio Partners, LLC and describes collecting and managing outstanding medical bills. Exact legal identity is confirmed; ownership remains unknown.'),('https://capstonecopper.com/news/capstone-mining-and-mantos-copper-complete-combination-to-create-capstone-copper/','The March 23, 2022 company announcement explicitly names Capstone Mining Corp. as Old Capstone and says it became a wholly owned subsidiary of Capstone Copper through the completed transaction. This confirms the historical identity and relationship. The group website is a parent reference, and the parent ticker is not assigned to this historical subsidiary.'),('https://www.transportation.gov/buildamerica/sites/buildamerica.dot.gov/files/2026-03/Web%20Pipeline%20List.March%202026.pdf','The US DOT Build America Bureau pipeline dated March 1, 2026 names Canal Edge, LLC as applicant for Chicago Keeps America Moving, an Illinois rail project seeking RRIF credit assistance. This independently confirms the project entity. A pipeline listing is not evidence that a loan was approved or closed. Ownership and standalone website remain unknown.'),('https://media.cancercare.org/documents/378/original/Cures-2.0-Letter_CLC_8.2.2024.pdf','A 2024 policy letter hosted by coalition member CancerCare identifies Cancer Leadership Council as a patient-centered forum of national cancer advocacy organizations and names its participating signatories. This confirms the operating coalition. Standalone corporate and tax status remain unknown; current website availability is not established.'),('https://www.californiascreditunions.org/news/ca-and-nv-leagues-and-utah-cu-association-form-alliance/','The official February 28, 2024 announcement names the California and Nevada Credit Union Leagues and their joint support-services arrangement with Utah. It explicitly preserves each state entity’s advocacy governance and identity. The filed collective operating identity is confirmed; the partnership is not treated as a merger of the state entities.'),('https://www.californiascreditunions.org/news/ca-and-nv-leagues-and-utah-cu-association-form-alliance/','The official league website names California and Nevada credit-union trade associations and lists 2855 East Guasti Road, Suite 202, Ontario, matching the 2023 filing. Its February 28, 2024 announcement preserves separate state advocacy governance. Operating identity is confirmed; no single combined legal corporation is inferred.')]
for i,(u,n) in zip(ids,rows):
 q=p[i];q.update(review_outcome='confirmed',checked_at='2026-09-14',notes=n,identity_evidence=n);q['sources'].append({'url':u,'label':'Primary evidence reviewed September 14, 2026','claim':n})
p[ids[0]].update(legal_form='LLC',website_status='verified')
p[ids[1]].update(legal_form='Corporation',website_status='partial')
p[ids[2]].update(legal_form='LLC',kind='Project company',description='Named applicant for the Chicago Keeps America Moving rail project in the US DOT credit-assistance pipeline as of March 2026. Loan approval is not established.')
p[ids[3]].update(kind='Advocacy coalition',ownership='Unknown')
for i in ids[4:]:p[i].update(website='https://www.californiascreditunions.org/',website_status='verified',kind='Trade associations',ownership='Nonprofit',name='California and Nevada Credit Union Leagues'+(' (singular filing label)' if i==ids[5] else ''))
(r/'featured296-decisions.json').write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n');(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');print('Six primary-source identity confirmations saved.')
