import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));b={};ds=[]
a=[('e09fd7a3ccb44984','https://docs.cpuc.ca.gov/PUBLISHED/AGENDA_DECISION/143467.htm','A CPUC decision’s service list names exact California Bioenergy LLC and its calbioenergy.com contact. This corroborates the company identity and domain; current ownership is unverified.'),('69b185a2ac4432ff','https://opc.ca.gov/wp-content/uploads/2019/10/CAWorkingGroup_WebinarSummary_Sept262019.pdf','The California Ocean Protection Council’s September 2019 working-group summary identifies California Coastal Crab Association and its feedback on crab-fishing risk-reduction proposals. This establishes the association identity and activity, not tax status or current governance.'),('6ccbc8228301e7b0','https://www.cdfa.ca.gov/mkt/mkt/BoardCommissionSites.html','California’s Department of Food and Agriculture lists the California Sea Urchin Commission Law and directly links CalUrchin.org. This verifies the commission identity and official website relationship.'),('675201cb8a0a2738','https://www.cit.uscourts.gov/sites/cit/files/26-95.pdf','A US Court of International Trade opinion identifies Camel Energy as a Camel Group subsidiary and specifically names Camel Energy Inc. in its discussion of shipment documentation. This evidence is used for corporate identity; no allegation or shipment determination is generalized into a finding about the company.'),('351a7de5f6934df6','https://interactive.web.insurance.ca.gov/companyprofile/companyprofile?doFunction=getCompanyProfile&eid=6729&event=companyProfile','California’s insurance regulator identifies exact Canada Life Reinsurance Company, NAIC 76694, Pennsylvania domicile, and Great West group 0769. It records the London Life Reinsurance Company name change effective April 23, 2024. Group membership alone does not establish the precise ownership percentage.'),('2004e07e15a4b8b3','https://gaming.ny.gov/rivers-casino-resort-schenectady-commercial-casino-license','New York Gaming Commission’s license award explicitly names Capital Region Gaming LLC as Rivers Casino. The December 21, 2015 commission minutes independently identify its Rivers Casino & Resort at Mohawk Harbor trade name. Current ownership percentage remains unverified.'),('7988fcdee0a30d50','https://mncifa.mn.gov/sites/default/files/2026-04/2026-02_MnCIFA%20Carba%20landfill%20CO2%20sequestration.pdf','Minnesota’s climate-finance authority identifies exact Carba Inc., a $500,000 five-year loan and its woody-biomass pyrolysis project at Burnsville. This confirms business identity; the project’s carbon-storage claims are not independently validated by this directory.')]
assert not (r/'featured119-before.json').exists()
for i,u,note in a:
 b[i]=json.loads(json.dumps(p[i]));assert p[i]['review_outcome']!='confirmed';p[i].update(review_outcome='confirmed',notes=note,identity_evidence=note,checked_at='2026-09-13',as_of='2026-09-13');s={s['url']:s for s in p[i]['sources']};s[u]=dict(url=u,label='Government primary record',claim=note)
 if i=='e09fd7a3ccb44984':s.pop('https://www.treasurer.ca.gov/caeatfa/meeting/2024/0916/4b3.pdf',None)
 if i=='69b185a2ac4432ff':s.pop('https://opc.ca.gov/wp-content/uploads/2009/04/DCTF-Draft-Meeting-Summary-October-27-28-2021.pdf',None)
 if i=='351a7de5f6934df6':p[i]['ownership']='Unknown'
 p[i]['sources']=list(s.values());ds.append(dict(id=i,notes=note,url=u))
(r/'featured119-before.json').write_text(json.dumps(b,indent=2)+'\n');(r/'featured119-decisions.json').write_text(json.dumps(ds,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('7 government-backed identities saved')
