import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured113-input.json'));before={};dec=[]
assert not (r/'featured113-before.json').exists()
a=[
('confirmed','Subsidiary','Harley-Davidson Financial Services Inc.','Harley-Davidson Financial Services provides motorcycle financing and related financial services.','https://www.sec.gov/Archives/edgar/data/793952/000079395226000011/hog-20251231.htm','The2025 SEC10-K explicitly identifies Harley-Davidson Inc. as the controlling shareholder of exact Harley-Davidson Financial Services Inc. and recognizes non-controlling interests. This supports subsidiary status, not wholly owned status or the parent’s HOG listing.'),
('confirmed','Subsidiary','Harley-Davidson Motor Company','Harley-Davidson Motor Company manufactures motorcycles and sells parts, accessories and apparel.','https://www.sec.gov/Archives/edgar/data/793952/000079395226000029/a8kq12026exhibit991.htm','The2026 first-quarter company release filed with the SEC explicitly identifies Harley-Davidson Inc. as parent of Harley-Davidson Motor Company. The operating company remains distinct from the listed holding company.'),
('confirmed','Unknown','AT&T (via HB Strategies)','East Capitol Advisors reported lobbying for HB Strategies on behalf of AT&T, the communications company.','https://lda.gov/filings/public/filing/4ebc9f37-7c4a-4dc9-9390-1e559a0f6c21/print/','The original2026 report identifies East Capitol Advisors LLC as registrant, HB Strategies as intermediary and AT&T Inc. as beneficiary. The HB former-name wording remains a reported label; this is a representation record, not a separate corporation or proof of a legal rename.'),
('confirmed','Unknown','Great Lakes Dredge & Dock (via HB Strategies)','CJ Lake reported lobbying for HB Strategies on behalf of Great Lakes Dredge & Dock, a dredging and marine-construction business.','https://lda.gov/filings/public/filing/cb278f3d-299c-4e39-9ab4-b1e657fc83ad/print/','The original2026 report identifies CJ Lake LLC as registrant, HB Strategies as intermediary and Great Lakes Dredge & Dock Co. as beneficiary. This confirms the arrangement without assigning a parent stock listing to the abbreviated beneficiary entity.'),
('confirmed','Government body','San Diego Community Power (via HB Strategies)','CJ Lake reported lobbying for HB Strategies on behalf of San Diego Community Power, a public electricity provider.','https://lda.gov/filings/public/filing/92928fb2-d690-4b38-8234-cdc3c4b56e21/print/','The original2026 report names CJ Lake LLC as registrant and HB Strategies as intermediary. San Diego Community Power’s own About page confirms the beneficiary is a public agency created as a joint powers authority; it buys electricity delivered through SDG&E.'),
('partial','Unknown','HDT Global','HDT Global supplies military shelters, support equipment and other defense systems.','https://www.hdtglobal.com/2023/03/15/nexus-capital-management-lp-and-hdt-global-acquire-aviation-ground-equipment-corp/','The official2023 announcement establishes the HDT defense business and its Nexus portfolio relationship. It does not identify the exact HDT Global LLC legal entity present in the aliases; that remaining legal-entity bridge is incomplete.'),
('partial','Unknown','HealthEquity (filed as formerly WageWorks)','HealthEquity provides health-benefit account services and acquired WageWorks in2019. The filing combines the two names.','https://healthequity.com/investor-relations/press-releases/healthequity-completes-acquisition-wageworks','The retained official acquisition evidence supports WageWorks becoming a subsidiary, not HealthEquity being a former name of WageWorks. No new independent rename evidence was found; the combined filing label remains incomplete.'),
('confirmed','Unknown','HealthPlanOne, LLC (HPOne)','HealthPlanOne is an insurance agency that helps people research and enroll in Medicare and other health-insurance plans.','https://www.hpone.com/licensing.aspx','The official licensing page identifies exact HealthPlanOne LLC at3 Corporate Drive, Suite300, Shelton, Connecticut, with state insurance-license numbers. Its May2025 privacy policy also explicitly identifies the Connecticut agency. Ownership remains unknown.'),
('confirmed','Unknown','Heartland Water Technology, Inc.','Heartland Water Technology develops systems for treating industrial wastewater and managing waste.','https://www.sec.gov/Archives/edgar/data/1704027/000170402718000003/0001704027-18-000003-index.html','The SEC FormD index independently identifies exact Heartland Water Technology Inc. Its official operating website describes water and waste treatment. The historical securities notice does not establish current ownership.'),
('partial','Unknown','Helsing Inc.','A US lobbying client associated with Helsing’s defense-software and autonomous-systems business.','https://helsing.ai/newsroom/helsing-expands-us-market-selecting-west-virginia-for-its-first-u-s-resilience-factory','The retained official announcement supports the US operation, but this review did not independently establish the exact Inc. corporate identity and ownership chain. European parent branding alone is insufficient; the profile remains incomplete.')]
for row,v in zip(rows,a):
 i=row['id'];before[i]=json.loads(json.dumps(p[i]));out,own,name,desc,url,note=v;p[i].update(name=name,description=desc,ownership=own,review_outcome=out,notes=note,identity_evidence=note,status='sourced',checked_at='2026-09-13',as_of='2026-09-13')
 if out=='confirmed':p[i]['website_status']='verified'
 ss={s['url']:s for s in p[i].get('sources',[])};ss[url]=dict(url=url,label='Primary identity evidence',claim=note)
 if i=='118cd35a5abeedbe':ss['https://sdcommunitypower.org/about/']=dict(url='https://sdcommunitypower.org/about/',label='Official public-agency description',claim='Public agency and joint powers authority; electricity procurement role.')
 p[i]['sources']=list(ss.values());dec.append(dict(**row,decision=out,evidence=note,sources=[ss[url]]))
(r/'featured113-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured113-first10.json').write_text(json.dumps(dec,indent=2)+'\n');(r/'featured113-middle10.json').write_text('[]\n');(r/'featured113-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('7 confirmed; 3 partial')
