import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));before={};dec=[];assert not (r/'featured98-before.json').exists()
rows=json.load(open(r/'featured98-first10.json'))+json.load(open(r/'featured98-middle10.json'))
names=['Venture Global LNG, Inc.','Verifone','Verily Health Inc. (formerly Verily Life Sciences LLC)','Verisign','Vertex Pharmaceuticals','Viatris (filed as Mylan, Inc.)','Viking River Cruises','Viz.ai','VMware on behalf of Broadcom','Volkswagen Group of America, Inc.','Volkswagen Group of America, Inc.','Volvo Car Corporation','Washington Commanders',"Welch’s",'Whatnot Inc.','WHOOP','Wise','Wise US Inc.','Wolters Kluwer','Wrap Technologies']
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for idx,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));f=dict(name=names[idx],description=d['description'],kind=d['kind'],ownership=d['ownership'] if d['ownership'] in ['Unknown','Subsidiary','Public company'] else 'Unknown',review_outcome='confirmed',notes=d['evidence'],identity_evidence=d['evidence'],website=d['website'],website_status='verified',status='sourced',checked_at='2026-09-13',as_of='2026-09-13');s=[src(d['official_url'],d['evidence'])]
 if idx==0:
  f['ownership']='Subsidiary';f['notes']='Venture Global LNG Inc. remains a subsidiary distinct from publicly listed Venture Global Inc.; the 2025 parent financial statements identify exact VGLNG and the ownership reorganization.';s=[src('https://www.sec.gov/Archives/edgar/data/2007855/000200785526000013/vg-20251231.htm','2025 Form 10-K notes explain exact Venture Global LNG Inc., its subsidiary status and the parent ownership reorganization. Parent listing not assigned to VGLNG.')]
 if idx==2:
  f['description']='Verily Health Inc. develops health-data platforms and AI tools for clinical research and patient care.';f['notes']='March 19 2026 official announcement states conversion from LLC to corporation with new name Verily Health Inc. and that Alphabet is now a significant minority investor without control. Historical filed name preserved; no longer described as an Alphabet-controlled subsidiary.';f['legal_form']='Corporation';s.append(src('https://verily.com/newsroom/verily-secures-300-million-investment-to-advance-its-precision-health-ai-strategy',f['notes']))
 if idx==3:s.append(src('https://investor.verisign.com/','Current official investor page identifies Nasdaq VRSN and critical internet infrastructure and domain registry business.'))
 if idx==5:f.update(ownership='Unknown',review_outcome='partial',website_status='partial');f['notes']='Official Viatris site establishes Mylan Inc. as a Viatris company, but combined filing label does not yet resolve whether the exact client is parent or subsidiary. Parent stock listing is not assigned.'
 if idx==6:
  f['ownership']='Subsidiary';s=[src('https://ir.viking.com/sec-filings/all-sec-filings/content/0001745201-26-000007/vik-ex8_1.htm','March 2026 subsidiary exhibit explicitly lists Viking River Cruises Ltd, Bermuda, 100 percent, separately from Viking River Cruises (Bermuda) Ltd and U.S. Inc.'),src('https://ir.viking.com/sec-filings/all-sec-filings/content/0001745201-26-000021/vik-20260630.htm','August 2026 report describes the river-cruise business.')] ;f['notes']='Exact Ltd confirmed in 2026 subsidiary exhibit. Similar Bermuda, Liberia and U.S. legal entities remain separate; rejected unsupported guarantor excerpt from a different exhibit.'
 if idx==8:
  f.update(review_outcome='partial',website_status='partial',ownership='Unknown');f['description']='VMware supplies enterprise virtualization and infrastructure software within Broadcom. This filing names VMware acting on behalf of Broadcom.';f['notes']='Acquisition confirmed by official SEC release. Filed on-behalf-of scope retained; precise current legal entity and filing attribution still require original report review.'
 if idx in [9,10]:
  f['notes']='Original 2021 member 301295017.xml and 2025 member 301725856.xml describe an automotive manufacturer at 601 Pennsylvania Ave NW Suite 740 Washington DC 20004. The extra n in American is treated as a spelling variant; original filing names are retained.';s += [src('https://disclosurespreview.house.gov/data/LD/2021_Registrations_XML.zip','Member 301295017.xml: Volkswagen Group of America Inc., matching Washington address and automotive manufacturer activity.'),src('https://disclosurespreview.house.gov/data/LD/2025_Registrations_XML.zip','Member 301725856.xml: Volkswagen Group of American Inc., matching Washington address and automotive manufacturer activity.')]
 if idx==13:s.append(src('https://ncfc.org/members/national-grape-cooperative-association-inc/','National Council of Farmer Cooperatives member page explicitly describes Welch’s as the processing and marketing subsidiary of National Grape Co-operative.'))
 if idx==18:s.append(src('https://assets.contenthub.wolterskluwer.com/api/public/content/3244121-wolters-kluwer-n-v-agm-agenda-2026-4426c985ef?v=aa60cf76','2026 AGM agenda refers to ordinary Wolters Kluwer shares traded on Euronext Amsterdam.'))
 f['identity_evidence']=f['notes'];p[i].update(f);bad={d['official_url']}-{x['url'] for x in s};byurl={x['url']:x for x in p[i].get('sources',[]) if x['url'] not in bad}
 for x in s:byurl[x['url']]=x
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes'],sources=s))
(r/'featured98-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured98-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False))
mp=pathlib.Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(mp));ids=['d34af8dc20ff8406','71c8ed8036b98c12'];assert not any(set(ids)&set(x['source_ids']) for x in m)
(r/'featured98-merges-before.json').write_text(json.dumps(m,indent=2)+'\n');m.append(dict(canonical_id=ids[0],source_ids=ids,rationale=dec[10]['notes'],sources=dec[10]['sources'],reviewed_at='2026-09-13'));mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()));print('Status changes',[(i,b.get('status'),p[i]['status']) for i,b in before.items() if b.get('status')!=p[i]['status']])
