import json,pathlib,copy
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));before={};dec=[]
assert not (r/'featured129-before.json').exists()
def edit(i,fields,note,source,claim):
 before.setdefault(i,copy.deepcopy(p[i]));p[i].update(fields);p[i]['checked_at']='2026-09-13';p[i]['as_of']='2026-09-13';p[i]['notes']+=' '+note
 ss={s['url']:s for s in p[i]['sources']};ss[source]={'url':source,'label':'Official organization evidence','claim':claim};p[i]['sources']=list(ss.values());dec.append({'id':i,'name':p[i]['name'],'fields':fields,'note':note,'source':source})
logos=[('b96bad59715daf2e','https://www.fortworthtexas.gov/files/assets/public/v/2/communications/images/homepage-events/logo-fit-homepage-space.png?dimension=pageimage&w=480','https://www.fortworthtexas.gov/about/logo','logo','Official Fort Worth wordmark and Molly logo, visually inspected from the city’s logo page.'),('1d7f710cec979987','https://www.okc.gov/files/ocfavicon/City/apple-touch-icon.png','https://www.okc.gov/','site_icon','Official Oklahoma City site icon, visually inspected; this is the website’s identifying crest.'),('1739c3676f808109','https://www.losalamosnm.gov/files/templates/00000000-0000-0000-0000-000000000000/b383ba09-6661-400a-bb0e-f6c41419403a/v/275/LAC_Logo_Color_StraplineH.png','https://www.losalamosnm.gov/','logo','Official Los Alamos County website logo, visually inspected.'),('d6cf11e5f482ec2a','https://www.kochinc.com/assets/koch-logo-color.svg','https://www.kochinc.com/','logo','Displayed logo is the shared Koch group brand, not a separate logo or ownership proof for Koch Government Affairs LLC.')]
for i,u,src,kind,note in logos:edit(i,dict(logo_url=u,logo_source_url=src,logo_kind=kind,logo_status='official_site_asset',logo_background='light'),note,src,note)
edit('af03e754890d8b37',{'website_status':'verified'},'The current khaero.com page identifies Kraus Hamdani Aerospace and its autonomous aircraft and communications systems.','https://www.khaero.com/','The official page names Kraus Hamdani Aerospace and describes its autonomous aerospace systems.')
i='83a1867279784562';edit(i,{'website':'https://www.usoma.us/en','website_status':'verified','ownership':'Nonprofit'},'USOMA’s own site names the United States OCTG Manufacturers Association and its domestic pipe-manufacturing mission. IRS EIN 93-4299389 lists the exact association in Washington DC under subsection 06.','https://www.usoma.us/en','Official USOMA website identifies the association and its domestic OCTG manufacturing members.')
p[i]['sources'].append({'url':'https://www.irs.gov/pub/irs-soi/eo2.csv','label':'IRS exempt organization record','claim':'EIN 934299389: US OCTG MANUFACTURERS ASSOCIATION, 900 7TH ST NW STE 500, WASHINGTON DC, subsection06.'})
(r/'featured129-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured129-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('Saved four official assets, two verified websites and exact USOMA nonprofit classification')
