import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));before={};dec=[];assert not (r/'featured100-before.json').exists()
rows=json.load(open(r/'featured100-first10.json'));names=['Ancestry','Aon (including filed Aon Corporation aliases)','BYD Motors, LLC and U.S. subsidiaries','ByteDance Inc.','C&S Wholesale Grocers (filed as Inc.)','Caesars Enterprise Services, LLC','California Forever, LLC','Cambium Learning Group, Inc.','Campari America','Canadian National Railroad']
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for idx,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));f=dict(name=names[idx],description=d['description'],kind=d['kind'],ownership='Unknown',review_outcome='confirmed',notes=d['evidence'],website=d['website'],website_status='verified',status='sourced',checked_at='2026-09-13',as_of='2026-09-13');s=[src(d['official_url'],d['evidence'])]
 if idx==0:
  f['notes']='Current official terms establish Ancestry family-history and DNA brand; service-specific operating entities are not collapsed. Current Blackstone people page still lists Ancestry among investments, but does not establish a current ownership percentage.';s.append(src('https://www.blackstone.com/the-firm/our-people/','Current people biographies include Ancestry among Blackstone current investments.'))
 if idx==1:
  f.update(review_outcome='partial',website_status='partial');f['notes']='2025 Aon plc 10-K identifies Aon Corporation as an indirect wholly owned subsidiary, distinct from the listed parent. Mixed unsuffixed AON and Corporation aliases require filing-level attribution before assigning one ownership category.';s=[src(d['official_url'],f['notes'])]
 if idx==2:f['notes']='Official U.S. contact page explicitly names BYD Motors LLC. Combined filing scope includes various U.S. subsidiaries; no parent listing or complete ownership chain is inferred from a contact page.'
 if idx==3:
  f['description']='ByteDance Inc. is named in ByteDance’s official website policy as an entity offering internet technology products and services.';f['notes']='Official ByteDance.com privacy policy explicitly names ByteDance Inc. and distinguishes product-specific policies. Does not equate Inc. with ByteDance Ltd. or assert current ownership of the U.S. TikTok joint venture.';s=[src(d['official_url'],f['notes'])]
 if idx==4:f.update(review_outcome='partial',website_status='partial');f['notes']='Official vendor terms directly name the historical Inc. entity; current corporate pages use LLC. Legal conversion has not been established and is not inferred.'
 if idx==5:
  f['description']='Caesars Enterprise Services provides services within Caesars’ hospitality business and is named as the Caesars Rewards Dining program partner.';f['notes']='Current official Caesars Rewards Dining terms explicitly name Caesars Enterprise Services LLC as Rewards Partner. Replaced inaccessible generic terms URL and avoided transferring public parent ownership.';s=[src('https://support.caesarsrewardsdining.com/hc/en-us/articles/360000241067-Terms-of-Use',f['notes'])]
 if idx==6:
  f['description']='California Forever is a development company proposing a new community in Solano County, California.';f['notes']='March2026 Fairfield-Suisun Sewer District meeting packet names California Forever LLC and Jan Sramek as manager, with legal@californiaforever.com contact. This bridges the LLC to the project website; proposed work is not described as completed.';s.append(src('https://www.fairfieldsuisunsewer.ca.gov/wp-content/uploads/2026/03/Executive-Committee-Meeting-Agenda-2026.03.16.pdf',f['notes']))
 if idx==7:
  f['notes']='Exact Inc. and education-technology activity established by official company and investor material. Veritas acquisition closed in2018 and stock ceased trading then; historical transaction is dated and no current percentage is invented.';s=[src('https://www.veritascapital.com/veritas-capital-completes-acquisition-of-cambium-learning-group-2/','December2018 investor announcement identifies exact Cambium Learning Group Inc., completed acquisition by Veritas affiliates and cessation of Nasdaq ABCD trading.'),src('https://www.cambiumlearning.com/','Current official company website supports continuing education-technology brand and activity.')]
 if idx==8:f['ownership']='Subsidiary';f['notes']='June30 2025 official group report lists exact Campari America LLC, manufacturing and trading company, as100percent owned. Group website retained without assigning parent logo or listing.'
 if idx==9:f.update(review_outcome='partial',website_status='partial');f['notes']='Official investor site identifies Canadian National Railway Company, but original unsuffixed Railroad filing has not been bridged to the issuer rather than a group subsidiary. No public ownership category assigned.'
 f['identity_evidence']=f['notes'];p[i].update(f);bad={d['official_url']}-{x['url'] for x in s};byurl={x['url']:x for x in p[i].get('sources',[]) if x['url'] not in bad}
 for x in s:byurl[x['url']]=x
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes'],sources=s))
(r/'featured100-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured100-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()));print('Status changes',[(i,b.get('status'),p[i]['status']) for i,b in before.items() if b.get('status')!=p[i]['status']])
