import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));ids=['3ccbb0065515a6c0','3bed5e1e0d4f2a95','8740fdf4e6a6a410','79022125b95ae74d'];f=r/'featured293-before.json';assert not f.exists();f.write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n')
rows=[('https://caiphi.com/terms-conditions/','Official terms dated February 14, 2023 explicitly name CAIPHI, Inc. as operator of caiphi.com and its healthcare products. This confirms the exact legal identity. The earlier password-protection response was an access limitation, not evidence of identity. Ownership remains unknown.'),('https://www.calcasieu.gov/public-visitors/parish-history','The official parish history identifies Calcasieu Parish as governed by the elected Police Jury. The exact government name matches registration 301317660 from 2021. This is a parish government, not a private policing company.'),('https://news.pacificsurfliner.com/CIRCLE-Advocacy-Coalition-Formed-by-California-Intercity-Rail-Corridors','The October 21, 2021 announcement by a founding rail agency explicitly establishes CIRCLE, California’s Intercity Rail Corridors Linking Everyone, as an advocacy coalition of LOSSAN, CCJPA and SJJPA. This matches the named intercity-rail client in registration 301447948 from 2023. The source is a member agency; no standalone coalition website or corporate status is asserted.'),('https://calumetheritage.org/','The indexed official homepage names Calumet Heritage Partnership, Inc. and lists 1100 N Mineral Springs Rd, Chesterton, Indiana, matching registration 301672346 from 2025. It describes a partnership preserving and interpreting the Illinois-Indiana Calumet region’s heritage. The page was available through the search index; direct HTTPS retrieval failed, so current availability is not asserted.')]
for i,(u,n) in zip(ids,rows):
 q=p[i];q.update(review_outcome='confirmed',checked_at='2026-09-14',notes=n,identity_evidence=n);q['sources'].append({'url':u,'label':'Primary identity evidence reviewed September 14, 2026','claim':n})
p[ids[0]].update(name='CAIPHI, Inc.',legal_form='Corporation',website_status='verified')
p[ids[1]].update(ownership='Government body',kind='Parish government',legal_form='Parish government',website_status='verified')
p[ids[2]].update(name='California Intercity Rail Corridors Linking Everyone (CIRCLE)',kind='Advocacy coalition',ownership='Unknown')
p[ids[3]].update(website_status='verified',legal_form='Corporation')
(r/'featured293-decisions.json').write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n');(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');print('Four additional identities saved.')
