import json,gzip
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));ids=['60a221be15ffa527','ced715c8caa88779','96aba871d2ec839e','b1b45bef1722fdd5'];f=r/'featured287-before.json';assert not f.exists();f.write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n')
notes=[
'Current LDA client 69475 explicitly identifies Burrell International Group acting on behalf of AMO Pharma. The official website describes rare-disease drug development, explicitly calls AMO privately held, and lists AMO Pharma Ltd., 1 Park Row, Leeds, matching direct registration 301801072 in the 2025 archive. The intermediary and beneficiary are distinguished.',
'Current LDA client 72900 explicitly identifies Burrell International Group LLC acting on behalf of Sentry View Systems, Inc. The official website names Sentry View Systems and lists 2700 Business Center Blvd, Melbourne, Florida, matching direct registration 301842975. It describes command-and-control, surveillance and remote-system integration. Ownership remains unknown.',
'Current LDA client 56491 explicitly identifies Burrell International Group LLC acting on behalf of Shionogi Inc. The official US website footer names Shionogi Inc. in Florham Park, New Jersey, matching direct registration 301874300. The US entity is confirmed; the global group’s public status is not assigned to this subsidiary without separate ownership evidence.',
'Current LDA client 66794 identifies Business Software Alliance, Inc., an enterprise-software trade association. BSA’s January 6, 2025 announcement explicitly connects Business Software Alliance with its earlier BSA | The Software Alliance brand. This duplicate joins the existing BSA organization while preserving its original filings and name.'
]
for i,n in zip(ids,notes):
 q=p[i];q.update(review_outcome='confirmed',website_status='verified',checked_at='2026-09-14',notes=n,identity_evidence=n)
 q['sources'].append({'url':q['website'] if i!=ids[3] else 'https://www.bsa.org/news-events/news/bsa-rebrands-as-business-software-alliance','label':'Official identity evidence reviewed September 14, 2026','claim':n})
p[ids[0]].update(name='AMO Pharma (represented by Burrell International Group)',kind='Biopharmaceutical company',ownership='Private company')
p[ids[1]].update(name='Sentry View Systems, Inc. (represented by Burrell International Group)',kind='Company',legal_form='Corporation',logo_url='https://images.squarespace-cdn.com/content/v1/64898c6803839c75bd5223a1/892073bf-fc87-4e7e-b337-2194124e2011/svs+logo+white.png?format=1500w',logo_kind='logo',logo_status='official_site_asset',logo_source_url='https://sentryviewsystems.com/')
p[ids[2]].update(name='Shionogi Inc. (represented by Burrell International Group)',kind='Pharmaceutical company',legal_form='Corporation',logo_url='https://www.shionogi.com/content/dam/shionogi/si/top/top-logo-03.png',logo_kind='logo',logo_status='official_site_asset',logo_source_url='https://www.shionogi.com/us/en/about.html')
(r/'featured287-decisions.json').write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n');(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n')
mp=Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(mp));(r/'featured287-merge-before.json').write_text(json.dumps(m,indent=2)+'\n');g=next(x for x in m if x['canonical_id']=='ca1ebe3b2a885ba2');assert not any(ids[3] in x['source_ids'] for x in m);d=json.load(gzip.open('lobbying-map/public/data/directory-v3.json.gz','rt'));cards={x['id']:x for x in d['companies'] if x['id'] in [g['canonical_id'],ids[3]]};assert len(cards)==2;(r/'featured287-cards-before.json').write_text(json.dumps(cards,indent=2)+'\n');g['source_ids'].append(ids[3]);g['rationale']+=' Additional Business Software Alliance Inc. client 66794 is the same operating association and is consolidated with original records retained.';mp.write_text(json.dumps(m,indent=2,ensure_ascii=False)+'\n');print('Saved four confirmations, two official logos and one additional BSA duplicate.')
