import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'))
rows={
'f73582cd28f7260c':('https://www.chaldeanfoundation.org/','Official foundation body retrieved September 14, 2026','Confirmed operating identity: the official Chaldean Community Foundation site names the organization, its Sterling Heights location and its acculturation, education, health-access, housing and minority-advocacy programs. The previously excluded mismatched IRS return remains excluded; no exact tax subsection is assigned.',{}),
'a4393fbbca9a4d6a':('https://www.charter.space/for-engineers','Official product body retrieved September 14, 2026','The official Charter site independently identifies its Ubik spacecraft-engineering and mission-planning software and linked insurance services. These match the San Francisco space-insurance client in registration 301897044. Operating identity is confirmed; current ownership and a separate legal corporate form remain unknown.',{'website_status':'verified'}),
'9e282e12154ab5e4':('https://www.charter.space/insurance','Official insurance-services body retrieved September 14, 2026','The official Charter site describes its space-industry insurance brokerage, including pre-launch, launch and on-orbit coverages. This confirms the operating service corresponding to the original Charter Space Insurance filing label. A separate insurance corporation, underwriter role or ownership relationship is not inferred, and the two Charter filing records remain separate.',{'description':'Charter’s space-insurance brokerage offering coverage for launch, on-orbit and other risks faced by space companies.'}),
'58e4a7fda7f98605':('https://charterbrokerage.net/customs-broker/','Official company body inspected through indexed retrieval','The official page describes customs brokerage, import/export clearance and duty-drawback services. Its CEO letter explicitly names Charter Brokerage LLC. Operating identity is confirmed. The historical Berkshire acquisition remains dated evidence; the current direct ownership chain is not asserted, and Charter Brokerage Services remains a separate filing name.',{'website_status':'verified','legal_form':'LLC'}),
'62ce0c8d04b5e0d8':('https://arlweb.msha.gov/REGS/Comments/2011-2255/AB73-COMM-30.pdf','MSHA comment, April 4, 2011; downloaded and read','The signed government-filed comment explicitly names Coal Operators & Associates, Inc. at Pikeville, Kentucky and describes an Eastern Kentucky trade association serving coal producers, suppliers and related firms. This independently confirms the historical organization named in lobbying records. Current membership, tax status, ownership and website remain unknown.',{'legal_form':'Corporation'}),
'e1b6dc97ba9fc287':('https://21stcenturypostal.org/about/','Official coalition body inspected through indexed retrieval','The official coalition site identifies its mission of restoring postal-system financial stability through legislation and public advocacy. This confirms the exact operating coalition; corporate incorporation or tax exemption is not required to recognize the coalition and is not asserted.',{'kind':'Trade coalition','website_status':'verified'}),
'be64c47aeb902e65':('https://www.erai.com/ewaste_industry_response','Industry association body retrieved September 14, 2026','ERAI independently identifies the Coalition for American Electronics Recycling and its domestic electronics-recycling and anti-counterfeit policy advocacy. Operating identity is confirmed. The undated source’s membership totals are not presented as current, and the coalition’s present legal form, governance and website availability remain unverified.',{}),
'eb53efcb54d6ccf7':('https://clinicalresearchforum.org/Advocacy/Coalition-for-Clinical-and-Translational-Science','Official member-organization body retrieved September 14, 2026','Clinical Research Forum identifies itself as an active member of the Coalition for Clinical and Translational Science and describes the nationwide research-policy network. This confirms the current coalition identity and activity. The former-name parenthetical remains a reported filing label, not an independently established legal name change; no nonprofit tax subsection is inferred.',{}),
'cf9e5735d15a3719':('https://www.aham.org/','Official organization site inspected September 14, 2026','The Association of Home Appliance Manufacturers is independently identified on its official AHAM site, with member, governance, standards and advocacy materials. The previous partial status reflected an ownership/tax-status gap, not an unresolved operating identity. Exact tax exemption remains unverified.',{'name':'Association of Home Appliance Manufacturers (AHAM)'}),
'1cee5e81694033b2':('https://apps.douglas.co.us/planning/projects/Default.aspx?PosseObjectId=94680573&PossePresentation=SubdivisionJob','Douglas County planning record SB2024-052, inspected September 14, 2026','Douglas County’s approved Sterling Ranch Filing 7B planning record explicitly names Sterling Ranch LLC as property owner at 8155 Piney River Avenue, Littleton, Colorado. This corroborates the official community website and exact LLC identity. It identifies property ownership, not the owners of the LLC; corporate ownership remains unknown.',{'legal_form':'LLC','website':'https://sterlingranch.com/','website_status':'verified'}),
'845079aaa42780aa':('https://cdn-web.cemex.com/documents/20143/65216227/02-ordinary-JGA2023-2022-audited-consolidated-financial-statements.pdf/ecb8b5f9-1a3d-a2be-faad-0ddc938644d2?t=1677173486627','Official audited financial statements, 2022; indexed table inspected','CEMEX’s audited financial statements name CEMEX, Inc. in the United States and report 100% group interest for 2022 and 2021. This corroborates the exact US subsidiary identity and its building-materials activity. The ownership percentage is historical, not a claim that the 2026 direct-parent chain was checked; the Mexican parent’s stock ticker is not assigned to this subsidiary.',{'ownership':'Subsidiary','legal_form':'Corporation'})
}
b=r/'featured310-before.json';assert not b.exists();b.write_text(json.dumps({i:p[i] for i in rows},indent=2,ensure_ascii=False)+'\n')
for i,(url,label,note,fields) in rows.items():
 p[i].update(fields);p[i].update(review_outcome='confirmed',checked_at='2026-09-14',notes=note,identity_evidence=note)
 p[i]['sources'].append({'url':url,'label':label,'claim':note})
(r/'featured310-decisions.json').write_text(json.dumps({i:p[i] for i in rows},indent=2,ensure_ascii=False)+'\n')
(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n')
print(f'Saved {len(rows)} identity decisions; no legal-entity merges.')
