import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));before={};dec=[]
assert not (r/'featured92-before.json').exists()
rows=json.load(open(r/'featured92-first10.json'))+json.load(open(r/'featured92-middle10.json'))
names=['Mastercard (via Tower 19)','The Toy Association, Inc.','Toyota','Toyota Tsusho America, Inc.','TPG','TracPlus','Tractor Supply Company','Tradeverifyd / mesur.io','Traditional Medicinals','Traeger Pellet Grills, LLC','Trane Technologies','Trans Union LLC','Transamerica Companies','Transamerica Life Insurance Company','TransMedics, Inc.','Trans Union LLC','Tree of Life — Pittsburgh memorial and museum','Trellix','Trellix (filed as formerly Musaruba US LLC)','Trellix Public Sector LLC']
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for idx,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));f={k:d[k] for k in ['description','kind','website']};f.update(name=names[idx],ownership='Unknown',review_outcome='confirmed',notes='Official organization materials establish the filed identity and described activity. Ownership remains unknown unless separately sourced.',checked_at='2026-09-13',as_of='2026-09-13',status='sourced',website_status='verified');s=[src(d['official_url'],d['exact_official_excerpt'])]
 if idx==0:
  f.update(kind='Represented-client filing label',ownership='Not applicable');f['notes']='2026 original filing expressly names Tower 19 on behalf of Mastercard. This is a represented-client label, not a corporate ownership relationship.';s.append(src('https://lda.gov/filings/public/filing/058b8002-6fcb-40f4-bfb9-161db0f78911/print/',f['notes']))
 if idx==1:
  s=[src('https://www.toyassociation.org/','Official site identifies The Toy Association, Inc. and its toy-industry advocacy and services.')];f['notes']='Exact association name and activity confirmed. The separate Toy Foundation is not this filing entity; nonprofit classification is left unknown without direct supporting evidence.'
 if idx==2:f['notes']='Confirmed at Toyota automotive-brand scope. Unsuffixed filing name does not select a specific subsidiary or transfer Toyota Motor Corporation listing status to an unspecified affiliate.'
 if idx==3:f['ownership']='Subsidiary';f['notes']='Toyota Tsusho 2025 financial-section subsidiary table identifies Toyota Tsusho America, Inc. as a 100 percent overseas subsidiary.'
 if idx in [4,6,10]:f['ownership']='Public company'
 if idx==4:f['website']='https://shareholders.tpg.com/ir-resources/investor-faqs'
 if idx==7:f['notes']='Official terms explicitly connect Tradeverifyd and mesur.io websites to mesur.io, Inc. Brand/operator relationship confirmed; no legal corporate rename is inferred from the filed FKA.'
 if idx==8:f['notes']='Confirmed at the unsuffixed herbal-tea brand scope. A third-party webstore operator is not treated as the lobbying client.'
 if idx==9:s=[src('https://www.traeger.com/terms-and-conditions','Official terms identify Traeger Pellet Grills, LLC as a Delaware limited liability company. The public parent is not substituted for this LLC.')]
 if idx==10:s=[src('https://investors.tranetechnologies.com/news-and-events/news-releases/news-release-details/2026/Trane-Technologies-Reports-Strong-Second-Quarter-Results-Raises-Full-Year-Revenue-and-EPS-Guidance/default.aspx','July 2026 issuer release identifies Trane Technologies plc, NYSE TT, and its climate-solutions business.')]
 if idx in [11,15]:
  f['ownership']='Subsidiary';f['notes']='Official legal terms use both TransUnion LLC and Trans Union LLC on the same page, with 555 W. Adams St., Chicago. Original registrations match that address. Existing verified merge already preserves both source IDs; no new merge added.';s += [src('https://www.transunion.com/legal/terms-of-use','Official terms use both spaced and unspaced LLC names and the same Chicago address.'),src('https://disclosurespreview.house.gov/data/LD/2020_Registrations_XML.zip','Original registration 301182761.xml names Trans Union LLC at 555 West Adams Street.'),src('https://disclosurespreview.house.gov/data/LD/2015_Registrations_XML.zip','Original registration 300767944.xml names TransUnion LLC at 555 W. Adams Street.')]
 if idx==12:
  s=[src('https://insuranceservicenow.transamerica.com/about_us.aspx','Official customer-service information describes Transamerica as the marketing name covering specified Transamerica insurers and related companies.')];f['notes']='Confirmed at the collective Transamerica brand scope; separate legal insurers retain their own identities. Ownership not inferred for every company in the collective label.'
 if idx==14:
  f.update(ownership='Subsidiary',kind='Medical-device company',website='https://www.transmedics.com/');s=[src('https://www.sec.gov/Archives/edgar/data/1756262/000119312526067032/tmdx-20251231.htm','Current Form 10-K identifies TransMedics, Inc. as an operating company wholly owned by TransMedics Group, Inc.')];f['notes']='The Inc. subsidiary is distinct from the listed TransMedics Group, Inc. parent; no public-company classification is transferred.'
 if idx==16:
  f.update(ownership='Nonprofit',kind='Memorial and museum',website='https://www.thetreeoflife.org/',description='Tree of Life is the Pittsburgh memorial, museum and education initiative addressing antisemitism after the 2018 synagogue attack.');s=[src('https://lda.gov/filings/public/filing/0567b117-1a2a-42f4-a065-e52a6b8682a3/print/','Original registration identifies a memorial and museum at 5898 Wilkins Avenue, Pittsburgh.'),src('https://www.thetreeoflife.org/','Official initiative site describes the memorial, museum and education work.'),src('https://www.thetreeoflife.org/donate','Official donation page identifies the charitable organization, EIN 88-1323223, with checks payable to T of L, Inc.')];f['notes']='Registration address and museum activity disambiguate this record. Corrected website to the memorial/museum initiative rather than the separate congregation. No legal merge with the congregation.'
 if idx==17:f['notes']='Confirmed at the unsuffixed cybersecurity brand scope. Official site describes Trellix products and history; no unsupported legal rename or ownership category added.'
 if idx==18:
  f.update(review_outcome='partial',website_status='partial');s=[src('https://www.trellix.com/about/','Official site identifies the Trellix cybersecurity brand and footer names Musarubra US LLC.')];f['notes']='Filed Musaruba spelling and former-name relation need a direct identity bridge. Current official site names Musarubra US LLC; a brand launch does not itself prove a legal rename. Preserve distinct source record.'
 if idx==19:f['kind']='Government-focused cybersecurity company';f['notes']='Official professional-services terms identify the exact Trellix Public Sector LLC legal entity. Preserve it separately from the general brand and Musarubra records.'
 f['identity_evidence']=f['notes'];p[i].update(f);byurl={x['url']:x for x in p[i].get('sources',[])}
 for x in s:byurl[x['url']]=x
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes']))
(r/'featured92-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured92-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()));print('Status changes',[(i,b.get('status'),p[i]['status']) for i,b in before.items() if b.get('status')!=p[i]['status']])
