import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));b={};ds=[]
a=[('20e8029198d7569e','Government body','https://hohtribe-nsn.org/','The Hoh Tribe’s official website identifies its sovereign tribal government in western Washington, consistent with the Bureau of Indian Affairs Olympic Peninsula agency listing. The former guessed .gov domain did not resolve and has been replaced with the verified .org website.'),('48684b2f95ad6eee','Government body','https://www.uii.utah.gov/pmn/sitemap/publicbody/2535.html','Utah’s Public Notice Website lists exact Housing Authority of Salt Lake City as a public body. The authority’s housing portal independently uses the same name. The generic city housing-department page is not treated as the authority’s own website.'),('cd14b14a309d30fc','Unknown','https://www.sbir.gov/portfolio/875123','The federal SBIR portfolio identifies exact Hydronalix Inc., UEI X7NNB7Q6Y5K1, at 1691 W Duval Commerce Court in Green Valley, Arizona, and describes robotic aquatic-system awards. Identity is established; current ownership remains unverified.'),('1d99788083600917','Unknown','https://www.idl.idaho.gov/wp-content/uploads/sites/2/land-board/lb/minutes-archive/2023/041823-materials-lb-watermark-v0418.pdf','An April 11, 2023 Idaho Forest Group letter in Department of Lands board materials identifies its Moyie Springs address, idfg.com domain and timber-sale activity. This confirms the business identity and historical domain relationship; current ownership is unverified.'),('5c6e36763b077daf','Unknown','https://data.capitol.hawaii.gov/sessions/session2022/Testimony/HB1687_TESTIMONY_EEP_01-30-24_.PDF','January 2024 Hawaii legislative testimony identifies exact Inception Financial LLC and managing partner Ryan Hamilton in connection with energy-resiliency policy and investment. This establishes identity and activity, not the firm’s ownership classification.')]
assert not (r/'featured123-before.json').exists()
for i,own,u,note in a:
 b[i]=json.loads(json.dumps(p[i]));assert p[i]['review_outcome']!='confirmed';p[i].update(ownership=own,review_outcome='confirmed',notes=note,identity_evidence=note,checked_at='2026-09-13',as_of='2026-09-13');ss={s['url']:s for s in p[i]['sources']};ss[u]=dict(url=u,label='Primary identity evidence',claim=note)
 if i=='20e8029198d7569e':
  ss={u:s for u,s in ss.items() if 'hohtribe-nsn.gov' not in u};p[i].update(website='https://hohtribe-nsn.org/',website_status='verified',logo_url='https://hohtribe-nsn.org/wp-content/uploads/2020/04/logo.png',logo_source_url='https://hohtribe-nsn.org/',logo_kind='logo',logo_status='official_site_asset',logo_background='light')
 p[i]['sources']=list(ss.values());ds.append(dict(id=i,url=u,notes=note))
(r/'featured123-before.json').write_text(json.dumps(b,indent=2)+'\n');(r/'featured123-decisions.json').write_text(json.dumps(ds,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('5 identities; Hoh website and official logo corrected')
