import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured105-first10.json'));before={};dec=[];assert not (r/'featured105-before.json').exists()
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
delta_sources=[src('https://lda.gov/filings/public/filing/17bdf393-4380-48d8-9c4b-c27a4436a877/print/','Original2010Delta registration with Capitol Tax Partners: airline at1212NewYorkAvenueNW Suite200; House356170047 retained in2026.'),src('https://lda.gov/filings/public/filing/c6d7a5aa-8be6-4483-8f5e-93a73db83e4c/print/','Original2025DeltaAirlines registration: commercial aviation at1030DeltaBlvdAtlanta.'),src('https://news.delta.com/sites/default/files/Objections%20to%20Show%20Cause%20Order.pdf','Delta-hosted2016DOTsubmission names exact Delta Air Lines Inc. at matching Washington suite and Atlanta headquarters.'),src('https://www.delta.com/us/en/legal/privacy-and-security','May2026policy names Delta Air Lines Inc. and1030DeltaBlvdAtlanta.')]
for k,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));f=dict(name=before[i]['name'],description=d['description'],kind=d['kind'],ownership='Unknown',review_outcome='confirmed',notes=d['evidence'],website=d['website'],website_status='verified' if d['website'] else 'unresolved',status='sourced',checked_at='2026-09-13',as_of='2026-09-13');s=[]
 if k==0:
  f.update(name='CX2 Inc.',description='CX2 builds electronic-warfare hardware and software that detect and disrupt radio-frequency threats.',kind='Defense technology',logo_url='https://cdn.prod.website-files.com/690158aaee650472ffae04fb/6a15fcb87103cc518ac9135d_CX2-Registered.svg',logo_source_url='https://www.cx2.com/',logo_kind='logo',logo_status='official_site_asset',logo_background='light');f['notes']='Official privacy policy names exact CX2 Inc.; current website describes electronic-warfare systems. Official CX2 wordmark fetched and visually reviewed; inaccurate template alt text was not used as identity evidence.';s=[src('https://www.cx2.com/privacy','Official privacy policy names exact CX2 Inc.'),src('https://www.cx2.com/','Current defense business and visually verified official CX2 wordmark.')]
 if k==1:
  f['description']='Cyberlux provides unmanned-aircraft technology, military communications and related defense systems.';f['notes']='July2026official shareholder letter names exact Cyberlux Corporation and defense operations. OTC disclosures are referenced, but current trading eligibility is not separately verified.';s=[src('https://cyberlux.com/shareholder-update-letter-070226/',f['notes'])]
 if k==2:
  f.update(review_outcome='partial',description='Cypress Home Developments describes itself in its lobbying registration as a female-owned land developer in Falls Church, Virginia.');f['notes']='OriginalLD1 supplies location and self-reported land development activity. Official website and independent exact company identity remain unresolved.';s=[src('https://lda.senate.gov/filings/public/filing/439f2e21-ee07-4b8d-ad48-50eb44f1e98a/print/',f['notes'])]
 if k==3:
  f.update(review_outcome='partial',description='A lobbying client filed as the Daimler Truck North American Dealer Council, distinct from the truck manufacturer.');f['notes']='Original2026report names the dealer council; no independently verified council website or legal identity record found. Not assigned Daimler parent ownership.'
 if k==4:
  f.update(name='Del Monte Fresh Produce Company',description='Del Monte Fresh Produce Company is a U.S. fresh-produce business associated with Fresh Del Monte.',kind='Fresh-produce company');f['notes']='March2026SEC-filed transaction amendment explicitly names exact Del Monte Fresh Produce Company as a Delaware corporation. Identity confirmed without assigning public-parent listing or assuming every Del Monte-branded business is this entity.';s=[src('https://www.sec.gov/Archives/edgar/data/1047340/000119312526124060/d101697dex21.htm','March2026asset-purchase amendment names exact Del Monte Fresh Produce Company as Delaware buyer.')]
 if k in [5,6]:
  f.update(name='Delta Air Lines',description='Delta Air Lines operates passenger and cargo flights from its Atlanta headquarters.',kind='Commercial airline',ownership='Public company',website='https://www.delta.com/');f['website_status']='verified';f['notes']='Original registrations match Delta Air Lines Inc. through its documented Washington suite and Atlanta headquarters. Generic Delta and Airlines spelling variant are consolidated with the existing airline record; original source IDs and filing names are preserved.';s=delta_sources
 if k==7:
  f.update(ownership='Subsidiary',description='Diageo Americas, Inc. is a U.S. company within Diageo’s alcoholic-beverage group.',kind='Beverage subsidiary');f['notes']='Diageo2026annual report Group Companies section lists exact Diageo Americas Inc. among fully owned subsidiaries, indirectly held by Diageo plc. Kept distinct from Diageo North America and Americas Supply.';s=[src('https://www.sec.gov/Archives/edgar/data/835403/000162828026057527/dia045-arax2026annualrep.htm',f['notes'])]
 if k==8:
  f.update(review_outcome='partial',name='Digicel Holdings (Bermuda) Limited',description='A Digicel telecommunications holding-company client named in the lobbying filing.');f['notes']='FY25ESGreport discusses DHBL board governance and restructuring; the extracted report does not expand that acronym into the exact filed name. Original filing names the Bermuda entity; precise current legal identity bridge and ownership remain unresolved.';s=[src('https://www.digicelgroup.com/api/assets/digicel-group/f09a51cb-2f3d-40a2-a03e-03721ca0427b/digicel-fy25-esg-report-final.pdf?version=0',f['notes'])]
 if k==9:
  f.update(description='Discovery Communications was the former name of Discovery Inc., a television and digital-media business.',kind='Media company');f['notes']='Discovery2018annual report explicitly documents the March6,2018rename from Discovery Communications Inc. to Discovery Inc. Historical identity confirmed; this record does not assert current standalone ownership or imply that a proposed merger announcement proves completion.';s=[src('https://www.sec.gov/Archives/edgar/data/1437107/000143710719000013/disca-2018123110k.htm',f['notes'])]
 if not s:s=[src(v['url'],d['evidence']) for v in d['sources']]
 f['identity_evidence']=f['notes'];p[i].update(f);byurl={v['url']:v for v in p[i].get('sources',[])}
 for v in s:byurl[v['url']]=v
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes'],sources=s))
ids=['cab627c579c81fa7','d079e7e1ed0e0922','19bdfa546f85ed89'];mp=pathlib.Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(mp));assert not any(set(ids)&set(v['source_ids']) for v in m)
(r/'featured105-merges-before.json').write_text(json.dumps(m,indent=2)+'\n');m.append(dict(canonical_id=ids[0],source_ids=ids,rationale='Original Delta and Delta Airlines registrations match Delta Air Lines Inc. at its Washington suite and Atlanta headquarters; spelling and abbreviated-name variants are consolidated with all filing provenance retained.',sources=delta_sources,reviewed_at='2026-09-13'));mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
(r/'featured105-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured105-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
meta_path=pathlib.Path('lobbying-map/research/publication-metadata.json');meta=json.load(open(meta_path));(r/'featured105-metadata-before.json').write_text(json.dumps(meta,indent=2)+'\n')
for i,b in before.items():
 if b['status']!=p[i]['status']:meta['counts'][b['status']]-=1;meta['counts'][p[i]['status']]+=1
meta['updated']='2026-09-13';meta_path.write_text(json.dumps(meta,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()));print('Merged3Delta sourceIDs; addedCX2logo')
