import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));before={};dec=[]
assert not (r/'featured95-before.json').exists()
rows=json.load(open(r/'featured95-first10.json'))+json.load(open(r/'featured95-middle10.json'));follow={x['id']:x for part in ['first','middle'] for x in json.load(open(r/f'featured95-{part}-followup.json'))}
names=['UCB Inc.','Ucore Rare Metals','Nanit (UdiSense, Inc.)','UGI Energy Services, LLC','UiPath','UKG','UL Solutions (UL LLC)','UL Research Institutes','Ultra Intelligence & Communications','Ultralife Corporation','ULVAC, Inc.','UMass Chan Medical School','Umbra Lab, Inc.','Umbra Space','Umicore Optical Materials USA, Inc.','Umicore USA Inc.','Underdog Sports Holdings, Inc.','Underdog Sports Holdings, Inc. and affiliates','UNICEF USA','TransparentBusiness, Inc. (formerly Unicoin Inc.)']
kinds=['Biopharmaceutical company','Rare-earth processing technology company','Baby-monitor technology company','Energy-services company','Business automation software company','HR and workforce software company','Product testing and certification company','Safety-science research organization','Defense communications technology company','Battery and communications equipment manufacturer','Vacuum-equipment manufacturer','Public medical school','Radar satellite company','Radar satellite brand','Optical-materials manufacturer','Materials group operating company','Sports-gaming holding company','Sports-gaming group','Children’s humanitarian organization','Software, talent-services and media company']
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for idx,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));e=follow.get(i,d);f=dict(name=names[idx],description=e.get('proposed_fields',d)['description'],kind=kinds[idx],ownership='Unknown',review_outcome='confirmed',notes=e['evidence'],website=e.get('proposed_fields',d)['website'],website_status='verified',status='sourced',checked_at='2026-09-13',as_of='2026-09-13');s=[src(e['official_url'],e['evidence'])]
 if idx in [0,3]:f['ownership']='Subsidiary'
 if idx==1:f['ownership']='Public company';s=[src('https://ucore.com/','Current official issuer page identifies Ucore Rare Metals and its TSXV UCU and OTCQX UURAF securities.')]
 if idx==4:f.update(website='https://www.uipath.com/',ownership='Public company');s=[src('https://ir.uipath.com/','Current investor site identifies UiPath Inc., PATH stock and its business automation software.')]
 if idx==6:f['notes']='Legal terms identify UL LLC using the UL Solutions brand. No public-parent listing is assigned to this LLC.'
 if idx==7:f['ownership']='Nonprofit';s=[src('https://ul.org/about/our-locations/','Official locations page explicitly identifies UL Research Institutes as an independent nonprofit safety-science organization.')]
 if idx==9:
  f.update(website='https://ultralifecorporation.com/',ownership='Public company');s=[src('https://investor.ultralifecorporation.com/press-releases','Current issuer release page identifies Ultralife Corporation as Nasdaq ULBI and its battery and communications business.')]
 if idx==10:f['ownership']='Public company';s.append(src('https://ir.ulvac.co.jp/en/ir/faq.html','Official investor FAQ identifies ULVAC shares on the Tokyo Stock Exchange, code 6728.'))
 if idx==11:
  f['ownership']='Public institution';s=[src('https://www.umassmed.edu/ccts/research-resources/ocr/research-agreements/contracting-guide/','Official contracting guide identifies the school as the Worcester campus of the public University of Massachusetts.'),src('https://www.umassmed.edu/umasschan/media/','Official university announcement documents renaming UMass Medical School to UMass Chan Medical School in 2021.')];f['notes']='Public university medical-school unit and documented name transition; distinct from its affiliated hospital system.'
 if idx==13:
  f['review_outcome']='partial';f['notes']='Umbra brand and Santa Barbara satellite business established. Exact mapping of this filing label to Umbra Lab Inc. versus affiliate scope remains open; no entity merge applied.'
 if idx in [14,15]:
  f['notes']='Exact entity is named in the official Umicore group directory. Its identity is confirmed separately from the parent; ownership percentage remains unknown.'
 if idx==14:
  f['description']='Umicore Optical Materials USA, Inc. produces optical materials and infrared components at the Umicore Quapaw operation in Oklahoma.';s.append(src('https://www.umicore.com/en/locations/all-sites/','Official location directory describes optical-materials and infrared-component work at Quapaw, Oklahoma.'))
 if idx in [16,17]:f['notes']='Official terms name Underdog Sports Holdings, Inc. separately from subsidiaries and affiliates. Preserve the different filing scopes without merging.'
 if idx==18:
  f['ownership']='Nonprofit';f['notes']='Official financial disclosure establishes U.S. Fund for UNICEF doing business as UNICEF USA, EIN 13-1760110. Original UNICEF USA registration uses the official New York address; in-house filing uses its Washington office.';s=[src('https://www.unicefusa.org/about-unicef-usa/finances','Official legal-name and DBA bridge, nonprofit status and EIN 13-1760110.'),src('https://www.unicefusa.org/how-help/donate/UNICEF-USA-donation-faqs','Official UNICEF USA page names United States Fund for UNICEF and 125 Maiden Lane address.')]
 if idx==19:
  f['description']='Formerly Unicoin Inc., TransparentBusiness operates software and talent-services platforms through a subsidiary and holds a majority interest in the producer of Unicorn Hunters. It previously marketed Unicoin rights and postponed its initial coin offering in 2025.';s=[src('https://www.sec.gov/Archives/edgar/data/1740742/000182912626005094/transparentbusiness_8k.htm','Issuer filing documents Unicoin Inc. changing its legal name to TransparentBusiness Inc. on April 13, 2026.'),src('https://www.sec.gov/Archives/edgar/data/1740742/000182912626008347/R8.htm','June 2026 issuer financial note describes SaaS/TaaS business, media subsidiary and August 2025 postponement of initial coin offering.')];f['notes']='Exact legal rename established by SEC issuer filing. Do not confuse the issuer with separately incorporated affiliate Unicoin International Inc. SEC reporting alone is not evidence of exchange listing.'
 f['identity_evidence']=f['notes'];p[i].update(f);bad={d['official_url'],e['official_url']}-{x['url'] for x in s};byurl={x['url']:x for x in p[i].get('sources',[]) if x['url'] not in bad}
 for x in s:byurl[x['url']]=x
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes'],sources=s))
mp=pathlib.Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(mp));ids=['983499729245fbd9','091312c10f635e96'];assert not any(set(ids)&set(x['source_ids']) for x in m);(r/'featured95-merges-before.json').write_text(json.dumps(m,indent=2)+'\n');m.append(dict(canonical_id=ids[0],source_ids=ids,rationale='Official financial disclosure explicitly identifies U.S. Fund for UNICEF doing business as UNICEF USA, EIN 13-1760110. Original UNICEF USA external registration is at its official 125 Maiden Lane address; U.S. Fund in-house registration uses Washington office. Preserve both source IDs and all reports.',sources=[src('https://www.unicefusa.org/about-unicef-usa/finances','Explicit same-entity legal name and DBA bridge.'),src('https://disclosurespreview.house.gov/data/LD/2024_Registrations_XML.zip','301541281.xml identifies UNICEF USA at 125 Maiden Lane.'),src('https://disclosurespreview.house.gov/data/LD/2026_Registrations_XML.zip','301842951.xml is U.S. Fund for UNICEF self-registration at Washington office.')],reviewed_at='2026-09-13'));mp.write_text(json.dumps(m,indent=2)+'\n')
(r/'featured95-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured95-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()));print('Status changes',[(i,b.get('status'),p[i]['status']) for i,b in before.items() if b.get('status')!=p[i]['status']])
