import json,pathlib,copy
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));assert not (r/'featured181-before.json').exists();before={};dec=[]
data=[
('8f2a84d9187690c0','Consumer-products corporate group associated with Amway and its direct-selling businesses.','Unknown','https://supplier.amway.com/terms-of-use/','Official supplier terms name Alticor Inc. and identify Amway and Alticor as the site parties. This supports identity, but not a current ownership classification.'),
('92091a389177484d','Cooperative helping independent pharmacies with group purchasing, business support and policy advocacy.','Cooperative / member-owned','https://www.supremecourt.gov/DocketPDF/23/23-1213/315014/20240614115635564_23-1213%20tsac%20AmericanPharmacies.pdf','The organization identifies itself by the exact filed name American Pharmacies, Inc. in its 2024 Supreme Court amicus brief and describes its cooperative activities. Historical membership counts are not presented as current.'),
('6159e5dc30719a82','Zeel connects customers with massage and wellness professionals through its booking network.','Unknown','https://www.zeel.com/terms-of-use','Official terms explicitly name Zeel Networks, Inc. as the service provider and describe the network. Identity is confirmed; the previous private-company classification lacked ownership evidence and is now Unknown.'),
('d0332557a8f89b23','Develops radioisotope batteries for long-duration power in space and underwater applications.','Unknown','https://www.nasa.gov/saa/domestic/39642_SAA3-1792.pdf','NASA agreement SAA3-1792 names Zeno Power Systems, Inc. and describes development of the Harmonia radioisotope generator. The official company site corroborates this activity. Development plans are not treated as completed deployments.')]
for i,d,o,u,n in data:
 v=p[i];before[i]=copy.deepcopy(v);v.update(description=d,ownership=o,review_outcome='confirmed',status='sourced',website_status='verified',checked_at='2026-09-13',identity_evidence=n,notes=n);v['sources'].append(dict(url=u,label='Primary identity evidence',claim=n));dec.append(dict(id=i,decision='confirmed',notes=n))
for n,v in [('before',before),('decisions',dec)]: (r/f'featured181-{n}.json').write_text(json.dumps(v,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('4 identities confirmed; unsupported ownership labels corrected')
