import json,pathlib,copy,collections
root=pathlib.Path(__file__).resolve().parents[2];base=root/'work/research-2026/identity-wave41-bulk';path=root/'work/research-2026/reviewed.json';p=json.loads(path.read_text());m=json.loads((base/'matches.json').read_text());holds={56:'Filed 47 Waubonsee Drive differs from official Route 47 at Waubonsee Drive; retain uncertainty in address corroboration.',58:'WE Soda group page does not establish filed Wyoming LP.',65:'Ting Labs page lacks explicit former Whisker Labs name link.',66:'WinnCompanies contact is group address; exact development entity link needs further review.',67:'Witham Health Services vs filed Witham Hospital needs explicit facility link.',72:'X-Bow Launch Systems differs from official X-Bow Systems; rename not established.',73:'Xanterra group page does not establish Leisure Holding LLC.',78:'Exact LLC identity not stated in cached pages.',79:'Exact LLC identity not stated in cached pages.',80:'Filed LLC conflicts with official Inc; legal continuity unproven.',83:'Yum Brands group page does not establish Restaurant Services Group LLC.'};decisions=[];backup={}
for i in range(44,88):
 x=m[i];id=x['id'];profile=p[id];backup[id]=copy.deepcopy(profile);a=x['matches'][0];r=a['registration'];proof=f"Official organization name, activity and address corroborate the registration: {r['client_name']}, {r['address']}, {r['city']}, {r['state']}. Source: {r['archive']} / {r['member']}.";decision={'id':id,'decision':'hold' if i in holds else 'confirm','evidence':holds.get(i,proof),'url':a['page_url']};decisions.append(decision)
 if i in holds:continue
 assert profile['review_outcome']=='partial'
 profile.update(status='sourced',review_outcome='confirmed',website_status='verified',checked_at='2026-09-12',as_of='2026-09-12');old=profile.get('identity_evidence','');profile['identity_evidence']=(old if isinstance(old,str) else json.dumps(old))+' '+proof
 profile['sources'] += [{'url':a['page_url'],'label':'Official identity and registration-address corroboration','claim':proof},{'url':r['source_url'],'label':'House registration archive: '+r['member'],'claim':proof}]

(base/'local44-before.json').write_text(json.dumps(backup,indent=2,ensure_ascii=False));(base/'local44-decisions.json').write_text(json.dumps(decisions,indent=2,ensure_ascii=False))
for f,pretty in [(path,True),(root/'lobbying-map/research/reviewed-2026.json',False),(root/'outputs/2026-research-trial/profiles.json',True)]:f.write_text(json.dumps(p,indent=2 if pretty else None,ensure_ascii=False))
print(collections.Counter(d['decision'] for d in decisions))
