import json,collections,datetime
from pathlib import Path
p=Path('work/research-2026');rows=json.loads((p/'partial-verified-assets-0-40.json').read_text());d=json.loads((p/'reviewed.json').read_text());ids={x['id'] for x in rows}|{'832bf2ba4cd3a1a7','327bc419d1823ad1'};(p/'partial-0-40-before.json').write_text(json.dumps({i:d[i] for i in ids},indent=2)+'\n')
for x in rows:
 assert x['http_status']==200 and x['content_type'].startswith('image/');a=d[x['id']];a.update(logo_url=x['url'],logo_source_url=x['source_url'],logo_kind=x['kind'],logo_status='official_site_asset');a['sources'].append({'label':'Official website branding','url':x['source_url'],'claim':'Organization logo or site icon identified on the official site; image response verified September 9, 2026.'})
 if x['id']=='cdea73eb0eae0b96':a['logo_background']='dark'
for i,url,bad,desc,member,address in [('832bf2ba4cd3a1a7','https://www.adsadsi.com/pages/index.asp','adsinc.com','IT and broadband consultancy helping education, healthcare and Tribal organizations with technology planning and E-Rate and Rural Health Care funding.','301815812.xml','410 North Jefferson Avenue, Suite 326, Mount Pleasant, Texas'),('327bc419d1823ad1','https://www.afellc.com/','afeonline.com','Pennsylvania manufacturer of industrial food cooling, freezing and processing equipment, including spiral and tunnel systems.','301814244.xml','14816 Boot Jack Road, Ridgway, Pennsylvania')]:
 a=d[i];a.update(website=url,description=desc,checked_at='2026-09-09',identity_evidence=f'Exact company name and {address} match House registration {member} and the corrected official website.');a['sources']=[x for x in a['sources'] if bad not in x['url']];a['sources'] += [{'label':'Corrected official website','url':url,'claim':f'Company name, services and address {address} corroborate the disclosed client.'},{'label':f'House registration — {member}','url':'https://disclosurespreview.house.gov/data/LD/2025_Registrations_XML.zip','claim':f'Exact disclosed legal name and address {address}.'}];a['notes']+=f' Corrected unrelated former website {bad}; name, street address and activity corroborate the replacement. Ownership remains unverified.'
for f in [p/'reviewed.json',Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(d,ensure_ascii=False,separators=(',',':')))
f=p/'publication.json';v=json.loads(f.read_text());v.update(local_changes_pending=True,pending_source_pushed=False,pending_change_summary='18 official assets and two corrected organization websites');f.write_text(json.dumps(v,indent=2)+'\n');f=p/'full-corpus-coverage-audit.json';a=json.loads(f.read_text());a.update(as_of=datetime.datetime.now(datetime.timezone.utc).isoformat(),logos=dict(collections.Counter(x.get('logo_status') for x in d.values())),publication=v,local_changes_pending=True,publication_stage='local_changes_pending');f.write_text(json.dumps(a,indent=2)+'\n');print(a['logos'])
