import json,gzip,pathlib,copy,datetime
w=pathlib.Path('work/research-2026');p=json.load(open(w/'reviewed.json'));b={x['id']:x for x in json.load(gzip.open('lobbying-map/research/directory-base.json.gz','rt'))['companies']};q={x['id']:x for x in json.load(open(w/'registration-evidence-queue.json'))};s={
'af6988a3cf469731':('https://app.collectors.com/collectorsuseragreement','Official user agreement explicitly lists Collectors Universe, Inc. among Collectors Holdings divisions and affiliates and describes authentication/grading services, matching the original exact filing alias.'),
'4cfea1dc7122531e':('https://www.regents.nysed.gov/sites/regents/files/219bra2.pdf','New York Regents January 2019 meeting summary records the charter amendment changing College Entrance Examination Board to College Board, directly matching the original filed former-name label.'),
'be801b2f69169c7a':('https://www.colpipe.com/wp-content/uploads/2024/12/Brochure_EX_2024_FINAL_Web.pdf','Official pipeline-safety brochure identifies Colonial Pipeline Company and its refined-petroleum pipeline operations, corroborating the original unsuffixed Colonial Pipeline filing.'),
'5fed91cfabbdf28d':('https://www.colpipe.com/wp-content/uploads/2024/12/Brochure_EX_2024_FINAL_Web.pdf','Official pipeline-safety brochure identifies Colonial Pipeline Company and refined-petroleum pipeline operations, matching the original exact Company registrations.'),
'71cb720b770d8828':('https://visit.columbia.edu/content/frequently-asked-questions','Official Columbia University visitor information identifies the New York university and 535 West 116th Street, matching the original university registration.'),
'c830f880688ca264':('https://corporate.comcast.com/contact-information','Official contact page identifies Comcast Corporation at 1701 JFK Boulevard, Philadelphia. The original registration set explicitly includes Comcast Corporation; this is not a match to Comcast Cable Communications LLC.'),
'bce067c329609cc3':('https://compasshealthnetwork.org/wp-content/uploads/2023/01/CHNA-December-2016.pdf','Official network needs assessment identifies Compass Health Network at 1800 Community Drive, Clinton, matching current original registration. Current official website corroborates Missouri behavioral, medical and dental services. Confirmation is network identity; no particular legal subsidiary substituted.'),
'99b63a7e0e53b128':('https://ir.compasspathways.com/files/doc_downloads/annual-general-meeting/Compass-Pathways-2023-Annual-Report.pdf','Official 2023 annual report names Compass Pathways Inc and 44 West 37th Street, 7th Floor, New York, matching 2026 registration. Report supports exact subsidiary identity; historical ownership evidence is not described as a new 2026 ownership check.'),
'4d2aa9ef90a71137':('https://ir.qorvo.com/sec-filings/sec-filing/10-k/0001628280-26-032873','Official 2026 issuer filing identifies Qorvo, Inc. Original alias explicitly records Clark Street Associates on behalf of Qorvo; preserve intermediary relationship.'),
'3dd6b64ccfa7a34f':('https://investor.marvell.com/sec-filings/all-sec-filings/content/0001835632-26-000011/mrvl-20260131.htm','Marvell fiscal 2026 annual report explicitly identifies Celestial AI, Inc. and acquisition completed February 2, 2026. Original alias explicitly represents Celestial AI; keep it distinct from Marvell and Clark Street Associates.'),
'7e573f5329156a7d':('https://ir.latticesemi.com/static-files/1bba6b65-d08b-4b7e-93e9-fb6ad3d74104','Official May 2026 results identify Lattice Semiconductor Corporation. Original alias explicitly names Clark Street Associates on behalf of Lattice Semiconductor; intermediary retained.'),
'62b42ac01f46873a':('https://www.lightpath.com/terms-and-conditions/','Official terms of sale identify LightPath Technologies, Inc., a Delaware corporation. Original filing explicitly names Clark Street Associates on behalf of LightPath Technologies; intermediary retained.'),
'ddcfaeaddfdb2fd8':('https://investor.marvell.com/company-information','Official investor contact identifies Marvell Technology, Inc. at 5488 Marvell Lane, Santa Clara. Original alias names Clark Street Associates on behalf of Marvell Technology, Inc.; intermediary retained.'),
'38fa5448a656bc8f':('https://www.clearview.ai/overview','Official company overview identifies Clearview AI as a privately owned U.S. company offering facial-recognition investigative tools, matching original unsuffixed client. Footer also names Clearview AI, Inc.')}
(w/'featured51-root-before.json').write_text(json.dumps({i:copy.deepcopy(p[i]) for i in s},indent=2,ensure_ascii=False)+'\n');a=[]
for i,(u,e) in s.items():
 x=p[i];assert x['review_outcome']!='confirmed';x.update(review_outcome='confirmed',website_status='verified',identity_evidence=e,checked_at=datetime.datetime.now(datetime.timezone.utc).isoformat());x['sources'].append({'url':u,'label':'Verified primary identity','claim':e});a.append({'id':i,'url':u,'evidence':e,'original_aliases':b[i]['aliases'],'registrations':q.get(i,{}).get('evidence',[])})
 if i=='38fa5448a656bc8f':x['ownership']='Private company'
 if i=='4cfea1dc7122531e':x['sources'].append({'url':'https://about.collegeboard.org/','label':'Current organization overview','claim':'Official website identifies College Board as a not-for-profit membership organization offering SAT and AP programs.'})
(w/'featured51-root-decisions.json').write_text(json.dumps(a,indent=2,ensure_ascii=False)+'\n')
for f,pretty in [(w/'reviewed.json',True),(pathlib.Path('lobbying-map/research/reviewed-2026.json'),False),(pathlib.Path('outputs/2026-research-trial/profiles.json'),True)]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2 if pretty else None)+('\n' if pretty else ''))
print('Confirmed',sum(x.get('review_outcome')=='confirmed' for x in p.values()))
