import json,pathlib,copy
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));xs=json.load(open(r/'verified-sites139-next100-review.json'));before={};dec=[];deferred=[]
assert not (r/'featured137-before.json').exists()
fix={4:'Develops software for national-security applications, including digital forensics and reverse engineering.',62:'Develops, owns and operates energy projects, including wind, solar and energy storage.',82:'A nonprofit advocating for domestic manufacturers, farmers, ranchers and workers on trade and economic policy.',83:'An industry coalition advocating rules that permit hemp-derived THC beverages in adult-beverage retail channels.',93:'A coalition of prediction-market exchanges, brokers and advocates seeking wider consumer access and federal regulatory oversight.',98:'A coalition bringing franchisee associations together to share resources and represent franchise owners.'}
specific={3:'The official Cintra U.S. page identifies the Austin-based highway infrastructure business and explicitly notes that individual project assets have separate legal management.',9:'The official aircraft site footer explicitly names Cirrus Design Corporation d/b/a Cirrus, linking the exact original entity to the current brand.',17:'The official municipal site explicitly identifies Johnson City, Tennessee; it is not assigned to similarly named cities.',27:'The official city site explicitly identifies Logan, West Virginia.',49:'CJ America’s official introduction names CJ America, Inc. and its U.S. offices, with its food, biotechnology, logistics and entertainment businesses.',50:'The official About page names Clairity, Inc., its Boston base and AI risk-assessment work. Identity verification does not establish clinical accuracy or approval.',59:'The official insulation site explicitly identifies CleanFiber Inc. as the CleanFiber trademark owner.',62:'The official site names Clearway Energy Group LLC in its footer and separately links its public affiliate. The public affiliate is not substituted for the group entity.',67:'The related foundation explicitly states that Climate Innovation Action Inc., then named LTC Action, was formed in 2019 as a separate related 501(c)(4) organization. The name change and separate entity are directly documented.',73:'The clinical laboratory site explicitly names Clinical Reference Laboratory, Inc. in its footer and describes laboratory and screening services.',75:'Cloud Software Group’s official page explicitly lists its brands and states that they operate as independent businesses supported by shared services.',77:'The official golf and utility vehicle site explicitly names Club Car LLC and its Evans, Georgia address.',83:'The coalition’s own page describes its proposed operating code and policy advocacy. Recommended regulations are not represented as current law or universal product legality.',87:'The official coalition About page explicitly names CEOSSG and its advocacy concerning enterprise open-source software acquisition.',88:'The SNAP Puerto Rico site explicitly identifies Coalition for Food Security Puerto Rico and its advocacy for transition to SNAP; this is a coalition, not a government benefit agency.',91:'The Santa Fe Group page explicitly identifies Coalition for Oral Health Policy as its initiative and lists the initiative’s policy priorities.',93:'The coalition site identifies its prediction-market membership and advocacy. Its interpretation of federal versus state regulatory authority is not adopted as a legal conclusion.'}
for n,v in enumerate(xs):
 if v['decision']!='confirmed':continue
 if n in [94,99]:
  deferred.append(dict(id=v['id'],name=v['original_name'],reason='Maintenance-only page with no substantive organizational evidence.' if n==94 else 'A publication credit names the older coalition, but the page belongs to another named coalition and does not establish the exact relationship.'));continue
 i=v['id'];assert p[i]['name']==v['original_name'] and p[i]['review_outcome']!='confirmed';before[i]=copy.deepcopy(p[i]);note=specific.get(n,'Official organization body text identifies this organization and supports the activity summarized. Existing ownership evidence is retained without inferring new ownership from its name.')
 p[i].update(description=fix.get(n,v['description']),notes=note,identity_evidence=note,review_outcome='confirmed',checked_at='2026-09-13',as_of='2026-09-13')
 e=v['fetched_evidence'][0];assert e['http_status']==200
 ss={s['url']:s for s in p[i]['sources']};ss[e['url']]={'url':e['url'],'label':'Official organization evidence','claim':note};p[i]['sources']=list(ss.values());dec.append(dict(id=i,name=p[i]['name'],decision='confirmed',notes=note,fetched_evidence=v['fetched_evidence']))
(r/'featured137-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured137-decisions.json').write_text(json.dumps(dec,indent=2)+'\n');(r/'featured137-deferred.json').write_text(json.dumps(deferred,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print(len(dec),'identity confirmations saved;',len(deferred),'proposed confirmations rejected')
