import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured107-first10.json'));before={};dec=[]
assert not (r/'featured107-before.json').exists()
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for k,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));f=dict(name=p[i]['name'],description=d['description'],kind=d['kind'],ownership='Unknown',review_outcome='confirmed',notes=d['evidence'],website=d['website'],website_status='verified',status='sourced',checked_at='2026-09-13',as_of='2026-09-13');s=[]
 if k==0:
  f.update(description='EDF power solutions Development, Inc. develops renewable-energy projects, including proposed solar installations in New York.');f['notes']='The official Sage Creek project page indexed by web search names exact EDF power solutions Development, Inc. as the parent of the project company; the direct page response currently omits dynamic project text. Identity is supported by the indexed primary page and filing. Current ownership is not inferred from an announced group transaction.';s=[src('https://www.edf-re.com/project/sage-creek-solar/',f['notes'])]
 if k==1:
  f['description']='EDF Renewable Energy was the U.S. renewable-power business of EDF Energies Nouvelles, developing and operating wind and solar projects.';f['notes']='EDF’s April 2016 official release explicitly identifies EDF Renewable Energy as the U.S. subsidiary of EDF Energies Nouvelles. Historical business identity confirmed; current legal continuity and ownership after later group changes are not assumed.';s=[src('https://www.edf-re.com/press-release/edf-renewables-announces-the-signature-of-ppas-with-the-ieso-for-two-solar-projects/',f['notes'])]
 if k==2:
  f.update(name='eHealthInsurance Services, Inc.',ownership='Subsidiary',description='eHealthInsurance Services, Inc. helps people compare and enroll in health-insurance plans through the eHealth marketplace.');f['notes']='The 2025 Form 10-K filed in 2026 names exact eHealthInsurance Services, Inc. as a wholly owned indirect subsidiary of eHealth, Inc. Public-parent listing is not assigned to this subsidiary.';s=[src('https://www.sec.gov/Archives/edgar/data/1333493/000133349326000010/ehth-20251231.htm',f['notes'])]
 if k==3:
  f.update(review_outcome='partial',website_status='partial',name='Eli Lilly and Company (filed as formerly Lilly USA, LLC)',description='A pharmaceutical lobbying client filed as Eli Lilly and Company, formerly Lilly USA, LLC. The relationship between the two named legal entities needs clarification.');f['notes']='Lilly’s current pharmaceutical business is identifiable, but the combined FKA label is not independently established as a corporate rename. The parent and LLC are not automatically consolidated.';s=[src('https://www.lilly.com/','Official Lilly pharmaceutical business; does not establish the filed FKA relationship.')]
 if k==4:
  f.update(review_outcome='partial',description='Elliott Management is an investment-management business. This filing also uses the historical Elliott Management Corporation name, whose exact relationship to current affiliates remains under review.');f['notes']='Current Elliott investment strategies are supported by the official website. The Corporation aliases require additional legal continuity evidence; ownership is not inferred from fund activity.';s=[src('https://www.elliottmgmt.com/private-equity-and-private-credit/','Official investment strategies, separate from exact Corporation identity and ownership.')]
 if k==5:
  f.update(name='Embraer Aircraft Holding, Inc.',ownership='Subsidiary',description='Embraer Aircraft Holding, Inc. coordinates Embraer’s corporate activities in the United States.');f['notes']='The 2025 SEC subsidiary table lists exact Embraer Aircraft Holding, Inc. as 100% directly controlled and describes its U.S. corporate role. Kept distinct from the Brazilian public parent.';s=[src('https://www.sec.gov/Archives/edgar/data/1355444/000162828026021824/R47.htm',f['notes'])]
 if k==6:
  f.update(review_outcome='partial',website_status='partial',description='A lobbying client filed as Embraer Aircraft Holdings. It may be a spelling variant of Embraer’s U.S. holding company, but that match has not been verified.');f['notes']='The exact singular Embraer Aircraft Holding, Inc. is independently documented, but the plural filing label needs address or registration continuity before consolidation.';s=[src('https://www.sec.gov/Archives/edgar/data/1355444/000162828026021824/R47.htm','Exact singular Holding entity only; not proof that plural Holdings is the same entity.')]
 if k==7:
  f.update(name='Embraer S.A. (formerly Empresa Brasileira de Aeronáutica)',ownership='Public company',description='Embraer designs, manufactures and supports commercial, executive and military aircraft.',logo_url='https://www.embraer.com/assets/images/Embraer-logo-blue.svg',logo_source_url='https://www.embraer.com/',logo_kind='logo',logo_status='official_site_asset',logo_background='light');f['notes']='The 2025 Form 20-F documents the 2010 change from Embraer–Empresa Brasileira de Aeronáutica S.A. to Embraer S.A. Its 2026-filed securities exhibit records NYSE ADS symbol EMBJ. The official blue Embraer wordmark was fetched and visually verified. U.S. holding-company records remain separate.';s=[src('https://www.sec.gov/Archives/edgar/data/1355444/000162828026021824/erj-20251231.htm','Annual report documents the 2010 corporate-name change.'),src('https://www.sec.gov/Archives/edgar/data/1355444/000162828026021824/embj-20251231xex26.htm','Securities exhibit identifies Embraer S.A. and NYSE-listed ADSs under EMBJ.'),src('https://www.embraer.com/','Official aerospace business and visually verified wordmark.')]
 if k==8:
  f.update(description='EMD Millipore Corporation supplies laboratory and biopharmaceutical products and services within the Merck Millipore life-science business.');f['notes']='Official sales conditions name EMD Millipore Corporation among the selling legal entities. Product-license terms name the corporation at its Burlington address. Exact identity and Merck KGaA business affiliation are supported; the precise ownership chain is not inferred from division wording.';s=[src('https://www.merckmillipore.com/INTL/en/20140317_144201','Official sales terms name exact EMD Millipore Corporation.'),src('https://www.merckmillipore.com/SG/en/life-science/legal/product-licenses','Official license terms name EMD Millipore Corporation at400 Summit Drive, Burlington, Massachusetts.')]
 if k==9:
  f.update(ownership='Subsidiary',description='Empower Retirement, LLC provides recordkeeping and administrative services for workplace retirement plans.');f['notes']='Empower’s official name-change notice explicitly says Empower Retirement, LLC is its recordkeeping and administrative-services company and was not renamed. The footnote lists it among Empower Annuity Insurance Company of America’s subsidiaries; developer terms independently name the LLC.';s=[src('https://www.empower.com/name-change',f['notes']),src('https://developer-sandbox.empower.com/DevTerms','Official terms define Empower as Empower Retirement, LLC.')]
 f['identity_evidence']=f['notes'];p[i].update(f);byurl={v['url']:v for v in p[i].get('sources',[])}
 for v in s:byurl[v['url']]=v
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes'],sources=s))
(r/'featured107-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured107-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()))
