import json,gzip,hashlib
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));b=json.load(open(r/'identity271-batch.json'));ids=[x['id'] for x in b['records']];f=r/'featured271-before.json';assert not f.exists();f.write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n')
for x in b['records']:
 q=p[x['id']];q['description']=x['description'];q['notes']=x['recommendation']+' Official organization bodies include September 5 cached captures, reviewed September 14, 2026. Ownership remains unknown unless separately established.';q['identity_evidence']=q['notes'];q['checked_at']='2026-09-14'
 if x['id']!='2f9e065197e7a96c':q['review_outcome']='confirmed'
 if x['id']=='aebd7d9b0a82a7e4':q['legal_form']='Corporation';q['notes']+=' The official footer states MedExpert International, Inc. and gives the matching 1300 Hancock Street address.';q['identity_evidence']=q['notes']
 for s in x['sources']:
  q['sources'].append({'url':s['url'],'label':'Original registration '+Path(s['retrieval_ref']).name if s['retrieval_ref'].endswith('.xml') else 'Official organization evidence','claim':s['excerpt']})
logo=(r/'featured271-bam-logo.svg').read_bytes();assert b'<script' not in logo and b'href=' not in logo;sha=hashlib.sha256(logo).hexdigest();target=Path('lobbying-map/public/assets/organization-logos')/(sha+'.svg');target.write_bytes(logo)
q=p['d63474a368ca7cb9'];q.update(logo_url='/assets/organization-logos/'+sha+'.svg',logo_kind='logo',logo_status='official_site_asset',logo_source_url='https://bambonds.com/about-bam/governance/');q['sources'].append({'url':'https://bambonds.com/about-bam/governance/','label':'Official BAM branding','claim':'Full BAM logo extracted from the official homepage link in its governance page and visually checked September 14, 2026.'})
(r/'featured271-decisions.json').write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n');(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n')
mp=Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(mp));(r/'featured271-merge-before.json').write_text(json.dumps(m,indent=2)+'\n');d=json.load(gzip.open('lobbying-map/public/data/directory-v3.json.gz','rt'));groups=[['0d8d68c7e163b027','aebd7d9b0a82a7e4'],['c68066f0bbe21731','387438e8fe074b23']];allids=sum(groups,[]);cards={x['id']:x for x in d['companies'] if x['id'] in allids};assert len(cards)==4;assert not any(set(allids)&set(x['source_ids']) for x in m);(r/'featured271-cards-before.json').write_text(json.dumps(cards,indent=2)+'\n')
for g,year,reg,url in [(groups[0],2025,'301815896 and 301820900','https://www.medexpert.com/'),(groups[1],2024,'301604607 and 301606577','https://www.wellhive.com/')]:
 m.append({'canonical_id':g[0],'source_ids':g,'rationale':'The direct registration and Brownstein on-behalf-of registration identify the same represented organization. Official company identity and address match the direct client. Consolidate the operating organization while retaining all original filing labels and member IDs.','sources':[{'url':f'https://disclosurespreview.house.gov/data/LD/{year}_Registrations_XML.zip','label':'Original registration pair '+reg,'claim':'Direct client and Brownstein intermediary explicitly name the same beneficiary.'},{'url':url,'label':'Official organization website','claim':'Company name, activity and address match the direct registered client.'}],'reviewed_at':'2026-09-14'})
mp.write_text(json.dumps(m,indent=2,ensure_ascii=False)+'\n');print('Saved four profiles, three confirmations, two merges, one full logo:',target)
