import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));before={};dec=[]
assert not (r/'featured97-before.json').exists()
rows=json.load(open(r/'featured97-first10.json'))+json.load(open(r/'featured97-middle10.json'))
follow={x['id']:x for x in json.load(open(r/'featured97-middle-followup.json'))}
names=['United States Council for Automotive Research, LLC','United States Marine, Inc.','United Wholesale Mortgage','Universal Health Services, Inc.','Universal Synaptics Corporation','University of Illinois System','University of Michigan','Unstructured Technologies, Inc.','UpCodes','UpToDate, Inc.','Upwork Global Inc.','US Acute Care Solutions','U.S. Bancorp','United States Pharmacopeia','V2X','V2X (filed as formerly Vertex Aerospace)','Valar Atomics Inc.','Valve Corporation','Vanta Inc.','VantageScore']
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for idx,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));e=follow.get(i,d);v=e.get('proposed_fields',d)
 f=dict(name=names[idx],description=v['description'],kind=v['kind'],ownership=d['ownership'] if d['ownership'] in ['Unknown','Subsidiary','Public company'] else 'Unknown',review_outcome='confirmed',notes=e['evidence'],website=v['website'],website_status='verified',status='sourced',checked_at='2026-09-13',as_of='2026-09-13');s=[src(e['official_url'],e['evidence'])]
 if idx==3:s=[src('https://uhs.com/news/universal-health-services-inc-publishes-2025-annual-report/','April 2026 company release identifies Universal Health Services Inc. as NYSE UHS and describes its healthcare facilities operated through subsidiaries.')]
 if idx in [5,6]:f['ownership']='Public institution'
 if idx==6:
  f.update(logo_url='https://umich.edu/skins/um2013/media/images/umich-logo.png',logo_source_url='https://umich.edu/',logo_kind='logo',logo_status='official_site_asset',logo_background='dark');s.append(src('https://umich.edu/skins/um2013/styles/skin.css?1740073863','Official homepage header stylesheet references the University of Michigan wordmark asset; downloaded and visually verified.'))
 if idx==10:f['ownership']='Subsidiary';f['notes']='Exact Upwork Global Inc. is listed in the parent 2022 subsidiary exhibit. The historical date is retained; no ownership percentage or parent stock listing is assigned to this entity.'
 if idx==11:
  f.update(website='https://www.usacs.com/',ownership='Private company',kind='Physician-owned healthcare group',description='US Acute Care Solutions is a physician-owned healthcare group whose affiliated clinicians provide hospital-based emergency and inpatient medicine.');f['notes']='Official terms define USACS as the LLC and related entities and state that the LLC itself does not practice medicine. Current 2026 news explicitly describes physician ownership; this is not automatically classified as employee ownership.';s.append(src('https://www.usacs.com/news','February 2026 official news describes the group as physician-owned and providing hospital-based emergency and inpatient medicine.'))
 if idx==12:
  f['kind']='Bank holding company';f['notes']='Exact bank holding company confirmed; original external registration and 2026 in-house report share 950 F St NW Suite 750 Washington DC. Merge joins these parent-company records, not a distinct bank subsidiary.';s=[src('https://www.sec.gov/Archives/edgar/data/36104/000003610426000011/usb-20251231.htm','2025 Form 10-K identifies U.S. Bancorp as the listed bank holding company, distinct from its banking subsidiaries.'),src('https://lda.gov/filings/public/filing/b510d8b3-bcf9-46e1-b55c-2d1783f40c91/print/','2026 in-house report identifies U.S. Bancorp formerly filed as U.S. Bank, at the matching Washington address.'),src('https://disclosurespreview.house.gov/data/LD/2024_Registrations_XML.zip','Original member 301589189.xml names U.S. Bancorp, bank holding company, at 950 F St NW Suite 750 Washington DC 20004.')]
 if idx==13:f.update(ownership='Nonprofit',kind='Scientific standards organization')
 if idx in [14,15]:
  f['kind']='Defense services company';f['description']='V2X supplies defense and government customers with mission support, logistics, training, technology and aerospace services.';s=[src('https://www.sec.gov/Archives/edgar/data/1601548/000110465926058322/tm2614073-1_424b5.htm','May 2026 prospectus identifies V2X Inc. and NYSE VVX and describes defense mission services.'),src('https://www.sec.gov/Archives/edgar/data/1601548/000110465922077110/tm2220234d1_8k.htm','July 2022 filing states Vectrus Inc. changed its name to V2X Inc. upon merger with the Vertex business; it does not establish a simple Vertex Aerospace legal rename.')]
  f['notes']='V2X is the renamed Vectrus parent following the Vertex transaction.'
  if idx==15:f.update(ownership='Unknown',review_outcome='partial',website_status='partial',notes='Filed former-name wording does not match the precise legal merger history. Group website and activity established, but exact predecessor scope remains unresolved; not merged with the separate V2X entry.')
 if idx==16:
  f['kind']='Nuclear energy company';s.append(src('https://www.energy.gov/sites/default/files/2026-04/NE_10CFR851_VariancePackage_Final_05JAN2026.pdf','January 2026 Department of Energy variance package names Valar Atomics Inc. in its nuclear reactor pilot program. Exact name and nuclear business align with original 2025 registration; government address is Hawthorne while the registration lists El Segundo, so an address identity match is not claimed.'));f['notes']='Exact corporation confirmed by Department of Energy reactor program record and original registration business description. Locations differ between records; no ownership inferred.'
 if idx==19:
  f.update(ownership='Joint venture',kind='Credit-scoring company');s=[src('https://www.vantagescore.com/about/about-vantagescore','Official about page identifies VantageScore and its credit scoring business.'),src('https://vantagescore.com/resources/faqs','Official FAQ identifies VantageScore Solutions LLC and the independent joint venture of Equifax, Experian and TransUnion.')];f['notes']='Official sources establish the credit-scoring business and joint venture ownership by Equifax, Experian and TransUnion.'
 f['identity_evidence']=f['notes'];p[i].update(f)
 bad={d['official_url'],e['official_url']}-{x['url'] for x in s};byurl={x['url']:x for x in p[i].get('sources',[]) if x['url'] not in bad}
 for x in s:byurl[x['url']]=x
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes'],sources=s))
(r/'featured97-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured97-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False))
mp=pathlib.Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(mp));ids=['f64311305889acf0','7543c9de9728f0c8'];assert not any(set(ids)&set(x['source_ids']) for x in m)
(r/'featured97-merges-before.json').write_text(json.dumps(m,indent=2)+'\n');m.append(dict(canonical_id=ids[0],source_ids=ids,rationale='Original 2024 registration and 2026 in-house filing identify the same U.S. Bancorp bank holding company at 950 F St NW Suite 750 Washington DC 20004. Legal parent remains distinct from U.S. Bank subsidiary.',sources=dec[12]['sources'],reviewed_at='2026-09-13'));mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()));print('Status changes',[(i,b.get('status'),p[i]['status']) for i,b in before.items() if b.get('status')!=p[i]['status']])
