import json,gzip
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));ids=['56ddc0ca7ada1b0e','83620e34015d1c0b','ca1ebe3b2a885ba2','cbba497255b3109d','3eac0739a74848f9'];f=r/'featured270-before.json';assert not f.exists();f.write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n')
q=p[ids[0]];q.update(review_outcome='confirmed',website='https://casl.org/',website_status='verified',ownership='Nonprofit/tax-exempt',checked_at='2026-09-14',logo_url='https://casl.org/images/casl-logo.svg',logo_source_url='https://casl.org/contact-us',logo_kind='logo',logo_status='official_site_asset')
q['notes']='The current official site at casl.org names Chinese American Service League and lists 2141 South Tan Court, Chicago, matching original registration 301871945. It describes the agency as nonprofit and presents its education, health, human services and advocacy programs. The old caslservice.org homepage is parked and has been replaced. The current site’s nonprofit description supports this classification; the unavailable older audit was not used as fresh evidence.';q['identity_evidence']=q['notes'];q['sources'].append({'url':'https://casl.org/contact-us','label':'Current official CASL website','claim':'Exact organization name and Chicago address match the registration. Current page describes a nonprofit agency and supplies the official CASL wordmark; retrieved and logo visually checked September 14, 2026.'})
q=p[ids[1]];q.update(review_outcome='confirmed',checked_at='2026-09-14');q['notes']='The official October 23, 2025 announcement explicitly identifies the change from HR Policy Association to CHRO Association, continuing the same association. It represents senior human-resource leaders and employers on workforce policy and practice. Operating identity and former-name relationship are confirmed; separate legal form and tax status remain unknown.';q['identity_evidence']=q['notes'];q['sources'].append({'url':'https://www.chro.org/w/the-hr-policy-association-announces-its-rebrand-to-the-chro-association','label':'Official CHRO name-change announcement','claim':'Release dated October 23, 2025 explicitly connects HR Policy Association to CHRO Association; readable page retrieved September 14, 2026.'})
u='https://www.bsa.org/news-events/news/bsa-rebrands-as-business-software-alliance'
for i in ids[2:]:
 q=p[i];q.update(review_outcome='confirmed',website_status='verified',checked_at='2026-09-14');q['notes']='BSA’s January 6, 2025 announcement explicitly connects its previous BSA | The Software Alliance brand with Business Software Alliance. The original filing names are preserved as aliases. Operating identity is confirmed by the official name-change notice and LDA client records; tax status and specific corporate legal form are not inferred from the brand change.';q['identity_evidence']=q['notes'];q['sources'].append({'url':u,'label':'Verified official former-name bridge','claim':'Official announcement says the enterprise-software trade association returned to Business Software Alliance after operating as BSA | The Software Alliance. Readable page checked September 14, 2026.'})
(r/'featured270-decisions.json').write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n');(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n')
mp=Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(mp));(r/'featured270-merge-before.json').write_text(json.dumps(m,indent=2)+'\n');d=json.load(gzip.open('lobbying-map/public/data/directory-v3.json.gz','rt'));cards={x['id']:x for x in d['companies'] if x['id'] in ids[2:]};assert len(cards)==3;assert not any(set(ids[2:])&set(x['source_ids']) for x in m);(r/'featured270-cards-before.json').write_text(json.dumps(cards,indent=2)+'\n')
m.append({'canonical_id':ids[2],'source_ids':ids[2:],'rationale':'Official BSA announcement establishes that Business Software Alliance and BSA | The Software Alliance are successive names of the same operating trade association. Original aliases include an explicit formerly label. Consolidate these duplicate operating-organization entries while preserving all original cards and member IDs.','sources':[{'url':u,'label':'Official former-name announcement','claim':'Explicitly links former BSA | The Software Alliance brand and Business Software Alliance.'},{'url':'https://lda.gov/api/v1/clients/72177/?format=json','label':'Current LDA client record','claim':'BSA Business Software Alliance Inc., global trade association, Washington DC.'},{'url':'https://lda.gov/api/v1/clients/66794/?format=json','label':'Current LDA client record','claim':'Business Software Alliance Inc., enterprise-software trade association, Washington DC.'}],'reviewed_at':'2026-09-14'});mp.write_text(json.dumps(m,indent=2,ensure_ascii=False)+'\n');print('Five identities confirmed; CASL website and logo corrected; three BSA entries consolidated.')
