import json,datetime
from pathlib import Path
p=Path('work/research-2026');f=p/'reviewed.json';d=json.loads(f.read_text());q={x['id']:x for x in json.loads((p/'registration-evidence-queue.json').read_text())};a=json.loads((p/'featured47-second10-reviewed.json').read_text());ids={'baa99ae514ae101e','b00181240a3e42d7','661459544299ef25','687e83908c6ee8fb','027267f65750660b'};before={};audit=[];now=datetime.datetime.now(datetime.timezone.utc).isoformat()
for r in a:
 if r['id'] not in ids:continue
 id=r['id'];v=d[id];assert v['review_outcome']!='confirmed';before[id]=dict(v);reg=q[id]['evidence'][-1]
 if id in ['687e83908c6ee8fb','027267f65750660b']:reg=next(x for x in q[id]['evidence'] if '1000' in x['address'])
 claim='Exact organization identity and described activity corroborated between the original registration and official primary organization evidence. '
 if id=='baa99ae514ae101e':claim+='The unsuffixed filing identifies the Broadcom group; issuer release establishes the group business but no new subsidiary or issuer classification is inferred.'
 elif id=='b00181240a3e42d7':claim+='Registration explicitly names Brownstein Hyatt Farber Schreck LLP OBO Palantir Technologies Inc.; issuer quarterly report identifies the represented corporation. Intermediary remains in original filing name.'
 elif id=='661459544299ef25':claim+='Bumble terms explicitly identify Bumble Trading LLC as a Delaware LLC within Bumble Group; ownership remains Unknown.'
 else:claim+='Parenthetical THE is a filing-name variant of Business Roundtable. Both registrations report 1000 Maine Avenue SW, Suite 500, Washington. One filing reports state WA; retained as a source discrepancy, not treated as Washington state operations.'
 url=r['legal_name_url'];v.update(review_outcome='confirmed',website_status='verified',status='sourced',checked_at=now,identity_evidence=claim)
 v['sources']=v['sources']+[{'url':url,'label':'Official organization identity','claim':claim},{'url':reg['source_url'],'label':'Original registration '+reg['member'],'claim':f"Filed client {reg['client_name']}; {reg['address']}, {reg['city']}, {reg['state']}; activity {reg['description']}."}];audit.append({'id':id,'decision':'confirm','claim':claim,'registration':reg,'official_url':url})
(p/'featured47-root-before.json').write_text(json.dumps(before,indent=2,ensure_ascii=False)+'\n');(p/'featured47-root-decisions.json').write_text(json.dumps(audit,indent=2,ensure_ascii=False)+'\n');f.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(d,ensure_ascii=False));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
mp=Path('lobbying-map/research/verified-entity-merges.json');merges=json.loads(mp.read_text());sourceids=['687e83908c6ee8fb','027267f65750660b'];assert not any(set(sourceids)&set(m['source_ids']) for m in merges);(p/'featured47-merges-before.json').write_text(mp.read_text());merges.append({'canonical_id':sourceids[0],'source_ids':sourceids,'rationale':'Business Roundtable and BUSINESS ROUNDTABLE (THE) identify the same association, with matching 1000 Maine Avenue SW Suite500 Washington addresses and association activity. The latter registration reports state WA rather than DC; this source discrepancy and all original IDs/filings are retained.','sources':[{'url':'https://www.businessroundtable.org/about-us','claim':'Official overview identifies the association of chief executives.'}]+[{'url':r['registration']['source_url'],'claim':'Registration '+r['registration']['member']+' identifies '+r['registration']['client_name']+' at '+r['registration']['address']+', '+r['registration']['city']+', '+r['registration']['state']} for r in audit if r['id'] in sourceids],'reviewed_at':now});mp.write_text(json.dumps(merges,indent=2,ensure_ascii=False)+'\n');print('Saved5identities1merge')
