import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured106-first10.json'));supp={x['id']:x for x in json.load(open(r/'featured106-supplement.json'))};before={};dec=[]
assert not (r/'featured106-before.json').exists()
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for k,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));f=dict(name=p[i]['name'],description=d['description'],kind=d['kind'],ownership=d['ownership'],review_outcome=d['decision'],notes=d['evidence'],website=d['website'],website_status='verified',status='sourced',checked_at='2026-09-13',as_of='2026-09-13');s=[]
 if i in supp:
  v=supp[i];f.update(review_outcome=v['decision'],notes=v['evidence']);s=[src(v['official_url'],v['evidence'])]
 if k==0:f.update(website_status='partial',description='DJI Technologies, Inc. is a lobbying client associated with the DJI drone and imaging-products business; its exact U.S. corporate identity remains unverified.')
 if k==1:
  f.update(review_outcome='confirmed',description='Dollar Tree Management, Inc. was a management-services subsidiary within the Dollar Tree retail group.',kind='Retail management services',ownership='Unknown');f['notes']='The 2018 SEC subsidiary exhibit identifies exact Dollar Tree Management, Inc. as a Virginia management-services subsidiary of Dollar Tree Stores, Inc. The 2026 exhibit instead lists Dollar Tree Management, LLC. Historical identity is confirmed; no unverified Inc.-to-LLC conversion or present ownership is asserted.';s=[src('https://www.sec.gov/Archives/edgar/data/935703/000093570318000013/dltr-2018x02x03x10kxex211.htm','2018 exhibit identifies the exact Inc. entity and historical management-services subsidiary relationship.'),src('https://www.sec.gov/Archives/edgar/data/935703/000093570326000025/dltr-2026x01x31x10kxex211.htm','2026 exhibit lists Dollar Tree Management, LLC; legal continuity to historical Inc. is not established here.')]
 if k==2:f.update(website_status='partial',description='A utility lobbying client filed as Dominion Energy, formerly Dominion Virginia Power. Dominion Virginia Power was a name used by Virginia Electric and Power Company; the precise current entity behind this combined label remains unresolved.')
 if k==3:
  f.update(review_outcome='confirmed',description='Dorel Juvenile Group, Inc. provides child-safety and baby products, including car seats and strollers, through brands such as Safety 1st and Maxi-Cosi.',logo_url='https://doreljuvenile.com/themes/custom/dorelcorp/logo.svg',logo_source_url='https://doreljuvenile.com/',logo_kind='logo',logo_status='official_site_asset',logo_background='light');f['notes']='Safety 1st consumer-support terms dated February 25, 2026 name exact Dorel Juvenile Group, Inc.; the official group website identifies its juvenile-products brands. Current exact-entity ownership is not inferred from a parent brand. Official Dorel Juvenile wordmark fetched and visually verified.';s=[src('https://safety1st.com/pages/consumer-support-mobile-terms-of-service','February 2026 official terms name exact Dorel Juvenile Group, Inc.'),src('https://doreljuvenile.com/','Official juvenile-products business and visually verified Dorel Juvenile logo.')]
 if k==4:f.update(name='The Dow Chemical Company (Dow)',ownership='Subsidiary',description='The Dow Chemical Company makes plastics, industrial chemicals and other materials. It is a wholly owned subsidiary of Dow Inc.')
 if k==5:f.update(name='Dr. Lorna Breen Heroes Foundation',ownership='Nonprofit')
 if k==6:
  f['notes']='March 31, 2026 SEC Form ADV identifies exact Dragonfly Digital Management, LLC, CRD 300750. Legal terms identify the same LLC. Identity is confirmed independently of ownership; an LLC or private-fund advisory activity alone does not establish ownership.';s=[src('https://reports.adviserinfo.sec.gov/reports/ADV/300750/PDF/300750.pdf','March 2026 Form ADV names exact Dragonfly Digital Management, LLC and CRD 300750.')]
 if k==7:
  f.update(name='DTEK International Limited',description='DTEK International Limited is a UK investment company associated with the DTEK energy group. Companies House records Rinat Akhmetov as controlling at least 75% of its shares and votes.');s=[src('https://find-and-update.company-information.service.gov.uk/company/13059079','Exact active UK private limited company; SIC 64303 venture and development capital activities.'),src('https://find-and-update.company-information.service.gov.uk/company/13059079/persons-with-significant-control','Active PSC Rinat Akhmetov holds 75% or more shares and voting rights.')]
 if k==8:
  f.update(review_outcome='confirmed',name='Duracell U.S. Operations, Inc.');f['notes']='Official Duracell privacy policy names exact Duracell U.S. Operations, Inc. as the Delaware corporation operating the U.S. website. Identity confirmed; current exact-entity ownership chain remains unverified.';s=[src('https://duracell.com/privacy',f['notes'])]
 if k==9:
  f.update(name='Ecolab on behalf of Nalco Company',kind='Water-treatment business represented in a filing',description='This filing names Ecolab acting on behalf of Nalco Company, a water-treatment business. OGR is the lobbying firm; Ecolab is the representative and Nalco is the beneficiary.',website='https://www.ecolab.com/en-us/about/our-businesses');f['notes']='Original LDA report distinguishes OGR as registrant from Ecolab Inc. on behalf of Nalco Company as client. Ecolab describes Nalco Water as its water and process-services business. The three roles are preserved; this combined filing label is not merged into either company.';s=[src(d['sources'][0]['url'],f['notes']),src('https://www.ecolab.com/en-us/about/our-businesses','Official Ecolab business page identifies Nalco Water water and process-services activity.')]
 f['identity_evidence']=f['notes'];p[i].update(f);byurl={v['url']:v for v in p[i].get('sources',[])}
 if k==4:byurl.pop('https://www.sec.gov/Archives/edgar/data/1751788/000119312526082632/dow_2025_annual_report.pdf',None)
 for v in s:byurl[v['url']]=v
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes'],sources=s))
(r/'featured106-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured106-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()))
