import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'))
rows=[('bb69ff436443b46c','https://cabc.co/home/who-we-are/','The official Canadian American Business Council overview explicitly identifies the council as a nonprofit business-policy organization focused on Canada-US commerce. Operating identity is confirmed; no additional corporate suffix or specific tax exemption is inferred.'),('1ec961bdf0132e64','https://lobbycanada.gc.ca/app/secure/ocl/lrs/do/vwRg?cno=566&regId=491819','The Canadian government lobbying registry explicitly records the change from Canadian Cattlemens Association to Canadian Cattle Association on June 17, 2022. Its current official About page describes a nonprofit federation of provincial cattle associations. The historic and current operating names refer to the same organization.'),('5b225dcda9ab5f37','https://www.csrxp.org/about/','The official About page spells out Campaign for Sustainable Rx Pricing and describes its healthcare, consumer and business coalition advocating lower prescription-drug prices. Identity is confirmed. Its policy arguments are advocacy positions; legal form and tax status remain unknown.'),('31c3c7fd98c5e37f','https://cfig.org/','The official homepage was retrieved as a readable body on September 14, 2026. It spells out Cannabis Financial Industry Group and describes financial institutions and service providers working on regulated-cannabis banking practices and policy. Exact operating identity is confirmed; legal form and ownership remain unknown.'),('482d094c1bfef80a','https://www.americafirstintl.org/','The official homepage names Campaign for America First International Assistance and describes a coalition of farmers, manufacturers, suppliers, community and faith groups advocating international-assistance programs. Operating identity is confirmed; the campaign is not assigned a standalone corporate or tax status. Its full official wordmark was retrieved and visually checked.'),('d37eafb2852bb2bb','https://www.camber.health/terms-of-service','Camber’s official website and terms describe medical billing, claims processing, payment posting and denial management, matching the Medicaid revenue-cycle activity in registration 301851047 from 2026. Operating identity is confirmed. This is distinct from Camber Mental Health; no exact legal suffix or ownership is inferred.')]
f=r/'featured292-before.json';assert not f.exists();f.write_text(json.dumps({i:p[i] for i,u,n in rows},indent=2,ensure_ascii=False)+'\n')
for i,u,n in rows:
 q=p[i];q.update(review_outcome='confirmed',checked_at='2026-09-14',website_status='verified',notes=n,identity_evidence=n);q['sources'].append({'url':u,'label':'Primary identity evidence reviewed September 14, 2026','claim':n})
p[rows[0][0]]['ownership']='Nonprofit';p[rows[1][0]]['ownership']='Nonprofit';p[rows[1][0]]['sources'].append({'url':'https://www.cattle.ca/about-us','label':'Official association structure','claim':'Describes CCA as a nonprofit federation of nine provincial member cattle associations.'})
p[rows[4][0]].update(name='Campaign for America First International Assistance',kind='Advocacy coalition',ownership='Unknown',description='A coalition of agricultural, manufacturing, community and faith groups advocating for US international-assistance programs.',logo_url='https://images.squarespace-cdn.com/content/v1/686ebdc0744fb06a9cb63dd7/6f91c883-c961-47ac-a8d0-f8b8c5bd8619/cafia-logo-main-red.png?format=1500w',logo_kind='logo',logo_status='official_site_asset',logo_source_url='https://www.americafirstintl.org/')
(r/'featured292-decisions.json').write_text(json.dumps({i:p[i] for i,u,n in rows},indent=2,ensure_ascii=False)+'\n');(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');print('Saved six confirmations and verified CAFIA logo.')
