import json,gzip
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));ids=['37953349c610e33e','f6b63da4b38fa917','f5583dfe27d803a0','28da524f7428c82b','e81bd59b62f20878','99ec21559dd8f911'];f=r/'featured288-before.json';assert not f.exists();f.write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n')
notes=[
'The official Burlington Fabrics website describes performance fabrics, textile research, yarn and military-apparel materials, matching the textile-manufacturing client in registration 301247990 from 2021. Operating identity is confirmed; no legal form or current ownership is inferred.',
'Current LDA client 66043 explicitly identifies Burrell International Group on behalf of Cogwear, Inc. The current official cogweartech.com About page names Cogwear, Inc. and lists 3401 Grays Ferry Avenue, Philadelphia, matching direct registration 301698180 from 2025. The prior cogwear.com domain is replaced. The website labels its device investigational; clinical-grade performance is a company claim.',
'The official About page explicitly identifies Business Impact NW as a nonprofit community development financial institution serving small businesses with coaching, classes and loans. This matches registration 301714028 from 2025. Its stated former names are Seattle Economic Development Fund and Community Capital Development. It is not a government agency.',
'Eagle Holdco Limited’s annual report for the year ended December 31, 2021 names Busy Bees US Holdings Limited as a US management-services/holding-company subsidiary, indirectly held 100%. This establishes the exact historical entity, not its current shareholding. The North American childcare website is a group reference, not a separate verified website for the holding company. The 2021 registration describes daycare/preschool services.',
'The 2025 client registration names C&C North America, Inc. d/b/a Cosentino North America. Official sales terms name C&C North America, Inc. and its distribution subsidiaries as suppliers of Cosentino products. The 2026 North American spelling variant has the same explicit Cosentino North America DBA and the same 355 Alhambra Circle, Suite 1000, Coral Gables address. These are consolidated as one operating organization; parent-group shareholding is not inferred.',
'The 2026 client registration uses C&C North American Inc. dba Cosentino North America, while the 2025 registration and official sales terms use C&C North America, Inc. The shared explicit DBA and identical Coral Gables address support an operating-organization duplicate. The filed spelling is preserved with its source records; it is not treated as proof of a separate corporation.'
]
urls=['https://burlingtonfabrics.com/','https://www.cogweartech.com/about-1','https://businessimpactnw.org/about-us/','https://tisegroup.com/umbraco/surface/proxyapi/newspdf?id=315325&name=Eagle+Holdco+Ltd',p[ids[4]]['sources'][1]['url'],p[ids[5]]['sources'][1]['url']]
for i,n,u in zip(ids,notes,urls):
 q=p[i];q.update(review_outcome='confirmed',checked_at='2026-09-14',notes=n,identity_evidence=n,website_status='verified' if i!=ids[3] else 'partial');q['sources'].append({'url':u,'label':'Primary identity evidence reviewed September 14, 2026','claim':n})
p[ids[0]].update(description='Develops and supplies performance fabrics, yarn and textile technologies for apparel, outdoor and military uses.',kind='Textile company')
p[ids[1]].update(name='Cogwear, Inc. (represented by Burrell International Group)',website=urls[1],description='Develops investigational wearable devices for measuring brain activity, using sensors and machine learning. Represented in this filing by Burrell International Group.',kind='Medical technology company',legal_form='Corporation')
p[ids[2]].update(website=urls[2],description='A nonprofit lender that provides small-business loans, coaching and classes in Alaska, Idaho, Oregon and Washington.',ownership='Nonprofit',kind='Community development financial institution')
p[ids[3]].update(description='A US holding company in the Busy Bees childcare group, identified in its 2021 corporate report. Current ownership is not independently verified.',ownership='Unknown',kind='Holding company')
for i in ids[4:]:p[i].update(description='Distributes Cosentino architectural surfaces through the North American business named C&C North America, Inc. in official sales terms.',kind='Company',ownership='Unknown')
(r/'featured288-decisions.json').write_text(json.dumps({i:p[i] for i in ids},indent=2,ensure_ascii=False)+'\n');(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n')
mp=Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(mp));(r/'featured288-merge-before.json').write_text(json.dumps(m,indent=2)+'\n');assert not any(set(ids[4:])&set(x['source_ids']) for x in m);d=json.load(gzip.open('lobbying-map/public/data/directory-v3.json.gz','rt'));cards={x['id']:x for x in d['companies'] if x['id'] in ids[4:]};assert len(cards)==2;(r/'featured288-cards-before.json').write_text(json.dumps(cards,indent=2)+'\n');m.append({'canonical_id':ids[4],'source_ids':ids[4:],'rationale':'Both registrations explicitly give Cosentino North America as DBA and the identical Coral Gables street address. Official sales terms establish C&C North America Inc. as the supplying entity. Consolidate the operating organization while preserving the North American spelling variant and all original records.','sources':[{'url':urls[4],'label':'Official Cosentino sales terms','claim':'C&C North America Inc. and distribution subsidiaries supply Cosentino products.'},{'url':'https://disclosurespreview.house.gov/data/LD/2025_Registrations_XML.zip','label':'Registration 301695348','claim':'C&C North America Inc. d/b/a Cosentino North America, 355 Alhambra Circle Suite 1000.'},{'url':'https://disclosurespreview.house.gov/data/LD/2026_Registrations_XML.zip','label':'Registration 301873339','claim':'C&C North American Inc. dba Cosentino North America, same address.'}],'reviewed_at':'2026-09-14'});mp.write_text(json.dumps(m,indent=2,ensure_ascii=False)+'\n');print('Six identities confirmed with historical ownership qualified; one Cosentino duplicate consolidated.')
