import json,datetime,collections
from pathlib import Path
w=Path('work/research-2026');p=json.loads((w/'reviewed.json').read_text());ids=['1dbf2257797375a8','c836bcff67a578f2'];(w/'nywaterway-before.json').write_text(json.dumps({k:p[k] for k in ids},indent=2)+'\n')
sources=[{'url':'https://www.nywaterway.com/employment.aspx','claim':'Official site explicitly describes NY Waterway as privately owned and a family business, at 4800 Avenue at Port Imperial, Weehawken NJ 07086.'},{'url':'https://reports.ethics.ny.gov/publicquery/ViewFiling/Index/NzQ0NTE50','claim':'2025-2026 state registration by Constantinople & Vallone names Port Imperial Ferry Corporation DBA NY Waterway at 4800 Avenue at Port Imperial; the same firm files the 2026 federal record.'},{'url':'https://disclosurespreview.house.gov/data/LD/2015_Registrations_XML.zip','claim':'300768077.xml names Port Imperial Ferry Corporation d/b/a NY Waterway, 4800 Avenue at Port Imperial, Weehawken NJ 07086.'},{'url':'https://disclosurespreview.house.gov/data/LD/2026_Registrations_XML.zip','claim':'301865613.xml names Port Imperial Ferry Corporation dba NY Waterway, with 400 Avenue at Port Imperial, same city and ZIP, through Constantinople & Vallone.'}]
for k in ids:
 r=p[k];r.update(ownership='Private company',review_outcome='confirmed',checked_at='2026-09-09');r['identity_evidence']='The exact corporate and trading names agree across both federal registrations. The 2026 filer’s state registration uses the same 4800 Avenue at Port Imperial address as the 2015 federal record and official NY Waterway site.';r['notes']='Family-owned ferry operator according to its official site. The 2026 federal record says 400 rather than 4800; the same registrant’s state record corroborates 4800. Original address text is preserved in the source filings.';r['sources'].extend([{**s,'label':'Primary identity and ownership evidence'} for s in sources])
mp=Path('lobbying-map/research/verified-entity-merges.json');m=json.loads(mp.read_text());assert not any(set(ids)&set(x['source_ids']) for x in m);m.append({'canonical_id':ids[0],'source_ids':ids,'rationale':'Exact corporate and DBA names differ only by punctuation/case. Both federal records report Weehawken NJ 07086. The 2026 registrant’s contemporaneous state filing confirms 4800 Avenue at Port Imperial, matching the 2015 federal filing and official site, resolving the 400/4800 discrepancy. Preserve every original filing and name.','sources':sources,'reviewed_at':datetime.datetime.now(datetime.timezone.utc).isoformat()});mp.write_text(json.dumps(m,indent=2)+'\n')
for path,c in [(w/'reviewed.json',False),(Path('lobbying-map/research/reviewed-2026.json'),True),(Path('outputs/2026-research-trial/profiles.json'),False)]:path.write_text(json.dumps(p,ensure_ascii=False,**({'separators':(',',':')} if c else {'indent':2}))+'\n')
pub=json.loads((w/'publication.json').read_text());pub={k:v for k,v in pub.items() if not k.startswith('pending_')};pub.update(local_changes_pending=True,pending_source_pushed=False,pending_change_summary='NY Waterway ownership and duplicate merge, plus pending QuVa, TruStage and MBDA corrections');(w/'publication.json').write_text(json.dumps(pub,indent=2)+'\n');a=json.loads((w/'full-corpus-coverage-audit.json').read_text());a.update(as_of=datetime.datetime.now(datetime.timezone.utc).isoformat(),publication=pub,publication_stage='local_changes_pending',local_changes_pending=True,verified_merge_groups=len(m))
for key,field in [('outcomes','review_outcome'),('websites','website_status'),('logos','logo_status'),('ownership','ownership')]:a[key]=dict(collections.Counter(v.get(field,'Unknown') for v in p.values()))
(w/'full-corpus-coverage-audit.json').write_text(json.dumps(a,indent=2)+'\n');print(a['outcomes'],len(m))
