import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured110-input.json'));supp={v['id']:v for v in json.load(open(r/'featured110-supplement.json'))};before={};dec=[]
assert not (r/'featured110-before.json').exists()
updates={
0:('partial','Unknown','Gen Digital (filed as formerly MoneyLion Technologies)','Gen Digital operates consumer cybersecurity and financial-services brands. This filing combines its name with the earlier MoneyLion Technologies client label.','https://www.sec.gov/Archives/edgar/data/849399/000114036125014313/ef20047501_8k.htm','The April 2025 SEC 8-K documents MoneyLion Inc. surviving an acquisition as a wholly owned Gen Digital subsidiary. It does not document MoneyLion Technologies Inc. being renamed Gen Digital. The combined filing label remains partial.'),
1:('partial','Unknown','General Mills Services Inc. (filed as formerly General Mills)','A lobbying client associated with the General Mills food business. The exact Services entity and filed former-name relationship remain unresolved.','https://www.generalmills.com/','The official parent website establishes the food business but does not prove the Services Inc. entity or its filed former-name relationship.'),
2:('confirmed','Unknown','Genomatica','Genomatica develops biological manufacturing processes for industrial chemicals and ingredients.','https://annuaire-entreprises.data.gouv.fr/entreprise/genomatica-inc-849320965','The French government enterprise directory identifies exact Genomatica Inc., SIREN849320965, as a foreign company headquartered at 4757 Nexus Center Drive, San Diego, and engaged in chemical manufacturing. This corroborates the California filing identity. Investment and collaboration do not establish a parent owner.'),
3:('partial','Unknown','Gentiva (filed as formerly Humana and Kindred at Home)','Gentiva provides hospice and related care services. The filing combines its name with earlier Humana and Kindred at Home labels.','https://www.sec.gov/Archives/edgar/data/49071/000004907126000009/hum-20251231.htm','Humana’s 2025 10-K reports approximately35% ownership of Gentiva Hospice at December31,2025 after selling60% in2022. The filed combined name does not represent a simple legal rename or prove that all Gentiva operations are Humana subsidiaries. Exact filing scope remains partial.'),
4:('confirmed','Unknown','Glacier Fish Company','Glacier Fish Company operates fishing vessels that catch and process groundfish at sea, with a business base in Seattle.','https://www.nsedc.com/wp-content/uploads/Glacier-Fish-Announcement-10_26_21.pdf','Glacier’s October26,2021 announcement independently identifies the Seattle fishing business, vessels, address and glacierfish.com website. Identity is confirmed. Its stated future controlling-interest transaction is not treated as evidence of closing or current ownership.'),
5:('partial','Unknown','GlaxoSmithKline Inc.','A pharmaceutical lobbying client associated with GSK. The exact jurisdiction of this Inc. entity remains unresolved.','https://www.gsk.com/media/3d3fxoxd/gsk-group-company-names-and-addresses.pdf','The group company list identifies a Canadian GlaxoSmithKline Inc. The current evidence lacks an address or jurisdiction bridge to establish that it is the filed entity. No US identity or public-parent ownership classification is inferred.'),
6:('confirmed','Unknown','Glencore Ltd.','Glencore Ltd. is a US commodities business associated with the Glencore group and its international supply chains.','https://www.glencore.com/dam/jcr%3A0a7d98b0-343b-4b76-bc9f-14865deade36/Security%20Survey.pdf','Glencore’s official supplier-security document identifies exact Glencore Ltd. at330 Madison Avenue, New York, with US supply-chain operations. This establishes the entity independently of Glencore plc; ownership remains unknown.'),
7:('confirmed','Subsidiary','Google Client Services LLC','Google Client Services LLC is a Google subsidiary used for government-affairs and political activity.','https://prd.cdn.sos.ca.gov/pdf/409/Googleclie-20221227-Initial.pdf','California’s December27,2022 Form409 identifies exact Google Client Services LLC at1600 Amphitheatre Parkway and lists Google LLC with100% ownership. It also identifies XXVI Holdings Inc. as Google LLC’s member. Ownership evidence is dated2022; the entity stays separate from Google LLC.'),
8:('confirmed','Subsidiary','Google (filed as Google Inc.)','Google provides internet search, advertising, cloud computing and consumer software and devices.','https://www.sec.gov/Archives/edgar/data/1652044/000165204418000007/goog10-kq42017.htm','Alphabet’s 2017 SEC 10-K explicitly documents Google Inc. converting into an LLC in September2017 within the Alphabet reorganization. The historical filing name is retained; it does not make Google a separately publicly traded parent.'),
9:('confirmed','Unknown','Aptera Motors (via GOVBIZ Advantage)','Bell & Lindsay reported lobbying for GOVBIZ Advantage on behalf of Aptera Motors, a developer of solar electric vehicles.','https://lda.gov/filings/public/filing/c92b33e7-d1b0-4cef-bd4f-979dcb35dc96/print/','The original2026 report identifies Bell & Lindsay as registrant, GOVBIZ Advantage as intermediary client and Aptera Motors as beneficiary. This annotation confirms that representation arrangement, not a legal equivalence between the filed Inc. suffix and the website’s Aptera Motors Corp. Ownership remains unknown.')}
for k,row in enumerate(rows):
 i=row['id'];before[i]=json.loads(json.dumps(p[i]));out,own,name,desc,url,note=updates[k]
 f=dict(name=name,description=desc,review_outcome=out,ownership=own,notes=note,identity_evidence=note,checked_at='2026-09-13',as_of='2026-09-13',status='sourced',website_status='verified' if out=='confirmed' else 'partial')
 p[i].update(f);ss={s['url']:s for s in p[i].get('sources',[])};ss[url]=dict(url=url,label='Primary identity evidence',claim=note);p[i]['sources']=list(ss.values());dec.append(dict(**row,decision=out,evidence=note,sources=[ss[url]]))
(r/'featured110-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured110-first10.json').write_text(json.dumps(dec,indent=2)+'\n');(r/'featured110-middle10.json').write_text('[]\n');(r/'featured110-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('Confirmed',sum(v[0]=='confirmed' for v in updates.values()))
