import json,pathlib,copy
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));xs=json.load(open(r/'verified-sites138-next100-review.json'));before={};dec=[]
assert not (r/'featured136-before.json').exists()
extra=json.load(open(r/'featured136-extra-evidence.json'))
fix={29:'Develops submarine electricity-transmission infrastructure in the Caribbean, including the proposed Project Hostos.',56:'A manufacturing and hardware business accelerator in Southfield, Michigan, offering product-development support and funding programs.',67:'Develops IBIS, software for querying and analyzing sensor data during field operations.',69:'A navigation and infrastructure district sponsoring a feasibility and environmental study for a deeper channel connection at Cedar Port, Texas.',71:'Operates a platform for virtual intensive outpatient mental-health and substance-use programs, with clinical care provided through affiliated professional practices.',89:'A national association representing children’s hospitals and advocating for children’s health.'}
specific={0:'The official Capchem USA site identifies its battery-chemical development focus and labels its Ohio and Louisiana facilities as planned projects.',29:'The official Spanish-language site explicitly names Caribbean Transmission Development Company and its submarine-transmission work and Project Hostos. Proposed infrastructure is not treated as completed.',40:'CEDIA’s official About page describes the smart-home professional association, its training and certification, advocacy and standards work.',48:'The official About page separately identifies the Center for Freedom and Prosperity and its affiliated Foundation. The Foundation’s 501(c)(3) designation is not assigned to the Center.',54:'The official tribal-government site names the Central Council of the Tlingit and Haida Indian Tribes of Alaska and describes services for tribal citizens.',69:'The official project page identifies Cedar Port Navigation and Improvement District as the non-federal study sponsor. The feasibility and environmental review is not a completed channel project.',71:'The footer names Charlie Health, Inc. and states that clinical services are delivered through separately owned professional practices. The platform company is not conflated with every clinical entity.',74:'The official Davie site describes shipbuilding and refit work and names Chantier Davie Canada Inc. as the trademark holder and site owner.',75:'The Chariot Defense page names Chariot Defense Inc. in its footer and describes portable power storage and distribution products.',86:'The Conafay Group coalition page explicitly names Child Genetic Screening Alliance and its childhood genetic-diagnosis policy advocacy; this coalition is not the consulting firm itself.',89:'The official Children’s Hospital Association site describes its hospital membership and advocacy. An unsupported former-name statement was removed.',97:'The church’s official organization FAQ explicitly places Church of Scientology International in the international coordinating structure and states that individual churches are separately incorporated.',99:'The official CIBO site describes its agricultural software and says it is becoming part of Terion. This statement does not independently establish closing or the current exact ownership chain.'}
for n,v in enumerate(xs):
 if v['decision']!='confirmed':continue
 i=v['id'];assert p[i]['name']==v['original_name'] and p[i]['review_outcome']!='confirmed';before[i]=copy.deepcopy(p[i]);note=specific.get(n,'Official organization body text identifies this organization and supports the activity described. Existing ownership evidence is retained without inferring additional ownership from its name.')
 p[i].update(description=fix.get(n,v['description']),notes=note,identity_evidence=note,review_outcome='confirmed',checked_at='2026-09-13',as_of='2026-09-13')
 ev=v['fetched_evidence'];e=ev[0];assert e['http_status']==200
 if n in [40,97]:
  e=extra[0 if n==40 else 2];assert e['http_status']==200;ev=ev+[e]
 if n==48:
  e={'url':'https://freedomandprosperity.org/about/','retrieval':'web.open successful after direct HTTP406','reviewed_facts':'The Center is a nonprofit advancing market liberalization, tax competition, fiscal sovereignty and financial privacy. Its affiliated Foundation is separately described as a 501(c)(3).','checked_at':'2026-09-13'};ev=ev+[e]
 if n==71:p[i]['kind']='Behavioral-health platform company'
 ss={s['url']:s for s in p[i]['sources']};ss[e['url']]={'url':e['url'],'label':'Official organization evidence','claim':note};p[i]['sources']=list(ss.values());dec.append(dict(id=i,name=p[i]['name'],decision='confirmed',notes=note,fetched_evidence=ev))
(r/'featured136-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured136-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print(len(dec),'identity confirmations saved')
