import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured114-input.json'));before={};dec=[]
assert not (r/'featured114-before.json').exists()
a=[
('confirmed','Unknown','Hendrick Motorsports Performance Group, LLC','A Hendrick performance and technical-solutions company associated with vehicle engineering and manufacturing.','https://tmng-al.uspto.gov/resting2/api/casedoc/cms/case/99489711/office-action/OfficeAction8096247.pdf','The December18,2025 USPTO attachment identifies exact North Carolina Hendrick Motorsports Performance Group LLC at4400 Papa Joe Hendrick Boulevard as the original COMMANDO registrant. It separately lists Hendrick Motorsports LLC as last-listed trademark owner. A trademark assignment is not treated as a corporate rename or ownership chain.'),
('confirmed','Unknown','Hertha Metals','Hertha Metals develops iron- and steelmaking processes using natural gas, hydrogen and electricity.','https://www.govinfo.gov/content/pkg/FR-2026-07-22/pdf/FR-2026-07-22.pdf','The July22,2026 Federal Register indexed membership notice names exact Hertha Metals Inc. in Conroe, Texas. Its official contact and technology pages independently corroborate Conroe and its steelmaking pilot operation. Venture funding is not treated as proof of current ownership.'),
('confirmed','Public company','Hewlett Packard Enterprise Company','Hewlett Packard Enterprise sells enterprise computing, networking, storage and related technology services.','https://www.sec.gov/Archives/edgar/data/1645590/000164559025000130/hpe-20251031.htm','The2025 SEC10-K identifies exact Hewlett Packard Enterprise Company as the public issuer and its NYSE-listed securities. This is the HPE enterprise-technology company, distinct from HP Inc.'),
('partial','Unknown','Hewlett Packard Enterprise and affiliates','A lobbying filing covering Hewlett Packard Enterprise and unspecified affiliates in its enterprise-technology business.','https://www.sec.gov/Archives/edgar/data/1645590/000164559025000130/hpe-20251031.htm','The parent issuer is independently established, but the filing label includes affiliates whose scope is not enumerated. The combined record is not silently merged with the standalone parent issuer or classified as one exact corporation.'),
('confirmed','Unknown','Hexium Inc.','Hexium develops isotope-enrichment technology.','https://www.nrc.gov/public-involve/public-meetings/pmns/20251205','The NRC’s December2025 public-meeting record names exact Hexium Inc. and describes discussion of its proposed operations and licensing. This independently establishes the company identity; participation in a meeting does not mean a license was granted.'),
('confirmed','Unknown','Hillandale-Gettysburg, LLC','Hillandale-Gettysburg is an egg-business entity operating from Gettysburg, Pennsylvania.','https://safer.fmcsa.dot.gov/query.asp?query_param=MC_MX&query_string=579919&query_type=queryCarrierSnapshot&searchtype=ANY','FMCSA’s official carrier snapshot names exact Hillandale-Gettysburg LLC, USDOT260558, at3910 Oxford Road, Gettysburg. The February2026 federal judicial-panel order independently names the entity among egg-market parties. These records establish identity, not current parent ownership or the truth of litigation allegations.'),
('confirmed','Unknown','Hilliary Communications LLC','Hilliary Communications is an Oklahoma telecommunications business associated with rural telephone and broadband services.','https://docs.fcc.gov/public/attachments/DA-25-1074A1.pdf','The December17,2025 FCC notice footnote2 explicitly names Hilliary Communications LLC as an Oklahoma limited liability company and a sister company of the separate acquisition applicant. Ownership of Hilliary Acquisition Oklahoma II is not transferred to this entity.'),
('confirmed','Unknown','Hills & Dales General Hospital','Hills & Dales General Hospital provides hospital and outpatient care in Cass City, Michigan, within Aspire Rural Health System.','https://aspirerhs.org/our-services/infusion-services/','The current Aspire system page identifies Hills & Dales General Hospital and4675 Hill Street, Cass City. Federal HHS recipient records independently identify the same name and address. It is distinct from Hillsdale Hospital in Hillsdale, Michigan. The displayed logo is the verified shared Aspire system brand.'),
('confirmed','Nonprofit','Hillside Atlanta','Hillside provides mental-health treatment for children and young people in Atlanta.','https://hside.org/support-hillside/','The official support page names Hillside Inc. as a501(c)(3) nonprofit, gives690 Courtenay Drive NE, Atlanta, and describes its youth mental-health services.'),
('partial','Unknown','HMS Holding Limited Partnership','A lobbying client associated with the Hendrick motorsports business whose exact partnership identity remains unresolved.','https://www.hendrickmotorsports.com/','The operating website establishes the Hendrick racing business, but evidence naming HMS Holding LLC is not proof of the separately filed limited partnership. No legal-form equivalence or current ownership is inferred.')]
for k,(row,v) in enumerate(zip(rows,a)):
 i=row['id'];before[i]=json.loads(json.dumps(p[i]));out,own,name,desc,url,note=v;p[i].update(name=name,description=desc,ownership=own,review_outcome=out,notes=note,identity_evidence=note,status='sourced',checked_at='2026-09-13',as_of='2026-09-13')
 if out=='confirmed':p[i]['website_status']='verified'
 if k==7:p[i].update(website='https://aspirerhs.org/our-services/infusion-services/',logo_url='https://aspirerhs.org/wp-content/uploads/2023/12/Aspire-Logo_4C.jpg',logo_source_url='https://aspirerhs.org/',logo_kind='logo',logo_status='official_site_asset',logo_background='light')
 ss={s['url']:s for s in p[i].get('sources',[])};ss[url]=dict(url=url,label='Primary identity evidence',claim=note);p[i]['sources']=list(ss.values());dec.append(dict(**row,decision=out,evidence=note,sources=[ss[url]]))
(r/'featured114-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured114-first10.json').write_text(json.dumps(dec,indent=2)+'\n');(r/'featured114-middle10.json').write_text('[]\n');(r/'featured114-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('8 confirmed; 2 partial')
