import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'))
rows={
'0a096ca786aed4bb':('https://pediatricresearchcoalition.org/','Official coalition body retrieved September 14, 2026','The official Coalition for Pediatric Medical Research site names the coalition, describes its children’s-hospital membership and pediatric research-policy mission, and publishes dated 2026 advocacy updates. Operating identity is independently confirmed. Separate incorporation and tax status are not asserted.',{}),
'96b35833b28025e0':('https://www.coalitionfortheamericandream.us/about/','Official coalition About body retrieved September 14, 2026','The official About page identifies the Coalition for the American Dream as a group of businesses and trade associations advocating a permanent legislative solution for Dreamers. This confirms the coalition identity. Its economic estimates and policy claims are not treated as independently established facts, and no separate tax status is inferred.',{}),
'489446a31e1ea5d1':('https://media.amtrak.com/2024/07/amtrak-awards-contract-for-east-river-tunnel-rehabilitation/','Amtrak release, July 12, 2024; indexed official body inspected','Amtrak’s July 12, 2024 project release identifies the Coalition for the Northeast Corridor and its board chair, with a statement about advocating funding for rail infrastructure. This independently corroborates the coalition’s operating identity. The supplied coalition domain failed DNS resolution on September 14, 2026; current website availability and legal/tax status remain unknown.',{'website_status':'partial'}),
'364467c7193c63bd':('https://www.irem.org/File%20Library/GlobalNavigation/Advocacy/CoalitionLetters/2019/2019IRC179DCoalitionForEnergyEfficientJobsAndInvestment.pdf','Coalition letter, June 5, 2019; downloaded and read','A June 5, 2019 coalition letter hosted by the Institute of Real Estate Management explicitly names the Coalition for Energy Efficient Jobs & Investment and advocates energy-efficient commercial-building tax policy. This independently establishes the historical coalition identity. Its historical membership is not presented as current; no standalone website or tax status is established.',{}),
'd24c728cedcde9fc':('https://cgsnet.org/wp-content/uploads/2025/09/Letter-to-Sec.-McMahon-International-Education-Funding.pdf','Coalition letter, September 29, 2025; downloaded and read','A September 29, 2025 letter hosted by the Council of Graduate Schools explicitly names the Coalition for International Education and advocates federal international-education and foreign-language funding. This confirms the operating coalition independently of its lobbying filing. The hosting organization is not assigned as the coalition’s owner or separate website.',{}),
'31d9271fe0621936':('https://stopunfairruralcopays.org/wp-content/uploads/2024/12/CRM-Two-Pager-241109-1.pdf','Official coalition policy publication; downloaded and read','The coalition’s own publication explicitly identifies the Coalition for Rural Medicare Equality as rural-health experts and providers advocating equal cost, access and quality for rural Medicare beneficiaries. Operating identity and the campaign website are confirmed. Numerical claims about Medicare costs are not repeated as independently verified current facts; separate legal and tax status remain unknown.',{'website_status':'verified'}),
'056598b5a14a40e9':('https://www.coalitionfortokenizedmarkets.org/','Official coalition body retrieved September 14, 2026','The official site identifies the Coalition for Tokenized Markets and its member-led advocacy on tokenized securities, funds and collateral in US and European markets. It names Thorn Run Partners as manager; management is not treated as ownership. Operating identity is confirmed without inferring separate incorporation or tax status.',{'website_status':'verified'}),
'afebf3124deb06bc':('https://www.govinfo.gov/content/pkg/FR-2025-10-03/pdf/FR-2025-10-03.pdf','Federal Register, October 3, 2025; downloaded and read','EPA’s October 3, 2025 proposed-rule discussion explicitly defines CUSER as Coalition for the Use of Safe and Efficient Refrigerants, Inc. and cites its March 6, 2025 request concerning refrigerant transition requirements. This independently confirms the named coalition and its regulatory advocacy. A proposal is not represented as a final rule; a current standalone website and ownership remain unknown.',{'legal_form':'Corporation'})
}
b=r/'featured317-before.json';assert not b.exists();b.write_text(json.dumps({i:p[i] for i in rows},indent=2,ensure_ascii=False)+'\n')
for i,(url,label,n,fields) in rows.items():
 p[i].update(fields);p[i].update(review_outcome='confirmed',checked_at='2026-09-14',notes=n,identity_evidence=n);p[i]['sources'].append({'url':url,'label':label,'claim':n})
p['96b35833b28025e0'].update(logo_url='https://www.coalitionfortheamericandream.us/img/logo.svg',logo_kind='logo',logo_status='official_site_asset',logo_source_url='https://www.coalitionfortheamericandream.us/')
q=next(x for x in json.load(open(r/'identity316-batch.json'))['records'] if x['id']=='056598b5a14a40e9')
p[q['id']].update(logo_url=q['logo_url'],logo_kind='logo',logo_status='official_site_asset',logo_source_url=q['website'])
(r/'featured317-decisions.json').write_text(json.dumps({i:p[i] for i in rows},indent=2,ensure_ascii=False)+'\n');(r/'reviewed.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n')
print('Eight independently corroborated coalition identities saved; official logos reviewed.')
