import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));before={};dec=[]
assert not (r/'featured93-before.json').exists()
rows=json.load(open(r/'featured93-first10.json'))+json.load(open(r/'featured93-middle10.json'))
names=['TridentUSA Health Services','TridentCare','Trimble Inc. (formerly Trimble Navigation Limited)','TriNet','TriNet USA, Inc.','Trinity Cyber','Vibrint (via TriPacer Strategic Consulting)','Tripadvisor LLC','Tris Pharma and Adneuris Therapeutics','TriWest Healthcare Alliance','TRM Labs, Inc.','Trout Unlimited, Inc.','True Anomaly, Inc.','Truehold','TruGreen Limited Partnership','Truist','Trulieve','Trust for Public Land','TruStage','TruStage (formerly CUNA Mutual Group)']
kinds=['Healthcare services group','Mobile diagnostic services company','Positioning and industrial technology company','Human-resources services company','Human-resources services company','Cybersecurity company','Represented-client filing label','Travel technology company','Pharmaceutical group','Healthcare benefits contractor','Blockchain-intelligence company','Conservation organization','Space-defense company','Residential real-estate company','Lawn-care services company','Banking and financial-services group','Cannabis company','Conservation organization','Financial-services brand','Financial-services brand']
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
for idx,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));f={k:d[k] for k in ['description','website']};f.update(name=names[idx],kind=kinds[idx],ownership='Unknown',review_outcome='confirmed',notes='Official organization materials confirm identity and activity. Ownership remains unknown unless separately evidenced.',checked_at='2026-09-13',as_of='2026-09-13',status='sourced',website_status='verified');s=[src(d['official_url'],d['exact_official_excerpt'])]
 if idx==0:
  f.update(website='https://tridentcare.com/',description='TridentUSA Health Services is the healthcare group whose diagnostic-service subsidiaries adopted the TridentCare brand in 2019.');s=[src('https://tridentcare.com/about/our-story/','Official history identifies TridentUSA Health Services and its subsidiaries adopting the TridentCare brand in 2019.')];f['notes']='Historical group-to-operating-brand relationship confirmed. This is not a corporate legal rename or a merger of all subsidiaries.'
 if idx==2:
  f['ownership']='Public company';s=[src('https://www.sec.gov/Archives/edgar/data/864749/000134100416001666/ex99-1.htm','Issuer announcement documents legal name change from Trimble Navigation Limited to Trimble Inc. effective October 1, 2016.'),src('https://investor.trimble.com/overview/','Current investor page identifies Trimble as Nasdaq TRMB and describes its positioning and industrial technology.')];f['notes']='Exact legal name-change bridge confirmed in issuer SEC exhibit; original filing aliases preserved.'
 if idx==3:f['ownership']='Public company'
 if idx==4:
  f['ownership']='Subsidiary';s=[src('https://www.sec.gov/Archives/edgar/data/937098/000093709819000030/tnet-123118xexhibit211.htm','TriNet Group subsidiary exhibit identifies TriNet USA, Inc. in Delaware.'),src('https://www.sec.gov/Archives/edgar/data/937098/000093709826000010/tnet-20251231.htm','Current 2025 Form 10-K continues to name TriNet USA, Inc. in employment agreements.')];f['notes']='Exact subsidiary identity supported by SEC records; public TriNet Group listing is not assigned to TriNet USA, Inc.'
 if idx==6:
  f.update(ownership='Not applicable',description='TriPacer Strategic Consulting acting on behalf of Vibrint, a national-security technology company.');s.append(src('https://lda.gov/filings/public/filing/8bc473c5-8da9-4400-ac20-c6ef8dfc94d9/print/','2026 original report explicitly identifies TriPacer acting on behalf of Vibrint.'));f['notes']='Confirmed represented-client relationship, not corporate ownership.'
 if idx==7:s=[src('https://tripadvisor.mediaroom.com/us-privacy-policy','Official July 2025 privacy statement identifies Tripadvisor LLC as the platform owner and operator.')]
 if idx==8:
  f['description']='Tris Pharma develops medicines and drug-delivery technologies. Its wholly owned Adneuris Therapeutics subsidiary develops pain treatments.';s=[src('https://www.trispharma.com/tris-pharma-launches-adneuris-therapeutics-pain-medicine/','Official July 2026 announcement identifies Adneuris Therapeutics as wholly owned by Tris Pharma.')];f['notes']='Confirmed combined parent-and-subsidiary filing scope. The truncated filed FKA text is not interpreted as Adneuris previously being the parent Tris Pharma. Overall group ownership remains unknown.'
 if idx==9:
  f.update(review_outcome='partial',website_status='partial');f['notes']='Healthcare alliance identity and activity established; the conflicting Corp, Corporation and Inc aliases remain unresolved at exact legal-entity scope.'
 if idx==10:s=[src('https://www.trmlabs.com/policies/trm-academy','Official academy agreement identifies TRM Labs, Inc. as a Delaware corporation.'),src('https://www.trmlabs.com/trm-labs-modern-slavery-statement-2025','Official 2025 statement covers TRM Labs, Inc. and its subsidiaries.')]
 if idx==11:f['ownership']='Nonprofit';f['notes']='Official governance page establishes nonprofit status, conservation mission and exact Inc. footer name.'
 if idx==12:s=[src('https://www.trueanomaly.space/legal/cookies-policy','Official April 2026 legal policy explicitly names True Anomaly, Inc.')]
 if idx==13:
  f['description']='Truehold offers home sales and sell-and-rent arrangements that let owners sell a property and lease it back.';f['notes']='Official disclosure identifies American Secure Living Inc. doing business as Truehold and distinguishes its affiliated lending business, SFR FinCo LLC.'
 if idx==14:s=[src('https://www.trugreen.com/sites/default/files/pdf/newsroom/TruGreen%20Fact%20Sheet-min.pdf','Official company fact sheet names TruGreen Limited Partnership and describes its lawn-care business. Historical exact-identity evidence; current ownership remains unknown.')]
 if idx==15:
  f['ownership']='Public company';s=[src('https://ir.truist.com/2026-04-28-Truist-declares-common-and-preferred-stock-dividends?asPDF=1','April 2026 issuer release identifies Truist Financial Corporation as NYSE TFC.')]
 if idx==16:
  f['ownership']='Public company';s=[src('https://investors.trulieve.com/2026-06-09-Trulieve-Announces-Share-Repurchase-Program','June 2026 issuer release identifies Trulieve Cannabis Corp. and its publicly traded shares.')]
 if idx==17:
  f['ownership']='Nonprofit';s=[src('https://www.tpl.org/who-we-are','Official site identifies The Trust for Public Land as a 501(c)(3), EIN 23-7222333. Both name forms are used on the same site.')];f['notes']='Original self-registration and external registration share 100 M Street SE Suite 700, Washington, and the same parks/conservation mission. The article The does not identify a separate organization.'
 if idx in [18,19]:
  f['description']='TruStage provides insurance, investment and technology solutions for credit unions, their members and consumers.';s=[src('https://www.trustage.com/newsroom/2023-press-releases/cuna-mutual-group-becomes-trustage','May 2023 official announcement confirms CUNA Mutual Group unified its enterprise and consumer brands as TruStage.')];f['notes']='Confirmed at enterprise-brand scope. This establishes the brand transition, not legal renaming of every underlying insurer. Rejected unrelated Trellix research citations.'
 f['identity_evidence']=f['notes'];p[i].update(f);byurl={x['url']:x for x in p[i].get('sources',[])}
 for x in s:byurl[x['url']]=x
 if idx in [18,19]:byurl={u:v for u,v in byurl.items() if 'trellix.com' not in u}
 p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes']))
for d in json.load(open(r/'featured93-logo-candidates.json'))['candidates']:
 if d['id'] in [rows[0]['id'],rows[2]['id']]:p[d['id']].update(logo_url=d['asset_url'],logo_source_url=d['source_page'],logo_kind='logo',logo_status='official_site_asset',logo_background='dark' if d['id']==rows[2]['id'] else 'light')
mp=pathlib.Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(mp));ids=['6d3d6bdf3ae9284a','fbcc8fdd944f1000'];assert not any(set(ids)&set(x['source_ids']) for x in m);(r/'featured93-merges-before.json').write_text(json.dumps(m,indent=2)+'\n');m.append(dict(canonical_id=ids[0],source_ids=ids,rationale='The Trust for Public Land and Trust for Public Land share the same 100 M Street SE Suite 700 Washington registration address and parks/conservation activity. Official site uses both name forms for EIN 23-7222333. Preserve all source IDs and reports.',sources=[src('https://www.tpl.org/who-we-are','Both name forms identify the same nonprofit, EIN 23-7222333.'),src('https://disclosurespreview.house.gov/data/LD/2022_Registrations_XML.zip','Self-registration 301421338.xml matches address and conservation purpose.'),src('https://disclosurespreview.house.gov/data/LD/2023_Registrations_XML.zip','External registration 301447909.xml matches address and conservation purpose.')],reviewed_at='2026-09-13'));mp.write_text(json.dumps(m,indent=2)+'\n')
(r/'featured93-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured93-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()));print('Status changes',[(i,b.get('status'),p[i]['status']) for i,b in before.items() if b.get('status')!=p[i]['status']])
