import json,pathlib,copy
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));c={x['id']:x for x in json.load(open(r/'sbir-unresolved-candidates.json'))};sites=json.load(open(r/'sbir207-sites.json'));assert not (r/'featured207-before.json').exists()
desc={'840a772d747f0f68':'Develops processes to recover critical minerals and other useful materials from coal ash, mine waste and discarded electronics. Operates a pilot facility in Bessemer, Alabama.','0d1fb6c17635c95e':'Develops Aware in-ear biometric sensors, custom hearing protection and ear-scanning technology.','3d5a6f21852268da':'Operates Hangar, which builds companies serving public-sector needs such as wildfire response, transportation analysis and community health.','5203f8e0ba7918dd':'Develops hardware and software that connect industrial sensors and existing systems, helping organizations collect, manage and visualize equipment data.','dd913b9d60a14a52':'Operates Ixana, developing chips that transfer data through localized electric fields for connected sensors, wearable devices and machines.','434019ff70e2a75d':'Provides engineering testing, simulation, software development and 3D scanning for government and industry, including aircraft and unmanned systems.','ca7a20f9bec03de5':'Operates SBCC, helping the U.S. military adopt commercial technology and providing data engineering, analysis and leadership training.','d53d2822441c500d':'Develops vertical-takeoff aircraft and remote flight-control systems for military and government uses.','f36af1616e9dc706':'Develops and integrates autonomous systems, sensors and software for defense surveillance and aircraft readiness.','cfb4ff0d308bfe5f':'Develops residential and commercial water-heating products designed to reuse heat from computing equipment.','1dae43f171bc4370':'Develops software that analyzes data from cameras and sensors to monitor physical operations, including manufacturing processes and workplace safety.','4f252e8cc8b0c07c':'Develops electrochemical processes for refining critical minerals and producing battery electrode materials.','3ea7aa9a67e4d794':'Develops cybersecurity software for mapping exposed systems, testing defenses and conducting adversary-emulation exercises.'}
before={};dec=[]
for s in sites:
 if s.get('status')!=200 or len(s.get('text',''))<=300:continue
 i=s['id'];v=p[i];a=c[i]['records'][0];before[i]=copy.deepcopy(v)
 n=f"SBIR official award data names {a['Company']} (UEI {a['UEI']}) and links {s['url']}. Live retrieval on September 13, 2026 reached {s['final_url']} and the page's business content corroborates the organization. Identity and current website confirmed; no ownership conclusion is inferred from this match."
 v.update(review_outcome='confirmed',website=s['final_url'],website_status='verified',checked_at='2026-09-13',identity_evidence=n,notes=n)
 if i in desc:v['description']=desc[i]
 if i=='d25c736fed7569e9':
  n+=' Previous logo was hosted on an unverified different domain and has been removed pending asset verification.';v.update(logo_url='',logo_kind='',logo_source_url='',logo_status='unresolved',notes=n)
 for u,label in [('https://data.www.sbir.gov/mod_awarddatapublic_no_abstract/award_data_no_abstract.csv','SBIR identity and website: '+a['UEI']),(s['final_url'],'Official operating website')]:v['sources'].append(dict(url=u,label=label,claim=n))
 dec.append(dict(id=i,decision='confirmed_identity_and_website',registry_record=a,website=s['final_url'],notes=n))
assert len(dec)==21
for k,v in [('before',before),('decisions',dec)]: (r/f'featured207-{k}.json').write_text(json.dumps(v,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('Saved 21 identities/websites; removed unverified Havik logo')
