import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));before={};dec=[]
assert not (r/'featured115-before.json').exists()
a=[
('2c1b4e9a5ef41776','Public company','Clearwater Paper manufactures paperboard for packaging.','https://www.sec.gov/Archives/edgar/data/1441236/000144123626000007/clw-20251231.htm','The2025 annual report confirms Clearwater Paper as the NYSE CLW issuer. Its tissue business was sold in2024; the current description focuses on paperboard.'),
('1426c32ce46a4d91','Subsidiary','Cleco Power LLC is a regulated electric utility serving Louisiana.','https://www.sec.gov/Archives/edgar/data/1089819/000108981926000004/cnl-20260424.htm','The April24,2026 SEC filing explicitly names exact Cleco Power LLC as an indirect wholly owned subsidiary of Cleco Partners LP. Its announced upstream sale was conditional in that source, so no completed buyer change is inferred.'),
('32916dbd7977a5d2','Subsidiary','Clene Nanomedicine develops potential treatments for neurodegenerative diseases.','https://www.sec.gov/Archives/edgar/data/1822791/000143774926008482/clnn20260316_8k.htm','The March2026 SEC filing and current official Clene releases explicitly identify exact Clene Nanomedicine Inc. as a wholly owned subsidiary of Clene Inc. The parent’s CLNN listing is not transferred to this subsidiary.'),
('bf8e7574cb7d1590','Subsidiary','CMFG Life Insurance Company issues life insurance and annuity products under the TruStage business.','https://www.sec.gov/Archives/edgar/data/1562577/000156257726000130/memberszoneannuityn-4202604.htm','The2026 SEC-filed organizational schedule lists exact Iowa CMFG Life Insurance Company as100% owned within TruStage Financial Group and CUNA Mutual Holding Company. The exact insurer is a subsidiary; mutual ownership characterizes the ultimate parent.'),
('35cbc29d87d2d2f1','Subsidiary','Cognizant Technology Solutions U.S. Corporation provides technology and consulting services within the Cognizant group.','https://www.sec.gov/Archives/edgar/data/1058290/000105829019000009/ctshexhibit21112312018.htm','The2018 SEC Exhibit21 identifies exact Cognizant Technology Solutions U.S. Corporation as a consolidated US subsidiary. A2023 SEC-filed employment agreement separately names the same employing entity. Historical ownership evidence is dated; no listed-parent equivalence is inferred.')]
for i,own,desc,url,note in a:
 before[i]=json.loads(json.dumps(p[i]));p[i].update(ownership=own,description=desc,notes=note,identity_evidence=note,review_outcome='confirmed',website_status='verified',checked_at='2026-09-13',as_of='2026-09-13');s={x['url']:x for x in p[i]['sources']};s[url]=dict(url=url,label='Primary evidence rechecked',claim=note);p[i]['sources']=list(s.values());dec.append(dict(id=i,name=p[i]['name'],decision='confirmed',notes=note,sources=[s[url]]))
(r/'featured115-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured115-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('5 root-verified SEC identities confirmed')
