import json,pathlib,copy
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));assert not (r/'featured183-before.json').exists();before={};dec=[]
rows=[('a0ba965a0ef76a7c','https://bigid.com/privacy-notice/','The March 9, 2026 official privacy notice explicitly identifies BigID Inc. and its bigid.com website. This confirms the legal-name bridge; ownership remains Unknown.'),('0b4fd0d1097c82ab','https://www.supremecourt.gov/DocketPDF/23/23-1122/326647/20240923152836857_Atsign%20merits%20amicus%20brief%20Free%20Speech%20Coal.%20v.%20Paxton%20No.%2023-1122.pdf','Its 2024 Supreme Court amicus brief identifies Atsign, Inc. and describes its data security and identity-management technology. Current official service terms corroborate the activity. Ownership remains Unknown.'),('ca13035731f6c757','https://www.atln.com/press/attalon-appoints-defense-technology-leader-jonathan-moneymaker-to-board-of-directors','The June 1, 2026 official company announcement names Attalon, Inc. and describes its directed-energy, optical, coating and thermal technology business. It says Advent backs the business; ownership percentage and legal parentage are not established.')]
for i,u,n in rows:
 v=p[i];before[i]=copy.deepcopy(v);v.update(review_outcome='confirmed',status='sourced',website_status='verified',checked_at='2026-09-13',identity_evidence=n,notes=n);v['sources'].append(dict(url=u,label='Primary legal-name evidence',claim=n));dec.append(dict(id=i,decision='confirmed',notes=n))
i='ea08404449e0534d';v=p[i];before[i]=copy.deepcopy(v);n='The Atropos domain now redirects to CHAOS. A July 29, 2026 company announcement states CHAOS acquired Atropos Group and the team joined its aerospace division. This does not establish whether Atropos Group, Inc. survives as a separate legal subsidiary, so legal ownership classification and exact entity continuity remain unresolved.';v.update(description='Developed autonomous aircraft for logistics and other missions; CHAOS announced its acquisition of Atropos Group in July 2026.',notes=n,checked_at='2026-09-13');v['sources'].append(dict(url='https://markets.financialcontent.com/prnews.pressre/article/bizwire-2026-7-29-chaos-industries-acquires-atropos-group-uniting-sensing-and-effects-with-autonomous-airborne-platforms',label='Company acquisition announcement, syndicated by Business Wire',claim=n));dec.append(dict(id=i,decision='partial',notes=n))
for name,value in [('before',before),('decisions',dec)]: (r/f'featured183-{name}.json').write_text(json.dumps(value,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False))
e=json.load(open(r/'featured183-evidence.json'));e[0]['text']=(r/'featured183-bigid.txt').read_text();e[0]['cache_path']='featured183-bigid.pdf';e[0]['note']='Response is PDF, decoded with pdftotext; earlier html cache was an invalid text decode and is not evidence.';(r/'featured183-evidence.json').write_text(json.dumps(e,indent=2)+'\n');print('3 confirmed; Atropos acquisition annotated without unsupported legal-parent inference')
