import json,pathlib,datetime
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));before={};dec=[]
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
rows=json.load(open(r/'featured83-first10.json'))+json.load(open(r/'featured83-middle10.json'))
names=['Seattle Arena Company','Seattle Children’s','Second Harvest Food Bank — South Louisiana','Secular Coalition for America','CLEAR (Secure Identity, LLC)','CLEAR (Secure Identity, LLC)','Securitize I, Inc. (formerly Securitize, Inc.)','Solar Energy Industries Association (SEIA)','Seismic Software, Inc.','Select Medical Corporation','Select Medical Holdings Corporation','Sempra (formerly Sempra Energy)','Sequoia Capital Operations LLC','Sevita','SHEIN Technology LLC','Shell USA, Inc. (formerly Shell Oil Company)','Shell USA, Inc.','Shell USA, Inc. (formerly Shell Oil Company)','Sherwin-Williams','SHI International Corp.']
extra={1:[src('https://lda.gov/filings/public/filing/f2f6bc3b-9c78-441b-b673-c3bc830754aa/print/','2026 registration names Seattle Children’s at 4800 Sand Point Way NE, Seattle, and describes a nonprofit pediatric hospital, health care provider and medical research institution.'),src('https://www.seattlechildrens.org/about/','Official institutional page describes pediatric care and research. The unsuffixed institution is identified; no Foundation-specific tax status is transferred.')],2:[src('https://lda.gov/filings/public/filing/c7447803-f558-45b5-a29c-168b2b22bd55/print/','2024 registration names Second Harvest Food Bank at 700 Edwards Avenue, New Orleans, LA 70123 and describes fighting hunger in South Louisiana. This resolves the geographic ambiguity among same-name food banks.')],6:[src('https://www.sec.gov/Archives/edgar/data/2094496/000162828026056164/secz-20260812.htm','August 2026 issuer filing explicitly identifies Securitize I, Inc. as formerly Securitize, Inc. and distinguishes it from listed Securitize Corp.')],11:[src('https://www.sec.gov/Archives/edgar/data/1032208/000103220824000007/R24.htm','Issuer financial statement explicitly states Sempra Energy changed its name to Sempra effective May 12, 2023.'),src('https://www.sempra.com/our-business','Current company page identifies Sempra and NYSE SRE.')],14:[src('https://seller-us.shein.com/agreement/global_seller_privacy_notice/R23120702','Official seller privacy notice identifies SHEIN Technology LLC at 777 S Alameda Street Suite 400, Los Angeles, as an entrusted technical-services provider maintaining marketplace functionality and protecting user data.')],19:[src('https://www.shi.com/terms/terms-and-conditions','Official terms name SHI International Corp.'),src('https://blog.shi.com/wp-content/uploads/2025/06/shi-2024-sustainability-and-action-report-1.pdf','Official 2024 sustainability report identifies SHI International Corp. and its private business.') ]}
clear=src('https://ir.clearme.com/sec-filings/all-sec-filings/content/0001856314-26-000006/exhibit211.htm','Clear Secure, Inc. 2026-filed subsidiary list explicitly lists Delaware Secure Identity, LLC. CLEAR terms identify Secure Identity, LLC as operator of the CLEAR program; the LLC is distinct from its publicly listed parent.')
shell=src('https://climatecasechart.com/wp-content/uploads/case-documents/2022/20220315_docket-22-1096_brief.pdf','Shell’s corporate disclosure in its March 15, 2022 court brief states Shell Oil Company changed its name to Shell USA, Inc. effective March 1, 2022. It identifies Shell USA as a subsidiary whose ultimate parent is Shell plc. The PDF is the party’s original brief hosted by a legal archive.')
select=src('https://www.sec.gov/Archives/edgar/data/1320414/000110465926079643/tm2619266d7_8k.htm','Select Medical Holdings acquisition became effective July 1, 2026; Holdings survived as an indirect subsidiary of Stallion Intermediate Corp. Its public-company status ended.')
selectop=src('https://www.selectmedical.com/-/media/project/selectmedical/inpatients/selectmedical/files/media-and-news/2025-annual-report-10-k.pdf?rev=ee6777fb01be4a488a8d4a03b8dd6569&t=20260219214305','2025 annual report distinguishes Select Medical Corporation, the wholly owned operating subsidiary, from Select Medical Holdings Corporation. They are not duplicate legal entities.')
for idx,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));s=[src(d['official_url'],d['exact_official_excerpt'])]
 for x in d.get('sources',[]):
  if x.get('excerpt'):s.append(src(x['url'],x['excerpt']))
 s+=extra.get(idx,[])
 f={k:d[k] for k in ['description','kind','website']};f.update(name=names[idx],ownership='Unknown',review_outcome='confirmed',notes=d['evidence'],identity_evidence=d['evidence'],checked_at='2026-09-13',as_of='2026-09-13',status='sourced',website_status='verified')
 if idx in [1,2,3]:f['ownership']='Nonprofit'
 if idx==1:f.update(description='Seattle pediatric healthcare and medical-research institution serving children and families across the Pacific Northwest.',kind='Pediatric healthcare institution')
 if idx==2:f['description']='South Louisiana food bank distributing food and providing hunger advocacy, education and disaster response; based in the New Orleans area.'
 if idx in [4,5]:f['ownership']='Subsidiary';s.append(clear)
 if idx==6:f.update(ownership='Subsidiary',description='Digital-asset tokenization business filed under Securitize, Inc.; an August 2026 SEC filing identifies its renamed entity as Securitize I, Inc., distinct from listed Securitize Corp.')
 if idx==7:f.update(ownership='Not applicable',description='National trade association representing the U.S. solar and energy-storage industry.');f['notes']='Official SEIA standards site expands the acronym and identifies the national trade association. Specific tax classification is not established by this source.'
 if idx in [9,10]:s.extend([select,selectop]);f['ownership']='Subsidiary' if idx==9 else 'Private company';f['description']='Hospital and rehabilitation care operator Select Medical Corporation, the operating subsidiary of Select Medical Holdings Corporation.' if idx==9 else 'Holding company for Select Medical’s hospital and rehabilitation business. Its acquisition closed effective July 1, 2026, taking the company private.'
 if idx in [11,18]:f['ownership']='Public company'
 if idx==14:f.update(description='SHEIN entity providing technical services for its marketplace, including maintaining functionality and protecting user data.',kind='Marketplace technology services')
 if idx in [15,16,17]:f.update(ownership='Subsidiary',description='U.S. Shell energy company, formerly Shell Oil Company. It adopted the Shell USA, Inc. name on March 1, 2022; part of the Shell group.');s.append(shell)
 if idx==19:f['ownership']='Private company'
 if idx in extra or idx in [4,5,9,10,15,16,17]:f['notes']=' '.join(x['claim'] for x in s[1:] if x in extra.get(idx,[]) or x in [clear,shell,select,selectop]);f['identity_evidence']=f['notes']
 if idx==7:f['identity_evidence']=f['notes'];s=[src(d['official_url'],'Official SEIA standards site identifies the Solar Energy Industries Association as a national solar and energy-storage trade association.')]
 p[i].update(f);seen={x['url'] for x in p[i]['sources']}
 for x in s:
  if x['url'] not in seen:p[i]['sources'].append(x);seen.add(x['url'])
 dec.append(dict(id=i,decision=f['review_outcome'],notes=f['notes']))
(r/'featured83-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured83-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
mfile=pathlib.Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(mfile))
for ids,evidence in [(['7b965de2343a51b4','eddaa5cb25312f79'],[src('https://www.clearme.com/terms-of-use','Official terms identify Secure Identity, LLC as CLEAR operator. Both source labels name the identical LLC and CLEAR DBA with punctuation differences.'),clear]),(['02948525f9a05a9b','62c7a4b321516b70','1f9e02688cbbbd65'],[shell])]:
 assert not any(set(ids)&set(x['source_ids']) for x in m)
 m.append(dict(canonical_id=ids[0],source_ids=ids,rationale=evidence[0]['claim'],sources=[dict(url=x['url'],claim=x['claim']) for x in evidence],reviewed_at=datetime.datetime.now(datetime.timezone.utc).isoformat()))
mfile.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()),'merges',len(m))
