import json,pathlib,copy
from bs4 import BeautifulSoup
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));xs=json.load(open(r/'verified-sites154-next100-review.json'));before={};dec=[]
assert not (r/'featured152-before.json').exists()
fix={1:'Develops a platform for digital tokens linked to physical gold coins.',2:'Provides software engineering, systems engineering and mission analytics for government customers.',4:'Researches, designs and flight-tests experimental rotorcraft and unmanned aircraft.',6:'Develops software and hardware that connect sensors, autonomous systems and operators for defense operations.',58:'Develops tests to help clinicians assess recurrence risk and treatment options for ductal carcinoma in situ, a form of breast cancer.',61:'Provides intelligence, engineering and mission-support services for U.S. defense and government agencies.',71:'Provides cardiac rehabilitation education, training and program support for healthcare providers.',72:'Develops hardware-based mobile security products for government and enterprise customers.',73:'A producer-owned beef business focused on connecting cattle producers with meat processing.',81:'Develops blockchain-based securities infrastructure through subsidiaries covering issuance, trading, custody and post-trade services.'}
special={1:'Official Phinance Gold LLC body describes a gold-token platform under development. Gold reserves, backing and regulatory claims are not independently established.',4:'Official Piasecki Aircraft Corporation body describes experimental rotorcraft development and flight testing.',6:'Official Picogrid body describes integrated sensors, systems and operators and identifies Picogrid Inc. in its footer.',14:'Official Pioneer Credit Recovery, Inc. body describes debt collection and government customer services. A new-ownership announcement is present, but the owner is not established by this page.',40:'Official PolyPlus body explicitly identifies PolyPlus Battery Company and its Berkeley battery-development operation. Performance and safety claims are not independently established.',58:'Official PreludeDx body describes DCISionRT testing. Clinical effectiveness and treatment recommendations are not independently assessed.',61:'Official Prescient Edge body describes government intelligence and engineering services and states veteran-owned status. No further legal ownership classification is inferred.',65:'Official Primergy body describes solar and battery projects, distinguishing development, construction and operation.',73:'Official Producer Owned Beef, LLC body identifies a producer-owned business and processing mission. This page does not establish when a processing plant began operating.',78:'Official Prolegis body identifies legislative software and names Prolegis, LLC in the footer.',81:'Official Prometheum body distinguishes its subsidiaries and their securities infrastructure activities. Regulatory compliance claims are not independently certified.',84:'Official ProShares body lists exchange-traded fund products. Fund performance and return claims are not adopted.',95:'Official PSYONIC body describes bionic hands for humans and robots. Performance and insurance-coverage claims are not independently established.',97:'Official PTS Expeditionary Communications, Inc. body identifies radio power and expeditionary communications equipment in Huntsville, Alabama.'}
for n,v in enumerate(xs):
 if v['decision']!='confirmed' or n in [62]:continue
 i=v['id'];assert p[i]['name']==v['original_name'] and p[i]['review_outcome']!='confirmed';before[i]=copy.deepcopy(p[i]);note=special.get(n,'Official organization body text identifies this organization and supports the activity summarized. Existing ownership evidence is retained without inferring additional ownership from its name.')
 p[i].update(description=fix.get(n,v['description']),notes=note,identity_evidence=note,review_outcome='confirmed',checked_at='2026-09-13',as_of='2026-09-13')
 

 e=v['fetched_evidence'][0];assert e['http_status']==200
 s=BeautifulSoup(open(e['cache_path']).read(),'html.parser')
 for t in s(['script','style','nav','header']):t.decompose()
 body=' '.join(s.stripped_strings)
 ss={s['url']:s for s in p[i]['sources']};ss[e['url']]={'url':e['url'],'label':'Official organization evidence','claim':note};p[i]['sources']=list(ss.values());dec.append(dict(id=i,name=p[i]['name'],decision='confirmed',notes=note,fetched_evidence=v['fetched_evidence'],reviewed_body=body))
(r/'featured152-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured152-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
(r/'featured152-deferred.json').write_text(json.dumps([dict(id=xs[62]['id'],name=xs[62]['original_name'],reason='Domain contains general preservation articles, not evidence of the claimed archival-equipment manufacturer. Exact website requires correction.')],indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print(len(dec),'identity confirmations saved')
