import json,copy,datetime
from pathlib import Path
p=Path('work/research-2026');d=json.load(open(p/'reviewed.json'));inp=json.load(open(p/'featured67-input.json'));before={x['id']:copy.deepcopy(d[x['id']]) for x in inp};rows=[
('2e2764a19dc73394','https://imbue.com/blog/introducing-imbue','Official company announcement identifies Imbue and its AI reasoning/coding research, and explicitly states the former Generally Intelligent name. The original filing is the unsuffixed Imbue brand; ownership is not inferred from funding.','Unknown'),
('155d9ed5617e5590','https://impossible-objects.com/','Official site identifies Impossible Objects and its composite-based additive-manufacturing printers and parts services, matching the original unsuffixed name and 3D-printing activity. No marketing performance comparisons are treated as independently verified.','Unknown'),
('c567095987ae5b3e','https://www.impulsespace.com/legal','Official August 13, 2025 terms explicitly identify Impulse Space Inc., matching the original brand/Inc aliases and space-transportation business.','Unknown'),
('60c6f00b0593584b','https://inari.com/privacy-policy/','Official May 29, 2026 privacy policy defines Inari as Inari Agriculture Inc. and affiliates and lists One Kendall Square, Building700 Suite7-501 Cambridge. The original unsuffixed Inari registration has this Cambridge address and agricultural activity; foreign affiliates are not substituted.','Unknown'),
('e8640b76ee6ef6d6','https://inari.com/privacy-policy/','Official May 29, 2026 privacy policy explicitly names Inari Agriculture Inc. and lists One Kendall Square Building700 Suite7-501 Cambridge, matching original filed legal aliases and address.','Unknown'),
('3ace88c3898f9cc8','https://includedhealth.com/resources/how-to-fix-healthcare-quality/','Official company article explicitly describes Grand Rounds as rebranded Included Health. This supports the original unsuffixed brand with former-name parenthetical; no separate subsidiary identity or ownership is inferred.','Unknown'),
('a64ff3ff005891c8','https://incompas.org/','Official INCOMPAS website identifies its communications and technology policy advocacy and membership activities, matching the original unsuffixed association. Tax-exempt status is not established by this page.','Unknown'),
('2ea08e0e518cc77e','https://www.indeed.com/legal/indeed-jobs','Official February 20, 2026 recruitment privacy policy explicitly names Indeed Inc. among US entities and states Indeed and affiliates are directly or indirectly owned by Recruit Holdings Co Ltd. Preserve Indeed Inc. as a subsidiary rather than marking it as the listed parent.','Subsidiary of Recruit Holdings'),
('08465d91d91cc026','https://www.itic.org/about/','Official About page spells out Information Technology Industry Council and acronym ITI, and describes technology-industry policy advocacy, matching the original name and acronym parenthetical. Tax-exempt status is not independently established.','Unknown')]
for i,u,e,o in rows:
 x=d[i];assert x['review_outcome']!='confirmed';x.update(review_outcome='confirmed',ownership=o,identity_evidence=e,notes=e,checked_at='2026-09-13',as_of='2026-09-13',website_status='verified');x['sources']=[s for s in x.get('sources',[]) if s.get('label')=='Original lobbying disclosure']+[{'url':u,'label':'Primary identity evidence','claim':e}]
(p/'featured67-before.json').write_text(json.dumps(before,indent=2,ensure_ascii=False)+'\n');(p/'featured67-root-decisions.json').write_text(json.dumps(rows,indent=2,ensure_ascii=False)+'\n')
for f,indent,nl in [(p/'reviewed.json',2,True),(Path('lobbying-map/research/reviewed-2026.json'),None,False),(Path('outputs/2026-research-trial/profiles.json'),2,True)]:f.write_text(json.dumps(d,ensure_ascii=False,indent=indent)+ ('\n' if nl else ''))
mf=Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(mf));ids=['e8640b76ee6ef6d6','60c6f00b0593584b'];assert not set(ids)&{i for x in m for i in x['source_ids']};e='Official policy defines Inari/Inari Agriculture Inc.; both original registrations share One Kendall Square Cambridge and agricultural activity. Preserve all filings and keep foreign affiliates distinct.';m.append({'canonical_id':ids[0],'source_ids':ids,'rationale':e,'sources':[{'url':'https://inari.com/privacy-policy/','claim':e}],'reviewed_at':datetime.datetime.now(datetime.timezone.utc).isoformat()});mf.write_text(json.dumps(m,indent=2,ensure_ascii=False)+'\n');print('Saved9, merge1')
