import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured102-first10.json'));before={};dec=[]
assert not (r/'featured102-before.json').exists()
def src(u,c):return dict(url=u,label='Primary organization evidence',claim=c)
fix=[
('Chemonics International, Inc.','Unknown','Current official privacy terms identify Chemonics International Inc. Historical employee ownership is documented in the signed 2023 statement; current ownership percentage has not been re-established.',[src('https://www.chemonics.com/terms/','Official privacy terms identify exact Chemonics International Inc.'),src('https://chemonics.com/wp-content/uploads/2023/08/Modern-Day-Slavery-and-Anti-Human-Trafficking-Statement_2023-signed.pdf','Signed 2023 statement describes employee ownership at that time; not a current percentage verification.')]),
('Chevron Phillips Chemical Company LP','Subsidiary','EPA identifies the exact LP as a subsidiary of Chevron Phillips Chemical Company LLC. The LLC is the joint venture. Ownership relationship is documented in the 2022 EPA record; latest intermediate ownership percentages are not independently refreshed.',[src('https://www.epa.gov/enforcement/chevron-phillips-chemical-company-clean-lp-air-act-settlement','EPA March2022 company overview names the LP, its petrochemical products, and its LLC parent.')]),
('Chevron U.S.A. Inc.','Subsidiary','Chevron’s 2025 subsidiary exhibit lists exact Chevron U.S.A. Inc., organized in Pennsylvania, as wholly owned directly or indirectly. Public-parent ticker is not assigned to this subsidiary.',[src('https://www.sec.gov/Archives/edgar/data/93410/000009341026000078/cvx12312025ex211.htm','2025 year-end subsidiary exhibit lists exact Chevron U.S.A. Inc. and wholly owned group relationship.'),src('https://www.sec.gov/Archives/edgar/data/93410/000009341025000062/cvx-20250630.htm','Note6 describes Chevron U.S.A. and subsidiaries managing most U.S. exploration, production, refining and marketing businesses.')]),
('Chicago Botanic Garden','Nonprofit','Official donor page identifies Chicago Horticultural Society doing business as Chicago Botanic Garden, EIN36-2225482. Nonprofit classification describes the operator; the garden property is publicly owned by the Forest Preserve District of Cook County.',[src('https://www.chicagobotanic.org/donate/daf','Official donor page explicitly names Chicago Horticultural Society as legal name and Chicago Botanic Garden as DBA.')]),
('Chime','Public company','Unsuffixed Chime filing is retained at company-brand scope. Current 2026 results and investor FAQ identify Chime Financial Inc., Nasdaq CHYM. Chime is a financial technology company providing services through partner banks.',[src('https://investors.chime.com/shareholder-services/investor-faqs','Issuer investor FAQ identifies Chime Financial Inc. and Nasdaq CHYM listing.'),src('https://www.chime.com/newsroom/chime-reports-second-quarter-2026-financial-results/','Current2026 results identify Chime as Nasdaq CHYM fintech company.')]),
('Chobani Yogurt','Unknown','Official brand and food-product identity confirmed. Original unsuffixed filing label retained. The prior privately-held citation concerns a 2023 Australian group statement; current ownership of the exact U.S. filing entity is not established.',[src('https://www.chobani.com/','Official Chobani brand website and food products.'),src('https://www.chobani.com.au/wp-content/uploads/Chobani-Modern-Slavery-Statement-2023.pdf','2023 Australian statement describes Chobani Pty Ltd and Chobani Global Holdings LLC; used for group context, not current U.S. entity ownership.')]),
("Christie’s Inc.",'Unknown','Official U.S. supplier terms explicitly identify Christie’s Inc., a New York corporation. This supports the filed Inc. aliases; exact current ownership chain is not assigned from the broad auction-house brand.',[src('https://www.christies.com/about/terms-and-conditions/terms-and-conditions-for-suppliers','U.S. supplier terms identify Christie’s Inc., a New York corporation at 20 Rockefeller Plaza.')]),
('The Cigna Group (formerly Cigna Corporation)','Public company','SEC8-K proves Cigna Corporation legally changed its name to The Cigna Group effective February13,2023. Current July2026 dividend notice confirms NYSE CI. Subsidiary insurers remain separate.',[src('https://www.sec.gov/Archives/edgar/data/1739940/000095015923000019/cigna8k.htm','February2023 SEC8-K documents Cigna Corporation name change to The Cigna Group.'),src('https://newsroom.thecignagroup.com/2026-07-22-The-Cigna-Group-Declares-Quarterly-Dividend','July2026 issuer notice identifies The Cigna Group as NYSE CI and describes Cigna Healthcare and Evernorth businesses.')]),
('Circle','Public company','Unsuffixed filing matched at Circle group-brand scope. Current2026 earnings identify listed issuer Circle Internet Group Inc., NYSE CRCL. Public listing is a group-level fact and does not establish an operating affiliate as the filing entity.',[src('https://www.circle.com/pressroom/circle-reports-second-quarter-2026-results','Current2026 earnings identify Circle Internet Group Inc., NYSE CRCL, and digital financial infrastructure business.')]),
('Citadel','Unknown','Investment-management brand confirmed. Federal Register2020 identifies Citadel Enterprise Americas LLC as formerly Citadel LLC, but the grouped unsuffixed and LLC lobbying aliases still need filing-level reconciliation. Citadel Securities is a separate business; no ownership chain or automatic merge assigned.',[src('https://www.citadel.com/notices/','Current official notice describes Citadel and affiliated advisers managing private investment funds.'),src('https://www.federalregister.gov/documents/2020/12/28/2020-28492/citadel-enterprise-americas-llc-formerly-citadel-llc-and-ceif-llc-notice-of-application','2020 SEC notice explicitly names Citadel Enterprise Americas LLC as formerly Citadel LLC; historical name bridge, not proof all lobbying records represent that entity.')])]
for idx,d in enumerate(rows):
 i=d['id'];before[i]=json.loads(json.dumps(p[i]));name,ownership,note,s=fix[idx]
 f=dict(name=name,description=d['description'],kind=d['kind'],ownership=ownership,review_outcome='partial' if idx==9 else 'confirmed',notes=note,identity_evidence=note,website=d['website'],website_status='verified',status='sourced',checked_at='2026-09-13',as_of='2026-09-13')
 if idx==3:f['description']='Chicago Botanic Garden is a living museum, plant-science and education organization operated by the nonprofit Chicago Horticultural Society on publicly owned property.'
 if idx==7:f['description']='The Cigna Group is a health-services company whose businesses include Cigna Healthcare insurance and Evernorth pharmacy and care services.'
 if idx==9:f.update(description='Citadel is an investment-management firm whose affiliated advisers manage private investment funds.',kind='Investment-management firm',website='https://www.citadel.com/')
 bad={d['official_url']} - {x['url'] for x in s}
 byurl={x['url']:x for x in p[i].get('sources',[]) if x['url'] not in bad}
 for x in s:byurl[x['url']]=x
 p[i].update(f);p[i]['sources']=list(byurl.values());dec.append(dict(id=i,decision=f['review_outcome'],notes=note,sources=s))
(r/'featured102-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured102-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for path in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:path.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False))
print('New confirmed',sum(p[i]['review_outcome']=='confirmed' and b['review_outcome']!='confirmed' for i,b in before.items()));print('Status changes',[(i,b.get('status'),p[i]['status']) for i,b in before.items() if b.get('status')!=p[i]['status']])
