import json,pathlib,copy
from bs4 import BeautifulSoup
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));xs=json.load(open(r/'verified-sites163-next100-review.json'));before={};dec=[]
assert not (r/'featured164-before.json').exists()
accepted=[25,28,29,31,34,35,38,40,42,45,49,51,52]
fix={28:'Develops an immune-activation technology platform intended for cancer and infectious-disease treatments.',31:'Developing the V-Eagle rare-earth separation project in San Bernardino County, California, with a stated target of commercial launch in 2028.',35:'Developing an ammonia-fertilizer project in Indiana that repurposes existing energy infrastructure and plans to capture and store carbon dioxide.',45:'Operates a rural water system serving north-central South Dakota.',51:'A family office operating across affordable housing, fund management, entertainment services and computer-aided design software.'}
special={25:'Official VLS body and Environmental Solutions LLC footer identify its waste, hazardous-waste, marine and rail services. Disposal safety and environmental-performance claims are not independently established.',28:'Official Voltron Therapeutics body describes a licensed immune-activation platform; footer identifies Voltron, Inc. Intended therapeutic benefits are not established clinical outcomes.',29:'Official body explicitly identifies Von Batten-Montague-York, L.C. and its advisory and lobbying services. Its criticism of news reporting is an advocacy position, not an independent finding.',31:'Official VTRU Corporation project page describes V-Eagle and a target 2028 launch. The facility is planned; claims about absence of competing U.S. facilities and projected capacity are not independently established.',35:'Official Wabash Valley Resources body describes a developing fertilizer project and future carbon capture. Planned employment, emissions and capture volumes are not operating results.',38:'Official association About body describes agricultural water providers and lists member irrigation districts and companies. Government members do not make the association itself a government agency.',40:'Official Watchtower Labs careers body describes the decision and simulation software it is building for military logistics and planning. Proposed capability is not proof of fielded performance.',42:'Official Waters Advocacy Coalition About body identifies business and agricultural membership and water-policy advocacy. Legal and economic assertions on the page are advocacy claims, not independent findings.',45:'Official body and address identify WEB Water Development Association Inc. and rural water service. Public water service does not by itself establish government ownership.',49:'Official WelbeHealth body describes its PACE senior-care services. Cost and eligibility are conditional; no universal free-care claim is made.',51:'Official firm overview explicitly identifies The Wentwood Companies as a family office and describes four operating areas. The description now includes activities beyond housing; affiliate assets are not assigned directly to each entity.'}
for n in accepted:
 v=xs[n];i=v['id'];assert p[i]['name']==v['original_name'] and p[i]['review_outcome']!='confirmed';before[i]=copy.deepcopy(p[i]);note=special.get(n,'Official organization body identifies this organization and supports its stated services. Existing ownership evidence is retained; advertised outcomes are not independently verified.')
 p[i].update(description=fix.get(n,v['description']),notes=note,identity_evidence=note,review_outcome='confirmed',checked_at='2026-09-13',as_of='2026-09-13')
 e=v['fetched_evidence'][0];assert e['http_status']==200
 s=BeautifulSoup(open(e['cache_path']).read(),'html.parser')
 for t in s(['script','style','nav','header']):t.decompose()
 ss={s['url']:s for s in p[i]['sources']};ss[e['url']]={'url':e['url'],'label':'Official organization evidence','claim':note};p[i]['sources']=list(ss.values());dec.append(dict(id=i,name=p[i]['name'],decision='confirmed',notes=note,fetched_evidence=v['fetched_evidence'],reviewed_body=' '.join(s.stripped_strings)))
for name,value in [('before',before),('decisions',dec),('deferred',[dict(id=xs[n]['id'],name=xs[n]['original_name'],reason=reason) for n,reason in [(33,'Product body identifies VulnCheck brand but reviewed page does not establish Inc. legal identity.'),(53,'Fetched page is only a region selector; no activity evidence in body.')]])]:
 (r/f'featured164-{name}.json').write_text(json.dumps(value,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print(len(dec),'identity confirmations saved')
