import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured112-input.json'));before={};dec=[]
assert not (r/'featured112-before.json').exists()
a=[
('Guidehouse','Private company','Guidehouse provides consulting and managed services to government agencies and commercial clients.','https://guidehouse.com/news/corporate-news/2023/guidehouse-completes-transaction-with-bain-capital','Guidehouse’s official December14,2023 announcement confirms the completed acquisition by Bain Capital Private Equity from Veritas. This establishes the consulting business and dated private-equity ownership; it does not identify every operating LLP within the group.'),
('Hackensack University Health Network (historical network)','Unknown','Hackensack University Health Network was a New Jersey healthcare network that merged with Meridian Health to form Hackensack Meridian Health.','https://www.nj.gov/njhcffa/meeting/minutes/pdf/July%2028%2C%20%202016%20minutes.pdf','New Jersey Health Care Facilities Financing Authority July2016 minutes independently confirm that the named network and Meridian Health completed their merger July1,2016. This establishes the historical organization; it does not equate every surviving hospital and foundation.'),
('Hackensack University Medical Center Foundation','Unknown','The foundation raises funds to support Hackensack University Medical Center and its clinical programs.','https://www.hackensackmeridianhealth.org/en/donate/hackensack-university-medical-center-foundation','The current hospital-system fundraising page names this exact foundation and the medical programs it supports. Its tax classification and separate legal continuity were not inferred solely from the word Foundation.'),
('Halcyon Tech, Inc.','Unknown','Halcyon develops software to protect organizations against ransomware attacks.','https://www.halcyon.ai/policies/privacy-policy','The official privacy policy effective May4,2026 names exact Halcyon Tech Inc. The official data-processing addendum further identifies its Delaware incorporation and Rancho Santa Fe business address. Current ownership remains unknown.'),
('Haleon US Holdings LLC','Unknown','Haleon US Holdings LLC is a US holding entity associated with the Haleon consumer-health business.','https://apps.sos.wv.gov/business/corporations/organization.aspx?org=346972','West Virginia’s official record identifies the Delaware LLC at184 Liberty Corner Road, Warren, New Jersey, and records the January29,2024 name change from GlaxoSmithKline Consumer Healthcare Holdings (US) LLC. Haleon’s supplier notice independently documents the same rename. The US LLC remains distinct from the listed plc.'),
('Halter USA LLC','Unknown','Halter USA LLC provides software services for livestock-management systems that use connected collars and farm equipment.','https://www.halterhq.com/en-us/legal/terms-of-service','Official US service terms identify exact Halter USA LLC as a Delaware entity with principal business in San Francisco, and explain its software-service role. The privacy policy lists Halter USA Inc. separately, so the LLC and Inc. are not merged.'),
('Hanwha Azdel','Subsidiary','Hanwha Azdel manufactures lightweight composite materials for vehicle and other industrial applications.','https://hwam.co.kr/en/company/global-network.do','Hanwha Advanced Materials’ official network page names Hanwha AZDEL Inc. in Virginia and documents its2007 acquisition. Azdel’s own website corroborates the business and specific operating identity. The parent’s stock-market classification is not assigned to Azdel.'),
('Hanwha Energy USA Holdings Corporation','Unknown','Hanwha Energy USA Holdings Corporation operates a US energy business associated with the Hanwha group.','https://www.hanwhaenergyusa.com/privacy-policy/','The entity’s official privacy policy spells out exact Hanwha Energy USA Holdings Corporation and explicitly identifies hanwhaenergyusa.com as its website. Hanwha Energy’s global network also lists the exact entity with the174 Power Global DBA. Exact ownership percentage remains unknown.'),
('Hapag-Lloyd (America) LLC','Unknown','Hapag-Lloyd (America) LLC handles US sales, customer service and regional shipping operations for the Hapag-Lloyd business.','https://www.hapag-lloyd.com/en/services-information/offices-localinfo/north-america/usa/local-info/export.html','The current official US directory names exact Hapag-Lloyd (America) LLC and its Atlanta regional headquarters and US sales offices. It lists Hapag-Lloyd USA LLC separately for US-flag services; these entities remain distinct. Current ownership percentage was not independently verified.'),
('Tides Medical (Harbinger Medical Group LLC)','Unknown','Tides Medical supplies human tissue-based products for medical care.','https://www.aatb.org/harbinger-medical-group-llc-dba-tides-medical','The tissue-banking association’s own directory explicitly identifies Harbinger Medical Group LLC DBA Tides Medical. This independently corroborates the exact DBA relationship and tissue business; it is not a similarly named Harbinger organization.')]
for k,(row,v) in enumerate(zip(rows,a)):
 i=row['id'];before[i]=json.loads(json.dumps(p[i]));name,own,desc,url,note=v;p[i].update(name=name,description=desc,ownership=own,review_outcome='confirmed',notes=note,identity_evidence=note,status='sourced',website_status='verified',checked_at='2026-09-13',as_of='2026-09-13')
 if k==2:p[i]['website']='https://www.hackensackmeridianhealth.org/en/donate/hackensack-university-medical-center-foundation'
 if k==6:p[i].update(website='https://www.azdel.com/',logo_url='https://www.azdel.com/wp-content/uploads/2023/03/Hanwha-Azdel-Logo-REV.svg',logo_source_url='https://www.azdel.com/',logo_kind='logo',logo_status='official_site_asset',logo_background='dark')
 if k==7:p[i]['website']='https://www.hanwhaenergyusa.com/'
 if k==9:p[i].update(logo_url='https://www.tidesmedical.com/wp-content/uploads/2021/10/Tides_Medical-blue-logo-mobile.png',logo_source_url='https://www.tidesmedical.com/',logo_kind='logo',logo_status='official_site_asset',logo_background='light')
 ss={s['url']:s for s in p[i].get('sources',[])};ss[url]=dict(url=url,label='Primary identity evidence',claim=note);p[i]['sources']=list(ss.values());dec.append(dict(**row,decision='confirmed',evidence=note,sources=[ss[url]]))
(r/'featured112-before.json').write_text(json.dumps(before,indent=2)+'\n');(r/'featured112-first10.json').write_text(json.dumps(dec,indent=2)+'\n');(r/'featured112-middle10.json').write_text('[]\n');(r/'featured112-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for f in [r/'reviewed.json',pathlib.Path('outputs/2026-research-trial/profiles.json')]:f.write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False));print('10 confirmed; 2 logos checked')
