import json
from pathlib import Path

root = Path(__file__).parent
reviewed = json.loads((root / 'reviewed.json').read_text())
ids = [
    'abfbe8c054afaa4','acaab7b13317c71c','03888f3e4c160199','19027866da380318',
    '97c67a5a69a7105e','9e2b07905b912381','cdc4bc5e15575c69','942bce2de643cdbb',
    '990b7302fedc9e9a','4756b0170958d4a3','aea19890995e09ee','d6485e241d268885',
    '969ac97b00bf4218','cb5c706a2ba22452','4228cb17ea6c1892','1134ff6c2b9240b5',
    '0c2c6214cf3102f4','a8c16aabad5ecb64','ff5a51c9774ff173','96c736fc210099aa','4a1b0920a49b8113'
]
extra = {
 'abfbe8c054afaa4': ('Private company (LLC)', 'A.D. Marble is an environmental consulting and engineering firm serving public and private clients.', 'https://admarble.com/about/', 'Official about page identifies A.D. Marble as a company and describes its consulting and engineering practice.'),
 'acaab7b13317c71c': ('Unknown', 'a16z (Andreessen Horowitz) is a venture-capital firm investing across technology categories and stages.', 'https://a16z.com/about/', 'Official about page identifies a16z as an investment firm; it does not state the exact legal entity or ownership class.'),
 '03888f3e4c160199': ('Unknown', 'The supplied record identifies Aav, Ltd., but no authoritative current operating website or exact business activity was located.', '', 'No official website or entity page was located; ownership remains unresolved.'),
 '19027866da380318': ('Unknown', 'The Florida-registered ABCO SUPPLY, LLC is an active Miami-area LLC; the similarly named abcosupply.com business is a Winnipeg electrical/mechanical contractor and cannot be matched to the LDA entity.', '', 'Florida Division of Corporations lists the exact name ABCO SUPPLY, LLC, active, principal address 2030 South Douglas Road 423, Coral Gables, FL 33134. The abcosupply.com site identifies a different Winnipeg business at 1346 Spruce Street, so its website is not assigned.'),
 '97c67a5a69a7105e': ('Private company', 'AccentCare, Inc. provides home health, personal care, palliative, and hospice services.', 'https://accentcare.com/about/', 'Official AccentCare materials identify AccentCare, Inc.; an official company article describes AccentCare as a portfolio company of Advent International.'),
 '9e2b07905b912381': ('Nonprofit', 'Accessia Health provides assistance and support services for people with chronic and rare conditions.', 'https://accessiahealth.org/', 'Official site describes Accessia Health as a nonprofit organization serving people with chronic and rare conditions.'),
 'cdc4bc5e15575c69': ('Unknown', 'Acesso Biologics develops and supplies biologic tissue products for surgical wound care.', 'https://www.acessobio.com/', 'Official site identifies Acesso Biologics and its biologics products but does not disclose ownership class.'),
 '942bce2de643cdbb': ('Unknown', 'Accipiter Systems develops electronic and photonic interconnect systems for edge and AI applications.', 'https://www.accipitersystems.com/', 'Official site identifies Accipiter Systems and its products but does not disclose ownership class.'),
 '990b7302fedc9e9a': ('Unknown', 'Accompany Health provides in-home primary and behavioral healthcare for people with complex needs.', 'https://www.accompanyhealth.com/', 'Official site identifies Accompany Health and its healthcare services but does not disclose ownership class.'),
 '4756b0170958d4a3': ('Private company (LLC)', 'Accordia Partners, LLC provides commercial real-estate investment and development services.', 'https://accordiapartners.com/', 'Official site identifies Accordia Partners, LLC and its real-estate investment and development practice.'),
 'aea19890995e09ee': ('Unknown', 'Accu Reference Medical Lab provides clinical laboratory testing and diagnostic services.', 'https://www.accureference.com/', 'Official site identifies Accu Reference and its laboratory testing services but does not disclose ownership class.'),
 'd6485e241d268885': ('Unknown', 'Accuride manufactures wheels and wheel-end components for commercial vehicles.', 'https://www.accuridecorp.com/', 'Official site identifies Accuride Corporation and its commercial-vehicle wheel products but does not disclose current ownership class.'),
 '969ac97b00bf4218': ('Unknown', 'Accutar Biotechnology develops computational and laboratory methods for discovering and designing medicines.', 'https://www.accutar.com/', 'Official site identifies Accutar Biotechnology and its drug-discovery work but does not disclose ownership class.'),
 'cb5c706a2ba22452': ('Unknown', 'Acelero, Inc. operates Acelero Learning and Shine Early Learning, providing early-childhood education and family-engagement services.', 'https://acelero.com/', 'Official Acelero site identifies Acelero, Inc. and its divisions. HHS TAGGS identifies the exact legal entity ACELERO INC at 500 7th Ave, New York, NY 10018; the official pages do not state nonprofit or for-profit status.'),
 '4228cb17ea6c1892': ('Unknown', 'Achieve is a digital personal-finance company offering lending and debt-relief products through affiliated businesses.', 'https://www.achieve.com/', 'Official site identifies Achieve and its consumer-finance products but does not disclose the exact legal entity or ownership class.'),
 '1134ff6c2b9240b5': ('Private subsidiary of a public company', 'ACI Payments, Inc. provides electronic bill payment and payment technology services.', 'https://www.aciworldwide.com/company', 'ACI Worldwide official company materials identify ACI Payments as part of ACI Worldwide; ACI Worldwide, Inc. is publicly traded on Nasdaq as ACIW.'),
 '0c2c6214cf3102f4': ('Unknown', 'ActionStreamer develops wearable cameras, wireless video transmission, and live first-person video software.', 'https://actionstreamer.com/', 'Official site identifies ActionStreamer and its products but does not disclose ownership class.'),
 'a8c16aabad5ecb64': ('Unknown', 'Active Optical Systems develops optical-control components and systems for defense, aerospace, and commercial applications.', 'https://www.activeopticalsystems.com/', 'Official site identifies Active Optical Systems and its optical systems but does not disclose ownership class.'),
 'ff5a51c9774ff173': ('Unknown', 'BlueVoyant provides cyber threat intelligence, supply-chain defense, and managed security services.', 'https://www.bluevoyant.com/about-us/', 'Official site identifies BlueVoyant and its cybersecurity services but does not disclose ownership class.'),
 '96c736fc210099aa': ('Unknown', 'BlueVoyant Federal provides BlueVoyant cybersecurity services to U.S. government customers.', 'https://www.bluevoyant.com/federal/', 'Official BlueVoyant Federal page identifies the federal business as part of BlueVoyant; separate ownership class is not disclosed.')
 ,'4a1b0920a49b8113': ('Nonprofit trade association', 'ACA Connects is a communications-industry trade association representing broadband and cable providers.', 'https://acaconnects.org/about/', 'Official about page identifies ACA Connects as a trade association representing communications providers; it does not identify a for-profit parent.')
}
before = {i: reviewed[i] for i in ids if i in reviewed}
patches = {}
for i in ids:
    if i not in reviewed or i not in extra: continue
    own, desc, site, claim = extra[i]
    p = dict(reviewed[i])
    p.update({'description': desc, 'ownership': own, 'website': site, 'notes': claim, 'sources': [*reviewed[i].get('sources', []), {'label':'Primary official web source','url':site,'claim':claim}] if site else reviewed[i].get('sources', []), 'review_outcome':'confirmed' if own != 'Unknown' else 'unresolved', 'checked_at':'2026-09-12', 'as_of':'2026-09-12'})
    patches[i] = p
out = Path(__file__).parent / 'parallel-company-sept12'
out.mkdir(exist_ok=True)
(out/'before_profiles.json').write_text(json.dumps(before, indent=2, ensure_ascii=False)+'\n')
(out/'proposed_profiles.json').write_text(json.dumps(patches, indent=2, ensure_ascii=False)+'\n')
(out/'evidence_urls.json').write_text(json.dumps({i:[s.get('url') for s in p.get('sources',[]) if s.get('url')] for i,p in patches.items()}, indent=2)+'\n')
(out/'README.json').write_text(json.dumps({'scope':'20 partial ownership-Unknown A-C profiles; official primary web evidence; unresolved records retained as Unknown','ids':ids,'excluded':['SAIC','UNFI','Primer','Neuralink','IoECorp','JBS']}, indent=2)+'\n')
evidence = {
 '19027866da380318': [{'url':'https://lda.gov/api/v1/clients/73164/?format=json','excerpt':'LDA client JSON: name ABCO SUPPLY, LLC; state FL; country US; no location supplied.'},{'url':'https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResultDetail?aggregateId=flal-l05000087213-d7e8cb0c-cf43-42dd-8783-4db6547b582c&directionType=Initial&inquirytype=EntityName&searchNameOrder=ABCOSUPPLY+L050000872130','excerpt':'ABCO SUPPLY, LLC; Florida Limited Liability Company; Status ACTIVE; Principal Address 2030 SOUTH DOUGLAS ROAD 423, CORAL GABLES, FL 33134.'},{'url':'https://abcosupply.com/about-us/','excerpt':'ABCO Supply & Service is a privately owned electrical/mechanical contracting firm based in Winnipeg; address 1346 Spruce Street Winnipeg, MB R3E 2V7. This does not match the Florida LDA entity.'}],
 '97c67a5a69a7105e': [{'url':'https://lda.gov/api/v1/clients/68314/?format=json','excerpt':'LDA client JSON: name ACCENTCARE; state TX; country US.'},{'url':'https://www.accentcare.com/accentcare-leverages-data-transparency-to-build-diverse-inclusive-workforce/','excerpt':'Dallas-headquartered AccentCare is a portfolio company of the private equity firm Advent International, offering hospice, palliative care, personal care, non-medical services, home health, care management and high-acuity home care.'},{'url':'https://accentcare.com/about/','excerpt':'AccentCare is a nationwide provider of post-acute and in-home health care, including personal care, home health, palliative care and hospice.'}],
 '9e2b07905b912381': [{'url':'https://accessiahealth.org/about/','excerpt':'Accessia Health is a national nonprofit 501(c)(3) organization that provides programs and services to individuals living with a rare or chronic health condition.'},{'url':'https://accessiahealth.org/contact/','excerpt':'Accessia Health is headquartered in Virginia; mailing address Accessia Health, P.O. Box 5930, Midlothian, VA 23112.'}],
 '1134ff6c2b9240b5': [{'url':'https://lda.gov/api/v1/clients/53697/?format=json','excerpt':'LDA client JSON: name ACI PAYMENTS, INC.; state NE; country US.'},{'url':'https://www.aciworldwide.com/what-is-this-charge','excerpt':'ACI Payments, Inc., a subsidiary of ACI Worldwide, provides secure payment processing for thousands of U.S. based businesses.'},{'url':'https://investor.aciworldwide.com/static-files/2069a399-35eb-4a07-a025-b22c0b2db505','excerpt':'Effective January 1, 2020, Official Payments Corporation, a wholly owned subsidiary, changed its name to ACI Payments, Inc.; an amended and restated certificate of incorporation was filed in Delaware.'}],
 'cb5c706a2ba22452': [{'url':'https://lda.gov/api/v1/clients/66490/?format=json','excerpt':'LDA client JSON: name ACELERO, INC.; state WI; country US.'},{'url':'https://acelero.com/','excerpt':'Acelero, Inc. and its divisions Acelero Learning and Shine Early Learning are pioneers in early childhood education and family engagement services.'},{'url':'https://taggs.hhs.gov/Detail/RecipDetail?arg_EntityId=GWhZeut6Ji4xZ%2BCvHhGptw%3D%3D','excerpt':'Legal Entity Name ACELERO INC; address 500 7TH AVE NEW YORK NY 10018-4502; Head Start and Early Head Start awards. This government record confirms the name but differs from LDA state WI.'}]
}
(out/'repair_evidence.json').write_text(json.dumps(evidence, indent=2, ensure_ascii=False)+'\n')
