import json
from pathlib import Path
p=Path('work/research-2026');r=json.load(open(p/'general-round84-input.json'));f=p/'round84-root-incremental-evidence.json';d=json.load(open(f))
def patch(i,**kw):d[r[i]['id']].update(kw)
def src(u,c):return {'url':u,'claim':c}
patch(49,description='Meridian Medical Technologies develops autoinjectors and medical countermeasures as the global health security business within Kindeva Drug Delivery.',website='https://www.kindevadd.com/global-health-security/',ownership='Subsidiary',review_outcome='partial',notes='Current Kindeva sources supersede the stale 2017 Pfizer affiliation. Kindeva describes Meridian as its global health security business unit; precise current legal entity structure remains to be checked.',sources=[src('https://www.kindevadd.com/global-health-security/','Current Kindeva site identifies Meridian as its global health security business unit.'),src('https://www.kindevadd.com/news/kindeva-and-meridian-combine-create-leading-drug-device-combination-product-cdmo/','Official announcement confirms completion of the Kindeva-Meridian combination in December 2022.')])
patch(89,name='MetOx International, Inc.',description='MetOx International manufactures high-temperature superconducting wire for power delivery, fusion equipment, high-field magnets and related energy applications.',website='https://www.metoxtech.com/',ownership='Unknown',review_outcome='partial',notes='Official website identifies the exact Houston company and Xeus superconducting wire. Ownership remains unverified.',sources=[src('https://www.metoxtech.com/','Official site names MetOx International Inc., its Houston address and superconducting wire business.')])
patch(94,ownership='Private company',review_outcome='partial',notes='Official company overview states 100% employee ownership. Exact short-name filing match still requires context verification.',sources=d[r[94]['id']]['sources']+[src('https://www.metsci.com/who-we-are/','Official overview explicitly identifies 100% employee ownership and applied mathematics, computing and engineering work.')])
patch(48,ownership='Nonprofit / tax-exempt',review_outcome='partial',notes='Official Meridian Health Services publication identifies it as not-for-profit; exact filing jurisdiction still requires comparison.',sources=d[r[48]['id']]['sources']+[src('https://rialzo.meridianhs.org/2019/blog/2019/04/meridian-recognizes-2019-spirit-of-meridian-recipients-through-a-decade-of-philanthropy/','Official organization publication explicitly describes Meridian Health Services as not-for-profit.')])
patch(60,website='https://www.matinetworks.net/',ownership='Subsidiary',review_outcome='partial',notes='Tribal enterprise website identifies Mescalero Apache Telecom among tribal operations. Provider broadband disclosures identify the exact legal entity. Classified as tribal enterprise, separate from the tribal government.',sources=[src('https://www.matinetworks.net/internet/','Provider broadband disclosure names Mescalero Apache Telecom Inc.'),src('https://www.skiapache.com/mountain-info/the-tribe/','Tribal enterprise site lists Mescalero Apache Telecom among the tribe-operated enterprises.')])
patch(38,ownership='Not applicable',kind='Animal health business division',notes='Official fact sheet identifies a division of Merck & Co., Inc.; division label does not establish a separately incorporated subsidiary.',sources=[src('https://www.merck-animal-health.com/wp-content/uploads/2024/05/Merck-Animal-Health-Corporate-Fact-Sheet.pdf','Official fact sheet explicitly calls Merck Animal Health a division of Merck & Co., Inc.')])
patch(99,ownership='Subsidiary',notes='Metropolitan Life Insurance Company is expressly identified as wholly owned by MetLife Inc. in its own 2025 annual report.',sources=[src('https://www.sec.gov/Archives/edgar/data/937834/000093783426000003/mlic-20251231.htm','Insurer annual report identifies exact legal entity, wholly owned parent relationship and insurance business.')])
for i in [56,57,59]:d[r[i]['id']]['notes']='Official source identifies the governmental entity and its public services.'
f.write_text(json.dumps(d,indent=2)+'\n')
bad={16:'Composite collection of airline logos, not authority logo',20:'GDPR badge, not organization logo',27:'X social platform logo',53:'Armis partner logo',60:'Tribal government seal rather than telecom logo; website corrected',61:'Army research lab customer logo',81:'Upstart customer logo',92:'Brightside Health customer logo'}
for i,why in bad.items():
 cfile=p/'website-cache'/f"{r[i]['id']}.json";c=json.load(open(cfile));c['root_logo_rejection']=why
 for k in ['logo_url','logo_kind','logo_source_url','logo_http_status','logo_content_type']:c.pop(k,None)
 cfile.write_text(json.dumps(c,indent=2)+'\n')
(p/'round84-logo-rejections.json').write_text(json.dumps({r[i]['id']:{'index':i,'reason':v} for i,v in bad.items()},indent=2)+'\n')
print('Corrected 10 profile records; rejected 8 mismatched logo candidates.')
