import json
from pathlib import Path
p=Path('work/research-2026');r=json.load(open(p/'general-round84-input.json'));f=p/'round84-root-incremental-evidence.json';d=json.load(open(f))
v=d[r[44]['id']];v.update(name='Mercy Health System (Missouri)',description='Mercy is a Catholic nonprofit health system based in Chesterfield, Missouri, operating hospitals, physician practices and outpatient services across several states.',website='https://www.mercy.net/',notes='Original House registration address is 14528 S Outer 40 Road, Chesterfield, Missouri, matching mercy.net. The earlier Wisconsin Mercyhealth match was incorrect and removed.',review_outcome='confirmed',sources=r[44]['profile']['sources']+[{'url':'https://www.mercy.net/about/','claim':'Official system overview and Chesterfield headquarters address match the original registration.'},{'url':'https://careers.mercy.net/jobs/JR249700?lang=en-us','claim':'Official employer posting identifies Mercy as a not-for-profit system.'}])
v=d[r[77]['id']];v.update(name='Metcon, Inc. (North Carolina)',description='Metcon provides building construction and infrastructure services from North Carolina, including schools, public buildings, wastewater facilities and underground utilities.',website='https://metconus.com/',ownership='Private company',review_outcome='confirmed',notes='LDA client 71432 identifies North Carolina, ruling out the Florida Met-Con steel company. Official company sources identify Native American ownership and Pembroke headquarters.',sources=r[77]['profile']['sources']+[{'url':'https://metconus.com/metcon-celebrates-new-kings-mountain-office-ribbon-cutting/','claim':'Official May 2025 company announcement identifies Native American ownership, Pembroke headquarters and construction services.'},{'url':'https://metconus.com/diversity/','claim':'Official company page states 100% minority ownership.'}])
for i,state in [(18,'California'),(23,'Maryland'),(93,'Ohio'),(94,'Virginia')]:
 v=d[r[i]['id']];v['sources']+=r[i]['profile']['sources'];v['notes']+=' Local cached LDA client record identifies '+state+', consistent with the researched organization.'
f.write_text(json.dumps(d,indent=2)+'\n')
exec((p/'check_round84_incremental.py').read_text().split('p=json.load(open(root/')[0])
choices={16:'https://i0.wp.com/flymemphis.com/wp-content/uploads/2018/06/cropped-11009951_1601904913357707_5087342235373522644_n.png?fit=180%2C180&ssl=1',20:'https://mhanational.org/wp-content/uploads/2025/02/cropped-Favicon-Bell-192x192.png',27:'https://www.countyofmerced.com/images/favicon.ico',53:'https://www.merlincyber.com/hubfs/Melin_Favicon.png',61:'https://cdn.prod.website-files.com/675247a5dc0d5f666c9b0843/67524b484daeb1376efa5084_Mesodyne-webclip.png',81:'https://framerusercontent.com/images/8VlzHm7NUhxHyDz7Bej54eBKKAc.png',92:'https://www.metriport.com/favicon.svg'}
for i,u in choices.items():
 try:
  final,mime,b=get(u,1000000);assert mime.startswith('image/') and len(b)>80
  cf=p/'website-cache'/f"{r[i]['id']}.json";c=json.load(open(cf));c.update(logo_url=u,logo_kind='site_icon',logo_source_url=c['final_url'],logo_http_status=200,logo_content_type=mime);cf.write_text(json.dumps(c,indent=2)+'\n');print(i,'replacement fetched')
 except Exception as e:print(i,str(e))
