import json,pathlib,gzip
r=pathlib.Path('work/research-2026');cs={c['id']:c for c in json.load(open(r/'general-round13-b-input.json'))};f=r/'general-round13-b-root-partial.json';p=json.load(open(f))
def add(k,desc,kind,own,site,url,claim):
 c=cs[k];v=dict(c.get('profile',{}));v.update(name=c['name'],description=desc,kind=kind,ownership=own,website=site,status='sourced',review_outcome='partial' if own=='Unknown' else 'confirmed',identity_evidence='Official organization source matches disclosed name and activity.',notes='Individually researched using primary organization evidence; filing name retained.'+(' Ownership not established by reviewed sources.' if own=='Unknown' else ''),as_of='2026-09-05',checked_at='2026-09-05',featured=False,legal_form='',logo_url='',logo_kind='',logo_source_url='');v['sources']=v.get('sources',[])
 if not v['sources']:
  rid=json.load(gzip.open(f'lobbying-map/public/data/reports/{k[:2]}.json.gz'))[k][0]['id'];v['sources']=[{'url':f'https://lda.gov/filings/public/filing/{rid}/print/','label':'Lobbying disclosure','claim':'Original disclosed client name.'}]
 v['sources'].append({'url':url,'label':'Official organization evidence','claim':claim});p[k]=v
add('b85fa00943310f33','Provides consumer financial services, including check cashing, cash advances, installment loans and money orders.','Company','Unknown','https://www.amscot.com/','https://www.amscot.com/','Amscot Financial describes its consumer lending and financial-services business.')
add('8856a477f6aaebc4','Veterans membership organization providing benefits-claim assistance, career services and advocacy for veterans and their families.','Veterans organization','Not applicable','https://www.amvets.org/','https://www.amvets.org/about','AMVETS identifies itself as American Veterans, a congressionally chartered membership and service organization. This profile refers to AMVETS rather than its separate service foundation.')
add('58a57a95e5dbc5a0','Owns and operates U.S. freight railroads and provides switching, track maintenance, transloading and dispatching services.','Company','Unknown','https://www.anacostia.com/','https://www.anacostia.com/about-us/','Anacostia Rail Holdings Company identifies its railroad ownership and operating activities.')
add('e834e64539b40a20','Protects and restores the Anacostia River watershed through conservation, pollution monitoring, education and public-policy advocacy.','Nonprofit organization','Nonprofit / tax-exempt','https://www.anacostiaws.org/','https://www.anacostiaws.org/','Official site describes watershed restoration work and identifies the organization as 501(c)(3), EIN 52-1666511.')
f.write_text(json.dumps(p,indent=2)+'\n');print(len(p))
