import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'general-round11-b-root-partial.json'));rows={v['id']:v for v in json.load(open(r/'general-round11-b-input.json'))}
def add(k,u,d,kind='Professional association',own='Unknown'):
 v=dict(rows[k].get('profile',{}));v.update(name=rows[k]['name'],website=u,description=d,kind=kind,ownership=own,review_outcome='confirmed',status='sourced',identity_evidence='Official source identifies the organization by name and describes its activities.',sources=[dict(url=u,label='Official organization overview',claim=d)],notes='Tax status and ownership are not inferred from the association name.',logo_url='',logo_kind='',logo_source_url='',legal_form='');p[k]=v
add('0e685b6260c73670','https://aoopa.org/about-aoopa','Industry association representing American olive oil producers and their state associations.','Trade association')
add('02e0b438ec076ee9','https://www.apdahealth.com/content.asp?contentid=133','National nonprofit association representing providers of bedside diagnostic services, including mobile X-rays, ultrasound and other testing.','Trade association','Nonprofit / tax-exempt')
add('92091a389177484d','https://aprx.org/aprx-advantage/','Member-owned pharmacy services group helping independent pharmacy owners with purchasing, business support and advocacy.','Cooperative','Cooperative / member-owned');p['92091a389177484d']['review_outcome']='partial';p['92091a389177484d']['notes']='Official history identifies Southwest Pharmacy Solutions Inc. doing business as American Pharmacies; filing name American Pharmacies Inc. is preserved and legal-name discrepancy remains.';p['92091a389177484d']['sources'].append(dict(url='https://www.aprx.org/templates/aprx/Assets/american-pharmacies-history.pdf',label='Official history',claim='History identifies Southwest Pharmacy Solutions Inc. doing business as American Pharmacies and describes member ownership.'))
add('d2393694d3b8e80c','https://www.americanpipeline.org/about/mission','Association representing merit-shop pipeline and station contractors and addressing their shared construction-industry interests.','Trade association')
add('58b078f2a5fd2054','https://www.nursingworld.org/ana/about-ana/','Professional association representing registered nurses, setting practice standards and advocating on nursing and healthcare policy.');p['58b078f2a5fd2054']['featured']=True
add('c2c91c8beb3783aa','https://www.aota.org/about','Professional association supporting occupational therapists, assistants and students through practice resources, education, research and advocacy.','Professional association','Nonprofit / tax-exempt');p['c2c91c8beb3783aa']['sources'].append(dict(url='https://www.aota.org/about/leadership-governance/aota-governance-documents/',label='Official governance documents',claim='AOTA identifies itself as a nonprofit organization.'))
add('c0f5745a21a1ef3b','https://www.aonl.org/about/overview','Professional organization supporting nurse leaders through education, professional development and advocacy; formerly American Organization for Nurse Executives.');p['c0f5745a21a1ef3b']['notes']='Official overview documents 2019 name change from American Organization for Nurse Executives.'
add('e1e00078f9a41f40','https://aopanet.org/about-aopa/our-mission/','Association serving orthotic and prosthetic care providers and suppliers through reimbursement guidance, education, research and advocacy.','Trade association')
add('3696ed21c2788ab7','https://peanut-shellers.org/','Nonprofit trade association representing commercial peanut shellers and crushers and promoting the peanut industry.','Trade association','Nonprofit / tax-exempt')
add('6d3814cd85089aff','https://americanpetproducts.org/about','Membership association supporting pet-product businesses with industry programs, business connections and market information.','Trade association')
add('4423580555620d28','https://www.api.org/membership','Trade association representing oil and natural gas businesses across the petroleum industry.','Trade association');p['4423580555620d28']['featured']=True
add('584ac28bd6af70b8','https://www.apta.org/apta-and-you/about-us','Professional membership association representing physical therapists, physical therapist assistants and physical therapy students.');p['584ac28bd6af70b8']['sources'].append(dict(url='https://www.apta.org/contentassets/46e67b95292b4a1581dd1fc8520d30aa/apta-association-profile-2024.pdf',label='Official association profile',claim='Association profile documents professional membership and organizational governance.'))
add('f50a4401610c4eaa','https://www.physiology.org/about/welcome','Scientific society advancing research and education on biological function through publications, scientific meetings and professional support.','Scientific society','Nonprofit / tax-exempt');p['f50a4401610c4eaa']['sources'].append(dict(url='https://www.physiology.org/about/governance/aps-financial-transparency',label='Official financial transparency',claim='APS identifies itself as a nonprofit organization.'))
add('a5f730de60a0f0fd','https://www.apsnet.org/ABOUT/Pages/default.aspx','Scientific society for plant-pathology researchers and practitioners, publishing research and supporting plant health education and policy.','Scientific society','Nonprofit / tax-exempt');p['a5f730de60a0f0fd']['sources'].append(dict(url='https://www.apsnet.org/members/engagement/ppb/PublishingImages/Pages/PPBPriorities/APS%20Federal%20Funding%20One%20Pager_Website.pdf',label='Official society policy overview',claim='APS describes itself as a nonprofit professional organization of plant pathology scientists and practitioners.'))
(r/'general-round11-b-root-partial.json').write_text(json.dumps(p,indent=2)+'\n');print(len(p))
