import pathlib
s=pathlib.Path('work/research-2026/extend19b.py').read_text().split('add(5,')[0].replace('general-round19-b-input','general-round20-b-input').replace('general-round19-b-root-draft','general-round20-b-root-draft');exec(s)
add(15,'https://bafl.com/','Membership organization advocating freedom, security and democratic institutions in Estonia, Latvia and Lithuania.','Unknown','https://bafl.com/','Official website identifies Baltic American Freedom League and its Baltic advocacy mission.',kind='Advocacy organization')
add(16,'https://www.binance.us/','Holding company behind the Binance.US cryptocurrency trading platform.','Unknown','https://blog.binance.us/martin-grant-joins-board/','Official Binance.US announcement identifies BAM Management US Holdings Inc as its parent company.','Keep separate from operating company BAM Trading and Binance Holdings Limited. Website belongs to operating platform.')
for i in [17,18]:add(i,'https://www.binance.us/','Operates Binance.US, a platform for trading and holding cryptocurrencies.','Unknown','https://www.binance.us/terms-of-use','Official terms identify BAM Trading Services Inc as the Binance.US operator and distinguish it from Binance Holdings Limited.','Two disclosed name groups remain traceable; no assumption that Binance.US and Binance.com are the same legal company.')
add(19,'https://bamboohealth.com/','Provides healthcare data-sharing and care-coordination software connecting health providers and patient-care teams.','Unknown','https://bamboohealth.com/about-us/','Official company history identifies Bamboo Health as the rebrand of Appriss Health after acquiring PatientPing in 2021.')
add(20,'','A beverage coalition disclosed under the name BAMCO LLC in a federal lobbying registration.','Unknown','https://lda.gov/api/v1/clients/71165/?format=json','Cached LDA client record identifies BAMCO LLC as a California beverage coalition.','Membership, legal ownership and official website remain unresolved. Do not substitute the unrelated investment manager BAMCO.',kind='Coalition')
out[rows[20]['id']]['review_outcome']='unresolved'
add(21,'https://www.banrural.com.gt/','Guatemalan bank providing financial services with a focus on rural communities and national access.','Unknown','https://www.banrural.com.gt/site/conocenos/bancodedesarrollorural?hsLang=es-gt','Official Banrural page names Banco de Desarrollo Rural; cached LDA record identifies Guatemala.','Shareholder composition requires direct review; not automatically classified as government-owned.')
add(22,'https://www.itauinternational.com/','Itaú international private-banking business serving clients through Miami.','Unknown','https://www.itau.com.br/content/dam/ibba/en/IBBAInt-Annual-Report-2021.pdf','Itaú BBA international annual report identifies Banco Itaú International and its Miami address.','Source establishes historical entity context; current legal ownership and exact operating name remain partial. Website is international banking platform.')
add(23,'https://banillagames.com/','Designs and distributes electronic games and equipment for skill, redemption and amusement markets.','Unknown','https://banillagames.com/about-us/','Official company page explicitly names Banilla Games Inc and its game development and distribution activities.')
(r/'general-round20-b-root-draft.json').write_text(json.dumps(out,indent=2)+'\n');print(len(out),'drafts')
