import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));b=json.load(open(r/'featured312-before.json'));batch=json.load(open(r/'identity313-batch.json'))['records']
notes={
'b55162d1a69921a1':'The official Fiber Broadband Association About body confirms the exact operating association and its fiber-network deployment, policy and education mission. Ownership and exact tax status remain unverified; the association is not itself represented as a broadband network operator.',
'a099d128e1ab94ee':'BGC’s April 25, 2024 release identifies FMX as part of its group and records ten financial firms becoming minority equity owners. It describes Treasury, foreign-exchange and interest-rate futures platforms. This independently confirms the financial-markets operating identity. FMX Holdings LLC, FMX Futures Exchange LP and the FMX UST operator remain distinct; current exact ownership percentages are unknown. The unrelated GoFMX maintenance-software business is excluded.',
'4db76dda42a448a6':'FoodHealth’s rendered official terms, dated September 23, 2025, identify the FoodHealth Company brand and its proprietary food-scoring APIs, software and applications. The corporate-name wording in the terms is incomplete, so no exact corporate name is inferred from it. Operating identity is confirmed; the service provides food information rather than selling groceries or providing clinical care. Ownership remains unknown.',
'6ef219093f71ca45':'The official Fors Marsh About body independently identifies its behavioral-science research, advisory and communications business and Arlington location. This confirms the operating identity corresponding to the filed Fors Marsh Group label; omission of Group in current branding does not establish a separate company. Current legal form and ownership are not inferred.',
'4688a797a1297f2a':'The official Georgia Fruit and Vegetable Growers Association About body confirms the expanded association name, specialty-crop advocacy and grower services. It describes growers holding voting rights and elective office; this is association governance rather than evidence of corporate share ownership. Exact tax status remains unknown.',
'2e9da40fe968e28f':'The official Great Lakes Group shipyard page confirms Great Lakes Shipyard as the Cleveland operation providing vessel construction, fabrication, conversion and repair. The shipyard is an operating unit; the parent/operator and any separately incorporated group companies remain distinct. No current ownership percentage is inferred.',
'3b7334f0a9d7b642':'The official Illinois Public Transportation Association About body confirms the expanded name, Springfield address and its representation, training, research and technical assistance for Illinois transit operators. Operating identity is confirmed. It is an association serving public operators, not itself classified as a government agency; tax status remains unverified.',
'66a76e3f0e74395f':'The University of Illinois research-unit page independently identifies the Illinois Quantum and Microelectronics Park and links iqmp.org. It describes a Chicago campus supporting quantum and microelectronics development. This confirms the operating project identity; the park is not collapsed into its university-related operating LLC and future facilities are not presented as already completed.'}
for q in batch:
 i=q['id'];assert i not in b;b[i]=p[i].copy();z=p[i];n=notes[i]
 z.update(review_outcome='confirmed',checked_at='2026-09-14',website=q['website'],website_status='verified',description=q['description'],notes=n,identity_evidence=n)
 for s in q['sources']:z['sources'].append({'url':s['url'],'label':'Primary organization evidence inspected September 14, 2026','claim':n})
# Full official images were downloaded by the worker and visually checked by root.
for q in json.load(open(r/'identity314-logos.json'))['records']:
 if q['status']!='verified_downloaded':continue
 i=q['id'];p[i].update(logo_url=q['logo_url'],logo_kind='logo',logo_source_url=q['logo_source_page'],logo_status='official_site_asset')
 if i in ['5919eba2ef6504a2','fe151e27976c37cc']:p[i]['logo_background']='dark'
(r/'featured312-before.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n')
(r/'featured312-decisions.json').write_text(json.dumps({i:p[i] for i in b},ensure_ascii=False,indent=2)+'\n')
(r/'reviewed.json').write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n');Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(p,ensure_ascii=False,separators=(',',':')));Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
(r/'evidence312/root-checks.md').write_text('Root reviewed primary bodies September14,2026. Direct HTTP captures in this directory retain blocked/empty responses as failures, not identity evidence. Indexed official bodies supplied ACI Alliance, ATA, AmeriQual, ADCES, Blackwatch, Fiber Broadband, ForsMarsh, GFVGA, GreatLakesShipyard and IPTA. FoodHealth terms read through ComputerUse tab15; explicit incomplete corporate-name placeholder was NOT normalized into a real corporate name. BGC April25,2024 announcement read for FMX minority-equity participation; GoFMX namesake removed from worker313. Four314 downloaded logos visually inspected by root; ACPA and Bravo require dark presentation.\n')
print('Eight further identities and four official logos saved; seventeen confirmed total in checkpoint312.')
