import json,pathlib,gzip
r=pathlib.Path('work/research-2026');cs={c['id']:c for c in json.load(open(r/'general-round13-b-input.json'))};f=r/'general-round13-b-root-partial.json';p=json.load(open(f))
def add(k,desc,kind,own,site,url,claim):
 c=cs[k];v=dict(c.get('profile',{}));v.update(name=c['name'],description=desc,kind=kind,ownership=own,website=site,status='sourced',review_outcome='partial' if own=='Unknown' else 'confirmed',identity_evidence='Official organization source matches disclosed name and activity.',notes='Individually researched using primary organization evidence; filing name retained.'+(' Ownership not established by reviewed sources.' if own=='Unknown' else ''),as_of='2026-09-05',checked_at='2026-09-05',featured=False,legal_form='',logo_url='',logo_kind='',logo_source_url='');v['sources']=v.get('sources',[])
 if not v['sources']:
  rid=json.load(gzip.open(f'lobbying-map/public/data/reports/{k[:2]}.json.gz'))[k][0]['id'];v['sources']=[{'url':f'https://lda.gov/filings/public/filing/{rid}/print/','label':'Lobbying disclosure','claim':'Original disclosed client name.'}]
 v['sources'].append({'url':url,'label':'Official organization evidence','claim':claim});p[k]=v
add('0f567bde17a0a75d','Trade association for operators of arcade games, jukeboxes and other out-of-home amusement equipment.','Trade association','Not applicable','https://www.amoa.com/','https://www.amoa.com/','AMOA describes its professional association for route operators, arcades and entertainment centers.')
add('2dfd6e8ba2641c14','Nonprofit education organization partnering with public school districts to provide academic and social-development programs in underserved communities.','Education nonprofit','Nonprofit / tax-exempt','https://achievabledream.org/','https://achievabledream.org/','An Achievable Dream describes its nonprofit status and partnerships co-operating public schools.')
p['2dfd6e8ba2641c14']['review_outcome']='partial';p['2dfd6e8ba2641c14']['notes']+=' Program website verified; the exact Academies legal entity relationship needs further confirmation.'
add('8c27ab67f54b4057','Develops medical-imaging systems and components, airport baggage-screening equipment, and industrial power and motion controls.','Company','Unknown','https://www.analogic.com/','https://www.analogic.com/about/','Analogic Corporation identifies its medical imaging, aviation security and industrial automation activities.')
add('c3178b232e4fbeb1','Develops software, diagnostics and automation tools to monitor food production and help manage operational and food-safety risks.','Company','Unknown','https://www.ancera.com/','https://www.ancera.com/','Ancera describes its food-production analytics, diagnostics and automation platform.')
f.write_text(json.dumps(p,indent=2)+'\n');print(len(p))
