import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'general-round12-b-root-partial.json'));rows={v['id']:v for v in json.load(open(r/'general-round12-b-input.json'))}
def add(k,u,d,kind='Company',own='Unknown',outcome='confirmed'):
 v=dict(rows[k].get('profile',{}));v.update(name=rows[k]['name'],description=d,kind=kind,ownership=own,website=u,review_outcome=outcome,status='sourced',website_status='partial',checked_at='2026-09-05',as_of='2026-09-05',identity_evidence='Exact organization name and activity appear on cited official source.',notes='Ownership is not inferred where a source does not state it.',logo_url='',logo_kind='',logo_source_url='',legal_form='');v['sources']=list(v.get('sources',[]))+[dict(url=u,label='Primary organization evidence',claim=d)];p[k]=v
add('cb20b8662f52dac3','https://www.americanterawatt.com/','Developer proposing a national high-voltage direct-current transmission network to serve large industrial electricity users.')
add('2b4b7edaa1a2c209','https://ata-usa.com/','Apparel sourcing and manufacturing business providing product and fabric development, manufacturing, quality assurance and logistics.')
add('65a96fac4dfe312e','https://americantrailercoalition.com/about-us/','Coalition of U.S. trailer manufacturers advocating for trade remedies on imported van trailers; members include Great Dane, Stoughton Trailers and Wabash.','Coalition','Not applicable')
add('47dc83eef2babc76','https://www.asa.org/about-us','Nonprofit helping young people explore careers and prepare for education and employment through career-readiness information and experiences.','Nonprofit / initiative','Nonprofit / tax-exempt');p['47dc83eef2babc76']['sources'][-1]['url']='https://www.asa.org/wp-content/uploads/2024/05/Building-Bridges-Report-FINAL.pdf'
add('4fc1ea371c410e80','https://asr-group.com/','Sugar-refining business associated with ASR Group and its American Sugar Refining subsidiary.','Company','Subsidiary of private company','partial');p['4fc1ea371c410e80']['notes']='Filing name American Sugar Refineries differs from official American Sugar Refining Inc.; exact legal linkage remains partial. Current group site names Florida Crystals ownership; older releases describe a different co-owner arrangement.';p['4fc1ea371c410e80']['sources'] += [dict(url='https://asr-group.com/privacy-policy',label='Official legal entity disclosure',claim='ASR Group International lists American Sugar Refining Inc. as a subsidiary.'),dict(url='https://asr-group.com/sustainability/governance/governance-communication-and-report',label='Official governance',claim='ASR Group family of companies is privately owned.')]
(r/'general-round12-b-root-partial.json').write_text(json.dumps(p,indent=2)+'\n');print(len(p))
