import json,pathlib
r=pathlib.Path('work/research-2026');rows={v['id']:v for v in json.load(open(r/'general-round10-b-input.json'))};f=r/'general-round10-b-root-partial.json';p=json.load(open(f))
def add(k,u,d,kind,own='Unknown',source=None):
 v=dict(rows[k].get('profile',{}));v.update(name=rows[k]['name'],description=d,kind=kind,ownership=own,legal_form='',website=u,status='sourced',review_outcome='partial',checked_at='2026-09-05',as_of='2026-09-05',identity_evidence=d,notes='Source corroborates activity; exact ownership is stated only where supported.',logo_url='',logo_kind='',logo_source_url='',website_status='partial');v['sources']=list(v.get('sources',[]))+[dict(url=source or u,label='Primary organization evidence',claim=d)];p[k]=v
for k,u,d in [('c3a378a3d89a085b','https://www.afm.org/','Labor union representing professional musicians in live performance, recording and other music work.'),('95b66cf670ca6ee0','https://www.theschoolleader.org/','Labor union and professional organization representing school principals and other school administrators.'),('e80505e84faa7681','https://www.afscme.org/','Labor union representing workers providing public services, including state, county and municipal employees.'),('d11eedde3d974f1e','https://www.aft.org/','Labor union representing educators, healthcare workers and other public-service professionals.'),('557ff38d46d977fc','https://afsa.org/about-afsa','Professional association and union representing members of the U.S. Foreign Service.')]:add(k,u,d,'Labor union','Not applicable')
for k in ['1c4646445b210306','4baab47bf950874b']:add(k,'https://afsaonline.org/about-afsa/','Trade association representing consumer-credit providers, including installment lenders, vehicle finance companies and mortgage providers.','Trade / business association')
add('40960fb4b191eec5','https://www.afia.org/','Trade association representing the U.S. animal-food industry and suppliers, with work on animal nutrition and policy.','Trade / business association',source='https://www.afia.org/pub/?id=992fbca2-05ed-00a6-75c2-dca9aac8df4e')
add('9b55c77b0cee3ddc','https://fisheries.org/','Professional scientific society supporting fisheries research, conservation and sustainable management.','Professional association',source='https://fishculture.fisheries.org/about/')
add('6b7d559b740d8252','https://affta.org/','Trade association representing the fly-fishing industry and advocating for fisheries conservation and a sustainable business community.','Trade / business association')
add('f7986d68b1fe9ed0','https://americanfidelity.com/about-us','Insurance holding company whose stock is controlled by the Cameron family investment partnership; parent of American Fidelity Assurance Company.','Company','Private company',source='https://americanfidelity.com/media/wh5ic2j4/separate-account-c-sai-and-financials.pdf');p['f7986d68b1fe9ed0']['notes']='Website is shared with the operating insurance group; holding company and insurer remain distinct.'
add('fe7833bbeff2124d','https://www.amfam.com/companyid','Property and casualty insurer organized as a stock insurance company within the American Family mutual holding-company structure.','Company','Unknown',source='https://oci.wi.gov/Pages/Companies/AmFamMutRestructuring.aspx');p['fe7833bbeff2124d']['notes']='S.I. denotes the converted stock insurer, not the ultimate mutual holding company. Exact current ownership chain is not simplified to policyholder ownership of this subsidiary.'
add('c25644a864525b76','https://www.miningamerica.org/','Trade association representing mineral exploration, mining and related businesses, with education and public-policy advocacy.','Trade / business association')
add('91d8fff4714418f1','https://www.afar.org/','Nonprofit organization supporting biomedical research on aging and healthier later life.','Nonprofit / initiative','Nonprofit / tax-exempt')
f.write_text(json.dumps(p,indent=2)+'\n');print(len(p),'draft profiles saved')
