import json,pathlib,gzip
r=pathlib.Path('work/research-2026');cs={c['id']:c for c in json.load(open(r/'general-round13-b-input.json'))};f=r/'general-round13-b-root-partial.json';p=json.load(open(f))
def add(k,desc,kind,own,site,url,claim):
 c=cs[k];v=dict(c.get('profile',{}));v.update(name=c['name'],description=desc,kind=kind,ownership=own,website=site,status='sourced',review_outcome='partial' if own=='Unknown' else 'confirmed',identity_evidence='Official organization source matches disclosed name and activity.',notes='Individually researched using primary organization evidence; filing name retained.'+(' Ownership not established by reviewed sources.' if own=='Unknown' else ''),as_of='2026-09-05',checked_at='2026-09-05',featured=False,legal_form='',logo_url='',logo_kind='',logo_source_url='');v['sources']=v.get('sources',[])
 if not v['sources']:
  rid=json.load(gzip.open(f'lobbying-map/public/data/reports/{k[:2]}.json.gz'))[k][0]['id'];v['sources']=[{'url':f'https://lda.gov/filings/public/filing/{rid}/print/','label':'Lobbying disclosure','claim':'Original disclosed client name.'}]
 v['sources'].append({'url':url,'label':'Official organization evidence','claim':claim});p[k]=v
add('1e5b1c86015d0cc3','Develops cargo drones for autonomous resupply and deliveries in remote locations for defense and commercial customers.','Company','Unknown','https://www.anatracompany.com/','https://www.anatracompany.com/','Anatra describes its unmanned cargo aircraft and plans for U.S. manufacturing; this is distinct from the historical aircraft maker.')
add('43b41353fb0b69a3','Provides marine maintenance, training, security operations and operational support primarily for the U.S. Navy.','Company','Private company','https://www.anchori.com/','https://www.anchori.com/','Anchor Innovation Inc identifies itself as a service-disabled veteran-owned small business in Virginia Beach.')
add('f5412a36b84e7087','Defense and space engineering contractor operating under the Arcfield name.','Company','Unknown','https://www.arcfield.com/aflcmc-xa-mac','https://www.arcfield.com/aflcmc-xa-mac','Arcfield official contracting page identifies Analex Corporation as the contractor.')
p['f5412a36b84e7087']['sources'].append({'url':'https://www.gao.gov/assets/890/883040.pdf','label':'GAO contract decision','claim':'GAO identifies Analex Corporation doing business as Arcfield.'})
add('a822944c59b1ba47','Manufactures glass bakeware, drinkware, food-storage containers and other household glass products.','Company','Unknown','https://www.anchorhocking.com/','https://www.anchorhocking.com/our-story/','Anchor Hocking describes its glassware manufacturing business and Lancaster, Ohio operations.')
add('e73cf98ce3965403','Parent company of Anchorage Digital businesses providing institutional digital-asset custody, trading and related services.','Company','Unknown','https://www.anchorage.com/','https://www.anchorage.com/legal','Official legal disclosures identify Anchorage Digital services as provided through wholly owned subsidiaries of Anchor Labs Inc.')
add('c48bd9261055414f','Digital-asset bank providing institutional custody, settlement, staking and governance services within Anchorage Digital.','Company','Unknown','https://www.anchorage.com/','https://www.anchorage.com/legal','Official legal disclosures identify Anchorage Digital Bank National Association as an Anchor Labs subsidiary providing custody, settlement, staking and governance.')
p['c48bd9261055414f']['notes']+=' Subsidiary of Anchor Labs Inc; parent public/private status not established in reviewed evidence. Shared group website.'
f.write_text(json.dumps(p,indent=2)+'\n');print(len(p))
