import json,pathlib,gzip
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round19-b-input.json'));out=json.load(open(r/'general-round19-b-root-draft.json'))
def add(i,website,desc,ownership,url,claim,notes='',kind='Business'):
 c=rows[i];sources=list(c.get('profile',{}).get('sources',[]));sources.append({'url':url,'label':'Organization evidence','claim':claim});reports=json.load(gzip.open(f"lobbying-map/public/data/reports/{c['id'][:2]}.json.gz",'rt'));rid=reports[c['id']][0]['id'];sources.append({'url':f'https://lda.gov/filings/public/filing/{rid}/print/','label':'LDA filing','claim':'Exact name-group filing reference from local federal lobbying report index.'})
 out[c['id']]={'name':c['name'],'description':desc,'kind':kind,'ownership':ownership,'website':website,'sources':sources,'identity_evidence':claim,'review_outcome':'partial','notes':notes,'status':'sourced','as_of':'2026-09-05','checked_at':'2026-09-05','featured':False,'legal_form':'','website_status':'partial' if website else 'unresolved','logo_url':'','logo_kind':'','logo_source_url':''}
add(5,'https://www.avara.com/','Pharmaceutical manufacturing organization producing medicines for other drug companies.','Unknown','https://www.avara.com/','Avara official site describes contract drug manufacturing and names Avara Pharmaceutical Services Inc.','Directory name Avara Pharmaceuticals Inc is not identical to website legal name; exact entity link requires further corroboration.')
add(6,'https://avathon.com/','Builds AI software for industrial operations, asset maintenance and fleet management.','Private company','https://avathon.com/company/','Official company page describes industrial, logistics and government AI operations.')
out[rows[6]['id']]['sources'].append({'url':'https://avathon.com/resources/press-releases/','label':'Company announcements','claim':'December 2024 announcement identifies membership of the World Economic Forum private-company Unicorn Community.'})
add(7,'https://www.avaya.com/en/solutions/government/','Avaya government communications business supplying contact-center, voice and collaboration systems.','Unknown','https://www.avaya.com/en/documents/fs-government-glance-mis15070en-gov.pdf','Avaya factsheet explicitly names Avaya Government Solutions and describes its public-sector communications services.','Business identity established; precise legal entity ownership not independently established. Parent website; hold parent logo.')
add(8,'https://avdyne.com/','Aircraft maintenance company based at Baltimore-Washington airport, serving commercial, cargo, corporate and government aviation.','Unknown','https://avdyne.com/','Official page names AvDyne AeroServices LLC and identifies its airport base and maintenance operations.')
add(9,'','Informal coalition disclosed as a federal lobbying client under the Aveda Institute Coalition name.','Not applicable','https://lobbyingdisclosure.house.gov/lookup.asp?reg_id=37996','House registrant list identifies Aveda Institute Coalition (Informal Coalition) as client 379960007 of Duane Morris.','Coalition membership and independent website remain unverified; do not substitute Aveda cosmetics corporate identity.',kind='Coalition')
for i in [10,11]:add(i,'https://www.aventiv.com/','Parent group behind Securus and JPay, providing communications, monitoring and payment services for correctional facilities.','Unknown','https://www.aventiv.com/content/aventiv-technologies-completes-recapitalization','Company announced completed debt-for-equity recapitalization and ownership transition July 2, with Securus and JPay brands continuing.','Current ownership transition documented; do not retain outdated Platinum Equity ownership automatically. Exact investor allocation is not supplied by this announcement.')
add(12,'https://www.aventra.io/','Defense technology business developing autonomous payload systems and precision-guidance equipment.','Unknown','https://www.aventra.io/media','Official media page explicitly names Aventra Defense Systems in Army evaluation reporting; site describes its guidance products.')
add(13,'https://www.averydennison.com/','Manufactures labeling materials and digital identification products, including RFID tags.','Publicly traded','https://averydennison.gcs-web.com/','Official investor site identifies Avery Dennison Corporation as NYSE: AVY and describes materials science and digital identification operations.')
(r/'general-round19-b-root-draft.json').write_text(json.dumps(out,indent=2)+'\n');print(len(out))
