import json,datetime
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured59-last10.json'));ids={a['id'] for a in json.load(open(r/'featured59-input.json'))[20:]};assert {a['originalID'] for a in rows}==ids;before={i:p[i] for i in ids};(r/'featured59-last-root-before.json').write_text(json.dumps(before,indent=2,ensure_ascii=False)+'\n');dec=[]
for x in rows:
 i=x['originalID'];a=p[i];patch=x['proposed'];ev=x['evidence'];urls=[s['url'] for s in x['exact_quotes']]
 if i in ['7a6d6a54d3c27f71','2c4af02b5e5dfd85']:patch['ownership']='Unknown';ev+=' The affiliate relationship is documented in 2015, not freshly verified as current ownership. Both 2026 filings use 1850 Parkway Place Suite 900, Marietta.'
 if i=='b8b65edc28484051':urls.append('https://www.flexport.com/privacy/');ev+=' Official privacy policy provides the legal organization context.'
 a.update(patch);a.update(review_outcome='confirmed',website_status='verified',identity_evidence=ev,notes=ev,checked_at='2026-09-13',as_of='2026-09-13',status='sourced')
 for u in dict.fromkeys(urls):
  if u not in [s['url'] for s in a['sources']]:a['sources'].append(dict(url=u,label='Primary organization evidence',claim=ev))
 dec.append(dict(id=i,patch=patch,evidence=ev,urls=urls))
a=p['5ac207500e152fc2'];a.update(logo_url='https://fireflyspace.com/wp-content/uploads/2021/12/firefly-logo.svg',logo_source_url='https://fireflyspace.com/',logo_kind='logo',logo_status='official_site_asset',logo_background='light');a['sources'].append(dict(url='https://fireflyspace.com/',label='Official logo',claim='Homepage primary Firefly Aerospace logo fetched and visually inspected.'))
(r/'featured59-last-root-decisions.json').write_text(json.dumps(dec,indent=2,ensure_ascii=False)+'\n')
for f,c in [(r/'reviewed.json',False),(Path('lobbying-map/research/reviewed-2026.json'),True),(Path('outputs/2026-research-trial/profiles.json'),False)]:f.write_text(json.dumps(p,ensure_ascii=False,indent=None if c else 2)+('' if c else '\n'))
f=Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(f));(r/'featured59-last-merges-before.json').write_text(json.dumps(m,indent=2)+'\n');pair=['2c4af02b5e5dfd85','7a6d6a54d3c27f71'];assert not any(set(pair)&set(a['source_ids']) for a in m);m.append(dict(canonical_id=pair[0],source_ids=pair,rationale='First Key Homes and FirstKey Homes, LLC 2026 registrations share 1850 Parkway Place Suite 900, Marietta and rental real-estate activity. Company-issued formation announcement defines FirstKey Homes as FirstKey Homes LLC. Preserve all filings and historical addresses.',sources=[dict(url='https://disclosurespreview.house.gov/data/LD/2026_Registrations_XML.zip',claim='301860897.xml and 301845257.xml share organization address and activity.'),dict(url='https://www.prnewswire.com/news-releases/firstkey-holdings-llc-announces-the-formation-of-firstkey-homes-llc-300139747.html',claim='Company-issued 2015 announcement defines brand and LLC.')],reviewed_at=datetime.datetime.now(datetime.timezone.utc).isoformat()));f.write_text(json.dumps(m,indent=2,ensure_ascii=False)+'\n');print('10 identities, one logo, one duplicate group saved')
