import json,datetime
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));inputs=json.load(open(r/'featured62-input.json'));ids={x['id'] for x in inputs};(r/'featured62-root-before.json').write_text(json.dumps({i:p[i] for i in ids},indent=2)+'\n');dec=[]
def put(i,ev,urls,patch=None):
 assert i in ids
 if patch:p[i].update(patch)
 p[i].update(review_outcome='confirmed',website_status='verified',identity_evidence=ev,notes=ev,status='sourced',checked_at='2026-09-13',as_of='2026-09-13')
 for u in urls:
  if u not in [s['url'] for s in p[i]['sources']]:p[i]['sources'].append(dict(url=u,label='Primary identity evidence',claim=ev))
 dec.append(dict(id=i,decision='confirmed',evidence=ev,urls=urls))
for x in json.load(open(r/'featured62-first10.json')):
 if x['decision']=='confirm':
  ev=x['evidence']
  if x['originalID']=='56b51e4ccbb0eefb':ev+=' Formerly-reported label is preserved as filing history, not proof that Advisors LLC and the attest LLP are the same legal entity.'
  put(x['originalID'],ev,[s['url'] for s in x['exact_quotes']],x['proposed'])
for x in json.load(open(r/'featured62-middle10.json')):
 if x['decision']=='confirm':
  urls=[u for u in x['source_urls'] if 'lda.gov' not in u];patch={k:x[k] for k in ['description','website','kind','ownership']}
  if x['id']=='315d9b245760ac12':urls.append('https://www.gs1us.org/who-we-are')
  put(x['id'],x['exact_official_excerpt']+' Original unsuffixed filing identity preserved.',urls,patch)
for i,u,ev in [('6daeddc3b7f11701','https://support.granicus.com/articles/How_To/Granicus-LLC-SubscriberPrivacy-Statement','Official subscriber privacy notice identifies Granicus LLC as a covered entity; exact filed LLC and government software activity match.'),('b9dffbb5aab4fa44','https://granitenet.com/legal-and-policy/','Official service terms name Granite Telecommunications LLC and affiliates, matching original exact legal aliases and telecommunications activity.'),('e3599edb4c567bf5','https://console.groq.com/docs/legal/archive','Official legal terms identify Groq Inc. as contracting party separately from UK and public-sector entities. Original exact Inc. identity confirmed; ownership remains unverified.')]:put(i,ev,[u],{'ownership':'Unknown'})
hr='https://investors.hrblock.com/static-files/2ef10c77-8b79-4cfa-bd06-0cb9c86cdb96';heb='https://www.heb.com/static/pdfs/Be-a-VIP-with-Jennette-McCurdy-Contest-Application-Form-and-Release.pdf';gun='https://gunvorgroup.com/news/gunvor-usa-upsizes-credit-facility-to-us-2-3-billion/'
root=[('0b8f67e289a61d7d','https://guardianmetalresources.com/','Current official homepage explicitly names Guardian Metal Resources PLC and its quoted exchange symbols; its Nevada tungsten development activity matches the filed brand.','Public company','Develops tungsten and other critical-mineral projects in Nevada.'),('6a293346e08b0da5',gun,'Official Gunvor release names exact Gunvor USA LLC; 2026 SEC contract independently identifies the Delaware LLC. Prior group ownership statement is dated, not a new ownership verification.','Unknown','Trades and supplies energy commodities, including crude oil and natural gas.'),('7e323db69a891ec3',gun,'Current legal name Gunvor USA LLC matches official release and 2026 contract. Nerobreeze wording is preserved as reported filing history, without separately asserting a legal conversion.','Unknown','Trades and supplies energy commodities; this filing includes a reported former-name label.'),('77bc4ea8d35b6506','https://gusto.com/legal/terms/check-printing-terms','Official terms explicitly link the Gusto brand with ZenPayroll and payroll services. The original unsuffixed Gusto brand is preserved; no exact corporate rename is asserted.','Unknown','Provides payroll, employee benefits, and human-resources software.'),('ee810a0b76cd2816',hr,'Official 2021 annual-report attachment names H&R Block Management LLC among participating affiliates. Exact current filing name and Kansas City address match; public-parent stock listing is not transferred to the LLC.','Unknown','An H&R Block entity associated with tax preparation and related business services.'),('92da2151e2f1386e',hr,'Same exact H&R Block Management LLC name appears in official annual-report attachment. Original filing additionally reports an H&R Block Inc. subsidiary relationship; preserve that attribution.','Unknown','An H&R Block entity associated with tax preparation and related business services.'),('cca152c662d81d7c','https://www.heb.com/','Official H-E-B grocery site matches the original brand and retail activity. Brand and full legal-name filings share 646 South Flores Street, San Antonio.','Unknown','Operates grocery stores in Texas and Mexico.'),('f4c008b7cccfdabb',heb,'Official H-E-B contest document identifies H-E-B Grocery Company LP; the original legal-name and brand filings share the San Antonio headquarters address. Historical legal name preserved.','Unknown','Operates the H-E-B grocery store business.'),('796aa08e6e125f0f','https://flauditor.gov/pages/nonprofit_forprofit%20rpts/2024%20h.%20lee%20moffitt%20cancer%20center%20%26%20research%20institute.pdf','Florida Auditor General published 2024 audited statements identify the exact H. Lee Moffitt Cancer Center and Research Institute nonprofit and its cancer-research mission, distinguishing the hospital and foundation subsidiaries.','Nonprofit / tax-exempt','Conducts cancer research and supports cancer treatment through the Moffitt health system.')]
for i,u,ev,o,d in root:put(i,ev,[u],dict(ownership=o,description=d))
for i in ['6a293346e08b0da5','7e323db69a891ec3']:p[i]['sources'].append(dict(url='https://www.sec.gov/Archives/edgar/data/1376139/000137613925000054/exhibit101-amendmentno1toa.htm',label='2026 contract',claim='Names Gunvor USA LLC as Delaware limited liability company.'))
seen={x['id'] for x in dec};dec += [dict(id=i,decision='hold',evidence='Exact legal identity or historical continuity not established by retrieved primary evidence.') for i in ids-seen];(r/'featured62-root-decisions.json').write_text(json.dumps(dec,indent=2)+'\n')
for f,c in [(r/'reviewed.json',False),(Path('lobbying-map/research/reviewed-2026.json'),True),(Path('outputs/2026-research-trial/profiles.json'),False)]:f.write_text(json.dumps(p,ensure_ascii=False,indent=None if c else 2)+('' if c else '\n'))
f=Path('lobbying-map/research/verified-entity-merges.json');m=json.load(open(f));(r/'featured62-merges-before.json').write_text(json.dumps(m,indent=2)+'\n')
for pair,u,reason in [(['6a293346e08b0da5','7e323db69a891ec3'],gun,'Same exact current legal name Gunvor USA LLC; second filed alias appends former-name wording. Preserve all history.'),(['ee810a0b76cd2816','92da2151e2f1386e'],hr,'Same exact H&R Block Management LLC legal name; second filing label appends parent-company relationship. Do not merge parent.'),(['f4c008b7cccfdabb','cca152c662d81d7c'],heb,'H-E-B brand and full legal-name registrations share 646 South Flores Street San Antonio and grocery activity. Official H-E-B document names the LP.')]:
 assert not any(set(pair)&set(a['source_ids']) for a in m)
 m.append(dict(canonical_id=pair[0],source_ids=pair,rationale=reason,sources=[dict(url=u,claim=reason)],reviewed_at=datetime.datetime.now(datetime.timezone.utc).isoformat()))
f.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');print(len(seen),'confirmed;3 merges')
