import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured60-input.json'))[20:];before={x['id']:p[x['id']] for x in rows};(r/'featured60-root-before.json').write_text(json.dumps(before,indent=2)+'\n')
d=[
('78c1ab58f81f26cd','Fujitsu provides IT services, computing systems, and communications technology.','https://global.fujitsu/en-us/subsidiaries','The filed brand Fujitsu and Richardson Telecom Parkway address match the official US group directory. This confirms the brand; it does not resolve the filing to Fujitsu Limited or a particular US subsidiary.'),
('1de464c674d1f5f4','Fullscript provides a platform for clinicians to recommend and dispense supplements and other health products.','https://fullscript.com/legal/privacy','The current privacy statement explicitly defines Fullscript as Healthy Web Inc., its parent Natural Partners Inc., and affiliates; its Manchester 1750 Elm Street address matches the original registration. Brand scope is preserved.'),
('26f824867597b7e1','Future Standard manages investments in private equity, credit, and real estate.','https://www.futurestandard.com/news-center/fs-investments-announces-rebrand-to-future-standard-signaling-vision-for-the-next-era-in-private-markets','The company announcement dated July 21, 2025 explicitly renames FS Investments as Future Standard. Original filed brand matches. Ownership is not established by this announcement.'),
('2c0b51d899e86f34','Galaxy Digital Holdings LP is a partnership in the Galaxy digital-asset financial services and investment business.','https://www.galaxy.com/terms','Official terms explicitly name Galaxy Digital Holdings LP separately from Galaxy Digital Inc. The exact original LP name is confirmed; the listed corporation and partnership remain distinct.'),
('a265140ca886cfea','Galls supplies uniforms, apparel, and equipment for police, first responders, and other public safety workers.','https://www.galls.com/pages/privacy','The August 5, 2026 privacy policy names Galls LLC and 1340 Russell Cave Road, Lexington, matching original registrations. Legal identity confirmed; ownership is not established.'),
('31df01ca89566146','Galls supplies public safety uniforms and equipment; this filing names Tremont Strategies Group on behalf of Galls LLC.','https://www.galls.com/pages/terms','Original filing explicitly names Tremont Strategies Group OBO Galls LLC and public safety equipment activity. Official terms identify Galls LLC. Preserve the intermediary wording and every original filing.'),
('80393655dd4ef45a','GeneDx LLC performs genetic testing, including exome and genome sequencing, to help diagnose rare and inherited diseases.','https://www.genedx.com/privacy-hub/privacy-policy','The official privacy policy explicitly identifies GeneDx LLC, matching the original filed legal name. The current homepage describes genetic testing. This does not transfer a parent company stock listing to the LLC.'),
('304cf375bddab404','General Catalyst is an investment firm that finances and helps build companies, including healthcare and technology businesses.','https://www.generalcatalyst.com/terms-and-conditions','The original unsuffixed General Catalyst brand and investment activity match the official site. Its legal notice defines General Catalyst as General Catalyst Group Management LLC and affiliates. The brand scope is preserved.'),
('231c3d9f4ff8d88d','General Catalyst Group Management LLC is the investment adviser behind the General Catalyst investment platform.','https://www.generalcatalyst.com/terms-and-conditions','Official terms explicitly name General Catalyst Group Management LLC as website operator and investment adviser, matching the original legal name. Ownership is not established by adviser registration.')]
for i,desc,url,ev in d:
 assert i in before
 p[i].update(description=desc,review_outcome='confirmed',ownership='Unknown',website_status='verified',identity_evidence=ev,notes=ev,checked_at='2026-09-13',as_of='2026-09-13',status='sourced')
 if url not in [s['url'] for s in p[i]['sources']]:p[i]['sources'].append(dict(url=url,label='Primary identity evidence',claim=ev))
(r/'featured60-root-decisions.json').write_text(json.dumps([dict(id=i,description=de,url=u,evidence=e) for i,de,u,e in d]+[dict(id='4c3a811c1487048d',decision='hold',evidence='Acquisition confirmed, but current filed Gen Digital/former MoneyLion grouping still lacks exact legal continuity evidence.')],indent=2)+'\n')
for f,c in [(r/'reviewed.json',False),(Path('lobbying-map/research/reviewed-2026.json'),True),(Path('outputs/2026-research-trial/profiles.json'),False)]:f.write_text(json.dumps(p,ensure_ascii=False,indent=None if c else 2)+('' if c else '\n'))
print('9 confirmed, 1 held; master and mirrors saved')
