import json
from pathlib import Path
r=Path('work/research-2026');p=json.load(open(r/'reviewed.json'));rows=json.load(open(r/'featured61-input.json'))[20:];ids={x['id'] for x in rows};(r/'featured61-root-before.json').write_text(json.dumps({i:p[i] for i in ids},indent=2)+'\n')
d=[('8629a5fe31beaf0e','GoFundMe','An online platform where people and organizations raise money through fundraising campaigns.','https://www.gofundme.com/c/terms','The original GO FUND ME crowdfunding label matches the official GoFundMe platform and terms. Brand identity confirmed; do not classify it as the separate GoFundMe.org nonprofit.','Unknown'),('513ccb3e68c9419b','GoBrands, Inc. (Gopuff)','Operates Gopuff, a delivery service for groceries, drinks, and other everyday goods.','https://www.gopuff.com/e/terms-and-conditions','Official terms explicitly identify GoBrands Inc. doing business as Gopuff, matching the filed legal name and delivery activity.','Unknown'),('840001f6ae8fdac1','Goodwill Industries International','Supports the Goodwill network and its job training, employment, and community programs.','https://www.goodwill.org/annual-report/','Official annual-report page identifies Goodwill Industries International as a 501(c)(3), EIN 53-0196517. Exact original aliases match. Local Goodwill organizations remain separate.','Nonprofit / tax-exempt'),('4a3865a4f0dc50f6','Google Public Sector (formerly reported as Google Cloud)','Provides cloud, artificial intelligence, and security services for government and educational institutions.','https://publicsector.google/','Official site explicitly identifies Google Public Sector and its government/education services. Filing former-name wording is preserved as reported history, not a claim that all Google Cloud became this organization.','Unknown'),('f129f139fa9dddad','Gotion, Inc.','Develops batteries and energy-storage systems for electric vehicles and other uses.','https://www.gotion.com/solutions-2/commercial/','Current official commercial-solutions page footer identifies Gotion Inc., matching the exact original filing aliases. Ownership is not inferred from a similarly named overseas parent.','Unknown'),('ff9508e3adcb1cd9','Govly','Provides software that helps government contractors find procurement opportunities and work with partners.','https://www.govly.com/','Official homepage identifies Govly and its market network for government contractors, matching the filed brand and public-sector procurement activity.','Unknown'),('35832576929ca8cf','Gowan Company','Develops and supplies crop-protection products, seeds, and fertilizers for agriculture.','https://www.gowanco.com/about-gowan','Official About page names Gowan Company and describes the Gowan Group as a family-owned agricultural business based in Yuma. Filed unsuffixed company brand is preserved.','Private / family-owned')]
for i,n,de,u,ev,o in d:
 assert i in ids;p[i].update(name=n,description=de,ownership=o,review_outcome='confirmed',website_status='verified',identity_evidence=ev,notes=ev,status='sourced',checked_at='2026-09-13',as_of='2026-09-13')
 if u not in [s['url'] for s in p[i]['sources']]:p[i]['sources'].append(dict(url=u,label='Primary organization evidence',claim=ev))
(r/'featured61-root-decisions.json').write_text(json.dumps([dict(id=i,name=n,description=de,url=u,evidence=e,ownership=o) for i,n,de,u,e,o in d]+[dict(id=i,decision='hold',reason='Needs exact legal identity or conversion evidence beyond generic Google brand') for i in ids-{z[0] for z in d}],indent=2)+'\n')
for f,c in [(r/'reviewed.json',False),(Path('lobbying-map/research/reviewed-2026.json'),True),(Path('outputs/2026-research-trial/profiles.json'),False)]:f.write_text(json.dumps(p,ensure_ascii=False,indent=None if c else 2)+('' if c else '\n'))
print('7 identities saved;3 held')
