exec(open('work/research-2026/extend_round10b.py').read().split("for k,u,d in")[0])
add('68c66b1d7f3cb27b','https://www.aec-sc.com/contact/','Civil engineering and surveying firm based in Cayce, South Carolina, serving infrastructure and utility projects.','Company');p['68c66b1d7f3cb27b']['notes']='LDA client location is South Carolina, corroborated by the official contact page and state university vendor directory. Not the similarly named Chicago firm.'
add('319a905854efd363','https://www.fb.org/about/who-we-are','Membership federation representing farmers, ranchers and rural communities through agricultural policy advocacy and leadership programs.','Trade / business association');p['319a905854efd363']['name']='American Farm Bureau Federation'
add('a7d039d49f3044d5','https://www.aep.com/','Service subsidiary within American Electric Power, supporting the utility group’s operations.','Company','Subsidiary of public company',source='https://www.sec.gov/Archives/edgar/data/4904/000000490426000013/ex2120254q.htm');p['a7d039d49f3044d5']['notes']='Official SEC subsidiary list identifies the Service Corporation. Website is the parent group site, not a separate corporate website.'
add('7ae462019a17539a','https://www.americanexpress.com/','Financial-services company providing payment cards, payment-network services and related services for consumers and businesses.','Company','Publicly traded',source='https://www.americanexpress.com/en-us/newsroom/articles/company-statements/long-lake--backed-by-general-catalyst--to-purchase-american-expr.html');p['7ae462019a17539a']['sources'][-1]['claim']='American Express Company identifies its listing NYSE: AXP.';p['7ae462019a17539a']['featured']=True
add('5beeca605b6cc3b9','https://ir.americanexpress.com/fixed-income-investors/default.aspx','Operating subsidiary of American Express supporting card, travel and related financial-service activities.','Company','Subsidiary of public company',source='https://www.sec.gov/Archives/edgar/data/4962/000000496225000016/axp-20241231exx21.htm');p['5beeca605b6cc3b9']['notes']='Exact subsidiary appears in SEC corporate structure; issuer site hosts its debt-program information. Distinct from Amex Global Business Travel.'
add('e02aa9c90cc68503','https://investors.amexglobalbusinesstravel.com/','Corporate travel, expense and meetings-services business operated by Global Business Travel Group, separately from American Express Company.','Company','Unknown',source='https://www.sec.gov/Archives/edgar/data/1820872/000162828026052168/gbtg-20260630.htm');p['e02aa9c90cc68503']['notes']='2026 filing reports an agreement for acquisition by Long Lake. Closing and exact filing entity require verification before assigning current public/private ownership.'
add('37cf80f5dc87058e','https://jobsenergysecurity.org/','Organization whose lobbying disclosure describes nonprofit activity on energy issues. Its similarly named website currently provides limited information.','Unknown');p['37cf80f5dc87058e']['notes']='Website footer uses Americans (plural), whereas filing uses American. Identity remains partial; nonprofit status is self-reported, not independently verified.'
k='56b1440501744bdb';v=dict(rows[k]['profile']);v.update(name=rows[k]['name'],description='Informal coalition of digital-asset exchange firms, according to its lobbying disclosure.',kind='Coalition',ownership='Not applicable',website='',status='sourced',review_outcome='partial',identity_evidence='House registry names this exact informal coalition under Sullivan & Cromwell; filing describes digital-asset exchange activity.',logo_url='',logo_kind='',logo_source_url='',website_status='unresolved',checked_at='2026-09-05',as_of='2026-09-05',notes='No independently verified standalone website or membership list.',legal_form='');v['sources'].append(dict(url='https://lobbyingdisclosure.house.gov/lookup.asp?reg_id=30572',label='House registrant and client registry',claim='Registry lists American Exchange Coalition (Informal Coalition).'));p[k]=v
assert len(p)==30
(r/'general-round10-b-researched.json').write_text(json.dumps(p,indent=2)+'\n');f.write_text(json.dumps(p,indent=2)+'\n');print('30 root B drafts saved; branding and final verification pending')
