exec(open('work/research-2026/extend_round11b.py').read().split("add('0e685")[0])
add('fe1a037525e3b8b5','https://americanpistachios.org/about-us','Nonprofit trade association representing American pistachio growers and supporting research, marketing and industry advocacy.','Trade association','Nonprofit / tax-exempt')
add('aa96f5f73a00037e','https://planning.org/aboutapa/','Professional association for planners and others working on community development, land use and the future of towns and cities.')
add('f0517ceeecd9b92b','https://www.apma.org/about-apma/governance/who-we-are/','Professional association representing podiatric physicians and surgeons, providing education, practice support and advocacy on foot and ankle care.')
add('07fd992979a352eb','https://www.pharmacist.com/who-we-are','Professional association supporting pharmacists, pharmacy students and technicians through education, practice resources and policy advocacy.')
add('54997a2a476faa4d','https://www.aoa.org/','Professional association representing doctors of optometry, optometric professionals and students, with eye-care policy advocacy and professional support.');p['54997a2a476faa4d']['sources']=[dict(url='https://memberservices.aoa.org/portal/en/kb/articles/what-is-the-americ',label='Official membership overview',claim=p['54997a2a476faa4d']['description'])]
add('c3b46c24eba54b7a','https://www.ansmobility.com/about','Wireless-device business offering mobile phones and related devices under the ANS name.','Company');p['c3b46c24eba54b7a']['review_outcome']='partial';p['c3b46c24eba54b7a']['notes']='Official site identifies American Network Solutions LLC; exact linkage to the filing name without LLC remains partial.'
add('5ffe60c58879111c','https://www.ampac.us/','Specialty chemical manufacturer producing materials for defense, space-launch and fire-suppression applications; part of NewMarket Corporation.','Company','Subsidiary of public company');p['5ffe60c58879111c']['sources'].append(dict(url='https://www.sec.gov/Archives/edgar/data/1282637/000119312525052433/d928499dars.pdf',label='NewMarket annual report',claim='NewMarket acquired all ownership units of AMPAC Intermediate Holdings LLC, ultimate parent of American Pacific Corporation, on January 16, 2024.'));p['5ffe60c58879111c']['notes']='Filing short name matched to specialty chemical activity. American Pacific is a subsidiary, not separately marked as a listed issuer.'
(r/'general-round11-b-root-partial.json').write_text(json.dumps(p,indent=2)+'\n');print(len(p))
