exec(open('work/research-2026/extend20b.py').read().split('add(15,')[0])
add(24,'https://www.bankofamerica.com/','Banking and financial-services group offering consumer banking, commercial banking, wealth management and investment services.','Publicly traded','https://newsroom.bankofamerica.com/content/newsroom/press-releases/2026/04/bank-of-america-reports-first-quarter-2026-financial-results.html','Official 2026 results identify Bank of America Corporation as NYSE: BAC.','Broad group name; individual bank subsidiaries remain separate entities.')
add(25,'https://bpi.com/','Banking industry association conducting policy research and advocating for its member banks.','Not applicable','https://bpi.com/about-us/','Official page identifies Bank Policy Institute as a policy, research and advocacy organization representing major banks.',kind='Trade association')
add(26,'https://www.bankaool.com/','Mexican bank providing deposit, payment and other financial services.','Unknown','https://www.bankaool.com/','Official footer names Bankaool SA Institucion de Banca Multiple and its Chihuahua address.','Announced intention to list shares does not establish that an IPO has occurred.')
add(27,'https://bankerslifeinsurance.com/','North Carolina life insurer in court-ordered liquidation, with information for policyholders maintained by its liquidators.','Unknown','https://bankerslifeinsurance.com/','Company site maintained or approved by appointed liquidators says liquidation became effective November 30, 2024.','Do not confuse this company with Bankers Life and Casualty Company or assign the unrelated retail brand website.')
add(28,'https://www.bannerhealth.com/','Nonprofit health system operating hospitals, outpatient care and health insurance services across the western United States.','Nonprofit / tax-exempt','https://www.bannerhealth.com/about','Official page identifies Banner Health as a nonprofit system headquartered in Phoenix.',kind='Healthcare organization')
add(29,'','A Florida nonprofit health system disclosed under the broad name Baptist Health.','Unknown','https://lda.gov/api/v1/clients/66849/?format=json','Live LDA client API identifies Baptist Health as a Florida nonprofit health system but supplies no city in the returned record.','Several distinct Florida health systems use Baptist names. Jacksonville candidate not assigned without exact filing address or other corroboration.',kind='Healthcare organization')
out[rows[29]['id']]['review_outcome']='unresolved'
(r/'general-round20-b-root-draft.json').write_text(json.dumps(out,indent=2)+'\n');print(len(out),'rootprofiles')
