import json
from pathlib import Path
p=Path('work/research-2026');a=json.load(open(p/'general-round75-input.json'));f=p/'round75-root-incremental-evidence.json';e=json.load(open(f))
def add(i,description,kind,ownership,website,notes,sources,outcome='partial'):
 assert a[i]['id'] not in e
 e[a[i]['id']]={'name':a[i]['name'],'description':description,'kind':kind,'ownership':ownership,'website':website,'notes':notes,'sources':[{'url':u,'claim':c} for u,c in sources],'review_outcome':outcome,'featured':False}
def lda(i):return [(s['url'],s['claim']) for s in a[i]['profile']['sources']]
add(26,'KIPP is a national network of public charter schools, with programs supporting students through college and careers.','Charter school network','Unknown','https://www.kipp.org/','The abbreviated filing name identifies the KIPP network; the specific contracting legal entity is not established. Keep separate from the explicitly named KIPP Foundation entry. Public charter schools do not make the network itself a government body.',lda(26)+[('https://www.kipp.org/','Official network website describes KIPP Public Schools and separately identifies KIPP Foundation.')])
add(29,'Joint lobbying client naming brothers Kiril and Georgi Domuschiev, whom the disclosure describes as owners of animal-health business Huvepharma.','Individuals','Not applicable','','The filing spells Georgi’s surname Domuschief; the company uses Domuschiev. This entry represents two individuals, not Huvepharma itself. No personal website or corporate logo assigned. Historical company evidence does not establish current ownership percentages.',lda(29)+[('https://www.huvepharma.com/news/article/huvepharma-generating-a-virtuous-circle/','Company-hosted 2022 article identifies president Kiril Domuschiev and his brother Georgi and describes their animal-health business activities.')])
add(31,'Joint client entry naming investment entities Evolve Buyer, LLC and Yoda Topco, LP, represented through Kirkland & Ellis. A 2026 filing reports lobbying on business competition regulation.','Investment entities represented through counsel','Unknown','','The law firm is an intermediary. The beneficiaries’ precise businesses, ownership and official websites remain unverified; no law-firm website or logo substituted.',lda(31)+[('https://lda.senate.gov/filings/public/filing/b0c66306-f2ee-456e-8bfd-ee8188ef22da/print/','2026 Q1 Ballard Partners report names both beneficiaries through Kirkland & Ellis and identifies business competition regulatory matters.')])
add(37,'Klal Yisroel Inc. is an advocacy nonprofit that participated with Tzedek Association in a campaign seeking insurance coverage for infertility treatment.','Advocacy nonprofit','Nonprofit / tax-exempt','','A joint fundraising disclosure identifies Klal Yisroel as a 501(c)(4), separately from Tzedek’s 501(c)(3). Current IRS status was not independently established. Tzedek’s website and EIN must not be assigned to this organization.',lda(37)+[('https://dryveup.com/tzedek23/','Joint campaign describes infertility-coverage advocacy and separately identifies Klal Yisroel Inc as a 501(c)(4) organization.')])
add(48,'Knight-Swift is a freight transportation group combining the Knight and Swift trucking businesses, with truckload and other logistics operations.','Freight transportation company','Public company','https://knight-swift.com/','The filing uses an abbreviated group name with a former Swift name. The public parent is Knight-Swift Transportation Holdings Inc., listed on NYSE as KNX; operating subsidiaries remain distinct.',[('https://investor.knight-swift.com/news/news-details/2017/Knight-Transportation-Inc.-and-Swift-Transportation-Company-Merge-to-Create-North-Americas-Premier-Truckload-Transportation-Company/default.aspx','Completed 2017 merger formed combined Knight-Swift group while preserving separate brands and operations.'),('https://www.sec.gov/Archives/edgar/data/1492691/000149269126000059/knx-20260630.htm','2026 SEC report identifies Knight-Swift Transportation Holdings Inc and NYSE KNX listing.')])
add(52,'Knob Petroleum Corp is a lobbying client describing itself as a petroleum company in its federal disclosure.','Petroleum business (self-reported)','Unknown','','Registration lists Panama City without a US state. Independent business identity, ownership, website and logo remain unverified; no namesake assigned.',lda(52),'unresolved')
add(58,'The Knox County Area Partnership supports business recruitment, expansion and entrepreneurship in Galesburg and Knox County, Illinois.','Economic development nonprofit','Nonprofit / tax-exempt','https://www.knoxpartnership.com/','The filing has conflicting city/state fields (Knoxville, TN), but its street address 200 East Main St and ZIP 61401 match the Galesburg organization. Exact IRS name and address match EIN 37-1356170. Preserve original filing location as disclosed; the researched organization is in Illinois.',lda(58)+[('https://www.knoxpartnership.com/about-us/','Official page identifies Galesburg/Knox County Illinois economic-development services and 501(c)(6) nonprofit status.'),('https://www.irs.gov/pub/irs-soi/eo2.csv','IRS record EIN 371356170 matches exact organization name and 200 E Main St Ste 200, Galesburg IL 61401.')],'confirmed')
add(81,'Komal Patel is listed as an individual lobbying client in a federal disclosure.','Individual','Not applicable','','The registration lists Coral Springs, Florida. No independently verified biography or professional affiliation was established; do not attach information about people sharing this name. Corporate ownership categories and company logos are not applicable.',lda(81),'unresolved')
add(90,'Konya Mining operates and develops industrial and critical-mineral mines, supplying silica sand and other materials.','Mining company','Private company','https://konyamining.com/','The site uses Konya Mining Company while the filing says Corporation. Exact street address 304 N Broadway, Coweta OK 74429 matches the registration. Its official site expressly describes the business as privately owned.',lda(90)+[('https://konyamining.com/about/','Official page describes privately owned mining business, products and exact Coweta street address matching registration 301848179.xml.')],'confirmed')
f.write_text(json.dumps(e,ensure_ascii=False,indent=2)+'\n');print('Saved',len(e),'profiles; missing',[(i,x['name']) for i,x in enumerate(a) if x['id'] not in e])
