import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'general-round12-b-root-partial.json'));rows={v['id']:v for v in json.load(open(r/'general-round12-b-input.json'))}
def add(k,u,d,kind='Trade association',own='Unknown'):
 v=dict(rows[k].get('profile',{}));v.update(name=rows[k]['name'],description=d,kind=kind,ownership=own,website=u,review_outcome='confirmed',status='sourced',identity_evidence='Official source identifies exact organization name and activities.',notes='Ownership and tax classification are not inferred from the organization name.',sources=[dict(url=u,label='Official organization overview',claim=d)],logo_url='',logo_kind='',logo_source_url='',checked_at='2026-09-05',as_of='2026-09-05');p[k]=v
add('ebafd4d400335d18','https://www.asaonline.com/about-us/','Association advocating for construction subcontractors, specialty contractors and suppliers, with education and professional networking.');p['ebafd4d400335d18']['review_outcome']='partial';p['ebafd4d400335d18']['notes']='Filing singular Subcontractor preserved; official association uses plural Subcontractors.'
add('746359884a277264','https://americansugarbeet.org/about/who-we-are/','Association uniting U.S. sugarbeet growers and representing the shared interests of sugarbeet grower organizations.')
add('a86ba8f45bd225d1','https://americansuppressorassociation.com/about/about-asa/','Industry association advocating for firearm-suppressor ownership and policy and promoting suppressor use for hearing protection.');p['a86ba8f45bd225d1']['sources'].append(dict(url='https://downloads.regulations.gov/ATF-2016-0001-0041/attachment_1.pdf',label='Association regulatory comment',claim='Association describes itself as a nonprofit 501(c)(6) organization.'));p['a86ba8f45bd225d1']['ownership']='Nonprofit / tax-exempt'
add('041dc59adb1b9418','https://americanorchestras.org/about-us/','Membership organization supporting orchestras and orchestra professionals through education, research, organizational support and policy advocacy.','Arts membership organization')
add('35a94aed87e5f88c','https://site.thoracic.org/about-us/overview','Medical and scientific society supporting respiratory health, critical care and sleep medicine through research, education and advocacy.','Professional association','Nonprofit / tax-exempt');p['35a94aed87e5f88c']['sources'].append(dict(url='https://www.thoracic.org/about/governance/ats-bylaws.pdf',label='Official bylaws',claim='ATS is a nonprofit corporation and international professional and scientific society.'))
add('220e0f714572af9b','https://atra.org/atras-mission/','Advocacy organization seeking changes to civil-liability laws through public education and legislative advocacy.','Advocacy organization')
add('deec3d2bbd4e71d7','https://www.atach.org/about','Trade association representing regulated cannabis and hemp businesses and advocating for their policy interests.')
add('9695363236366639','https://www.atssa.com/about-us/atssa/','Trade association representing businesses that design, manufacture and install roadway safety and traffic-control devices.')
(r/'general-round12-b-root-partial.json').write_text(json.dumps(p,indent=2)+'\n');print(len(p))
