exec(open('work/research-2026/research30a_root.py').read())
add(1,'Firstfloor','Develops education facilities, student housing, and other real-estate projects, offering turnkey development services.','https://www.firstfloor.biz/',sources=[('https://www.firstfloor.biz/','Official site identifies a Raleigh development firm serving education and housing clients.'),('https://www.sfla.biz/sfla-team/robbie-ferris-aia-refp-leed-ap/','Related architecture firm identifies Robbie Ferris as creator of Firstfloor.')],notes='Name and educational real-estate activity match; current legal ownership of Firstfloor is not established from founder biography alone.')
add(4,'Advanced Situational Awareness, LLC','Develops GPS tracking and communications tools for first responders, including personnel and equipment tracking.','https://advancedsa.com/',legal='LLC',sources=[('https://advancedsa.com/','Official site describes first-responder tracking technology, including RangerTrax.')],notes='Matches exact client name and specialized disclosed activity; manager identity does not establish equity ownership.')
add(12,'Climate Innovation Action','Advocates for climate policy and supports lobbying related to climate solutions.','https://advocatesforclimate.org/climate-innovation-action/','Advocacy nonprofit','Nonprofit / tax-exempt',sources=[('https://advocatesforclimate.org/climate-innovation-action/','Official page identifies Climate Innovation Action Inc., formerly LTC Action, as a separate related 501(c)(4) entity created in 2019.'),('https://advocatesforclimate.org/wp-content/uploads/2025/10/990-2024-Filed-Returns-for-public-inspection.pdf','Official-hosted 2024 return provides tax-status evidence.')],notes='Separate legal entity from Advocates for Climate Innovation; linked page is hosted by its related organization, so parent branding is not assigned.')
add(22,'Prime Minute, Inc.','Develops technology for disaster-response teams and partners with emergency-response operators; its lobbying disclosure describes aerial wildfire suppression services.','https://prime-minute.com/',sources=[('https://prime-minute.com/','Official site describes technology for natural-disaster responders and partnerships with emergency-response operators.')],notes='General emergency-response identity matches; the specific aerial-suppression description remains self-reported, and ownership is unknown.')
add(23,'Resource Public Affairs LLC','The filing describes a manufacturer of float systems and aircraft conversions for waterborne single-engine air tankers; the independent business identity is not established.','',kind='Unknown',legal='LLC',sources=[('https://lobbyingdisclosure.house.gov/lookup.asp?reg_id=44446','House registry lists Capitol Counsel on behalf of Resource Public Affairs LLC, client ID 444460038.')],notes='Exact filing label established, but no verified official website or independent identity linkage; do not infer an aircraft manufacturer from the description alone.',outcome='unresolved')
# An unknown ownership field remains partial even when operating identity is clear.
for v in p.values():
 if v['ownership']=='Unknown' and v['review_outcome']=='confirmed':v['review_outcome']='partial'
(r/'general-round30a-root-draft.json').write_text(json.dumps(p,indent=2)+'\n');print('Final draft',len(p))
s=(r/'check_general29c.py').read_text().replace('29c','30a');(r/'check_general30a.py').write_text(s)
