import json,pathlib
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round76-input.json'));path=r/'round76-root-incremental-evidence.json';e=json.load(open(path))
def add(i,desc,website,kind,notes,sources,out='partial'):
 e[rows[i]['id']]={'name':rows[i]['name'],'description':desc,'website':website,'kind':kind,'ownership':'Unknown','notes':notes,'review_outcome':out,'featured':False,'sources':[{'url':u,'claim':c} for u,c in sources]}
add(10,'Kropp Holdings operates as KHI, providing payment networks for aviation and marine fuel purchases by government agencies and commercial operators.','https://khinc.com/','Fuel payment services company','Current official privacy policy explicitly identifies Kropp Holdings as KHI. The official site describes TreviPay as an affiliate and technology partner. Older World Kinect subsidiary records do not establish current ownership; leave ownership unresolved.',[('https://khinc.com/privacy/','November 2025 privacy notice explicitly names Kropp Holdings Inc. and identifies khinc.com.'),('https://khinc.com/about/','Official description identifies aviation and marine payment business and TreviPay affiliate relationship; footer names exact legal entity.')])
add(29,'Kyocera-related lobbying client whose reported name combines Kyocera International and the Kyocera AVX electronic-components business.','https://americas.kyocera.com/','Electronics and industrial components business','Kyocera identifies International Inc. as its US subsidiary and separately lists AVX Components Corporation. The filing says formerly Kyocera AVX, but that legal succession is unverified. Website is the regional Kyocera group site. Do not merge these entities or assign the listed parent stock ticker.',[('https://americas.kyocera.com/careers/kii/why-kyocera/at-a-glance.html','Official profile describes International Inc., its subsidiary relationship and business divisions.'),('https://global.kyocera.com/company/location_gl/region/area/america.html','Official Americas directory lists distinct Kyocera entities.'),('https://lda.gov/filings/public/filing/a0392931-6bcb-4220-9283-a76ca285b2db/print/','Current reported name includes former Kyocera AVX alias.')])
add(34,'Commercial real-estate lobbying client seeking changes involving development incentives, federal properties and investment regulations.','','Real estate organization','Current federal filing establishes property-related advocacy. A Missouri ethics record names L-S Commercial Real Estate Inc. with the same lobbyist Phillip Scaglia in Overland Park, Kansas; exact legal suffix continuity and current official domain remain unverified. Do not match similarly named Canadian or UK firms.',[('https://lda.gov/filings/public/filing/1a9863a9-b45a-43ad-b43c-6a9eeaf479c3/print/','Current filing describes GSA properties, development incentives and SEC issues.'),('https://www.mec.mo.gov/Lobbyist/PrincipalLobbyist.pdf','Historical Missouri principal report lists L-S Commercial Real Estate Inc. and Phillip Scaglia; contextual candidate, not proof of legal continuity.')])
add(35,'Lobbying client describing its business as taxi-hailing and payment systems.','','Taxi technology business','Business description is self-reported. Arbitration sources concern similarly named L1bre Holding LLC, singular Holding, and digital-taximeter investments in Mexico. Exact identity with this plural Holdings LLC is unverified; do not import arbitration ownership or allegations. No current official website verified.',[('https://lda.gov/api/v1/clients/68371/?format=json','Exact client record supplies taxi-hailing and payment-system description.'),('https://lda.gov/filings/public/filing/3cc26b97-5567-4127-b75a-68c2929bfcd9/print/','2026 filing preserves exact client name.')])
add(65,'Lobbying client that describes itself as a real estate consulting company; its 2026 filing concerns federal property management at the General Services Administration.','','Real estate consultancy','Historical registration supplies self-reported business description; current filing confirms federal property advocacy. Independent ownership, current official domain and logo remain unverified. Retain these limits rather than guessing a similarly named property company.',[('https://disclosurespreview.house.gov/data/LD/2020_Registrations_XML.zip','House registration 301227997.xml signed December 22, 2020 supplies self-reported real estate consulting description.'),('https://lda.gov/filings/public/filing/49ae0122-565d-40bb-8bcb-67e310b37cc8/print/','2026 filing concerns GSA federal property management.')])
add(79,'Virginia lobbying client describing its business as management consulting; its 2026 advocacy covers disaster response, aerospace technology and federal research funding.','','Management consultancy','Business description and Virginia location are self-reported in the exact LDA client record. No independent current website or ownership verified. A similarly named federal contractor alone is insufficient to assign identity or a logo; do not infer links to other Langford businesses.',[('https://lda.gov/api/v1/clients/72830/?format=json','Exact client record describes management consulting in Virginia.'),('https://lda.gov/filings/public/filing/ffa53081-10a1-453c-b49d-c76c9afaf1e2/print/','Current filing describes disaster response, aerospace technology and FY27 research appropriations.')])
assert len(e)==100
path.write_text(json.dumps(e,indent=2,ensure_ascii=False)+'\n')
h=r/'latest-handoff.json';d=json.load(open(h));d['round76_incremental_evidence_count']=100;d['round76_remaining_indices']=[];d['round76_next_action']='Finish remaining logo audit, normalize and validate all 100 drafts before integration.';h.write_text(json.dumps(d,indent=2)+'\n');print('Saved 100 evidence drafts')
