import pathlib,json
r=pathlib.Path('work/research-2026');exec((r/'append32b_more.py').read_text())
add(3,'Center for Organ Recovery and Education — on behalf of Donor Alliance','Organ-procurement nonprofit appearing in a lobbying filing on behalf of Donor Alliance, a separate organ and tissue donation nonprofit serving Colorado and most of Wyoming.','https://www.core.org/',kind='Organ procurement nonprofit',own='Nonprofit / tax-exempt',sources=[('https://www.core.org/about-us/','CORE identifies nonprofit organ procurement services.'),('https://www.donoralliance.org/who-we-are/','Donor Alliance identifies its separate nonprofit organ and tissue donation mission.'),('https://lda.gov/filings/public/filing/3ff9ab43-5367-496b-9d67-33e0213a5820/print/','Registration names CORE at Pittsburgh address with Donor Alliance parenthetical.')],notes='Preserves the reported on-behalf-of relationship. It does not establish common ownership or a corporate rename. Website identifies CORE; Donor Alliance website is linked as a source.',outcome='partial')
add(4,'Center for Procurement Advocacy','Advocacy organization focused on federal procurement law, policy and industry engagement.','https://thecpagroup.org/',kind='Procurement advocacy organization',sources=[('https://thecpagroup.org/','Official site describes federal procurement advocacy.'),('https://lda.gov/filings/public/filing/397a4472-60d8-4ac6-8492-fe538d77a9f8/print/','2026 registration/report identifies organization as lobbying client and registrant.')],notes='Exact legal ownership and tax status not verified.')
add(8,'Center for Sportfishing Policy','Membership nonprofit advocating on federal marine recreational fishing and boating policy.','https://sportfishingpolicy.com/',kind='Fishing policy nonprofit',own='Nonprofit / tax-exempt',sources=[('https://sportfishingpolicy.com/about/frequent-questions/','Official FAQ identifies former Center for Coastal Conservation name and 501(c)(4) status.'),('https://sportfishingpolicy.com/about/','Official mission and membership governance.')])
add(9,'Center for Transportation and the Environment','Member-supported nonprofit helping develop and deploy zero-emission vehicles and transportation infrastructure.','https://cte.tv/',kind='Transportation nonprofit',own='Nonprofit / tax-exempt',sources=[('https://cte.tv/mission','Official mission page identifies 501(c)(3) and zero-emission vehicle projects.')])
add(10,'Center Phase Energy LLC','Provides utility restoration, construction coordination and project-management services.','https://centerphaseenergy.com/',sources=[('https://centerphaseenergy.com/','Official company website describes utility services.'),('https://search.sunbiz.org/Inquiry/corporationsearch/SearchResultDetail?aggregateId=forl-m24000009086-c0a5b042-23ed-460f-97a1-b1010c4bc24d&directionType=PreviousList&inquirytype=EntityName&listNameOrder=CENTERPHARMACY+1549480&searchNameOrder=CENTERPHASEENERGY+M240000090860&searchTerm=CENTERPOINT+ONE+CORP.','Florida registry lists Oklahoma LLC and CPE Holdco LLC as member.')],notes='Registry member relationship is documented; full ownership percentages and ultimate ownership not established.',legal='LLC')
add(11,'Center Point Inc.','Lobbying client reporting health and substance-use policy interests; likely associated with the San Rafael social-services nonprofit Center Point.','',kind='Health and social-services client',sources=[('https://www.cpinc.org/about-us-center-point/history-about-center-point/','Candidate nonprofit describes social-service history.'),('https://taggs.hhs.gov/Detail/AwardDetail?arg_AwardNum=H79TI085206&arg_ProgOfficeCode=147','HHS award identifies Center Point Inc at 135 Paul Drive, San Rafael.')],notes='Current 2026 disclosure found across merged filing variants. Exact address linkage between the filing client and candidate nonprofit remains unconfirmed; website and logo withheld. Not assumed to be CenterPoint Energy.',outcome='unresolved')
add(12,'Center Road Solutions LLC','Washington, DC government-relations firm working on legislation, federal funding, regulatory advocacy and coalitions.','https://www.centerroadsolutions.com/',kind='Government relations firm',own='Private company',sources=[('https://www.centerroadsolutions.com/','Official site identifies woman-owned government-relations firm.'),('https://lda.gov/filings/public/filing/65ba63b5-3650-4770-ab32-f32e72267bee/print/','Official filing corroborates firm name and contact domain.')],notes='Woman-owned is the organization’s statement; individual ownership percentages not established.',legal='LLC')
add(13,'Centerra Gold Inc.','Canadian gold and copper mining company with operations and projects in Canada, the United States and Türkiye.','https://www.centerragold.com/',kind='Mining company',own='Publicly traded',sources=[('https://www.centerragold.com/overview/default.aspx','Official corporate overview describes mining activities.'),('https://www.centerragold.com/investor-relations/investor-overview/default.aspx','Official investor page identifies listings TSX: CG and NYSE: CGAU.')],notes='Stock ticker CGAU on NYSE; CG on TSX.',featured=True)
add(14,'Centerstone','Behavioral-health nonprofit providing mental-health, addiction, crisis and related support services.','https://centerstone.org/',kind='Behavioral healthcare nonprofit',own='Nonprofit / tax-exempt',sources=[('https://centerstone.org/about/','Official profile identifies nonprofit behavioral-health services.'),('https://centerstone.org/','Official footer identifies 501(c)(3), EIN 20-0072992.')],notes='System identity; affiliated service entities may have separate legal registrations.')
add(16,'Centinel Public Partnerships LLC','Operates military housing and lodging communities acquired from Lendlease’s United States portfolio.','https://centinelus.com/',kind='Military housing company',own='Private company',sources=[('https://centinelus.com/about/','Official profile describes military housing and lodging.'),('https://centinelus.com/news/leadership-team-with-nearly-25-years-of-experience-acquires-lendlease-groups-military-housing-and-lodging-portfolio-and-launches-new-u-s-based-business/','January 2025 announcement identifies ownership by institutional clients of Guggenheim Partners Investment Management.')],notes='Institutional investment clients are owners as reported; Guggenheim itself is not assumed to own the business outright.',legal='LLC')
assert len(p)==30
(r/'general-round32b-root-draft.json').write_text(json.dumps(p,indent=2)+'\n');print('30 drafts saved; not yet integrated')
