import json,pathlib
r=pathlib.Path('work/research-2026');inputs=json.load(open(r/'general-round2-a-input.json'))[:10];old=json.load(open(r/'general-round2-a-researched.json'));old={v['id']:v for v in old} if isinstance(old,list) else old
spec=[
('ABQ Bernco Water Utility Authority','Public water and wastewater utility serving Albuquerque and Bernalillo County, New Mexico.','Public utility','Government / public entity','https://www.abcwua.org/','https://www.abcwua.org/','Authority website identifies the Albuquerque Bernalillo County Water Utility Authority and its water and wastewater services.'),
('Abra Group Limited','Airline holding group bringing together Avianca and GOL, with an investment in Wamos Air; its airlines carry passengers and cargo across Latin America and international routes.','Airline holding company','Unknown','https://www.abragroup.net/','https://abragroup.net/wp-content/uploads/2026/01/ABRA_Q3-2025-17.12.25-002-002.pdf','Company interim financial statements identify Abra Group Limited and its airline subsidiaries and ownership interests.'),
('AbraWorks Limited','UK technology company developing defense applications in aircraft control, optical sensing, and tactical communications.','Defense technology company','Private company','','https://find-and-update.company-information.service.gov.uk/company/15658591','Companies House identifies active private limited company ABRAWORKS LIMITED, number 15658591, in Toddington, Bedfordshire. Exact disclosed entity link remains partial.'),
('Abridge AI Inc.','Develops AI software that converts clinician-patient conversations into draft clinical notes and billing documentation for healthcare providers.','Healthcare software company','Unknown','https://www.abridge.com/','https://www.abridge.com/about','Official Abridge page describes clinical conversation documentation products for clinicians, nurses, and revenue-cycle teams.'),
('Absolute Software Corporation','Provides cybersecurity software that monitors, repairs, and restores security tools and network access on laptops and other devices. Operates under the Absolute Security brand.','Cybersecurity company','Private company','https://www.absolute.com/','https://www.absolute.com/press-releases/absolute-software-announces-completion-of-acquisition-by-crosspoint-capital-partners','July 2023 completed acquisition release identifies Crosspoint affiliate ownership, delisting, and transition to a privately held company.'),
('Absorbits, Inc. (DRYOUT)','Develops moisture-removal materials and protective storage products for electronics, cameras, firearms, and other equipment under the DRYOUT brand.','Materials and protective equipment company','Unknown','https://www.dryout.com/','https://www.dryout.com/','Official DRYOUT site describes moisture-wicking materials and partnerships to design protective cases, bags, and packs. Disclosed name explicitly includes DBA DRYOUT.'),
('Abt Global','Consulting and technology company helping government agencies evaluate programs, analyze data, and modernize systems in health, housing, environmental policy, and agriculture.','Consulting and technology company','Unknown','https://www.abtglobal.com/','https://www.abtglobal.com/about','Official Abt Global about page describes government consulting and technology services across health, housing, environment, and agriculture.'),
('Abtech Industries','Makes Smart Sponge filtration materials and systems that remove pollutants from stormwater, industrial wastewater, and other contaminated water.','Water treatment manufacturer','Unknown','https://abtechindustries.com/','https://www.abtechindustries.com/water-treatment-products','Official product page describes hydrocarbon, heavy-metal, bacteria, and phosphorus filtration media and stormwater treatment systems.'),
('ABX Air (Air Transport Services Group)','Cargo airline operating Boeing 767 freighters for express-delivery, e-commerce, and government customers; part of Air Transport Services Group.','Cargo airline','Subsidiary of Air Transport Services Group','https://www.abxair.com/','https://www.abxair.com/about','ABX Air official page describes cargo operations and explicitly identifies ATSG as its parent.'),
('Abyss Defense','Disclosed as a defense manufacturer. Its exact current products, ownership, and official website have not been independently established.','Defense manufacturer (self-reported)','Unknown','','https://lobbyingdisclosure.house.gov/lookup.asp?reg_id=35365','House registrant list identifies Abyss Defense as a client of Strategic Marketing Innovations, House client ID 353650579; it does not establish current products or ownership.')]
out={}
for x,s in zip(inputs,spec):
 k=x['id'];v=old[k].copy();name,desc,kind,ownership,website,url,claim=s
 v.update(name=name,description=desc,kind=kind,ownership=ownership,website=website,website_status='partial' if website else 'unresolved',status='sourced' if website or name=='AbraWorks Limited' else 'unresolved',review_outcome='partial' if not website else 'confirmed',identity_evidence=claim,checked_at='2026-09-05',as_of='2026-09-05',featured=name in ['Abridge AI Inc.','Absolute Software Corporation'],notes='Individual source review. Ownership remains unknown where a current primary source does not establish it. Original filing names remain searchable.',logo_url='',logo_kind='',logo_source_url='',logo_status='unresolved')
 v['sources']=x.get('profile',{}).get('sources',[])+[dict(url=url,label='Primary identity and activity evidence',claim=claim)]
 if name=='AbraWorks Limited':v['sources'].append(dict(url='https://uk.linkedin.com/company/abraworks',label='Company-managed profile',claim='AbraWorks describes defense technology research and its Toddington location; legal-company linkage remains partial.'))
 if name=='Abyss Defense':v['review_outcome']='unresolved'
 out[k]=v
(r/'general-round2-root10.json').write_text(json.dumps(out,indent=2)+'\n')
