import json,pathlib
r=pathlib.Path('work/research-2026');p=json.load(open(r/'general-round35a-root-draft.json'));rows=json.load(open(r/'general-round35-a-input.json'))
fix={53:('https://www.cityofhenderson.com/','Official registered .gov landing page redirects visitors to cityofhenderson.com.'),102:('https://www.cityofloganwv.com/','Official city site provides municipal resources and City Hall at 219 Dingess Street, Logan, West Virginia. The loganwv.us local-history website was rejected.'),112:('https://www.lyndenwa.org/','Official city site identifies Lynden, Washington, City Council and City Hall at 300 4th Street.'),115:('https://www.manassasparkva.gov/','Official City of Manassas Park website; the fire-department subpage is not used as the municipality homepage.'),131:('https://monroela.us/','Official City of Monroe, Louisiana site lists its city administration and services; this is distinct from Monroe, Washington.'),145:('https://www.nlauderdale.org/','City municipal agendas and official payment portal identify nlauderdale.org for North Lauderdale, Florida.'),173:('https://www.phl.org/about/about-us','Official airport profile describes Philadelphia International and Northeast Philadelphia airports; City Department of Aviation is separately identified on the airport operations page.')}
for i,(web,claim) in fix.items():
 v=p[rows[i]['id']];v['website']=web;v['sources']=[v['sources'][0],dict(url=web,label='Official organization website',claim=claim)];v['review_outcome']='partial';v['notes']=claim;v['identity_evidence']='Disclosed client scope compared with primary organization evidence. '+claim
v=p[rows[63]['id']];v['ownership']='Nonprofit / tax-exempt';v['name']='City of Hope Medical Center';v['sources']=[v['sources'][0],dict(url='https://www.cityofhope.org/sites/www/files/files/2025-City-of-Hope-Financial-Statements.pdf',label='2025 audited financial statements',claim='Note 1 identifies National Medical Center as a California nonprofit public benefit corporation treating cancer and other life-threatening diseases, with City of Hope as sole corporate member.')];v['notes']='Medical-center identity kept separate from the wider City of Hope group and its other affiliates. This is not a municipality.';v['identity_evidence']='Medical-center filing label compared with Note 1 of the official audited financial statements.'
v=p[rows[173]['id']];v['name']='City of Philadelphia — Department of Aviation';v['description']='City department operating Philadelphia International Airport and Northeast Philadelphia Airport.';v['kind']='Municipal airport system';v['sources'].append(dict(url='https://www.phl.org/newsroom/who-does-what',label='Official airport operations',claim='Airport operations page identifies the City of Philadelphia Department of Aviation as owner and maintainer of airport facilities.'))
for i in [156,157,181,182]:p[rows[i]['id']]['notes']+=' Another preserved filing-name group refers to the same municipality; separate name groups are not necessarily separate governments.'
(r/'general-round35a-root-draft.json').write_text(json.dumps(p,indent=2)+'\n')
s=(r/'check_general34c_final.py').read_text().replace('general-round34c-root-draft','general-round35a-root-draft');(r/'check_general35a_final.py').write_text(s)
