import json,pathlib
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round61-input.json'));d=json.load(open(r/'general-round61-root-draft.json'));f=r/'round61-root-corrections.json';p=json.load(open(f))
def patch(i,desc,u=None,**kw):
 k=rows[i]['id'];v=p.setdefault(k,{});v.update(description=desc,**kw)
 if u:v.update(website=u,sources=d[k]['sources']+[{'url':u,'claim':'Official organization website supports the described activities and identity.'}])
patch(0,'Community-owned utility providing electricity, water, sewer, and natural gas to Greenville and surrounding Pitt County, North Carolina.',notes='Official about page confirms North Carolina charter, public ownership, and services; corrected South Carolina misidentification.',sources=[{'url':'https://www.guc.com/about-us','claim':'GUC identifies Greenville and Pitt County, North Carolina, its community ownership, and four utility services.'}])
patch(1,'Public water utility supplying treated drinking water to the Greenville, South Carolina region.')
patch(2,'Provides aircraft parts sourcing, logistics, and aviation program support for military and civilian customers.','https://greenwood.aero/',notes='Official Greenwood Aerospace site and GSA page identify the aviation supplier; replaced an empty unrelated domain.')
patch(4,'Individual lobbying client reporting conservation work in Mozambique; the exact identity has not been independently established.',ownership='Not applicable',review_outcome='partial')
patch(5,'Investment fund disclosed as Grey Rock Net Zero Opportunities Fund I, LP, reporting private-equity activity; the exact fund structure remains unverified.',ownership='Unknown',review_outcome='partial')
patch(6,'Nonprofit advocating stronger greyhound protections, an end to commercial dog racing, and greyhound rescue and adoption.')
patch(10,'Develops spatial mapping, artificial intelligence, and extended-reality software for industrial manufacturing, maintenance, and defense applications.')
patch(12,'Makes distribution-transformer monitoring equipment and software that help utilities detect grid faults, energy losses, and wildfire risks.')
patch(14,'Develops tools to identify available electrical-grid capacity and accelerate power access for AI data centers.','https://www.gridcare.ai/',notes='Replaced gridcare.com, which returned a parked-domain page.')
patch(16,'Designs and manufactures unmanned aircraft, aerial targets, and ground-support equipment, with flight-engineering services.')
patch(17,'North American shared-services entity within Grifols, a group developing plasma-derived medicines, diagnostics, and healthcare products.')
patch(20,'Helps government customers find, license, and integrate commercial datasets from data vendors.','https://www.gristmillexchange.com/about/')
patch(22,'Provides hardware and cloud services for running trained AI models, including language-model inference.')
patch(23,'Public district operating Grossmont and Cuyamaca community colleges in eastern San Diego County, California.')
patch(25,'Develops and manufactures silicon anode materials used in rechargeable batteries for electric vehicles, electronics, and other applications.')
patch(28,'Florida lobbying client reporting finance activity under the name Grow Valley LLC; its exact operating identity is unresolved.',review_outcome='partial')
patch(29,'Natural-gas utility serving Washington, D.C., and nearby Maryland and Virginia communities, represented in this filing by growth[period].',name='Washington Gas Light Company (represented by growth[period])',ownership='Subsidiary',notes='Official corporate-governance page identifies Washington Gas Light Company as an indirect wholly owned AltaGas subsidiary.',sources=d[rows[29]['id']]['sources']+[{'url':'https://www.washingtongas.com/about/corporate-governance','claim':'Washington Gas Light Company is an indirect wholly owned subsidiary of AltaGas serving Washington DC, Maryland, and Virginia.'}])
patch(31,'Americas entity within Grundfos, a group manufacturing pumps and water-management systems for buildings, industry, and utilities.')
patch(32,'General contractor providing preconstruction planning, construction management, building renovation, and restoration services.','https://grunley.com/')
f.write_text(json.dumps(p,indent=2)+'\n')
