import json,pathlib
r=pathlib.Path('work/research-2026');a=json.load(open(r/'featured98-input.json'));p=json.load(open(r/'featured98-middle-worker-proposals.json'))['records'];out=[]
urls=['https://www.vw.com/en/privacysweeps.html','https://www.volvocars.com/intl/media/press-releases/196E78D5A4E72057/','https://www.commanders.com/team/front-office-roster/','https://www.welchs.com/b2b/about-us/who-we-are/','https://legal.whatnot.com/','https://www.whoop.com/us/en/whoop-terms-of-use/','https://wise.com/about','https://wise.com/help/articles/5toCJQjm9MkTs8bEKSm30O/how-our-us-entity-wise-us-inc-protects-customer-funds/','https://assets.contenthub.wolterskluwer.com/api/public/content/3210406-wolters-kluwer-2025-annual-report-pdf-8bb01b4e47?v=ddef685b','https://ir.wrap.com/news-releases/news-release-details/wrap-technologies-announces-pricing-120-million-registered']
web=['https://www.vw.com/','https://www.volvocars.com/','https://www.commanders.com/','https://www.welchs.com/','https://www.whatnot.com/','https://www.whoop.com/','https://wise.com/','https://wise.com/us/','https://www.wolterskluwer.com/','https://ir.wrap.com/']
kinds=['Automotive company','Automotive manufacturer','Professional football team','Food and beverage company','Live-shopping marketplace','Wearable health technology company','Payments technology brand','Money transfer company','Professional information and software company','Public safety technology company']
own=['Unknown','Subsidiary','Unknown','Subsidiary','Unknown','Unknown','Unknown','Unknown','Public company','Public company']
ev=['Original 2021 and 2025 registrations share automotive activity and exact Washington office at 601 Pennsylvania Ave NW Suite 740, supporting American as a spelling variant of America; official privacy policy supplies exact corporate name.','March 2026 annual-report release explicitly identifies Volvo Car Corporation as the wholly owned subsidiary of Volvo Car AB; parent listing not transferred.','Official team website and front office identify Washington Commanders and Josh Harris as managing partner; brand identity established without inventing a legal suffix.','Official business page explicitly identifies Welch Foods Inc. and farmer ownership through National Grape Co-operative; NCFC member page establishes processing and marketing subsidiary relationship.','Official terms on legal.whatnot.com explicitly identify Whatnot Inc. as operator of the platform and corresponding mobile application.','Official August 3 2026 terms identify Whoop Inc. and its device, application and membership services.','Official about page confirms Wise global money-transfer business; brand-level filing not automatically merged with Wise US Inc. or attributed a parent listing.','Official U.S. entity page explicitly identifies Wise US Inc. and its money-transfer regulatory status; this is not evidence of bank status or a parent stock listing.','2025 annual report describes professional information and software businesses; 2026 AGM agenda refers to ordinary Wolters Kluwer shares trading on Euronext Amsterdam.','August 2026 official investor release explicitly identifies Wrap Technologies Inc., Nasdaq WRAP, and public safety technology business.']
for k,(i,d) in enumerate(zip(a[10:],p)):
 out.append(dict(**i,decision='confirmed',description=d['proposed']['description'],kind=kinds[k],ownership=own[k],website=web[k],official_url=urls[k],evidence=ev[k],sources=[{'url':urls[k],'claim':ev[k]}]))
json.dump(out,open(r/'featured98-middle10.json','w'),indent=2)
