import json,pathlib,gzip
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round25-c-input.json'));p={};e={}
for row in rows:
 k=row['id'];old=row.get('profile') or {};sources=old.get('sources',[])
 if not sources:
  report=json.load(gzip.open(f'lobbying-map/public/data/reports/{k[:2]}.json.gz','rt'))[k][0];sources=[dict(url=f"https://lda.gov/filings/public/filing/{report['id']}/print/",label='Lobbying disclosure',claim='Identifies the disclosed client name.')]
 p[k]=dict(name=row['name'],description='The filing identifies this client; independent exact operating identity remains unresolved.',kind='Unknown',ownership='Unknown',website='',sources=sources,identity_evidence='Exact filing label retained; independent web searches did not establish a current exact-entity website.',review_outcome='partial',notes='Unknown fields remain explicitly unverified.',as_of='2026-09-05',checked_at='2026-09-05',featured=False)
 e[k]=dict(input_name=row['name'],queries=[row['name']+' official website ownership'],sources=[])
def put(k,desc,url,claim,ownership='Unknown',kind='Business',name=None):
 v=p[k];v.update(description=desc,website=url,ownership=ownership,kind=kind,identity_evidence=claim,review_outcome='confirmed' if ownership!='Unknown' else 'partial',notes='')
 if name:v['name']=name
 v['sources'].append(dict(url=url,label='Primary organization evidence',claim=claim));e[k]['sources'].append(url)
put('9c285c9c7810c18a','BP’s U.S. energy business, covering oil and gas production, refining, fuels, retail, and bioenergy.','https://www.bp.com/en_us/united-states/home/who-we-are/what-we-do.html','The official BP America page describes its US operations; the brand is not treated as the listed BP plc issuer.')
put('0a9219ac2537d9fa','Advocates for bipartisan federal policies on economic growth, fiscal policy, energy, and workforce issues.','https://bpcaction.org/about-us/','BPC Action identifies itself as the advocacy partner of the separate Bipartisan Policy Center; exact tax status remains to be verified.',kind='Advocacy organization')
put('871ffc6a73e4f04d','Central institution of the French BPCE banking group, supporting retail banking, insurance, asset management, and investment banking.','https://www.groupebpce.com/en/the-group/organization/','The official group structure states Banques Populaires and Caisses d’Epargne each own 50% of BPCE; those banks are owned by cooperative shareholders.','Cooperative-owned company')
for k in ['0015d81590dd019e','e8ab75ec07a476df']:
 put(k,'Professional association advocating for the careers, working conditions, and welfare of active and retired FBI agents.','https://www.fbiaa.org/','FBIAA’s official site identifies a nonprofit association of active and retired FBI agents; the filing names it as Bracewell’s represented client.','Nonprofit / tax-exempt','Professional association','FBI Agents Association (via Bracewell)')
put('741e020a67268f73','Manufactures residential, commercial, and industrial water-heating, space-heating, and storage products.','https://www.bradfordwhitecorporation.com/careers/','The corporate site identifies Bradford White Corporation and its American-owned water- and space-heating manufacturing business; American-owned does not establish private/public status.')
put('6b1c59a604436324','Develops and commercializes treatments for opioid use disorder.','https://braeburnrx.com/about-us','Braeburn’s official site describes its opioid-use-disorder treatment business; current ownership remains unverified.')
for k in ['073385c505d64f59','52a72ef0194c83c8']:
 put(k,'Provides brain-injury education, support, advocacy, and professional training for patients, families, and care providers.','https://biausa.org/','The official Brain Injury Association of America site identifies its patient support, advocacy, education, and certification programs.',kind='Patient advocacy organization')
put('215bd29ffc828a60','Assesses and promotes practical applications of neuroscience in mental health, learning, and recovery.','https://www.brainfutures.org/about/','BrainFutures describes itself as a national nonprofit launched by the Mental Health Association of Maryland in 2015.','Nonprofit / tax-exempt','Nonprofit')
put('a7778a72cfbd3f5e','Operates reusable pallet and container pooling networks through CHEP to support global supply chains.','https://www.brambles.com/','Brambles’ official results identify CHEP pooling operations; its August 2026 ASX results substantiate listed-company activity.','Unknown')
p['a7778a72cfbd3f5e']['sources'].append(dict(url='https://www.brambles.com/Content/cms/FY26-Results/pdf/Brambles-FY26-Result-ASX-Media-Release.pdf',label='Brambles August 2026 ASX results',claim='Reports Brambles and its CHEP pooling operations and financial results to ASX.'))
put('96d884a883507f54','Outdoor-advertising entity associated with digital signage in Washington, D.C.','https://brandedcities.com/markets/washingtondc/','The group’s official DC market page describes its digital-signage network; DC records separately list Branded Cities DC LLC. Exact subsidiary ownership is unverified.')
put('84c6a04c80a03e12','Holding company with agriculture, industrial, real-estate, entertainment, and hospitality businesses.','https://brandtholdings.com/divisions/','The official Brandt Holdings company site lists its operating divisions and hospitality and equipment businesses.')
put('87d1bcfba2037788','Owns, develops, and manages real estate, with a focus on Philadelphia and Austin.','https://investor.brandywinerealty.com/','The current issuer site identifies Brandywine Realty Trust as publicly traded NYSE: BDN.','Publicly traded','Real estate investment trust')
put('3397f9b7a73ce2e9','U.S. polypropylene producer within the Braskem chemicals group.','https://www.braskem.com.br/imgreen/details-news/braskem-announces-project-to-evaluate-production-of-bio-based-polypropylene','The official Braskem announcement identifies Braskem America as an indirect wholly owned subsidiary headquartered in Philadelphia.','Subsidiary of private or public company')
put('560f31d04d77b810','Makes wheelchair-accessible vehicles, lifts, and other mobility equipment.','https://www.braunability.com/us/en/about-us/our-history.html','BraunAbility’s official history identifies its acquisition by Investor AB and membership in the Patricia Industries portfolio.','Subsidiary of private or public company')
put('fe151e27976c37cc','Defense manufacturer developing warheads for autonomous defense systems.','https://warhead.co/','The official site identifies Bravo Ordnance and its warhead-development business; it is distinct from similarly named firearm manufacturers.')
put('c603b13918326b15','Promotes job creation and business investment in Braxton County, West Virginia.','https://www.braxtoncountywv.com/','The official site identifies Braxton County Development Authority and its Sutton WV office and economic-development mission.',kind='Economic development organization')
put('984f66467e1125a3','Manages water supplies and provides water-quality and wastewater services in Texas’s Brazos River basin.','https://brazos.org/about-us/news/news-room/resource-library/about-the-brazos-river-authority','The authority explicitly identifies itself as a political subdivision of Texas and describes its water-management responsibilities.','Government body','Water authority')
put('32c45b954e95fea3','Provides public transportation services across its Texas service area.','https://www.btd.org/','The official district site identifies Brazos Transit District as a political subdivision of Texas.','Government body','Transit authority')
put('a114663ef7eaef20','Provides mental-health assessment and monitoring services supporting physicians who treat chronic-condition patients.','https://www.bresystem.com/privacy-policy','The official privacy policy names BRE Program Administrative Services LLC; a Senate-hosted company letter describes its physician-support and mental-health assessment program.')
p['a114663ef7eaef20']['sources'].append(dict(url='https://www.finance.senate.gov/imo/media/doc/BRE%20Senate%20Letter-August%202021.pdf',label='Company letter hosted by Senate Finance',claim='BRE describes mental-health testing, evaluation, and ongoing monitoring for chronically ill patients.'))
for k in ['83eb6bb96b4be045','9c8fa1f6ce0bdd61','9efa8056bf0fae61']:
 put(k,'Provides consumer payment, lending, and savings products, including credit-card programs for retail partners.','https://investor.breadfinancial.com/','The current investor site identifies Bread Financial as NYSE: BFH and describes its payment, lending, and saving solutions.','Publicly traded')
for k,d,kind in [('91eb59bb327565b9','Reports real-estate development activity; an exact current operating website has not been established.','Business'),('5fa771287306771e','Land-holding client; government records identify a same-named Chubbuck Mine landowner, but the exact filing-to-entity link remains unresolved.','Business'),('deda3db0c5397ed1','Reports importing cannabis seed genetics; the exact current business website and ownership remain unverified.','Business'),('4ce7471b6472ec51','Individual lobbying client, described as retired in the filing. No company identity is implied.','Individual'),('c5bbb162ef09d6d8','Family listed as a lobbying client; the filing does not establish a distinct company or an exact public-facing identity.','Family'),('9e5b963454692082','Represents Brazilian avocado producers on trade issues, including access to the U.S. market. A current official website remains unverified.','Trade organization')]:
 p[k].update(description=d,kind=kind)
 if kind in ['Individual','Family']:p[k]['ownership']='Not applicable'
p['5fa771287306771e']['sources'].append(dict(url='https://eplanning.blm.gov/public_projects/2034427/200627445/20127681/251027661/Braavos%20ROW%20-%20NEPA%20EA_Jan%202025%20-%20FINAL.pdf',label='BLM environmental assessment',claim='Identifies Braavos LLC and Chubbuck Mine access infrastructure; exact connection to the lobbying client remains to be confirmed.'))
p['9e5b963454692082']['sources'].append(dict(url='https://lda.gov/filings/public/filing/e16c7cdf-e69c-4e48-a3ea-16a3f12ebfe3/print/',label='Commission lobbying disclosure',claim='Discloses advocacy on USDA rules allowing Brazilian avocado imports.'))
(r/'general-round25-c-researched.json').write_text(json.dumps(p,indent=2)+'\n');(r/'general-round25-c-evidence.json').write_text(json.dumps(e,indent=2)+'\n');print(len(p),'root-researched')
