import json,pathlib,gzip
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round32-a-input.json'));p={};s=(r/'research30c_root.py').read_text();exec(s[s.index('def add('):s.index("add(0,'Carbon")])
add(2,'Cempa Community Care','Provides primary care, infectious-disease care, dental services, pharmacy services and behavioral health support.','https://cempa.org/',kind='Community healthcare organization',sources=[('https://cempa.org/who-we-are/','Official site describes community care mission and clinical services.')],notes='Exact tax classification remains unverified; healthcare-service provision alone does not establish it.')
add(3,'CenCal Health','Public health plan administering Medi-Cal benefits through local providers in Santa Barbara and San Luis Obispo counties.','https://www.cencalhealth.org/',kind='Public health plan',own='Government body',sources=[('https://www.cencalhealth.org/explore-cencal-health/','Official profile explicitly identifies public entity and County Organized Health System.')],notes='Public county-organized health system, not a privately owned insurer.')
for i in [4,5]:
 add(i,'Cencora, Inc.','Distributes pharmaceuticals and provides services connecting medicine manufacturers, pharmacies and healthcare providers.','https://www.cencora.com/',own='Publicly traded',sources=[('https://www.cencora.com/about','Official company profile describes pharmaceutical solutions.'),('https://investor.cencora.com/resources/investor-faq/default.aspx','Investor FAQ identifies NYSE: COR and former AmerisourceBergen name.')],notes='Documented AmerisourceBergen-to-Cencora rename; underlying filing labels retained.',featured=True)
add(17,'Center for American Progress Action Fund','Advocacy organization promoting progressive public-policy proposals and public engagement.','https://www.americanprogressaction.org/',kind='Policy advocacy nonprofit',own='Nonprofit / tax-exempt',sources=[('https://www.americanprogressaction.org/capaf-mission/','Official mission identifies 501(c)(4) nonprofit organization.')],notes='Action Fund is distinct from the related Center for American Progress 501(c)(3).')
add(19,'Center for Biological Diversity','Environmental nonprofit using research, litigation and advocacy to protect species and their habitats.','https://www.biologicaldiversity.org/',kind='Environmental nonprofit',own='Nonprofit / tax-exempt',sources=[('https://www.biologicaldiversity.org/about/','Official profile identifies mission and 501(c)(3) status, EIN 27-3943866.')])
add(29,'Center for Law and Social Policy (CLASP)','Policy nonprofit researching and advocating for measures addressing poverty and economic security.','https://www.clasp.org/',kind='Policy research nonprofit',own='Nonprofit / tax-exempt',sources=[('https://www.clasp.org/about/','Official organization profile identifies nonprofit and low-income policy mission.')],notes='Distinct from the unrelated Clasp healthcare staffing business at clasp.com.')
for i in [6,7]:
 add(i,'CenCore' if i==6 else 'CenCore Group','Provides physical security, cleared personnel, secure infrastructure and defense technology services.','https://cencoregroup.com/',sources=[('https://cencoregroup.com/about-cencore/','Official profile describes security, infrastructure and defense services.'),('https://lda.gov/api/v1/clients/'+('66864' if i==6 else '68044')+'/?format=json','LDA identifies Utah security-services client.')],notes='Exact legal relationship between CenCore and CenCore Group filing labels not independently established. Founder titles do not establish ownership.')
add(9,'Cenith Innovations, LLC','Develops defense mission software and navigation technologies, including LiDAR-based positioning systems.','https://www.cenithinnovations.com/',sources=[('https://www.sbir.gov/portfolio/1616419','Federal SBIR portfolio identifies exact Virginia LLC and navigation technology.'),('https://lda.gov/api/v1/clients/71126/?format=json','LDA describes Virginia defense-software client.')],notes='Specific members and ownership percentages not established.',legal='LLC')
add(16,'Centennial Technologies, Inc.','Provides financial-management and information-technology services to federal and commercial customers.','https://www.centennialtechnologies.com/',sources=[('https://www.centennialtechnologies.com/','Official company site describes financial management and IT services.'),('https://lda.gov/api/v1/clients/71470/?format=json','LDA identifies Virginia professional and technical services client.')],notes='Not the similarly named historical computer-memory manufacturer. Current shareholders not established.')

add(8,'Cengage','Provides educational publishing, digital course materials and workforce-learning products.','https://www.cengagegroup.com/',sources=[('https://www.cengagegroup.com/about/what-we-do/','Official group describes higher education, school, workforce and language-learning products.'),('https://www.cengagegroup.com/about/ourhistory/','Current history documents 2026 unified Cengage brand.')],notes='Broad operating brand; exact legal entity and current ownership chain remain unverified.')
add(10,'Cennox, Inc.','Provides ATM, security, technology and facilities services to financial and commercial customers.','https://www.cennox.com/',sources=[('https://www.cennox.com/about-us/','Official group profile describes financial, retail and hospitality services.'),('https://lda.gov/api/v1/clients/68600/?format=json','LDA identifies exact Inc client and ATM-security business.')],notes='Exact Inc ownership chain not established. Historical private-equity investment in the group is not used as current entity ownership proof; group logo held.')
add(11,'Cenovus Energy (filing label)','Oil and natural-gas business associated with Cenovus production, refining and marketing operations.','https://www.cenovus.com/',sources=[('https://www.cenovus.com/Our-company','Official group describes oil and gas production, refining and marketing.'),('https://lda.gov/api/v1/clients/64388/?format=json','LDA identifies broad Cenovus Energy label.')],notes='Exact client is not assumed to be Canadian listed parent Cenovus Energy Inc; separate Cenovus US Corporation label also exists. Parent ticker and logo held pending linkage.')
add(13,'Censys, Inc.','Provides internet-infrastructure intelligence and tools for identifying exposed internet assets and security risks.','https://censys.com/',own='Private company',sources=[('https://censys.com/newsroom/censys-raises-70-million-in-strategic-funding-to-expand-its-internet-intelligence-platform/','March 2026 company announcement describes Series D private financing and internet-intelligence platform.')],notes='Investor participation does not establish individual ownership percentages.')
add(15,'Centene Corporation','Operates health plans and services, including government-sponsored healthcare programs.','https://www.centene.com/',own='Publicly traded',sources=[('https://www.centene.com/who-we-are.html','Official company profile describes healthcare programs.'),('https://www.sec.gov/Archives/edgar/data/1071739/000107173926000049/cnc-20251231.htm','Annual report identifies NYSE: CNC issuer.'),('https://lda.gov/api/v1/clients/64529/?format=json','Filing plural Corporations label reports government-sponsored healthcare.')],notes='Display corrects plural filing label; original name retained. Exact spelling linkage is partial.',outcome='partial',featured=True)
add(18,'Center for Baby and Adult Hygiene Products (BAHP)','Industry association representing makers of diapers, period products and adult incontinence products.','https://www.bahp.com/',kind='Trade association',sources=[('https://www.bahp.com/about-bahp/','Official association profile identifies absorbent hygiene products industry advocacy.')],notes='Exact tax classification not independently established.')
add(20,'Center for BrainHealth','University of Texas at Dallas center conducting neuroscience research and offering brain-health education programs.','https://centerforbrainhealth.org/',kind='University research center',own='Not applicable',sources=[('https://centerforbrainhealth.org/about-us','Official site explicitly identifies center as part of UT Dallas.')],notes='University program rather than independently owned company. Research and training center, not a medical-care provider.')
add(21,'Center for Capital Markets Competitiveness, U.S. Chamber of Commerce','U.S. Chamber program advocating on financial regulation, capital formation and access to business financing.','https://www.uschamber.com/program/center-for-capital-markets-competitiveness',kind='Trade association program',own='Not applicable',sources=[('https://www.uschamber.com/program/center-for-capital-markets-competitiveness','Official Chamber program page identifies mission and leadership.')],notes='Part of the U.S. Chamber, not a separately owned company; parent logo held.')
add(22,'Center for Climate and Energy Solutions (C2ES)','Policy nonprofit conducting research and engaging businesses and policymakers on climate and energy policy.','https://www.c2es.org/',kind='Climate policy nonprofit',own='Nonprofit / tax-exempt',sources=[('https://www.c2es.org/about/','Official profile describes climate and energy policy work.'),('https://www.c2es.org/about/annual-reports-finances-and-management/','Official financials page identifies Delaware 501(c)(3), EIN 54-1892252.')])
add(23,'Center for Educational Innovation','Nonprofit supporting public schools through teacher development, school improvement and student-enrichment programs.','https://the-cei.org/',kind='Education nonprofit',own='Nonprofit / tax-exempt',sources=[('https://the-cei.org/our-history/','Official history documents CEI-PEA merger and return to CEI name in 2015.'),('https://the-cei.org/wp-content/uploads/2020/10/CEI-990-EOY-2019.pdf','Organization tax filing identifies nonprofit corporation, EIN 13-4113613.')],notes='Historical CEI-PEA filing name retained as provenance.')
add(25,'Center for Freedom and Prosperity','Nonprofit advocating limited government, tax competition, financial privacy and market-oriented economic policies.','https://freedomandprosperity.org/',kind='Policy advocacy nonprofit',own='Nonprofit / tax-exempt',sources=[('https://freedomandprosperity.org/about/','Official page distinguishes nonprofit Center from affiliated 501(c)(3) Foundation.')],notes='Exact Center tax subsection not established; Foundation 501(c)(3) status is not assigned to this entity.',outcome='partial')
add(26,'Center for Health and Social Care Integration (CHaSCI)','Rush-based center working on social-care workforce training, healthcare integration, research and policy.','https://www.rush.edu/services/social-work-and-community-health-services/professional-leadership-and-development',kind='Healthcare institution program',own='Not applicable',sources=[('https://www.rush.edu/sites/default/files/media-documents/social-work-annual-report-2024.pdf','Rush annual report describes internal social-care training and policy center.'),('https://www.rushu.rush.edu/faculty/bonnie-ewald','Rush faculty profile identifies applied think tank based at Rush University Medical Center.')],notes='Internal Rush center rather than independently owned corporation. Parent logo held.')
add(27,'Center for Health and Democracy','Advocacy nonprofit promoting patient-focused healthcare reform and examining healthcare industry political influence.','https://www.centerforhealthanddemocracy.org/',kind='Health policy advocacy nonprofit',own='Nonprofit / tax-exempt',sources=[('https://www.centerforhealthanddemocracy.org/about-us','Official profile identifies 501(c)(4) organization and healthcare-reform mission.')],notes='Organization policy positions are attributed to the organization, not presented as neutral findings.')
add(28,'Center for Inquiry, Office of Public Policy','Public-policy arm of the Center for Inquiry advocating on secular government, science and freedom of inquiry.','https://centerforinquiry.org/',kind='Nonprofit advocacy program',own='Not applicable',sources=[('https://progress2016.centerforinquiry.org/','Official report identifies Office of Public Policy lobbying work.'),('https://centerforinquiry.org/wp-content/uploads/2020/09/CFI-Opening-Brief-Walmart.pdf','Organization legal brief identifies nonprofit Center for Inquiry.')],notes='Office is part of Center for Inquiry Inc, not a separate company; organization logo held pending office branding review.')

add(0,'Cement Kiln Recycling Coalition','Industry coalition working on the use of waste-derived fuels and materials in cement kilns and related regulation.','https://www.ckrc.org/',kind='Industry coalition',sources=[('https://www.ckrc.org/wp-content/uploads/2018/09/CKRC-Workshop-April-2018.pdf','Coalition technical workshop documents cement-kiln waste-fuel and regulatory work.')],notes='Historical primary materials establish activity; current tax status and website accessibility need verification. No independent safety claim is made about waste combustion.')

add(1,'CEMEX, Inc.','U.S. building-materials business supplying cement, concrete and related materials.','https://www.cemexusa.com/',own='Subsidiary',sources=[('https://lda.gov/api/v1/clients/64939/?format=json','LDA identifies CEMEX Inc in Texas, not the Mexican listed parent.'),('https://cdn-web.cemex.com/documents/20143/53358271/corporate-structure-20221231.pdf/77111ddd-0c7a-1610-ee61-43c271c39454?t=1676396157485','Official 2022 corporate structure identifies wholly owned U.S. CEMEX Inc.'),('https://www.cemexusa.com/about-us','Official U.S. business profile.')],notes='Subsidiary relationship documented in 2022; precise current chain not independently reverified. Parent NYSE ticker and group logo held.',outcome='partial')
add(12,'Cenovus US Corporation','U.S. entity reporting petroleum-refining activity, associated with Cenovus energy operations.','https://www.cenovus.com/',sources=[('https://lda.gov/api/v1/clients/54506/?format=json','LDA identifies Ohio entity and petroleum refining.'),('https://www.sec.gov/Archives/edgar/data/1475260/000147526026000008/a2025annualinformationform.htm','Parent annual information form describes U.S. refining operations, but does not establish this exact entity chain.')],notes='Exact direct parent and percentage remain unknown. Not assigned Canadian parent stock ticker; group logo held.')
add(14,'Centegix Holdings, LLC','Safety-technology business associated with emergency alerts, campus mapping and incident-response systems.','https://www.centegix.com/',sources=[('https://lda.gov/filings/public/filing/1320ff2a-f1ce-4b44-abbe-f7d4cdcf2bef/print/','Original registration identifies exact Atlanta Holdings LLC.'),('https://www.charlesbank.com/news/charlesbank-capital-partners-invests-in-centegix-provider-of-emergency-response-technology/','2025 investor announcement describes Charlesbank investment with Gauge and management rollover.'),('https://www.centegix.com/','Company site describes emergency-response safety platform.')],notes='Group private-equity backing is documented, but member-level ownership and exact Holdings LLC chain are unverified. Group logo held.',legal='LLC')
add(24,'Center for Employment Training','Nonprofit providing hands-on occupational training and employment support.','https://cetweb.edu/',kind='Career training nonprofit',own='Nonprofit / tax-exempt',sources=[('https://lda.gov/filings/public/filing/1a4b04b6-13d0-4353-987c-39e60bff4806/print/','Original registration gives 701 Vine Street San Jose address, resolving generic-name identity.'),('https://cetweb.edu/locations/san-jose-ca','Official San Jose location matches original filing address.'),('https://pay.cetweb.edu/wp-content/uploads/2023/07/SJ-Student-Catalog-and-Addenda-2023-24-0710.pdf','Official student catalog identifies nonprofit training organization.')],notes='Original filing includes the word and; shared exact San Jose address corroborates identity.')

assert len(p)==30
(r/'general-round32a-root-draft.json').write_text(json.dumps(p,indent=2)+'\n');print(len(p),'drafts saved')
