import pathlib,json,gzip,copy
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round28-b-input.json'));old=json.load(open(r/'reviewed.json'));p={}
def add(i,desc,kind,own,url,claim,source=None,out=None,notes=''):
 x=rows[i];v=dict(id=x['id'],name=x['name'],description=desc,kind=kind,ownership=own,website=url,sources=copy.deepcopy((x.get('profile') or {}).get('sources',[])),identity_evidence=claim,review_outcome=out or ('partial' if own=='Unknown' else 'confirmed'),notes=notes,as_of='2026-09-05',checked_at='2026-09-05',featured=False)
 if source or url:v['sources'].append(dict(url=source or url,label='Organization or primary registry evidence',claim=claim))
 if not v['sources']:
  z=json.load(gzip.open(f"lobbying-map/public/data/reports/{x['id'][:2]}.json.gz",'rt'))[x['id']][0];v['sources']=[dict(url=f"https://lda.gov/filings/public/filing/{z['id']}/print/",label='Original lobbying disclosure',claim='Identifies the disclosed client label.')]
 p[x['id']]=v;return v
add(0,'Caesars-affiliated service entity supporting casino and hospitality businesses.','Business','Unknown','https://www.caesars.com/','Issuer-filed agreement identifies Caesars Enterprise Services LLC; present ownership and operating scope remain unverified.','https://investor.caesars.com/static-files/738efb34-4ba0-4ab9-a5a8-02fc5a810e6a',notes='Historical 2014 agreement; group website, not standalone entity branding.')
add(1,'Develops and owns commercial real estate from a base in McLean, Virginia.','Business','Unknown','https://www.caffertycommercial.com/','Company website identifies its commercial-real-estate development and ownership business and McLean address.')
add(2,'Invests in and develops real estate, with a base in Las Vegas.','Business','Unknown','https://www.caicap.com/','Official company overview identifies the Las Vegas real-estate investment and development firm.','https://www.caicap.com/about/')
add(3,'Provides software and training to help healthcare organizations manage HIPAA compliance and emergency preparedness.','Business','Unknown','https://caiphi.com/','Official CAIPHI site describes its healthcare compliance software and training services.')
add(4,'Public district providing drinking water and wastewater service in Calaveras County, California.','Government','Government body','https://www.ccwd.org/','Official district website identifies Calaveras County Water District and its water and sewer services.')
add(5,'California public online community college offering workforce certificate programs.','College','Government body','https://www.calbright.edu/','Official college website identifies Calbright as a California public community college.')
add(6,'Manufactures, blends, and distributes hydrazine and related chemicals for aerospace and industrial applications.','Business','Subsidiary / affiliated entity','https://calcasolutions.com/','Official Calca site describes its hydrazine business and completed acquisition by NewMarket Corporation.')
add(7,'Parish government providing public services in Calcasieu Parish, Louisiana.','Government','Government body','https://www.calcasieu.gov/','Official parish website identifies the Calcasieu Parish Police Jury and its public services.')
add(8,'Hospital and healthcare provider serving Princeton, Caldwell County, and surrounding Kentucky communities.','Healthcare provider','Unknown','https://caldwellmedical.com/','Official hospital mission page identifies its healthcare services and Princeton, Kentucky address.','https://caldwellmedical.com/about-us/our-mission/')
for i in [9,10]:add(i,'Public port authority operating maritime facilities at Point Comfort, Texas, serving industrial cargo and access to global shipping markets.','Government','Government body','https://www.calhounport.com/','Official port website identifies Calhoun Port Authority and its public maritime facilities.')
add(11,'Provides financial technology, loan-servicing support, payments, compliance, and related services for lending businesses.','Business','Unknown','https://www.caliberfs.com/','Official services page describes lending-related technology, payments, compliance, and customer support.','https://www.caliberfs.com/our-services')
add(12,'Automotive-services holding business associated with Caliber collision repair and auto-glass services.','Business','Unknown','https://www.caliber.com/','Caliber’s website names Caliber Holdings LLC in its legal footer and describes automotive services.',notes='Exact current shareholding remains unverified.')
add(13,'Develops software infrastructure for autonomous defense systems, including TempestOS and the Mission Bay capability platform.','Business','Subsidiary / affiliated entity','https://caliburn.us/','Official mission page describes Caliburn’s 2026 emergence from Fathom5 and identifies Fathom5 as its parent.','https://caliburn.us/mission')
add(14,'Professional association supporting California agricultural commissioners and weights-and-measures officials.','Trade association','Unknown','https://cacasa.org/','Official association website describes its agricultural and regulatory professional membership.')
add(15,'Represents credit unions in California and Nevada through advocacy, education, and industry services.','Trade association','Unknown','https://www.ccul.org/','Official league website describes credit-union advocacy and member services.')
add(16,'Supports local economic-development professionals through advocacy, training, and resources for California communities.','Trade association','Unknown','https://caled.org/','Official association website identifies California Association for Local Economic Development and its professional programs.')
add(17,'Represents marriage and family therapists through professional education, advocacy, and practice resources.','Trade association','Unknown','https://www.camft.org/','Official CAMFT site identifies its professional membership and therapist support programs.')
add(18,'Represents California real-estate professionals through advocacy, education, market information, and professional resources.','Trade association','Unknown','https://www.car.org/','Official California Association of Realtors site describes its real-estate professional membership and services.')
add(19,'Supports California resource conservation districts through advocacy, training, partnerships, and conservation programs.','Nonprofit','Nonprofit / tax-exempt','https://carcd.org/','Official association identifies itself as a nonprofit membership organization supporting resource conservation districts.',notes='Association is distinct from the individual public districts it represents.')
add(20,'Supports California school business officials with training, professional development, and education-finance advocacy.','Trade association','Unknown','https://www.casbo.org/','Official CASBO site describes school-business professional development and advocacy.')
add(21,'Promotes California avocados and supports industry research and market development.','Commodity commission','Government body','https://www.californiaavocado.com/','California Department of Food and Agriculture lists the California Avocado Commission as a state marketing commission and provides its website.','https://www.cdfa.ca.gov/mkt/mkt/BoardCommissionSites.html')
add(22,'Develops dairy-biogas projects that capture methane and produce renewable natural gas.','Business','Unknown','https://www.cabioenergy.com/','Official California Bioenergy site describes dairy methane capture and renewable-natural-gas production.')
add(23,'Municipal government providing public services in California City, California.','Government','Government body','https://www.californiacity-ca.gov/','Official city website identifies California City and its municipal departments.',notes='Separate from the California Avocado Commission; no agricultural-commission branding belongs on this record.')
add(24,'Client reporting representation of California peach growers. Its exact relationship to the cling-peach marketing board or canning-peach association remains unverified.','Trade association','Unknown','','Original disclosure describes a grower trade association; related state marketing-board and bargaining-association names are not assumed identical.',out='partial')
add(25,'Represents California commercial crab-fishing interests through industry advocacy and fisheries-related work.','Trade association','Unknown','https://www.calcoastalcrab.com/','Official association website identifies its coastal crab industry membership and advocacy.')
add(26,'State higher-education office overseeing and supporting California’s community-college system.','Government','Government body','https://www.cccco.edu/','Official Chancellor’s Office website identifies the state community-college system office.')
add(27,'Promotes California dates and supports research and market development for the state’s date industry.','Commodity commission','Government body','https://californiadates.com/','California Department of Food and Agriculture lists the California Date Commission and its official website.','https://www.cdfa.ca.gov/mkt/mkt/BoardCommissionSites.html')
add(28,'State agency managing water resources, flood programs, and the State Water Project in California.','Government','Government body','https://water.ca.gov/','Official Department of Water Resources site identifies its state water-management responsibilities.')
add(29,'Plans a new city and associated housing, industrial, and infrastructure development in Solano County, California.','Business','Unknown','https://californiaforever.com/','Official company page identifies California Forever’s development plans and investors. Exact shareholding remains unverified.','https://californiaforever.com/company/')
for i in [0,5,12,18,23,26,28,29]:p[rows[i]['id']]['featured']=True
assert len(p)==30
(r/'general-round28-b-root-draft.json').write_text(json.dumps(p,indent=2)+'\n')
