from pathlib import Path
p=Path('work/research-2026');s=(p/'research89_root.py').read_text();exec(s[:s.index('add(0,')])
for i,ein,part in [(0,'38-2400330','eo2.csv'),(4,'52-1212849','eo3.csv'),(5,'94-1543185','eo2.csv')]:
 v=d[rows[i]['id']];v.update(ownership='Nonprofit / tax-exempt',review_outcome='confirmed',notes='Exact association/fund matched to IRS exempt-organization master file, EIN '+ein+'.');v['sources'].append({'url':'https://www.irs.gov/pub/irs-soi/'+part,'claim':'IRS master file identifies this organization under EIN '+ein+' as tax-exempt.'})
add(11,'Nanohmics Inc.','Nanohmics develops sensing and measurement technology using electro-optics, computational imaging, electronics and advanced materials.','https://www.nanohmics.com/','Unknown',[('https://www.nanohmics.com/our-approach','Official approach page describes the company’s sensing and measurement engineering, applied science and microfabrication work.')],'Current ownership remains unverified.')
add(12,'NanTrak Industries','NanTrak Industries develops tactical information and sensing technologies; its official site describes tactical-intelligence, outdoor and corporate applications.','https://www.nantrak.com/','Unknown',[('https://www.nantrak.com/','Official site identifies NanTrak Industries LLC with Franklin, Virginia and Wake Forest, North Carolina offices, and tactical and outdoor technology areas.')],'Specific product details and ownership are not established by the limited public site.')
add(13,'NAORE — National Association for Oilheat Research and Education','NAORE is an oil-heating research and education association named in federal hearing records; the lobbying disclosure reports outreach on heating-fuel research and consumer education.','','Unknown',[('https://www.dpc.senate.gov/hearings/hearing31/bios.pdf','Senate hearing biography explicitly expands NAORE as National Association for Oilheat Research and Education.')],'Historic expansion established; current independent website and ownership not verified. Do not substitute the separate National Oilheat Research Alliance (NORA).')
add(14,'Napa County Flood Control and Water Conservation District','The district manages flood protection, stormwater, watersheds and water-supply planning in Napa County, California.','https://www.napacounty.gov/1403/Flood-Control-Water-Conservation-Distric','Government body',[('https://www.napacounty.gov/1403/Flood-Control-Water-Conservation-Distric','County page describes the district’s flood and water-management duties and its board of elected county and municipal officials.')])
add(15,'Napa Valley Transportation Authority','NVTA plans transportation improvements for Napa County and operates Vine Transit bus, shuttle and paratransit services.','https://nvta.ca.gov/','Government body',[('https://nvta.ca.gov/about-nvta/nvta/','Official page identifies NVTA as a joint powers authority created by Napa County and local cities and describes transportation planning and Vine Transit operations.')])
add(18,'NAPEO — National Association of Professional Employer Organizations','NAPEO represents professional employer organizations that provide payroll, benefits, human-resources and regulatory-administration services to businesses.','https://napeo.org/','Unknown',[('https://napeo.org/about/about-napeo/','Official association page describes PEO industry representation, advocacy, events and educational programs.')],'Trade association activity verified; exact tax status pending.')
add(19,'Naper Settlement Museum','Naper Settlement is an outdoor history museum in Naperville, Illinois, with historic buildings, exhibitions and educational demonstrations.','https://napersettlement.org/','Unknown',[('https://napersettlement.org/Visit','Official museum page identifies the Naperville location and outdoor history museum with historic buildings and exhibitions.')],'Current city-versus-historical-society legal management relationship requires verification.')
add(20,'Nara Organics, Inc.','Nara Organics develops and sells whole-milk infant formula.','https://nara.com/','Unknown',[('https://nara.com/pages/nara-organics-faqs','Official brand FAQ identifies Nara Organics, founder Esther and its whole-milk infant formula product.')],'Brand and product established; exact corporate legal ownership not established.')
f.write_text(json.dumps(d,indent=2)+'\n');print('Saved',len(d),'root records')
(p/'round89-checkpoint.json').write_text(json.dumps({'root_saved':len(d),'root_remaining_indices':[i for i in range(25) if rows[i]['id'] not in d],'integrated':False},indent=2)+'\n')
