import json,pathlib
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round38-input.json'));p={}
def add(i,name,desc,web,kind='Company',own='Unknown',source=None,claim=None,notes=''):
 row=rows[i];p[row['id']]=dict(name=name,description=desc,website=web,kind=kind,ownership=own,review_outcome='partial' if own=='Unknown' else 'confirmed',notes=notes or 'Official organization identity and business compared with the disclosed client. Current ownership unknown unless separately sourced.',sources=[dict(url=source or web,claim=claim or desc)])
add(75,'Connecticut Center for Advanced Technology (CCAT)','Nonprofit supporting manufacturing technology adoption, applied research and workforce training.','https://www.ccat.us/','Applied technology nonprofit','Nonprofit / tax-exempt','https://www.ccat.us/news-insights/trak-ccat','Official partnership announcement identifies CCAT as a nonprofit applied technology and training organization.')
add(76,'Connecticut Public Broadcasting','Nonprofit public-media organization operating Connecticut Public television, radio, news and educational services.','https://www.ctpublic.org/','Public media nonprofit','Nonprofit / tax-exempt','https://www.ctpublic.org/about/','Official profile identifies Connecticut Public Broadcasting Inc, doing business as Connecticut Public, as a locally controlled 501(c)(3).')
add(77,'Connections Health Solutions','Operates behavioral-health crisis centers and urgent psychiatric services.','https://connectionshs.com/','Behavioral health provider',source='https://connectionshs.com/about')
add(78,'Conntour, Inc.','Develops AI-powered video intelligence and surveillance search tools for security teams.','https://www.conntour.com/','Security software company',source='https://www.conntour.com/about',notes='Official privacy policy identifies Conntour Inc. Current equity ownership not established.');p[rows[78]['id']]['sources'].append(dict(url='https://www.conntour.com/privacy-policy',claim='Privacy policy identifies the operator as Conntour Inc.'))
add(79,'Conrad Industries, Inc.','Builds, repairs and converts marine vessels, including barges and tugboats, through its shipyard operations.','https://www.conradindustries.com/','Shipbuilding company','Public company','https://www.conradindustries.com/wp-content/uploads/2026/04/03-31-2026-CNRD-Press-Release-2025-Results-and-Backlog-FINAL.pdf','March 2026 issuer announcement identifies Conrad Industries Inc trading OTCID: CNRD and reports its shipbuilding backlog.')
add(80,'Begin (Conscious Content Media, Inc.)','Provides early-childhood learning products and subscriptions through brands including HOMER, codeSpark and Little Passports.','https://www.beginlearning.com/','Education technology company',source='https://www.beginlearning.com/terms-of-use/',claim='Official terms identify Conscious Content Media and its Begin affiliated learning brands.',notes='Company filed Chapter 11 in December 2025. Current post-restructuring ownership not established.');p[rows[80]['id']]['sources'].append(dict(url='https://cases.stretto.com/consciouscontentmedia/',claim='Court-appointed claims site identifies Conscious Content Media Inc and affiliated debtors, their early-learning operations, and December 17, 2025 Chapter 11 filing.'))
add(81,'Consejo Coordinador Empresarial','Umbrella organization representing Mexican business associations and advocating private-sector economic policy.','https://cce.org.mx/','Business federation',source='https://cce.org.mx/acerca-de/',notes='Private-sector representative body, not a Mexican government agency. Specific nonprofit legal status not verified.')
add(82,'Consejo Hondureño de la Empresa Privada (COHEP)','Business federation representing Honduran private-sector organizations on economic and public policy.','https://www.cohep.org/','Business federation','Nonprofit / tax-exempt','https://www.cohep.org/informacion-legal/','Official legal-information page identifies COHEP as a nonprofit institution representing Honduran enterprise.')
add(83,'Consensus Cloud Solutions','Provides cloud fax, document exchange and digital workflow technology, including healthcare communications.','https://www.consensus.com/','Cloud communications company','Public company','https://investor.consensus.com/overview/','Official investor page identifies Consensus Cloud Solutions Inc as Nasdaq: CCSI, independently public since October 2021.')
add(84,'Conservation Coalition','Alabama lobbying client describing advocacy for real-estate investors, land conservation donors and land trusts.','','Land conservation advocacy client',source='https://lda.gov/api/v1/clients/67639/?format=json',claim='Exact Alabama client describes a trade association of real estate investors.',notes='No independent official website or ownership verified. Not assumed to be American Conservation Coalition or Conservation Coalition of Oklahoma.');p[rows[84]['id']]['sources'].append(dict(url='https://lda.gov/api/v1/clients/67342/?format=json',claim='Another same-name Alabama client record describes advocacy for land conservation donors and land trusts.'));p[rows[84]['id']]['review_outcome']='unresolved'
add(85,'Conservation International','Nonprofit working on biodiversity, ocean and land conservation and nature-based climate protection.','https://www.conservation.org/','Conservation nonprofit','Nonprofit / tax-exempt','https://www.conservation.org/docs/default-source/publication-pdfs/conservation-international-foundation_22_fs_final.pdf?sfvrsn=2f0ba5b_3','Audited financial statements identify Conservation International Foundation as exempt under section 501(c)(3).')
add(86,'Conservation Trust of Puerto Rico','Nonprofit conserving ecologically important land and historic sites in Puerto Rico through programs including Para la Naturaleza.','https://www.paralanaturaleza.org/','Conservation nonprofit','Nonprofit / tax-exempt','https://www.drna.pr.gov/historico/oficinas/arn/recursosvivientes/costasreservasrefugios/pmzc/humedales-1/Final%20draft%20PR%20CELCP%20Plan%2010%20Mar10.pdf','Puerto Rico natural resources agency describes the Conservation Trust as a private nonprofit land conservation organization.');p[rows[86]['id']]['sources'].append(dict(url='https://desarrollo.paralanaturaleza.org/es/formas-de-donar/dafs/',claim='Official Para la Naturaleza donation page supplies legal name Puerto Rico Conservation Trust and EIN 66-0288581.'))
add(87,'Conservatives for Property Rights','Coalition advocating protection of physical, personal and intellectual property rights in federal policy.','https://www.property-rts.org/','Policy coalition','Not applicable','https://www.property-rts.org/about-us',notes='Coalition of conservative and libertarian organizations; no separate tax status established.')
add(88,'Conservice Parent LLC','Holding-company client associated with utility billing and management services for property owners and managers.','https://www.conservice.com/','Utility management holding company',source='https://lda.gov/api/v1/clients/53774/?format=json',claim='Exact Utah client describes utility billing and management.',notes='Group domain matches activity; current ownership of this exact Parent LLC remains unknown. A transaction announcement alone does not establish completion or this LLC ownership.')
add(89,'Consolidated Edison Company of New York, Inc.','Regulated utility providing electricity, gas and steam service in New York City and surrounding areas.','https://www.coned.com/','Electric and gas utility','Subsidiary','https://www.sec.gov/Archives/edgar/data/23632/000104786226000031/ed-20251231.htm','2025 annual report states Consolidated Edison Inc owns all common stock of Consolidated Edison Company of New York Inc.',notes='Separate from public parent Consolidated Edison Inc; parent ED ticker is not assigned to the utility subsidiary.')
add(90,'Consolidated Mill Supply, Inc.','Distributes pig iron and sources scrap, direct-reduced iron, alloys and other materials for steel mills and foundries.','https://consolidatedmillsupply.com/','Industrial materials distributor',notes='Palatine, Illinois business; distinct from similarly named equipment supplier Consolidated Mill Supplies.')
add(91,'Conrail (Consolidated Rail Corporation)','Provides freight-rail switching and shared-asset services in the Detroit, New Jersey and Philadelphia areas.','https://conrail.com/','Freight railroad','Subsidiary','https://conrail.com/contact-us/real-estate-contacts/','Official Conrail page identifies its owners as Norfolk Southern and CSX.',notes='Jointly owned railroad; no public-parent stock ticker assigned.')
add(92,'Consolidated Safety Services, Inc.','Provides scientific, environmental, health and safety services for government and commercial clients.','https://www.css-inc.com/','Science and safety services company','Private company','https://www.css-inc.com/company/','Official company profile states CSS became 100% employee-owned through an employee stock ownership plan in 2012.',notes='Employee-owned through an ESOP; no individual ownership percentages claimed.')
add(93,'Consortium of Regional Climate Centers','Lobbying client representing regional climate-center interests.','','Climate research consortium',source='https://lobbyingdisclosure.house.gov/lookup.asp?reg_id=37008',claim='House registrant list identifies Consortium of Regional Climate Centers as an Akerman client.',notes='NOAA describes a Regional Climate Center program, but that alone does not prove the legal identity or ownership of this consortium. No independent consortium domain verified.');p[rows[93]['id']]['review_outcome']='unresolved'
add(94,'Consortium of State Maritime Academies','Joint voice of state maritime academies on maritime education, training and related federal policy.','','Education consortium','Not applicable','https://www.nmc.edu/news/2021/10/Consortium-of-State-Maritime-Academies-letter-10-14-21.pdf','Member academy hosts a joint letter identifying the Consortium and its academy leadership.',notes='Consortium of educational institutions, not the federal Maritime Administration. No separate official website verified.');p[rows[94]['id']]['review_outcome']='partial'
add(95,'Consortium of State School Boards Associations','Alliance sharing resources, training and advocacy support among state school-board associations.','https://www.cossba.org/','Education association','Nonprofit / tax-exempt','https://projects.propublica.org/nonprofits/organizations/882226986','IRS-derived nonprofit record identifies the exact Consortium of State School Boards Associations.');p[rows[95]['id']]['sources'].append(dict(url='https://www.cossba.org/about',claim='Official site identifies the national alliance founded by state school-board associations in 2022.'))
for i in [96,97]:
 add(i,'Constellation Energy','Energy group generating and supplying electricity from nuclear, natural-gas, geothermal and renewable assets.','https://www.constellationenergy.com/','Energy company',source='https://investors.constellationenergy.com/news-releases/news-release-details/constellation-completes-calpine-transaction-powering-americas',claim='January 2026 company announcement confirms the Calpine acquisition and describes the combined generation business.',notes='Short filing name identifies the Constellation energy group but does not uniquely establish whether this client is the public parent or its generation subsidiary. Exact legal ownership classification remains partial.')
for i in [98,99]:
 add(i,'Constellation Energy Generation, LLC','Electricity-generation and energy-supply subsidiary within the Constellation group.','https://www.constellationenergy.com/','Energy generation company','Subsidiary','https://investors.constellationenergy.com/static-files/2eb8d8fa-d637-412d-a3e7-c0b78df3f7ab','2025 combined annual report identifies Constellation Energy Generation LLC and distinguishes it from parent Constellation Energy Corporation, which holds its interests.',notes='Nasdaq CEG belongs to the parent corporation, not this LLC. Original filing parenthetical retained without treating it as independently proved legal rename.')
(r/'round38-root25-evidence.json').write_text(json.dumps(p,indent=2)+'\n')
