import json,pathlib
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round77-input.json'));path=r/'round77-root-incremental-evidence.json';e=json.load(open(path)) if path.exists() else {}
def add(i,name,desc,web,kind,own,notes,sources,featured=False):
 e[rows[i]['id']]={'name':name,'description':desc,'website':web,'kind':kind,'ownership':own,'notes':notes,'sources':[{'url':u,'claim':c} for u,c in sources],'review_outcome':'partial' if own=='Unknown' else 'confirmed','featured':featured}
add(0,'Lassonde Pappas and Company, Inc.','Produces juices, beverages and food products for retailers and food-service customers.','https://lassondepappas.com/','Beverage manufacturer','Subsidiary','Official website identifies Lassonde Pappas & Co., Inc. as a Lassonde Industries subsidiary; do not assign the Canadian parent stock listing to this US entity.',[('https://lassondepappas.com/','Official business description and footer identify exact subsidiary.'),('https://lassondepappas.com/our-heritage/','Company history connects Clement Pappas and Lassonde Pappas names.')])
add(1,'Last Energy, Inc.','Develops modular nuclear power plants intended to supply on-site electricity to industrial customers.','https://www.lastenergy.com/','Nuclear power developer','Unknown','Describe planned reactor development, not an independently verified operating commercial fleet. Exact company website is established by legal notice; current ownership remains unverified.',[('https://www.lastenergy.com/','Official site describes modular reactor and energy-service offering.'),('https://www.lastenergy.com/privacy-terms','Legal notice explicitly names Last Energy Inc. and Washington DC contact address.')])
add(4,'Latino Film Institute','Supports filmmakers and media careers through festivals, youth filmmaking education and professional fellowships.','https://latinofilm.org/','Film education nonprofit','Nonprofit / tax-exempt','Official website identifies 501(c)(3) status and names LALIFF, Youth Cinema Project and fellowships as programs, not separate aliases to merge automatically.',[('https://latinofilm.org/','Official page states nonprofit status and describes programs.')])
add(6,'Lattice Semiconductor','Designs low-power programmable chips used in industrial equipment, vehicles, computers and communications systems.','https://www.latticesemi.com/','Semiconductor company','Public company','Investor FAQ identifies NASDAQ ticker LSCC; exact corporation listing applies to this semiconductor company.',[('https://ir.latticesemi.com/investor-overview/shareholder-services/investor-faqs','Official FAQ describes FPGA business and NASDAQ LSCC listing.')])
add(15,'Lea County, New Mexico','County government serving residents of southeastern New Mexico, with administrative offices in Lovington.','https://www.leacounty.gov/','County government','Government body','Official government site identifies Lea County, New Mexico, its commission, budget and Lovington address.',[('https://www.leacounty.gov/','Official county services, board and contact information.')])
add(19,'Leading Builders of America','Trade association representing large homebuilders in policy debates about housing affordability and residential construction.','https://www.leadingbuildersofamerica.org/','Homebuilding trade association','Not applicable','Membership includes public and private builders; those ownership labels do not describe the association. Separate from its affiliated Building Talent Foundation and political action committee.',[('https://www.leadingbuildersofamerica.org/about/','Official association describes membership, purpose and policy advocacy.')])
path.write_text(json.dumps(e,indent=2)+'\n');print('Saved',len(e))
