import pathlib,json,gzip,copy
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round28-c-input.json'));old=json.load(open(r/'reviewed.json'));p={}
def add(i,desc,kind,own,url,claim,source=None,out=None,notes=''):
 x=rows[i];v=dict(id=x['id'],name=x['name'],description=desc,kind=kind,ownership=own,website=url,sources=copy.deepcopy((x.get('profile') or {}).get('sources',[])),identity_evidence=claim,review_outcome=out or ('partial' if own=='Unknown' else 'confirmed'),notes=notes,as_of='2026-09-05',checked_at='2026-09-05',featured=False)
 if source or url:v['sources'].append(dict(url=source or url,label='Organization or primary registry evidence',claim=claim))
 if not v['sources']:
  z=json.load(gzip.open(f"lobbying-map/public/data/reports/{x['id'][:2]}.json.gz",'rt'))[x['id']][0];v['sources']=[dict(url=f"https://lda.gov/filings/public/filing/{z['id']}/print/",label='Original lobbying disclosure',claim='Identifies the disclosed client label.')]
 p[x['id']]=v;return v
add(0,'Plans a new city and related housing, industrial, and infrastructure development in Solano County, California.','Business','Unknown','https://californiaforever.com/','Company overview describes its development plans and named investors; exact ownership of this LLC remains unverified.','https://californiaforever.com/company/',notes='Company brand website; plans are proposed development, not completed construction.')
add(1,'Supports California Head Start programs through advocacy, training, and resources for early-childhood education providers.','Nonprofit','Nonprofit / tax-exempt','https://www.headstartca.org/','Official site identifies Head Start California as a 501(c)(3) nonprofit; its strategic plan records the former California Head Start Association name.','https://headstartca.org/wp-content/uploads/2023/01/2023-HSC-Strategic-Plan-Overview-Final-2.pdf');p[rows[1]['id']]['name']='Head Start California'
add(2,'State authority planning and building California’s high-speed passenger rail system.','Government','Government body','https://hsr.ca.gov/','Official project overview describes the authority and rail system under development.','https://hsr.ca.gov/project-overview/')
add(3,'Coalition of California’s intercity passenger-rail agencies advocating for rail service and investment.','Government coalition','Not applicable','','Capitol Corridor board materials identify CIRCLE as the advocacy coalition formed in 2021 by California’s three intercity rail authorities.','https://www.capitolcorridor.org/wp-content/uploads/2025/06/June-18-2025-CCJPA-Board-Meeting_Agenda-Notice-Packet_Final.pdf',out='partial',notes='No standalone coalition website established; source is a member public agency.')
add(4,'Administers a food-safety program for California leafy-green handlers, including standards and government audits.','Marketing agreement','Government body','https://lgma.ca.gov/','State marketing-agreement document identifies the California Leafy Green Products Handler Marketing Agreement.','https://www.cdfa.ca.gov/mkt/mkt/pdf/LeafyGreensProductsHandlerMktAgmt.pdf',notes='Industry-funded marketing agreement operating under state oversight; not a produce-growing company.')
add(5,'Represents biotechnology, pharmaceutical, medical-device, and related life-sciences organizations through advocacy and member programs.','Trade association','Unknown','https://www.califesciences.org/','Official overview describes California Life Sciences and its industry advocacy and member services.','https://www.califesciences.org/about-us/')
add(6,'Coalition of California ports, harbors, and maritime interests advocating for navigation projects and marine infrastructure.','Trade association','Unknown','https://cmanc.org/','Official history describes the conference’s port and harbor membership and navigation advocacy.','https://cmanc.org/about-cmanc/')
add(7,'Represents California physicians through health-policy advocacy, legal support, and professional resources.','Trade association','Nonprofit / tax-exempt','https://www.cmadocs.org/','CMA identifies itself as a 501(c)(6) nonprofit membership association.','https://www.cmadocs.org/legal-resources')
add(8,'Provides advanced-materials processing, including spark-plasma sintering, cryogenic milling, and research and pilot-production services.','Business','Unknown','https://www.calnanocorp.com/','Company site describes materials-processing services; issuer page names California Nanotechnologies Corp., while this filing says Inc. Exact legal relationship remains unverified.','https://www.calnanocorp.com/investors',notes='Do not transfer the Canadian Corp. issuer listing to this Inc. entity without subsidiary or legal-continuity evidence.')
add(9,'Cancer treatment center in San Diego providing proton-beam radiation therapy.','Healthcare provider','Unknown','https://www.californiaprotons.com/','Official center site identifies its San Diego location and proton-therapy services.','https://www.californiaprotons.com/why-us/')
cd='https://www.cdfa.ca.gov/mkt/mkt/BoardCommissionSites.html'
add(10,'Promotes California prunes and supports market development and research for the state’s prune industry.','Commodity board','Government body','https://californiaprunes.org/','California Department of Food and Agriculture lists the California Prune Board and links its official website.',cd,notes='Industry-funded state marketing program; not a private prune producer.')
for i in [11,12]:add(i,'California public pension system administering retirement and health benefits for participating public employees, retirees, and their families.','Government','Government body','https://www.calpers.ca.gov/','Original disclosures identify California Public Employees’ Retirement System; its official site provides pension and health-benefit services.')
add(13,'Coalition advocating for small and mid-sized recycling businesses and sustainable recycling practices in California.','Industry coalition','Unknown','https://www.carecyclingalliance.org/','Official site identifies the statewide coalition of recyclers, business leaders, and community advocates.')
add(14,'Produces oil and natural gas in California and develops carbon-management projects.','Business','Publicly traded','https://www.crc.com/','Company’s August 2026 results identify California Resources Corporation as NYSE: CRC.','https://www.crc.com/news-releases/news-release-details/california-resources-corporation-reports-second-quarter-2026')
add(15,'Supports California rice growers and handlers through industry promotion, research, and regulatory and environmental programs.','Commodity commission','Government body','https://calrice.org/','California Department of Food and Agriculture lists the California Rice Commission and links its official website.',cd)
add(16,'Represents California school-board members and provides governance training, policy resources, and public-education advocacy.','Nonprofit','Nonprofit / tax-exempt','https://www.csba.org/','Official overview identifies CSBA as a nonprofit education association representing school districts’ and county education offices’ elected governing officials.','https://www.csba.org/About/AboutCSBA?p=1')
add(17,'Nonprofit health-benefits trust serving California school and other public-sector employees and their families.','Benefits trust','Nonprofit / tax-exempt','https://calveba.org/','CalVEBA identifies itself as a nonprofit, tax-exempt trust providing employee health benefits and wellness programs.','https://calveba.org/help-center/?vd=1');p[rows[17]['id']]['name']='California Schools VEBA (CalVEBA)'
add(18,'Raises funds and helps operate educational exhibits and programs at the California Science Center.','Nonprofit','Nonprofit / tax-exempt','https://californiasciencecenter.org/','Audited financial statements identify the foundation as a California nonprofit corporation supporting and operating programs with the state-owned Science Center.','https://californiasciencecenter.org/sites/default/files/documents/2023-11/CSCF_Audited%20FS_2023-06-30-remediated.pdf',notes='Shared Science Center website; foundation is distinct from the state institution.')
add(19,'Supports California’s commercial sea-urchin industry through research, promotion, and fisheries-related programs.','Commodity commission','Government body','https://calurchin.org/','California Department of Food and Agriculture identifies the Sea Urchin Commission Law and links the commission website.',cd)
add(20,'Represents California counties through policy advocacy, leadership development, and county-government services.','Nonprofit','Nonprofit / tax-exempt','https://www.counties.org/','CSAC identifies itself as a nonprofit corporation governed by elected county supervisors.','https://www.counties.org/about/',notes='Membership corporation, not itself a county government.')
add(21,'State agency funding coastal conservation, habitat restoration, public access, and related climate-resilience projects.','Government','Government body','https://scc.ca.gov/','Official Coastal Conservancy website identifies the state agency and its conservation and public-access programs.')
add(22,'Upper chamber of California’s state legislature, responsible for legislation, budgets, and oversight.','Government','Government body','https://www.senate.ca.gov/','Official California Senate website identifies the legislative chamber, members, committees, and legislative work.')
add(23,'Administers retirement, disability, and survivor benefits for California public-school educators.','Government','Government body','https://www.calstrs.com/','Official CalSTRS website identifies its educator retirement system and benefit programs.')
add(24,'California’s public university system providing undergraduate and graduate education, research, and workforce preparation.','University','Government body','https://www.calstate.edu/','Official CSU overview identifies it as a public university system.','https://www.calstate.edu/csu-system/about-the-csu/facts-about-the-csu/Pages/introduction.aspx')
add(25,'Public university in Sacramento offering undergraduate and graduate degree programs as part of the California State University system.','University','Government body','https://www.csus.edu/','Sacramento State’s catalog identifies its membership in the public California State University system.','https://catalog.csus.edu/csu-system/')
add(26,'Promotes California fresh table grapes and supports market development and industry research.','Commodity commission','Government body','https://www.grapesfromcalifornia.com/','California Department of Food and Agriculture lists the California Table Grape Commission and links its official website.',cd)
add(27,'Markets California as a travel destination through campaigns and partnerships with the tourism industry.','Nonprofit','Nonprofit / tax-exempt','https://www.visitcalifornia.com/','Visit California identifies its legal name as California Travel and Tourism Commission and its status as a 501(c)(6) nonprofit corporation.','https://missions.visitcalifornia.com/about');p[rows[27]['id']]['name']='Visit California (California Travel and Tourism Commission)'
add(28,'Promotes California walnuts internationally and supports market development and nutrition research.','Commodity commission','Government body','https://walnuts.org/','California Department of Food and Agriculture lists California Walnut Commission and links its official website.',cd,notes='Website also serves the California Walnut Board; the two bodies are not silently merged.')
add(29,'Represents California harvesters and processors of squid, sardines, anchovies, and mackerel and supports cooperative fisheries research.','Trade association','Nonprofit / tax-exempt','https://californiawetfish.org/','Official site identifies CWPA as a nonprofit association established in 2004 with voluntary harvester and processor members.')
for i in [0,2,11,12,14,18,23,24,25,27]:p[rows[i]['id']]['featured']=True
assert len(p)==30
(r/'general-round28-c-researched.json').write_text(json.dumps(p,indent=2)+'\n')
(r/'general-round28-c-evidence.json').write_text(json.dumps({k:{'name':v['name'],'sources':v['sources'],'identity_evidence':v['identity_evidence']} for k,v in p.items()},indent=2)+'\n')
