import json,pathlib,gzip
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round32-b-input.json'));p={};s=(r/'research30c_root.py').read_text();helper=s[s.index('def add('):s.index("add(0,'Carbon")];exec((r/'filing_evidence.py').read_text());helper=helper.replace("filing=json.load(gzip.open('lobbying-map/public/data/reports/'+row['id'][:2]+'.json.gz','rt'))[row['id']][0]","filing,filing_member=latest_filing(row)");exec(helper)
for i in [0,1]:
 add(i,'Center for Learner Equity','Advocates for access to public education and better learning opportunities for students with disabilities.','https://www.centerforlearnerequity.org/',kind='Education advocacy organization',sources=[('https://www.centerforlearnerequity.org/who-we-are/our-story/','Official history identifies former National Center for Special Education in Charter Schools name and education mission.')],notes='Documented former-name connection; original truncated filing labels retained. Exact tax classification not yet verified.')
add(2,'Center for Lyme Action','Advocacy nonprofit working to increase federal support for Lyme and other tick-borne disease research and programs.','https://centerforlymeaction.org/',kind='Health policy advocacy nonprofit',own='Nonprofit / tax-exempt',sources=[('https://centerforlymeaction.org/wp-content/uploads/2025/02/CLA-Overview-Flyer_DIGITAL.pdf','Official organization overview identifies 501(c)(4) and federal funding advocacy mission.')])
add(5,'Center for Reproductive Rights','Legal advocacy nonprofit working on reproductive rights through litigation and policy advocacy.','https://reproductiverights.org/',kind='Legal advocacy nonprofit',own='Nonprofit / tax-exempt',sources=[('https://reproductiverights.org/wp-content/uploads/2021/03/Center-for-Reproductive-Rights-2020-Final-FS.pdf','Official audited statements describe nonprofit legal advocacy organization.'),('https://secure.reproductiverights.org/a/join-us','Current official site identifies 501(c)(3), EIN 13-3669731.')])
for i in [6,7]:
 add(i,'Center for Responsible Lending','Research and policy nonprofit advocating against abusive lending practices and for consumer financial protections.','https://www.responsiblelending.org/',kind='Financial policy nonprofit',own='Nonprofit / tax-exempt',sources=[('https://www.self-help.org/who-we-are/self-help-family/center-for-responsible-lending','Self-Help identifies affiliated nonprofit research and policy organization.'),('https://www.responsiblelending.org/about-us/history','Organization history documents establishment by Self-Help in 2002.')],notes='Affiliated with Self-Help; not itself the credit union. Original supporting-corporation filing wording retained.')
add(23,'Central Arizona Shelter Services','Nonprofit providing emergency shelter and support for people experiencing homelessness in metropolitan Phoenix.','https://www.cassaz.org/',kind='Homelessness services nonprofit',own='Nonprofit / tax-exempt',sources=[('https://www.cassaz.org/about-cass','Official profile describes shelter services.'),('https://www.cassaz.org/financials---annual-reports','Official financials page identifies 501(c)(3) charitable organization.')])
add(24,'Central Arizona Water Conservation District','Public district governing the Central Arizona Project water-delivery system.','https://www.cap-az.com/',kind='Public water district',own='Government body',sources=[('https://www.azcleanelections.gov/how-government-works/central-arizona-water-conservation-district','Arizona agency identifies elected special-purpose taxing district.'),('https://www.cap-az.com/finances-of-cap/property-taxes/','Official project site identifies CAWCD as governing entity.')],notes='District is distinct from the federal government that funded construction and from individual water customers.')
add(26,'Central Contra Costa Sanitary District','California public district collecting and treating wastewater in central Contra Costa County.','https://www.centralsan.org/',kind='Public sanitary district',own='Government body',sources=[('https://www.centralsan.org/post/about-us','Official district page identifies public special district and wastewater services.')])
add(29,'Central Nebraska Public Power and Irrigation District','Nebraska public district managing water resources, irrigation and hydroelectric power infrastructure.','https://cnppid.com/',kind='Public power and irrigation district',own='Government body',sources=[('https://cnppid.com/about','Official profile identifies political subdivision of Nebraska organized under public power and irrigation district laws.')])
(r/'general-round32b-root-draft.json').write_text(json.dumps(p,indent=2)+'\n');print(len(p),'drafts saved')
