from pathlib import Path
p=Path('work/research-2026');s=(p/'research89_root.py').read_text();exec(s[:s.index('add(0,')])
add(2,'Nahigian Strategies on behalf of Clarios','This filing names communications firm Nahigian Strategies acting on behalf of Clarios; the intermediary and represented client are preserved together.','https://www.nahigianstrategies.com/','Unknown',[('https://www.nahigianstrategies.com/','Official site identifies Nahigian Strategies and its strategic communications, media and public-relations services.')],'Website belongs to the intermediary, not Clarios; representation comes from the disclosure label.')
add(9,'NanoDx','NanoDx develops a point-of-care diagnostic platform using nanosensors to detect biomarkers in small blood samples.','https://nanodiagnostics.com/','Unknown',[('https://nanodiagnostics.com/','Official NanoDx site identifies its biomarker-detection platform and Southborough, Massachusetts address; it states the system has not been evaluated by the FDA or other regulatory agencies.')],'Development-stage product description; do not imply regulatory clearance. Not the unrelated similarly named Indian company.')
add(16,'Napa Valley Vintners Association','Napa Valley Vintners represents wineries through regional promotion, industry advocacy, member services and stewardship of the Napa Valley wine region.','https://napavintners.com/','Nonprofit / tax-exempt',[('https://napavintners.com/about/','Official About page explicitly identifies Napa Valley Vintners as a nonprofit trade association and describes regional promotion, advocacy and member resources.')])
add(17,'Napatree Technology, LLC','Napatree Technology, LLC reports defense technology as its business in the lobbying disclosure. Its precise current products and ownership remain unverified.','','Unknown',[(x['url'],x['claim']) for x in rows[17].get('profile',{}).get('sources',[])],'Candidate napatreetechnology.com could not be verified. Contractor-directory matches are discovery leads, not proof of current official website.');d[rows[17]['id']]['review_outcome']='unresolved'
add(21,'Nareit — National Association of Real Estate Investment Trusts','Nareit represents real estate investment trusts and related real-estate businesses through policy advocacy, industry research, conferences and education.','https://www.reit.com/','Unknown',[('https://www.reit.com/nareit','Official About page expands Nareit and describes its REIT membership, public-policy advocacy, research, conferences and education.')],'Trade-association activity established; tax status not yet verified.')
add(22,'NASCAR','NASCAR sanctions and organizes stock-car racing series and related motorsports events.','https://www.nascar.com/','Unknown',[('https://www.nascar.com/news-media/2025/02/01/cup-series-2025-bowman-gray-clash-preview/','Official NASCAR coverage identifies its Cup Series stock-car competition and race events.')],'Current legal ownership evidence pending; association in the name is not proof of nonprofit status.')
add(23,'Nasdaq, Inc. (formerly The NASDAQ OMX Group)','Nasdaq operates financial-market infrastructure and provides market technology, data and financial software services.','https://www.nasdaq.com/','Unknown',[('https://ir.nasdaq.com/news-releases/news-release-details/nasdaq-reports-record-quarterly-non-gaap-diluted-earnings-share','Company earnings release documents the legal name change from The NASDAQ OMX Group Inc. to Nasdaq Inc., effective in the third quarter of 2015.')],'Historical name continuity established; current issuer classification requires current corporate evidence.')
add(24,'Nashville Songwriters Association International','NSAI supports songwriters through education, professional development, local chapters and advocacy for songwriters’ interests.','https://www.nashvillesongwriters.com/','Nonprofit / tax-exempt',[('https://www.nashvillesongwriters.com/inside-nsai-chapter','Official NSAI article identifies it as a not-for-profit songwriter trade association and describes chapter-based education and professional support.')])
f.write_text(json.dumps(d,indent=2)+'\n');print('Saved',len(d),'root records')
