import json,pathlib,copy,gzip
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round30-b-input.json'));old=json.load(open(r/'reviewed.json'));p={}
for i,k in {0:'7586b30104f579b9',1:'47dc83eef2babc76',2:'0777610248c84880',8:'b63d75ca4631e02d'}.items():
 row=rows[i];v=copy.deepcopy(old[k]);v['name']+=(' (via Capitol Hill Partners)' if i<2 else ' (via Capitol Venture)' if i==2 else '');v['identity_evidence']='Exact represented organization named in the filing compared with existing researched identity. '+v['identity_evidence'];v['sources']+=row.get('profile',{}).get('sources',[]);v['notes']+=' Research reused after individual identity comparison; reference '+k+'.';p[row['id']]=v
 f=r/f'website-cache/{k}.json'
 if f.exists():
  c=json.load(open(f));c['id']=row['id'];(r/f"website-cache/{row['id']}.json").write_text(json.dumps(c,indent=2))
def add(i,name,desc,web,kind='Company',own='Unknown',sources=[],notes='',legal='',outcome=None,featured=False):
 row=rows[i];filing=json.load(gzip.open('lobbying-map/public/data/reports/'+row['id'][:2]+'.json.gz','rt'))[row['id']][0]
 p[row['id']]=dict(name=name,description=desc,website=web,kind=kind,ownership=own,legal_form=legal,review_outcome=outcome or ('partial' if own=='Unknown' else 'confirmed'),featured=featured,identity_evidence='Disclosed client name and activity compared with the cited primary organization evidence. '+notes,notes=notes,sources=[dict(url='https://lda.gov/filings/public/filing/'+filing['id']+'/print/',label='Original lobbying disclosure',claim='Original client label and report provenance retained; this filing alone does not establish ownership.')]+[dict(url=u,label='Organization evidence',claim=c) for u,c in sources])
add(3,'Meeder Funds (via Capitol Venture)','Family of mutual funds managed within Meeder Investment Management, covering several investment strategies and asset classes.','https://www.meederinvestment.com/meeder-funds-resources/','Investment fund family',sources=[('https://www.meederinvestment.com/meeder-funds-resources/','Official resources list Meeder fund prospectuses and shareholder reports.'),('https://www.sec.gov/Archives/edgar/data/702435/0001752724-24-277739-index.htm','SEC identifies Meeder Funds, CIK 702435, including the government money-market fund.')],notes='Fund family is distinct from its investment adviser and distributor; no company ownership classification is inferred.')
add(4,'Othram, Inc. (via Capitol Venture)','Provides forensic DNA sequencing and genetic-genealogy services to help identify people and investigate unresolved cases.','https://othram.com/',sources=[('https://othram.com/solve','Official site describes forensic laboratory and investigative services.'),('https://othram.com/request/terms_of_use','Terms identify Othram, Inc. as a Delaware corporation.'),('https://fsc.txcourts.gov/AccreditedLabPublic/AccreditedLabDetailsPublic/133','Texas forensic regulator lists the Othram laboratory and official website.')],legal='Corporation',notes='Operating identity established; current equity ownership unknown.')
add(5,'Verkada Inc. (via Capitol Venture)','Develops cloud-managed physical-security systems including cameras, access control, alarms, intercoms, and visitor-management software.','https://www.verkada.com/',own='Private company',sources=[('https://www.verkada.com/about/','Official company profile describes security products and private funding.'),('https://www.verkada.com/ca/blog/our-new-valuation-dec-2025/','December 2025 company announcement describes an investment led by CapitalG.')],notes='Original intermediary label spells LLS; retained in aliases.',featured=True)
add(6,'Capricor','Develops cell and exosome-based therapies for rare diseases.','https://www.capricor.com/',sources=[('https://www.capricor.com/investors','Official profile identifies Capricor Therapeutics, NASDAQ: CAPR, and its biotechnology programs.')],notes='The abbreviated client label does not establish whether the legal client is Capricor Therapeutics or its similarly named operating subsidiary; issuer ticker is not assigned to this unresolved legal identity.')
add(7,'Capstone Mining','Copper-mining business that became part of Capstone Copper through the 2022 combination with Mantos Copper.','https://capstonecopper.com/',own='Subsidiary',sources=[('https://capstonecopper.com/news/capstone-mining-and-mantos-copper-complete-combination-to-create-capstone-copper/','Company announcement states old Capstone became a wholly owned subsidiary of Capstone Copper in March 2022.')],notes='Historical client name retained; parent branding is not assigned as an exact subsidiary logo.',outcome='partial')
add(9,'Capstone USA Advisory Group LLC','Consulting firm that reports supporting Ukrainian businesses participating in reconstruction of Ukraine.','','Consulting firm',sources=[('https://lda.gov/api/v1/clients/63848/?format=json','Exact client record supplies the Ukrainian reconstruction consulting description.')],notes='Activity is self-reported; no independently verified official website or exact LLC ownership. Do not substitute similarly named Capstone consultancies.',outcome='unresolved')
add(10,'Captial Funding Group Inc (filing label)','Long-running lobbying client reported under the spelling “Captial Funding Group Inc”; the precise organization behind that label remains unresolved.','','Unknown',sources=[('https://www.capfundinc.com/','Capital Funding Group is a plausible similarly spelled healthcare and multifamily finance company; linkage to this filing label is not established.')],notes='Possible spelling correction to Capital Funding Group is held pending exact address or legal-identity linkage; candidate site is evidence only.',outcome='unresolved')
add(11,'Captive Insurance Companies Association','Membership association providing education, networking, and advocacy for captive-insurance and risk-management professionals.','https://www.cicaworld.com/','Trade association','Not applicable',sources=[('https://www.cicaworld.com/join-cica/','Official membership page describes captive insurance and risk-management membership classes.')],notes='Association rather than an insurer; no specific tax subsection inferred from membership alone.')
add(12,'Captura Biopharma','Develops oral chelator drug candidates intended to remove internal radionuclide contamination and certain heavy metals.','https://www.capturabiopharma.com/',sources=[('https://www.capturabiopharma.com/background/','Company background describes its oral C2E2 chelator development.'),('https://www.sec.gov/Archives/edgar/data/1846809/000110465922088367/tm2223054d1_ex99-1.htm','SEC-hosted announcement identifies Captura Biopharma, Inc. and its oral-chelator business.')],notes='Separate from Captura Corp ocean-carbon technology; development is not a claim of regulatory approval.',legal='Corporation')
add(13,'Captura Corp.','Develops electrodialysis systems that remove carbon dioxide from seawater, including direct-ocean-capture pilot technology.','https://capturacorp.com/',own='Private company',sources=[('https://capturacorp.com/','Official site identifies Captura Corp, its ocean-carbon technology, and June 2026 Series B financing.'),('https://netl.doe.gov/projects/project-information.aspx?p=FE0032416','DOE project identifies Captura Corp as direct-ocean-capture developer.')],notes='Separate from Captura Biopharma; pilot and commercial-development status are not evidence of fully scaled deployment.')
add(14,'CapturePoint Solutions','Develops carbon capture and underground carbon-storage projects.','https://capturepointllc.com/',own='Private company',sources=[('https://capturepointllc.com/sites/default/files/BiaEnergypressrelease_4824.pdf','Company release identifies CapturePoint LLC and CapturePoint Solutions LLC as privately held.'),('https://capturepointllc.com/about','Official site describes the related companies and carbon-management business.')],notes='Shared company site; exact CapturePoint Solutions branding must be distinguished from CapturePoint LLC.',legal='LLC')
add(15,'Caracol, Inc.','Supplies large-format robotic additive-manufacturing equipment for polymer, composite, and metal parts.','https://www.caracol-am.com/',sources=[('https://www.caracol-am.com/wp-content/uploads/2024/05/PR_Caracol-Impac-Systems-Engineering-Partnership-2024_EN.pdf','Company release names Caracol Inc. in the US additive-manufacturing business.'),('https://www.caracol-am.com/','Official group site describes robotic additive manufacturing systems.')],notes='Exact US operating entity is supported; current ownership chain to the Italian group is not established, and parent asset is held.')
add(16,'Elastic (via Carahsoft)','Develops search, observability, and cybersecurity software built around Elasticsearch.','https://www.elastic.co/',own='Publicly traded',sources=[('https://www.carahsoft.com/elastic','Carahsoft describes its partnership with Elastic and its search, security and observability offerings.'),('https://ir.elastic.co/overview/default.aspx?LanguageId=1','Official investor relations identifies NYSE: ESTC.')],notes='Elastic is the represented business; Carahsoft is the intermediary. Listed issuer is Elastic N.V.',featured=True)
add(17,'Carba Inc.','Develops reactors that convert waste biomass into biocarbon for industrial uses and carbon-storage projects.','https://carba.com/',sources=[('https://carba.com/','Official site describes biomass-to-biocarbon reactors and storage applications.'),('https://mncifa.mn.gov/sites/default/files/2026-04/2026-02_MnCIFA%20Carba%20landfill%20CO2%20sequestration.pdf','Minnesota climate-finance authority identifies Carba, Inc. and its landfill biomass-sequestration project.')],notes='Business identity established; ownership unknown. Company durability claims are not independently endorsed.')
add(18,'Carbice Corporation','Manufactures carbon-nanotube thermal-interface materials for cooling electronics and other high-performance equipment.','https://carbice.com/',own='Private company',sources=[('https://carbice.com/company/about-us','Official history identifies Carbice Corporation and its seed and Series A financing.'),('https://carbice.com/','Official site describes thermal-interface products and identifies the Atlanta corporation.')])
add(19,'Carbon180','Nonprofit advocating for policies and programs that advance carbon dioxide removal.','https://carbon180.org/','Climate nonprofit','Nonprofit / tax-exempt',sources=[('https://carbon180.org/','Official site identifies Carbon180 as a nonprofit and describes carbon-removal policy work.')])
for i in [20,21]:add(i,'Carbon Capture Impact','Advocates for federal policies supporting carbon-management technologies and projects.','https://carboncaptureimpact.org/','Advocacy nonprofit','Nonprofit / tax-exempt',sources=[('https://carboncaptureimpact.org/','Official site describes federal carbon-management advocacy.'),('https://carboncapturecoalition.org/wp-content/uploads/2025/11/Carbon-Capture-Impact_Organizational-Principles.pdf','Organizational principles identify Carbon Capture Impact as a 501(c)(4) affiliated with the Carbon Capture Coalition.')],notes='Separate organization from the affiliated Carbon Capture Coalition; both client-name variants retained.')
add(22,'Carbon County, Wyoming','County government serving Carbon County, Wyoming, including public records, elections, roads, and local administration.','https://carboncountywy.gov/','County government','Government body',sources=[('https://carboncountywy.gov/','Official county website identifies Wyoming government services and offices.')])
add(23,'Carbon Engineering ULC','Develops direct-air-capture technology that removes carbon dioxide from ambient air.','https://www.carbonengineering.com/',own='Subsidiary',sources=[('https://www.carbonengineering.com/','Official site describes direct-air-capture research and identifies Carbon Engineering ULC in its legal footer.'),('https://occidentalpetroleum.gcs-web.com/static-files/bf53af81-d4c6-450a-aec0-00b3dde53543','Occidental annual report lists Carbon Engineering ULC as a British Columbia subsidiary.')],notes='Subsidiary relationship sourced; prior Ltd. name remains in the filing alias.',legal='Unlimited liability company')
add(24,'Carbon GeoCapture Corp','Develops carbon capture and underground storage projects using coal formations.','https://carbongeocapture.com/',sources=[('https://carbongeocapture.com/','Official company site describes carbon storage using coal seams.'),('https://www.sec.gov/Archives/edgar/data/2034583/000203458324000002/xslFormDX01/primary_doc.xml','SEC Form D identifies Carbon GeoCapture Corp as a Wyoming issuer, CIK 2034583.')],notes='Issuer identity established; Form D roles do not establish ownership shares.',legal='Corporation')
add(25,'Carbon Management Alliance (formerly Energy Advance Center)','Industry association advocating for carbon capture, utilization, and storage policy.','','Industry association','Unknown',sources=[('https://downloads.regulations.gov/IRS-2019-0026-0092/attachment_2.pdf','2019 signed Energy Advance Center submission describes a voluntary association supporting CCUS and lists member companies.')],notes='Rename is reported in the filing label. Historical primary-source activity is established; current standalone website, legal status, and governance unresolved. Do not use the unrelated German Carbon Management Alliance website.')
add(26,'Carbon Removal Alliance','Nonprofit bringing together carbon-removal developers and buyers to advocate for permanent carbon-removal policy.','https://www.carbonremovalalliance.org/','Industry nonprofit','Nonprofit / tax-exempt',sources=[('https://www.carbonremovalalliance.org/','Official site identifies a public nonprofit convening companies and advocating carbon-removal policy.')])
add(27,'Vaulted Deep (Carbon Removal Co., Inc.)','Processes organic waste into slurries for underground geological storage as a carbon-removal service.','https://vaulteddeep.com/',sources=[('https://www.energy.gov/hgeo/carbon-dioxide-removal-purchase-pilot-prize-phase-1-semifinalists','DOE identifies Vaulted Deep as a provider of geological storage of slurried organic waste.'),('https://cms2.revize.com/revize/winfield/2025-08-04%20Agenda.pdf','Municipal contract identifies Carbon Removal Co., Inc. doing business as Vaulted Deep.'),('https://vaulteddeep.com/payment/','Official site describes biomass geological storage carbon-removal units.')],notes='DBA identity supported by a municipal contract; current ownership remains unknown.')
add(28,'Carbon SiC Technologies, Inc.','Develops carbon-carbon and carbon-ceramic materials, including lightweight brake rotors.','https://www.carbonsic.com/',sources=[('https://www.carbonsic.com/capabilities','Official site describes carbon-ceramic and carbon-carbon brake rotor capabilities.'),('https://inl.gov/feature-story/big-brake-for-small-business-sintering-tech-could-make-rotors-90-cheaper-and-faster/','Idaho National Laboratory identifies Carbon SiC Technologies Inc. and its ceramic-brake development.')],notes='Founder identity is documented but current equity ownership is not.',legal='Corporation')
add(29,'Carbon Solutions Group','Develops distributed clean-energy projects and manages solar renewable-energy certificates, EV-charging infrastructure, and environmental assets.','https://www.carbonsolutionsgroup.com/',sources=[('https://www.carbonsolutionsgroup.com/about/','Official company history describes solar aggregation, EV-charging development and environmental services.')],notes='Business and brand established; current ownership unknown.')
assert len(p)==30
(r/'general-round30b-root-draft.json').write_text(json.dumps(p,indent=2)+'\n')
s=(r/'check_general30a.py').read_text().replace('30a','30b');(r/'check_general30b.py').write_text(s)
print('30 source-backed drafts')
