import pathlib,json,gzip,copy
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round29-a-input.json'));p={}
def add(i,desc,kind,own,url,claim,source=None,notes=''):
 x=rows[i];v=dict(id=x['id'],name=x['name'],description=desc,kind=kind,ownership=own,website=url,sources=copy.deepcopy((x.get('profile') or {}).get('sources',[])),identity_evidence=claim,review_outcome='partial' if own=='Unknown' else 'confirmed',notes=notes,as_of='2026-09-05',checked_at='2026-09-05',featured=False)
 v['sources'].append(dict(url=source or url,label='Organization or primary registry evidence',claim=claim));p[x['id']]=v;return v
add(0,'Represents credit unions in California and Nevada through advocacy, regulatory support, training, and member services.','Trade association','Unknown','https://www.californiascreditunions.org/','Official league overview identifies both state credit-union trade associations and their joint working relationship.','https://www.californiascreditunions.org/about/who-we-are/',notes='Joint league label in the disclosure; do not treat every credit union member as this organization.')
add(1,'Alaska Native regional corporation managing land, resources, and diversified businesses for shareholders from the Yukon-Kuskokwim region.','Alaska Native corporation','Shareholder-owned Alaska Native corporation','https://www.calistacorp.com/','Official regional history identifies Calista as a for-profit regional corporation established under ANCSA.','https://www.calistacorp.com/about-us/region/',notes='Alaska Native shareholder corporation; not a tribal government.');p[rows[1]['id']]['name']='Calista Corporation'
add(2,'Generates electricity from natural-gas and geothermal power plants and supplies energy to wholesale and retail customers.','Business','Subsidiary','https://www.calpine.com/','Constellation states its acquisition of Calpine closed on January 7, 2026.','https://www.constellationenergy.com/news/2026/01/constellation-completes-calpine-transaction-powering-americas-clean-energy-future.html',notes='Owned by Constellation following the completed 2026 acquisition; historical Energy Capital Partners ownership is not current.')
add(3,'Produces and distributes cement, concrete, aggregates, asphalt, and related construction materials.','Business','Subsidiary','https://www.calportland.com/','Taiheiyo Cement’s 2025 report states Taiheiyo Cement USA owns 100% of CalPortland Company.','https://www.taiheiyo-cement.co.jp/english/csr/pdf/data/2025/Taiheiyo-Cement-rep2025en_a4.pdf',notes='Indirect subsidiary of Taiheiyo Cement; not itself the listed Japanese issuer.');p[rows[3]['id']]['name']='CalPortland Company'
add(4,'Produces cement, ready-mixed concrete, aggregates, and other construction materials under the CalPortland brand.','Business','Unknown','https://www.calportland.com/','Official CalPortland overview matches the disclosed construction-materials business; exact Corporation versus Company legal-name relationship remains unverified.','https://www.calportland.com/about/',notes='Group website; do not silently merge this legal-name variant with CalPortland Company.')
add(5,'Works with businesses and public agencies to develop and adopt cleaner vehicles, fuels, and transportation technologies.','Nonprofit','Nonprofit / tax-exempt','https://calstart.org/','CALSTART identifies itself as a national nonprofit and describes technology development, evaluation, market programs, and policy work.','https://calstart.org/about/');p[rows[5]['id']]['name']='CALSTART'
add(6,'Restores California rivers and watersheds and advocates for policies protecting wild fish and healthy freshwater habitats.','Nonprofit','Nonprofit / tax-exempt','https://caltrout.org/','Official overview identifies California Trout as a 501(c)(3) nonprofit and describes fish and watershed conservation.','https://caltrout.org/who-we-are/');p[rows[6]['id']]['name']='California Trout (CalTrout)'
add(7,'Manufactures printed circuit boards and advanced electronic substrates for defense, aerospace, medical, and industrial applications.','Business','Unknown','https://www.calumetelectronics.com/','Official product overview identifies the Michigan electronics manufacturer and its printed-circuit-board production.','https://www.calumetelectronics.com/home/',notes='American ownership does not by itself establish public versus private ownership.')
add(8,'Preserves and interprets the natural, industrial, labor, and cultural heritage of the Calumet region of Illinois and Indiana.','Nonprofit','Nonprofit / tax-exempt','https://calumetheritage.org/','Organization’s grant announcement identifies CHP as a 501(c)(3) nonprofit and states its regional heritage mission.','https://calumetheritage.org/calumet-heritage-partnership-receives-a-grant-to-document-the-underground-railroad-through-northwest-indiana/')
add(9,'Manufactures specialty petroleum products, branded consumer and industrial products, and renewable fuels.','Business','Publicly traded','https://calumet.investorroom.com/','Official investor site identifies Calumet, Inc. as NASDAQ: CLMT and describes its specialty products and renewable fuels.',notes='Investor-relations website; distinct from Calumet Electronics.')
add(10,'Local recreation and park district operating Calwa Park and community recreation programs in the Fresno area.','Government','Government body','https://www.calwarecreation.org/','Official district site identifies its public board, resolutions, facilities, and Fresno address.');p[rows[10]['id']]['name']='Calwa Recreation and Park District'
add(11,'Develops medical devices for removing kidney-stone fragments, including the CVAC aspiration system used by urologists.','Business','Unknown','https://calyxoinc.com/','Company financing announcement identifies Calyxo, Inc. and its kidney-stone treatment devices.','https://calyxoinc.com/wp-content/uploads/2023/12/PressReleaseSeriesD-Draft08-FINAL-2.pdf',notes='Venture financing is documented; current exact ownership remains unverified.')
add(12,'Represents businesses in Puerto Rico through commercial advocacy, networking, and economic-development programs.','Trade association','Unknown','https://www.camarapr.org/','Chamber’s official membership portal identifies the Puerto Rico Chamber of Commerce and describes programs connecting member businesses.','https://camarapr.wildapricot.org/Default.aspx');p[rows[12]['id']]['name']='Cámara de Comercio de Puerto Rico'
add(13,'Represents Paraguay’s beef, pork, and poultry businesses and promotes domestic and international markets for Paraguayan meat.','Trade association','Nonprofit / tax-exempt','https://www.cpc.org.py/','Official history identifies the chamber as a civil nonprofit trade organization established in Asunción in 1998.','https://www.cpc.org.py/nosotros/');p[rows[13]['id']]['name']='Cámara Paraguaya de Carnes'
add(14,'Provides medical billing and revenue-cycle software that helps healthcare providers submit claims, manage denials, and track reimbursements.','Business','Unknown','https://www.camber.health/','Official Camber website describes healthcare billing automation and claims management, matching the disclosed revenue-cycle business.','https://www.camber.health/terms-of-service',notes='Not Camber Mental Health, the unrelated clinical-care organization.')
for i in [15,16]:add(i,'Operates health plans and healthcare services, including the Regence family of regional health insurers.','Nonprofit','Nonprofit / tax-exempt','https://www.cambiahealth.com/','Cambia’s official homepage describes it as a not-for-profit healthcare and technology company.',notes='Nonprofit status does not mean all operations are tax-exempt; Cambia describes itself as a tax-paying nonprofit.');p[rows[i]['id']]['name']='Cambia Health Solutions'
for i in [17,18]:add(i,'Develops advanced materials for extreme conditions, including thermal protection, high-temperature structures, and directed-energy protection.','Business','Unknown','https://www.cambium-usa.com/','Official site’s footer identifies Cambium Biomaterials, Inc. and describes advanced-materials products.',notes='Not Cambium Learning, Cambium Bio, or the similarly named wood-products company.');p[rows[i]['id']]['name']='Cambium Biomaterials (Cambium)'
add(19,'Provides education technology, digital curricula, assessments, and instructional services for schools and learners.','Business','Private company','https://www.cambiumlearning.com/','Company announced its completed sale to Veritas Capital affiliates in December 2018.','https://www.cambiumlearning.com/about-us/news/5536/veritas-capital-completes-acquisition-of-cambium-learning-group',notes='Historical take-private transaction documented; current ownership percentages are not disclosed here.')
add(20,'Manufactures engineered quartz surfaces for countertops and other residential and commercial interiors.','Business','Private company','https://www.cambriausa.com/','Official Cambria FAQ identifies the business as a family-owned American quartz-surfaces company.','https://www.cambriausa.com/quartz-countertops/faq/about-cambria',notes='Exact LLC identity is checked against the company legal terms; the raw filing’s broad Mining description obscures its quartz-products business.')
add(21,'Analyzes driving data from mobile devices and connected sensors for road safety, insurance, and fleet programs.','Business','Unknown','https://www.cmtelematics.com/','Official company history identifies CMT’s MIT origins and mobile telematics products.','https://www.cmtelematics.com/who-we-are/')
add(22,'Produces uranium and supplies nuclear-fuel products and services for nuclear power generation.','Business','Publicly traded','https://www.cameco.com/','Official investor page identifies Cameco Corporation as TSX: CCO and NYSE: CCJ.','https://www.cameco.com/invest/stock-information')
add(23,'Supplies and develops automotive batteries and energy-storage products as part of the Camel battery group.','Business','Subsidiary','https://www.camelenergyus.com/','US Court of International Trade decision identifies Camel Energy as a Camel Group subsidiary and refers to Camel Energy Inc. documentation.','https://www.cit.uscourts.gov/sites/cit/files/26-95.pdf',notes='US subsidiary, not the parent company’s listed shares.')
add(24,'Governing body of Cameron County, Texas, overseeing county administration, budgets, infrastructure, and local public services.','Government','Government body','https://www.cameroncountytx.gov/','Official county administrator page identifies the Commissioners’ Court as the county governing authority.','https://www.cameroncountytx.gov/county-administrator/');p[rows[24]['id']]['name']='Cameron County Commissioners Court'
add(25,'Independent community hospital and healthcare system serving Steuben County, Indiana, and nearby communities.','Healthcare provider','Nonprofit / tax-exempt','https://www.cameronmch.com/','Official hospital overview identifies Cameron as an independent, not-for-profit healthcare system.','https://cameronmch.com/about/')
add(26,'Parish governing body providing local administration and public services in Cameron Parish, Louisiana.','Government','Government body','https://cameronpj.org/','Official parish site identifies the Police Jury and publishes its public meetings and parish services.',notes='Police jury is Louisiana’s parish governing body; not merely a police department.')
add(27,'Develops AI and machine-intelligence software for defense missions, including air and missile defense and counter-drone operations.','Business','Private company','https://www.camgian.com/','Official overview describes defense AI products and identifies recognition among fast-growing private companies.','https://www.camgian.com/about/',notes='Founder and management roles do not establish individual equity percentages.')
add(28,'Coalition advocating for US international-assistance programs and their links to American farming, manufacturing, and jobs.','Advocacy coalition','Unknown','https://www.americafirstintl.org/','Official campaign website names CAFIA and describes its farmer, manufacturer, supplier, community, and faith-group coalition.',notes='Advocacy claims are the coalition’s stated positions; funding and legal tax status remain unverified.')
add(29,'Coalition advocating for independent family farms and policy changes affecting industrial livestock operations, rural communities, and the environment.','Advocacy coalition','Unknown','https://fightfactoryfarms.org/','Official website identifies the Campaign for Family Farms and the Environment and lists its six member organizations.',notes='Coalition members remain separate organizations; no standalone tax status established.')
for i in [1,2,3,9,15,16,19,20,22]:p[rows[i]['id']]['featured']=True
assert len(p)==30
(r/'general-round29a-root-draft.json').write_text(json.dumps(p,indent=2)+'\n')
