import json,pathlib
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round35-b-input.json'));p={}
def add(i,name,desc,web='',own='Unknown',kind='Company',sources=[],notes='',outcome='partial'):
 row=rows[i];p[row['id']]=dict(name=name,description=desc,website=web,ownership=own,kind=kind,sources=row.get('profile',{}).get('sources',[])+[dict(url=u,claim=c) for u,c in sources],notes=notes,review_outcome=outcome)
add(138,'Clear Blue Enterprises Ltd. (Hong Kong filing)','Hong Kong-listed lobbying client describing its business as consulting.',notes='Exact legal organization and official website remain unresolved. Rejected unrelated clearblue.com and Florida LLC matches.',outcome='unresolved')
add(146,'Clearwater Channels, LLC','North Carolina lobbying client reporting dredging services.',notes='Exact identity and current official website not independently established; activity is self-reported.',outcome='unresolved')
add(157,'Cleveland LD, LLC','Real-estate development entity identified in Cleveland city records as Bedrock, planning and financing development along the Cuyahoga riverfront and Tower City.',sources=[('https://cityofcleveland.legistar.com/View.ashx?GUID=20788B59-A3E4-4CC4-A83D-1998A8341D6D&ID=12147402&M=F','Cleveland Ordinance 787-2023 names Cleveland LD LLC as Bedrock and authorizes a riverfront development and finance agreement.')],notes='Public record establishes project identity and Bedrock connection, not precise current equity ownership; no parent logo assigned.')
add(178,'Cloud Computing Technologies (Castillo Technologies)','Provides cloud computing, cybersecurity and AI consulting to federal agencies, defense contractors and businesses.','https://cloudcomputingtechnologies.ai/',own='Private company',sources=[('https://cloudcomputingtechnologies.ai/press/castillo-technologies-awarded-a-mda-shield-idiq-contract/','Official announcement names Castillo Technologies LLC doing business as Cloud Computing Technologies and identifies a service-disabled veteran-owned small business in Chandler, Arizona.')],notes='Arizona locality and defense/cloud services align with the original filing. Contract vehicle award does not mean the entire program ceiling was awarded to this firm.',outcome='confirmed')
add(180,'CloudFactors LLC','Provides Microsoft cloud, device, cybersecurity and compliance services for federal agencies and government contractors.','https://www.cloudfactors.com/',sources=[('https://lda.gov/filings/public/filing/2dbc48fe-3e1f-4734-bc69-7627415467bc/print/','2026 self-filing identifies CloudFactors LLC in Orlando and a cloudfactors.com business email domain.'),('https://www.linkedin.com/company/cloudfactors-llc','Company-maintained profile describes Microsoft cloud and device services and matches the Orlando filing address.')],notes='Official domain corroborated but homepage access failed; ownership not independently established.')
add(182,'Clover Aquisition Group (filing spelling)','Texas lobbying client describing its business as an aviation group.',notes='Original misspelling preserved as an alias; no unique acquisition company or website independently established.',outcome='unresolved')
add(184,'Clovia BV (Belgium filing)','Belgium-listed lobbying client describing advisory and consulting services.',notes='Same-name Belgian registry candidate was found but exact connection to this filer remains unproven. No unrelated consumer-brand website assigned.',outcome='unresolved')
add(185,'County Line Rail (via CLR Fund I, LP)','Operates short-line railroads, railcar storage, switching and industrial rail facilities along the Texas Gulf Coast.','https://www.clrail.com/',own='Private company',sources=[('https://www.clrail.com/company-history','Official company history describes the Texas Gulf Coast rail network and Houston offices.'),('https://www.clrail.com/news','May 7, 2026 company announcement identifies County Line Rail as privately held.'),('https://dcms-external.s3.amazonaws.com/DCMS_External_PROD/1768596149866/310752.pdf','Surface Transportation Board filing identifies County Line Rail Fund I LP alongside CLIP Property Owner and Sabine River & Northern Railroad.')],notes='Represented railroad business identified; exact abbreviated fund-name legal linkage remains partial.')
add(187,'CM Consortium LLC','New York lobbying client reporting investments in critical minerals.',notes='No unique independently verified organization website or ownership established. Same-name academic consortia rejected.',outcome='unresolved')
add(189,'CMBRC Services, LLC','Texas lobbying client reporting operation of an EB-5 investment regional center.',notes='Exact connection to similarly named regional-center groups remains unverified; no group website or logo assigned.',outcome='unresolved')
add(190,'CMC Pharmaceuticals, Inc.','Provides drug formulation, analytical testing, stability evaluation and pharmaceutical product-development services.','https://www.cmcpharm.com/',sources=[('https://www.cmcpharm.com/contact-us/','Official site identifies CMC Pharmaceuticals Inc at 30625 Solon Road, Solon, Ohio and describes formulation, analytical, stability and regulatory services.')],notes='Ohio address and drug-formulation activity align with filing; ownership unknown.')
add(193,'CMH Services, Inc. (Clayton)','Clayton housing-group entity associated with manufactured-home construction and related services.','https://www.claytonhomes.com/',own='Subsidiary',sources=[('https://portal.cmhrichfield.com/legal','Clayton portal legal policy directs privacy matters to CMH Services at 5000 Clayton Road, Maryville, Tennessee.'),('https://icc.illinois.gov/downloads/public/filing/2/15/16/372847.pdf','Government-hosted 2024 affiliate list identifies CMH Services Inc within the Clayton/Berkshire group.')],notes='Housing activity and Tennessee location match; distinct from same-name Ohio computer-services and South Carolina forklift businesses. Group website linked; historical affiliate evidence does not prove unchanged current ownership percentages.')
(r/'round35b-root-exceptions.json').write_text(json.dumps(p,indent=2)+'\n');print(len(p),'root researched exceptions')
