import pathlib,json,gzip,copy
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round26-c-input.json'));old=json.load(open(r/'reviewed.json'));p={}
def add(i,desc,kind,own,url,claim,source=None,out=None,notes=''):
 x=rows[i];v=dict(id=x['id'],name=x['name'],description=desc,kind=kind,ownership=own,website=url,sources=copy.deepcopy((x.get('profile') or {}).get('sources',[])),identity_evidence=claim,review_outcome=out or ('partial' if own=='Unknown' else 'confirmed'),notes=notes,as_of='2026-09-05',checked_at='2026-09-05',featured=False)
 if source or url:v['sources'].append(dict(url=source or url,label='Organization or primary registry evidence',claim=claim))
 if not v['sources']:
  z=json.load(gzip.open(f"lobbying-map/public/data/reports/{x['id'][:2]}.json.gz",'rt'))[x['id']][0];v['sources']=[dict(url=f"https://lda.gov/filings/public/filing/{z['id']}/print/",label='Original lobbying disclosure',claim='Identifies the disclosed client label.')]
 p[x['id']]=v;return v
add(0,'Makes water-filter pitchers, dispensers, bottles, and replacement filters for consumers. This California filing matches the North American Brita brand.','Business','Subsidiary / affiliated entity','https://www.brita.com/','Clorox’s 2026 SEC report lists Brita water-filtration products among its brands; LDA client is in California.','https://www.sec.gov/Archives/edgar/data/21076/000002107626000034/clx-20260630.htm',notes='North American brand associated with Clorox; do not substitute the separate German Brita ownership.')
add(1,'Develops cloud software and modernizes case-management systems for government agencies and other organizations.','Business','Unknown','https://www.britesys.com/','Company white paper identifies Brite Systems Inc., its Indianapolis address, and Salesforce-based public-sector modernization work.','https://www.britesys.com/wp-content/uploads/2025/11/APS-whitepaper-v03.pdf')
x=rows[2];v=copy.deepcopy(old['47dc83eef2babc76']);v.update(id=x['id'],name='Britebound');v['sources']+=(x.get('profile') or {}).get('sources',[]);p[x['id']]=v
add(3,'Operates international and domestic passenger flights, with a major hub at London Heathrow.','Business','Subsidiary / affiliated entity','https://www.britishairways.com/','British Airways identifies IAG as its parent company.','https://mediacentre.britishairways.com/factsheet/details/9')
add(4,'Designs, installs, and operates broadband networks, telephone systems, and IT infrastructure for government and commercial customers.','Business','Private company','https://broadbandconnectllc.com/','Official site identifies a veteran-owned business and Maryland office, matching the LDA state and telecommunications activity.',notes='Company self-identifies as veteran owned; individual equity percentages not established.')
add(5,'Licenses public performances of music and distributes royalties to songwriters, composers, and music publishers.','Business','Private company','https://www.bmi.com/','BMI announced the closing of New Mountain Capital’s majority investment on February 8, 2024.','https://www.bmi.com/news/new-mountain-capital-announces-the-closing-of-its-majority-growth-investment-in-bmi')
for i in [6,7]:add(i,'Designs and supplies semiconductors and infrastructure software for networking, data centers, enterprise computing, and other technology systems.','Business','Publicly traded','https://www.broadcom.com/','September 2026 issuer results identify Broadcom Inc. as NASDAQ: AVGO and describe semiconductor and infrastructure software operations.','https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial')
add(8,'Semiconductor and infrastructure-software business recorded under the historical Broadcom Limited name.','Business','Unknown','https://www.broadcom.com/','Current issuer is Broadcom Inc., NASDAQ: AVGO; the exact legal continuity of this older Limited label is held unresolved.','https://investors.broadcom.com/restricted-partnership-units',notes='Do not treat the historical Singapore entity as the current Delaware issuer without resolving the filing relationship.')
add(9,'Missouri lobbying client reporting business-development activity. A same-named real-estate partnership appears in SEC records, but the precise connection remains unverified.','Business','Unknown','','SS&C’s 2025 annual-report note describes Broadway Square Partners LLP as a 50%-owned real-estate joint venture; this is a candidate match rather than established filing identity.','https://www.sec.gov/Archives/edgar/data/1402436/000119312526076745/R17.htm')
add(10,'Advocates on mortgage policy for independent mortgage brokers and homebuyers.','Advocacy organization','Nonprofit / tax-exempt','https://brokeractioncoalition.com/','The organization identifies itself as an independent 501(c)(4) nonprofit representing mortgage brokers.','https://brokeractioncoalition.com/about-the-bac')
add(11,'Financial-industry coalition participating in advocacy about retirement advice and fiduciary regulation. Its membership and standalone legal structure remain unverified.','Industry coalition','Unknown','','The coalition signed a joint financial-industry letter about the Department of Labor retirement-advice rule.','https://www.irionline.org/wp-content/uploads/2024/05/Senate-JT-CRA-Support-Letter-FINAL-WITH-SIGNATORIES-05-14-2024.pdf')
add(12,'Funds programs improving the welfare of working horses, donkeys, and mules and supporting the people who depend on them.','Nonprofit','Nonprofit / tax-exempt','https://www.brookeusa.org/','Brooke USA’s mission and published audited statements identify its equine-welfare programs and nonprofit status.','https://brookeusa.squarespace.com/s/2023-Brooke-USA-Financial-Statements-5124-FINAL.pdf')
for i in [13,14]:add(i,'Brookfield-affiliated U.S. renewable-power asset-management and lobbying record.','Business','Subsidiary / affiliated entity' if i==13 else 'Unknown','https://bep.brookfield.com/','Brookfield Renewable’s CDP response identifies Brookfield Power US Asset Management LLC as an affiliate submitting U.S. lobbying reports.','https://bep.brookfield.com/sites/bep-brookfield-ir/files/Brookfield-BEP-IR-V2/2025/cdp-response-brookfield-renewable-partners-l-p.pdf',out='partial',notes='Group website. The second US in the disclosed label is retained; exact legal-name variant is not silently merged.')
add(15,'Manages and operates Brookhaven National Laboratory for the U.S. Department of Energy.','Research operator','Joint venture','https://www.bnl.gov/about/bsa.php','The laboratory identifies BSA as a partnership of Battelle and the SUNY Research Foundation on behalf of Stony Brook University.')
add(16,'Municipal government providing local services in Brookhaven, Georgia.','Government','Government body','https://www.brookhavenga.gov/','Official city website identifies Brookhaven, Georgia, its council, police, parks, and municipal services.')
add(17,'Membership organization supporting Brooklyn businesses through advocacy, networking, and economic-development programs.','Trade association','Unknown','https://www.brooklynchamber.com/','Official chamber site identifies the Brooklyn business membership organization; exact tax classification still requires verification.')
add(18,'Redevelops the former Brooks Air Force Base in San Antonio for housing, employment, and other economic activity.','Government','Government body','https://livebrooks.com/','Official financial statements identify BDA as a special-purpose Texas political subdivision created by San Antonio.','https://livebrooks.com/wp-content/uploads/2022/03/FINAL-BDA-Audit-Report-2021.pdf')
add(19,'Labor union representing locomotive engineers and train-service workers.','Labor union','Not applicable','https://ble-t.org/','Union history identifies BLET and its 2004 merger with the International Brotherhood of Teamsters.','https://ble-t.org/history/')
add(20,'Labor union representing workers who construct, inspect, maintain, and repair railroad tracks and related infrastructure.','Labor union','Not applicable','https://www.bmwe.org/','Official union website identifies the Brotherhood of Maintenance of Way Employes Division of the International Brotherhood of Teamsters.')
add(21,'Labor union representing workers who install, inspect, maintain, and repair railroad signaling and communications systems.','Labor union','Not applicable','https://www.brs.org/','Official union site identifies BRS and the rail-signal and communications workers it represents.','https://www.brs.org/index.cfm?page=About20the20BRS2022E0&zone=%2Funionactive%2Fview_page.cfm')
add(22,'Raises philanthropic support for Broward College scholarships, educational programs, and student success.','Nonprofit','Unknown','https://www.browardcollegefoundation.org/','Official foundation and college advancement site describes its fundraising role; exact tax status is pending source verification.')
for i in [23,24]:add(i,'County government providing public services in Broward County, Florida, including transportation, libraries, parks, and infrastructure.','Government','Government body','https://www.broward.org/','Official Broward County government website identifies county services, commission, and Fort Lauderdale government center.')
add(25,'Coordinates regional transportation planning and investment priorities for Broward County, Florida.','Government','Government body','https://www.browardmpo.org/','Official MPO site identifies transportation planning programs and the Broward MPO public agency.')
add(26,'Provides law enforcement, detention, fire rescue, and related public-safety services in Broward County, Florida.','Government','Government body','https://www.sheriff.org/','Original filing identifies the Broward Sheriff’s Office; official public-agency website provides its services.',out='partial')
add(27,'Operates hospitals, physician practices, and other healthcare services in Rhode Island and nearby communities. Formerly named Lifespan.','Nonprofit','Nonprofit / tax-exempt','https://www.brownhealth.org/','Brown University Health describes itself and its affiliates as a not-for-profit healthcare organization.','https://www.brownhealth.org/about/community-affairs')
add(28,'Produces and markets alcoholic beverages, including Jack Daniel’s whiskey and other spirits brands.','Business','Publicly traded','https://www.brown-forman.com/','Official investor page identifies Brown-Forman Corporation as NYSE: BF.B.','https://investors.brown-forman.com/investors/overview/default.aspx')
x=rows[29];v=copy.deepcopy(old['83e820e3dfbc10c7']);v.update(id=x['id'],name='Apollo Global Management (via Brownstein)',notes=v.get('notes','')+' This filing identifies Brownstein as representative; website and business description refer to Apollo.');v['sources']+=(x.get('profile') or {}).get('sources',[]);p[x['id']]=v
assert len(p)==30
(r/'general-round26-c-researched.json').write_text(json.dumps(p,indent=2)+'\n')
(r/'general-round26-c-evidence.json').write_text(json.dumps({k:{'name':v['name'],'sources':v['sources'],'identity_evidence':v['identity_evidence']} for k,v in p.items()},indent=2)+'\n')
