import pathlib,json,gzip,copy
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round27-c-input.json'));old=json.load(open(r/'reviewed.json'));p={}
def add(i,desc,kind,own,url,claim,source=None,out=None,notes=''):
 x=rows[i];v=dict(id=x['id'],name=x['name'],description=desc,kind=kind,ownership=own,website=url,sources=copy.deepcopy((x.get('profile') or {}).get('sources',[])),identity_evidence=claim,review_outcome=out or ('partial' if own=='Unknown' else 'confirmed'),notes=notes,as_of='2026-09-05',checked_at='2026-09-05',featured=False)
 if source or url:v['sources'].append(dict(url=source or url,label='Organization or primary registry evidence',claim=claim))
 if not v['sources']:
  z=json.load(gzip.open(f"lobbying-map/public/data/reports/{x['id'][:2]}.json.gz",'rt'))[x['id']][0];v['sources']=[dict(url=f"https://lda.gov/filings/public/filing/{z['id']}/print/",label='Original lobbying disclosure',claim='Identifies the disclosed client label.')]
 p[x['id']]=v;return v
add(0,'Makes canned baked beans and other bean products sold under the Bush’s brand.','Business','Private company','https://www.bushbeans.com/','Bush’s identifies itself as family owned; its privacy policy names Bush Brothers & Company.','https://www.bushbeans.com/en_US/bean-hub/article/white-beans-101')
p[rows[0]['id']]['sources'].append(dict(url='https://www.bushbeans.com/en_US/privacy-policy',label='Company legal identity',claim='Privacy policy identifies Bush Brothers & Company.'))
add(1,'Advocates for businesses in southeastern North Carolina on economic development, infrastructure, and public policy.','Trade association','Nonprofit / tax-exempt','https://ncbase.org/','BASE identifies itself as a 501(c)(6) nonprofit serving New Hanover, Brunswick, Pender, and Onslow counties.','https://ncbase.org/base-facts/')
add(2,'Represents energy-efficiency, natural-gas, and renewable-energy businesses in advocacy for clean-energy policies.','Trade association','Unknown','https://bcse.org/','Council’s official overview describes its energy-industry membership and policy advocacy.','https://bcse.org/about-bcse/')
add(3,'Represents leaders of major Canadian businesses in economic and public-policy advocacy.','Trade association','Nonprofit / tax-exempt','https://www.thebusinesscouncil.ca/','Council describes itself as a nonprofit, nonpartisan organization of Canadian business leaders.','https://www.thebusinesscouncil.ca/publication/joint-policy-priorities/')
add(4,'Provides small-business loans, coaching, and classes, with a focus on underserved entrepreneurs in the Pacific Northwest and Alaska.','Nonprofit','Nonprofit / tax-exempt','https://businessimpactnw.org/','Organization identifies itself as a nonprofit community development financial institution.','https://businessimpactnw.org/about-us/')
for i in [5,6]:add(i,'Association of chief executives of major U.S. companies advocating on economic, tax, trade, workforce, and other business policies.','Trade association','Unknown','https://www.businessroundtable.org/','Official overview identifies the association of chief executives of leading U.S. companies.','https://www.businessroundtable.org/about-us?stream=top')
add(7,'Represents enterprise-software companies on technology policy and promotes software licensing compliance and asset management.','Trade association','Unknown','https://www.bsa.org/','Official overview identifies Business Software Alliance as the enterprise-software industry’s global trade association.','https://www.bsa.org/about-bsa')
add(8,'U.S. holding entity in the Busy Bees childcare group, whose North American businesses operate daycare and preschool centers.','Business','Subsidiary / affiliated entity','https://www.busybeesna.com/','Eagle Holdco annual report lists Busy Bees US Holdings Limited as a wholly owned U.S. holding-company subsidiary.','https://www.tisegroup.com/umbraco/surface/proxyapi/newspdf?id=304760&index=0',out='partial',notes='Group website; exact holding entity has no separately verified public-facing brand.')
add(9,'Coordinates regional transportation planning and public transit for Butte County and its incorporated cities in California.','Government','Government body','https://www.bcag.org/','Official site identifies BCAG as a joint powers authority between Butte County and five incorporated municipalities.')
add(10,'County government providing public services in Butte County, California.','Government','Government body','https://www.buttecounty.ca.gov/','Official county website identifies the board of supervisors, departments, and public services.')
add(11,'Lobbying client that reports healthcare activity. Its precise business, ownership, and official website remain unverified.','Business','Unknown','','Original lobbying disclosure reports healthcare activity; no independent official website was established.',out='partial')
add(12,'Florida real-estate limited liability company. Its precise property operations and ownership remain unverified.','Business','Unknown','','Florida registry identifies active BW Arbour Apartments LLC, document L14000077792; listed managers are not treated as owners.','https://search.sunbiz.org/Inquiry/CorporationSearch/SearchResultDetail?aggregateId=flal-l14000077792-b82c407c-07e4-46e3-8372-a5b9d3bc1710&directionType=CurrentList&inquirytype=EntityName&listNameOrder=BWAPARTMENTS+K092830&searchNameOrder=BWARBOURAPARTMENTS+L140000777920&searchTerm=BWA+CORPORATION')
v=add(13,'Operates Drifters Riverfront Bar and Grill, a restaurant on the St. Johns River in Astor, Florida.','Business','Unknown','https://www.driftersriverfront.com/','Florida restaurant license identifies BWI of Central Florida Inc as the licensee for Drifters Riverfront Bar and Grill at 55716 Front Street, matching the restaurant website.','https://www.myfloridalicense.com/portalsearches/VerifyLicensee/LicenseDetail?ID=4BE4CC25BC2008D1CBE4F534C97FE70C');v['name']='Drifters Riverfront Bar and Grill (BWI of Central Florida)'
v['sources'].append(dict(url=v['website'],label='Restaurant website',claim='Restaurant identifies its Astor location and 55716 Front Street address.'))
add(14,'Manufactures nuclear components and provides nuclear technology and services for government and commercial customers.','Business','Publicly traded','https://www.bwxt.com/','Company’s July 2026 acquisition announcement identifies BWX Technologies as NYSE: BWXT and describes its nuclear manufacturing business.','https://investors.bwxt.com/news-releases/news-release-details/bwxt-completes-acquisition-precision-components-group-expanding')
for i in [15,16]:add(i,'Provides IT systems, cybersecurity, and training and simulation technology for government and commercial customers.','Business','Unknown','https://bylight.com/','Official company overview describes By Light’s IT, cyberspace, and simulation operations; exact present ownership remains unverified.','https://bylight.com/about/',notes='The LLC and Inc. filing labels remain separately traceable; legal continuity has not been silently assumed.')
add(17,'Runs Christian after-school programs in Chicago supporting children’s academic work, health, and broader development.','Nonprofit','Nonprofit / tax-exempt','https://bythehand.org/','Official website identifies By The Hand Club For Kids as a 501(c)(3) organization and describes its after-school programs.','https://bythehand.org/')
add(18,'U.S. BYD business involved in electric vehicles and energy-storage technology. This filing also refers to multiple U.S. subsidiaries.','Business','Unknown','https://en.byd.com/','BYD’s U.S. contact page identifies BYD Motors LLC in Pasadena; the full set of entities covered by the filing and exact ownership remain unverified.','https://en.byd.com/energy/contact/',notes='Not labeled publicly traded merely because BYD’s overseas parent is an issuer.')
add(19,'Develops electric aircraft for flight training, including the eFlyer program.','Business','Unknown','https://byeaerospace.com/','Official site describes the eFlyer electric training-aircraft development program; this does not establish completed aircraft certification.')
add(20,'Infant-formula manufacturer operating under the ByHeart brand.','Business','Unknown','https://byheart.com/','Company website identifies the infant-formula business and its June 2026 update on work toward resuming production.',notes='Website reports a return-to-market process following recall; current production resumption is not asserted.')
add(21,'Public water district serving agricultural and municipal customers in parts of Alameda, Contra Costa, and San Joaquin counties, California.','Government','Government body','https://bbid.org/','Official district website identifies Byron Bethany as a multi-county special district providing agricultural and municipal water.')
add(22,'Internet-technology company recorded under the ByteDance Inc. name, associated with the wider ByteDance group.','Business','Unknown','https://www.bytedance.com/','Original filing identifies ByteDance Inc.; group website describes its internet technology products. Exact current ownership of this legal entity remains unverified.',notes='Group website. This entry does not equate ByteDance Inc. with ByteDance Ltd. or assert current ownership of the U.S. TikTok joint venture.')
add(23,'Develops radar, surveillance, and related engineering technology for defense and security applications.','Business','Unknown','https://www.cspeed.com/','Official privacy policy identifies C Speed LLC; company site describes radar and surveillance technology.','https://www.cspeed.com/privacy-policy/')
add(24,'Provides wireless service, fiber internet, and business IT and connectivity services.','Business','Private company','https://www.cspire.com/','Company’s leadership announcement identifies C Spire as privately held.','https://www.cspire.com/cms/news/wireless/39500002/c-spire-appoints-suzy-hays-as-new-president-and-ceo',notes='Private-company status supported by the company’s June 2024 announcement.')
add(25,'Lobbying client reporting faith-based advocacy and media activity. Its precise organizational identity and website remain unverified.','Advocacy organization','Unknown','','Original filing reports faith-based advocacy and media; no independently corroborated website was identified.',out='unresolved')
add(26,'Virginia lobbying client describing itself as a strategy firm. Its precise identity and official website remain unverified.','Business','Unknown','','Original filing describes a strategy firm. Similarly named advisory businesses and municipal street projects are not treated as matches.',out='unresolved')
for i in [27,28]:
 v=add(i,'Distributes Cosentino architectural surfaces used for countertops, cladding, and other building applications in North America.','Business','Unknown','https://www.cosentino.com/usa/','Cosentino’s sales terms identify C&C North America Inc. and its distribution subsidiaries as the entities supplying Cosentino products.','https://assetstools.cosentino.com/api/v1/bynder/doc/9175801C-0F26-459C-85EA3D656A00C508/2023-general-tc-cosentino-usa-canada-pr.pdf?dl=2023-general-tc-cosentino-usa-canada-pr.pdf',notes='Cosentino brand website; exact shareholding is unverified. The North American spelling variant remains traceable.')
 v['name']='Cosentino North America ('+('C&C North America' if i==27 else 'C&C North American filing label')+')'
add(29,'Supplies groceries and related products to retailers and operates grocery retail businesses.','Business','Unknown','https://www.cswg.com/','Official site identifies C&S grocery wholesale and retail operations; current legal footer uses LLC rather than this filing’s Inc. label.','https://www.cswg.com/about/',notes='Historical Inc. filing label retained; current LLC conversion and exact ownership require further verification.')
for i in [0,5,6,14,18,20,22,24,29]:p[rows[i]['id']]['featured']=True
assert len(p)==30
(r/'general-round27-c-researched.json').write_text(json.dumps(p,indent=2)+'\n')
(r/'general-round27-c-evidence.json').write_text(json.dumps({k:{'name':v['name'],'sources':v['sources'],'identity_evidence':v['identity_evidence']} for k,v in p.items()},indent=2)+'\n')
