import pathlib,json,gzip,copy
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round28-a-input.json'));old=json.load(open(r/'reviewed.json'));p={}
def add(i,desc,kind,own,url,claim,source=None,out=None,notes=''):
 x=rows[i];v=dict(id=x['id'],name=x['name'],description=desc,kind=kind,ownership=own,website=url,sources=copy.deepcopy((x.get('profile') or {}).get('sources',[])),identity_evidence=claim,review_outcome=out or ('partial' if own=='Unknown' else 'confirmed'),notes=notes,as_of='2026-09-05',checked_at='2026-09-05',featured=False)
 if source or url:v['sources'].append(dict(url=source or url,label='Organization or primary registry evidence',claim=claim))
 if not v['sources']:
  z=json.load(gzip.open(f"lobbying-map/public/data/reports/{x['id'][:2]}.json.gz",'rt'))[x['id']][0];v['sources']=[dict(url=f"https://lda.gov/filings/public/filing/{z['id']}/print/",label='Original lobbying disclosure',claim='Identifies the disclosed client label.')]
 p[x['id']]=v;return v
add(0,'Brings regulators, researchers, drug developers, and patient groups together to improve drug-development tools and clinical-trial methods.','Nonprofit','Nonprofit / tax-exempt','https://c-path.org/','Critical Path Institute identifies itself as an independent 501(c)(3) nonprofit public-private partnership.','https://c-path.org/about/c-path-faq/');p[rows[0]['id']]['name']='Critical Path Institute (C-Path)'
add(1,'Provides freight brokerage, transportation management, logistics, and supply-chain services.','Business','Publicly traded','https://www.chrobinson.com/','Issuer results identify C.H. Robinson Worldwide Inc. as NASDAQ: CHRW.','https://investor.chrobinson.com/Financials/Quarterly-Results/default.aspx')
add(2,'Represents businesses involved in used clothing, wiping materials, fiber recovery, and textile recycling.','Trade association','Unknown','https://www.smartasn.org/','SMART’s official site identifies the Secondary Materials and Recycled Textiles Association; C2 publicly identifies SMART as its client.','https://www.smartasn.org/',notes='Represented client is the textile-recycling association, not a smart-mobility group.');p[rows[2]['id']]['name']='Secondary Materials and Recycled Textiles Association (via C2 Association Strategies)'
for i,oid in [(3,'c99a636b9b8301ec'),(7,'4d3d57181671f80e'),(9,'0c82525b733fd404'),(10,'4092e646f8b7bab7')]:
 v=copy.deepcopy(old[oid]);v.update(id=rows[i]['id'],name=old[oid]['name']+' (via C2 Strategies)',notes=old[oid].get('notes','')+' This filing names C2 as intermediary; profile refers to represented client.');v['sources']+=(rows[i].get('profile') or {}).get('sources',[]);p[rows[i]['id']]=v
add(4,'Develops electronic training ammunition that simulates gunfire, recoil, and muzzle flash without conventional blank cartridges.','Business','Unknown','https://greenammo.com/','Norwegian defense-industry association identifies Green Ammo AS and its electronic blank-ammunition systems and website.','https://www.fsi.no/medlemsskap/medlemsbedrifter/green-ammo-as/')
add(5,'Supplies expeditionary shelters, power systems, air filtration, robotics, and support equipment for defense and other demanding environments.','Business','Unknown','https://www.hdtglobal.com/','Official site and terms identify the HDT group and its defense-equipment businesses.','https://www.hdtglobal.com/terms-of-use/')
add(6,'Manufactures equipment wash racks, water-treatment systems, and cleaning and decontamination equipment.','Business','Unknown','https://riveer.com/','Official Riveer site describes its washing and treatment systems.','https://riveer.com/about/')
for i in [8,13]:add(i,'Develops solid rocket motors, modular launch vehicles, and flight-test services for defense and space customers.','Business','Unknown','https://www.xbowsystems.com/','Naval Sea Systems Command identifies X-Bow Launch Systems Inc. and its solid-rocket manufacturing partnership.','https://www.navsea.navy.mil/Media/News/Article-View/Article/3344152/nswc-indian-head-division-announces-center-for-industrial-and-technical-excelle/')
add(11,'Provides protective shelters and corrosion-prevention products and services for military equipment.','Business','Unknown','https://www.cocoon-inc.com/','Official Cocoon site describes protection of military assets from weather and corrosion.','https://www.cocoon-inc.com/about-cocoon')
add(12,'Develops expeditionary airfield lighting, wireless control systems, and mobile power equipment for military applications.','Business','Unknown','https://www.tacticallighting.com/','Official site identifies Tactical Lighting Systems and its airfield-lighting products.')
add(14,'Client reporting consulting activity and seeking funding related to long-endurance unmanned aircraft. The precise legal identity and official website remain unverified.','Business','Unknown','','Original disclosure identifies Delta Black as the represented client; similarly named drone companies are candidates, not verified identity matches.',out='partial')
add(15,'Lower chamber of California’s state legislature, responsible for lawmaking, budgets, and oversight.','Government','Government body','https://www.assembly.ca.gov/','Official California State Assembly website identifies its legislative role.')
add(16,'Provides mental-health support services and private workplace pods for accessing care.','Business','Unknown','https://www.yourcabana.com/','Company’s official site describes Cabana Live and Cabana Pods, matching the filing’s mental-health pod activity.')
add(17,'Makes custom cabinetry for kitchens, bathrooms, and other living spaces under the Cabico and Elmwood brands.','Business','Unknown','https://corpo.cabico.com/','Official corporate site identifies Cabico&co and its cabinet brands.')
add(18,'Manufactures specialty chemicals and performance materials, including carbon products, conductive additives, and aerogels.','Business','Publicly traded','https://www.cabotcorp.com/','Company overview identifies Cabot Corporation as NYSE: CBT.','https://www.cabotcorp.com/company/about-cabot')
add(19,'Develops commercial and residential real estate, with a long history of projects in Boston and New England.','Business','Unknown','https://ccfne.com/','Official company history identifies Cabot, Cabot & Forbes and its real-estate development business.','https://ccfne.com/about/')
add(20,'Lobbying client reporting aerospace activity. Its precise identity, ownership, and official website remain unverified.','Business','Unknown','','Original disclosure reports aerospace activity; the generic CAC LLC name is not sufficient to identify a particular business.',out='unresolved')
add(21,'Provides national-security and government technology, including software, intelligence, cybersecurity, and defense systems.','Business','Publicly traded','https://www.caci.com/','Official investor stock-quote page identifies CACI International Inc. as NYSE: CACI.','https://investor.caci.com/stock-quote')
add(22,'Provides energy-project development, construction, and related energy services.','Business','Unknown','https://us.cadaenergy.com/','Official CADA Energy site describes its energy-service and construction competencies.','https://us.cadaenergy.com/about-us/',notes='Exact Inc. legal ownership remains unverified.')
add(23,'Supports conservation and research concerning Caddo Lake and its watershed on the Texas-Louisiana border.','Nonprofit','Unknown','https://caddolakeinstitute.org/','Official institute website describes Caddo Lake conservation and research programs.')
add(24,'Provides remote patient monitoring and clinical support for people managing chronic conditions.','Healthcare technology','Unknown','https://www.cadence.care/','Company site describes remote chronic care, matching the LDA client description.',notes='This healthcare business is distinct from Cadence Design Systems, the chip-design software issuer.')
for i in [25,26]:add(i,'Provides consulting and implementation services on energy, environmental, public-sector, and organizational challenges.','Business','Unknown','https://cadmusgroup.com/','Company’s March 2026 announcement describes advisory and implementation services for government and commercial organizations.','https://cadmusgroup.com/cadmus-announces-cadmus-logic-ai/')
add(27,'Provides aviation and defense training, flight simulators, and related simulation and mission-support services.','Business','Publicly traded','https://www.cae.com/','CAE’s financial report identifies the issuer’s listings as TSX: CAE and NYSE: CAE.','https://www.cae.com/content/docs/corporate/CAE-FY25-FinancialReport_EN.pdf')
add(28,'U.S. CAE business providing defense training, simulation, and mission-support services.','Business','Unknown','https://www.cae.com/','CAE group website describes U.S. defense training activities; exact current ownership of the USA Inc. legal entity remains unverified.',notes='Group website; not labeled publicly traded from the parent’s listing.')
add(29,'Advocates for public-health policies and resources for people living with HIV/AIDS, including Ryan White programs.','Advocacy organization','Unknown','','A joint NACCHO-CAEAR report identifies Communities Advocating Emergency AIDS Relief Coalition and its HIV-care policy work.','https://aidsnet.org/wp-content/uploads/2023/03/Final_NACCHO-CAEAR-Status-Neutral-Report_3.14.23.pdf')
for i in [4,5,6,8,11,12,13,14]:
 n=rows[i]['name'];n=n.split(' OBO ')[-1] if ' OBO ' in n else n.split('Behalf Of ')[-1].rstrip(')');p[rows[i]['id']]['name']=n+' (via C2 Strategies)'
for i in [1,18,21,24,27]:p[rows[i]['id']]['featured']=True
assert len(p)==30
(r/'general-round28-a-root-draft.json').write_text(json.dumps(p,indent=2)+'\n')
