import pathlib,json,gzip,copy
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round29-b-input.json'));p={}
def add(i,desc,kind,own,url,claim,source=None,notes='',out=None):
 x=rows[i];v=dict(name=x['name'],description=desc,kind=kind,ownership=own,website=url,sources=copy.deepcopy((x.get('profile') or {}).get('sources',[])),identity_evidence=claim,review_outcome=out or ('partial' if own=='Unknown' else 'confirmed'),notes=notes,as_of='2026-09-05',checked_at='2026-09-05',featured=False)
 if not v['sources']:
  z=json.load(gzip.open(f"lobbying-map/public/data/reports/{x['id'][:2]}.json.gz",'rt'))[x['id']][0];v['sources'].append(dict(label='Original lobbying disclosure',url=f"https://lda.gov/filings/public/filing/{z['id']}/print/",claim='Identifies the disclosed client name.'))
 if source or url:v['sources'].append(dict(url=source or url,label='Organization or primary registry evidence',claim=claim))
 p[x['id']]=v;return v
add(0,'Coalition of healthcare organizations, insurers, pharmacy benefit managers, consumers, and businesses advocating for lower prescription-drug prices.','Advocacy coalition','Unknown','https://www.csrxp.org/','Official overview identifies the Campaign for Sustainable Rx Pricing and describes its coalition membership and policy goals.','https://www.csrxp.org/about/',notes='Policy arguments are the coalition’s positions; it is not a drug manufacturer.');p[rows[0]['id']]['name']='Campaign for Sustainable Rx Pricing (CSRxP)'
add(1,'US spirits business marketing and distributing Campari Group brands, including aperitifs, whiskey, vodka, tequila, and liqueurs.','Business','Subsidiary','https://www.camparigroup.com/','Campari Group’s annual report lists Campari America LLC as a wholly owned manufacturing and trading company.','https://www.camparigroup.com/sites/default/files/downloads/01.1%20Campari%20Group_Annual%20Report%20for%20the%20year%20ended%2031%20December%202024_1.pdf',notes='Group website; parent branding not separately attributed as the subsidiary’s logo.')
add(2,'Designs and manufactures data loggers, measurement systems, and control equipment for environmental monitoring, infrastructure, energy, and research.','Business','Private company','https://www.campbellsci.com/','Official recruiting document describes Campbell Scientific as a privately held company.','https://s.campbellsci.com/documents/eu/miscellaneous/GSE%20Software%20Engineer%20v2%20-%20Cloud%20-%20UK.pdf')
add(3,'Tel Aviv-based organization describing its work in lobbying registrations as public relations; its 2026 report discusses Middle East counter-extremism and democracy programs.','Business','Unknown','','Original 2026 filing identifies Campco Research Ltd. at a Tel Aviv address and reports the specific advocacy topics.','https://lda.gov/filings/public/filing/b4d6e39d-616e-460f-973e-3cfb52f1766d/print/',notes='No exact official website or independent ownership evidence established. Description is explicitly based on the disclosure.',out='partial')
add(4,'Public water district providing drinking water, non-potable and recycled water, and sewer services in southern Ventura County, California.','Government','Government body','https://www.camrosa.com/','Official homepage identifies Camrosa as an independent special district and describes its water and sewer services.')
add(5,'Provides HIV, hepatitis C, sexually transmitted infection, and related medical, dental, behavioral-health, pharmacy, and support services.','Nonprofit','Nonprofit / tax-exempt','https://www.cancommunityhealth.org/','Official mission page identifies CAN Community Health Inc. as a private, not-for-profit organization.','https://www.cancommunityhealth.org/our-mission/')
add(6,'Manufactures and sells premium outerwear, apparel, footwear, and accessories under the Canada Goose brand.','Business','Subsidiary','https://www.canadagoose.com/','2026 SEC financial statement note identifies Canada Goose Inc. as a wholly owned subsidiary of Canada Goose Holdings Inc.','https://www.sec.gov/Archives/edgar/data/1690511/000169051126000012/R32.htm',notes='The public issuer is Canada Goose Holdings Inc.; this operating subsidiary is not separately labelled publicly traded.')
add(7,'Life and disability reinsurance company operating within the Canada Life and Great-West Lifeco group.','Insurance company','Subsidiary','https://www.canadalifere.com/','California insurance regulator identifies Canada Life Reinsurance Company, NAIC76694, domiciled in Pennsylvania; Great-West Lifeco lists it among group rated entities.','https://interactive.web.insurance.ca.gov/companyprofile/companyprofile?doFunction=getCompanyProfile&eid=6729&event=companyProfile',notes='Shared reinsurance business website covers several group legal entities.');p[rows[7]['id']]['sources'].append(dict(label='Group subsidiary ratings',url='https://www.greatwestlifeco.com/investor-relations/credit-ratings.html',claim='Lists Canada Life Reinsurance Company among group rated insurance entities.'))
add(8,'Coalition advocating for open, rules-based international trade for Canadian agriculture and food exporters.','Trade coalition','Unknown','https://www.cafta.org/','Official CAFTA site identifies the Canadian Agri-Food Trade Alliance and its agricultural and food-sector membership.')
add(9,'Business membership organization advocating for commerce and dialogue between Canada and the United States.','Nonprofit','Nonprofit / tax-exempt','https://cabc.co/','Official overview identifies CABC as a nonprofit, nonpartisan business-policy organization.','https://cabc.co/home/who-we-are/')
add(10,'Represents Canadian beef farms and feedlots on agricultural policy, trade, animal health, and industry sustainability.','Trade association','Unknown','https://www.cattle.ca/','Official association homepage describes representation of Canadian beef farms; its annual report documents the current Canadian Cattle Association branding.','https://www.cattle.ca/wp-content/uploads/2023/04/CCA_AR_FINAL.pdf');p[rows[10]['id']]['name']='Canadian Cattle Association (formerly Canadian Cattlemen’s Association)'
add(11,'Trade association of Canadian pharmacies that certifies member online-pharmacy services and advocates on cross-border prescription access.','Trade association','Unknown','https://www.cipa.com/','Official CIPA overview describes its pharmacy membership and certification program.','https://www.cipa.com/about',notes='Industry association, not a government pharmacy regulator. Its safety claims are not independently endorsed here.')
for i in [12,13]:add(i,'Canadian National rail business transporting freight across Canada and the United States.','Business','Unknown','https://www.cn.ca/','CN’s official site describes its freight rail network; the filing’s abbreviated label does not independently establish the exact legal entity.',notes='Group website. Exact relationship of the disclosed name to Canadian National Railway Company remains unverified; do not transfer stock listing solely by name similarity.')
add(14,'Operates the CN freight-rail network connecting Canadian and US markets, with related logistics and intermodal services.','Business','Publicly traded','https://www.cn.ca/','Official investor page identifies CN shares as TSX: CNR and NYSE: CNI.','https://www.cn.ca/en/investors/stock-information/')
add(15,'Advocates for Canadians who spend extended periods abroad, including issues involving travel, health coverage, and cross-border stays.','Nonprofit','Nonprofit / tax-exempt','https://www.snowbirds.org/','Official overview identifies the Canadian Snowbird Association as a national not-for-profit advocacy organization.','https://www.snowbirds.org/about-us/')
add(16,'Manufactures solar-energy products and develops renewable-energy and battery-storage projects.','Business','Publicly traded','https://www.canadiansolar.com/','Official investor FAQ identifies Canadian Solar Inc. shares as NASDAQ: CSIQ.','https://canadiansolar.gcs-web.com/faq')
add(17,'Represents Canadian steel producers and pipe and tube manufacturers on trade, competitiveness, and industry policy.','Trade association','Unknown','https://www.canadiansteel.ca/','Official overview and member list identify the Canadian Steel Producers Association and the steel businesses it represents.','https://www.canadiansteel.ca/about')
add(18,'Provides marine freight transportation on US inland waterways and through an oceangoing deck-barge fleet.','Business','Private company','https://www.canalbarge.com/','Official homepage identifies Canal Barge Company as a privately owned marine transportation company headquartered in New Orleans.')
add(19,'Rail-infrastructure investment and development entity associated with the Chicago Keeps America Moving rail project.','Business','Unknown','','US Department of Transportation’s January 2026 financing pipeline lists Canal Edge LLC and the Chicago Keeps America Moving project.','https://www.transportation.gov/buildamerica/sites/buildamerica.dot.gov/files/2025-12/January%202026%20Pipeline%20List.pdf',notes='Pipeline listing is not proof a loan has been approved or disbursed. No standalone company website established.')
add(20,'Coalition of cancer patient, professional, and advocacy organizations addressing cancer research and healthcare policy.','Advocacy coalition','Unknown','https://cancerleadership.org/','Council’s policy letter describes a forum of national advocacy organizations addressing cancer-related public policy.','https://cancerleadership.org/policy/cancer_research/pdf/000401.pdf',notes='Distinct from university advisory councils with the same name.')
add(21,'Provides free counseling, support groups, education, financial assistance, and other support for people affected by cancer.','Nonprofit','Nonprofit / tax-exempt','https://www.cancercare.org/','Official overview identifies CancerCare as a 501(c)(3) nonprofit providing cancer support services.','https://www.cancercare.org/about');p[rows[21]['id']]['name']='CancerCare'
add(22,'Develops risk-management software and advisory services for personnel security and national-security organizations, including Fresh Haystack.','Business','Unknown','https://www.candasolutions.com/','Official company site identifies CANDA Solutions and its risk-management software and services.');p[rows[22]['id']]['name']='CANDA Solutions'
add(23,'Develops utility-scale renewable-energy projects in the United States, particularly solar power and battery storage.','Business','Unknown','https://www.candelarenewables.com/','Official services page describes Candela’s project development and solar and storage focus.','https://www.candelarenewables.com/what-we-do',notes='Project-company ownership should not be transferred to the developer without exact legal evidence.')
add(24,'Provides cybersecurity engineering, assessment, and technology integration services for government networks.','Business','Unknown','https://www.novacoastfederal.com/','Official Novacoast Federal site describes government cybersecurity services matching the represented client’s disclosed activity.',notes='Website belongs to represented client Novacoast Federal. Filing spells it Novocoast; original name preserved in aliases and sources. Exact Inc. ownership remains unverified.');p[rows[24]['id']]['name']='Novacoast Federal (via Canfield Consulting)'
add(25,'Develops software that brings together digital and physical security information to support risk monitoring and response.','Business','Unknown','https://www.securepassage.com/','Official Secure Passage overview identifies its security software engineering and integrated digital and physical protection services.','https://www.securepassage.com/about/',notes='Website belongs to represented client Secure Passage, not Canfield Consulting.');p[rows[25]['id']]['name']='Secure Passage (via Canfield Consulting)'
add(26,'Makes and sells low-dose THC beverages and related drink products under the Cann brand.','Business','Unknown','https://drinkcann.com/','Official Cann storefront sells cannabinoid beverages, matching the disclosed alternative adult-beverage business.',notes='Brand website; exact Inc. legal ownership remains unverified.');p[rows[26]['id']]['name']='Cann'
add(27,'Coalition of financial institutions and service providers addressing banking and compliance for the regulated US cannabis industry.','Trade association','Unknown','https://cfig.org/','Official CFIG homepage spells out Cannabis Financial Industry Group and describes its member industries.');p[rows[27]['id']]['name']='Cannabis Financial Industry Group'
add(28,'Unclear client label in filings reporting advocacy on recycling, sustainable manufacturing, food labeling, and agricultural policy.','Unknown','Unknown','','Original 2026 disclosure names Canned Manufacturers but does not establish which exact company or association the label denotes.','https://lda.gov/filings/public/filing/b92a4c98-3f81-44e8-b1ae-e533bbc3b4c9/print/',notes='Do not assume this is the Can Manufacturers Institute based only on a similar name.',out='unresolved')
add(29,'Provides equipment financing and leasing services for Canon customers and authorized distribution channels.','Business','Subsidiary','https://www.cfs.canon.com/','Official company overview identifies Canon Financial Services Inc. as a wholly owned subsidiary of Canon USA Inc.','https://www.cfs.canon.com/AboutUs',notes='Financial-services subsidiary, not the public Canon parent.')
for i in [1,6,12,13,14,16,21,26,29]:p[rows[i]['id']]['featured']=True
assert len(p)==30
(r/'general-round29b-root-draft.json').write_text(json.dumps(p,indent=2)+'\n')
