import json,pathlib
p=pathlib.Path('work/research-2026');rows=json.load(open(p/'general-round89-input.json'));f=p/'round89-root-incremental-evidence.json';d=json.load(open(f)) if f.exists() else {}
def add(i,name,desc,web,own,src,notes=''):
 d[rows[i]['id']]={'name':name,'description':desc,'website':web,'ownership':own,'kind':'Organization','sources':[{'url':u,'claim':c} for u,c in src],'notes':notes,'review_outcome':'partial' if own=='Unknown' else 'confirmed','featured':False}
add(0,'NAGDCA — National Association of Government Defined Contribution Administrators','NAGDCA supports administrators of public-employer retirement plans through research, education, peer collaboration and policy advocacy.','https://www.nagdca.org/','Unknown',[('https://www.nagdca.org/about/','Official association page expands NAGDCA and describes its defined-contribution and deferred-compensation plan membership and activities.')],'Professional association; exact tax category awaits registry match.')
add(1,'NAHEFFA — National Association of Health and Educational Facilities Finance Authorities','NAHEFFA represents public financing authorities that help nonprofit healthcare and education institutions access tax-exempt bond financing.','https://www.naheffa.com/','Unknown',[('https://www.govinfo.gov/content/pkg/CHRG-113hhrg21127/pdf/CHRG-113hhrg21127.pdf','2013 congressional testimony expands NAHEFFA and describes its representation of nonprofit bond issuers and financing authorities.')],'Membership in public authorities does not make the association itself a government body.')
add(3,'Nalas Engineering','Nalas Engineering provides chemistry, analytical testing, chemical engineering and pharmaceutical process-development and scale-up services.','https://www.nalasengineering.com/','Unknown',[('https://www.nalasengineering.com/','Official site identifies Nalas Engineering Services LLC, its Connecticut offices and chemical and pharmaceutical process-development services.')],'Current ownership not established.')
add(4,'NALEO Educational Fund','NALEO Educational Fund provides civic-engagement programs and professional development for Latino elected and appointed officials and communities.','https://naleo.org/','Unknown',[('https://naleo.org/','Official site describes Educational Fund civic participation, policy institutes and leadership-development programs.')],'Distinguish the Educational Fund from the related membership association; exact nonprofit record pending.')
add(5,'National Association of Landscape Professionals (formerly PLANET)','The National Association of Landscape Professionals represents businesses working in landscaping, lawn and tree care, irrigation and landscape installation.','https://www.landscapeprofessionals.org/','Unknown',[('https://www.landscapeprofessionals.org/LP/lp/media/2015-press-releases/professional-landcare-network-to-become-national-association-of-landscape-professionals.aspx','Official February 2015 announcement documents the Professional Landcare Network name change effective April 2015 and its landscape-industry membership.')],'Retain former PLANET filing aliases; nonprofit legal category pending.')
add(6,'NAMM — National Association of Music Merchants','NAMM represents the musical-instrument and music-products industry through trade events, advocacy and programs promoting music participation.','https://www.namm.org/','Nonprofit / tax-exempt',[('https://www.namm.org/sites/default/files/2026-01/NAMM_25_ANNUAL_Report.pdf','NAMM 2025 annual report identifies the National Association of Music Merchants Inc. as a not-for-profit association.')],'The trade association is distinct from The NAMM Foundation.')
add(7,'Nammo Inc.','Nammo Inc. is the U.S. holding company for Nammo defense businesses and conducts the group’s U.S. government-relations activities.','https://www.nammo.com/','Subsidiary',[('https://www.nammo.com/locations/washington-d-c/','Official Nammo page identifies Nammo Inc. as the holding company for U.S.-based subsidiaries, based in Arlington, Virginia, with government-relations responsibilities.')],'Corporate group site; distinguish the U.S. holding company from its individual manufacturing subsidiaries.')
add(8,'NANA Regional Corporation','NANA is a shareholder-owned Alaska Native regional corporation managing business investments, land and resources for shareholders with roots in Northwest Alaska.','https://www.nana.com/','Private company',[('https://www.nana.com/about-us/','Official page identifies NANA as a for-profit Alaska Native Corporation formed under ANCSA and owned by Iñupiaq shareholders.')],'Alaska Native corporation, not a tribal government; shareholder ownership is explicit.')
add(10,'NanoGraf Corporation','NanoGraf develops silicon-anode battery materials intended to improve the energy capacity and performance of lithium-ion batteries.','https://www.nanograf.com/','Unknown',[('https://www.nanograf.com/media/nanograf-awarded-up-to-15-million-army-contract-to-provide-lighter-longer-lasting-batteries-to-the-military-lmgm8','Official facility announcement describes NanoGraf silicon-anode technology, Chicago operations and battery-development contracts.')],'Current legal ownership category unverified.')
f.write_text(json.dumps(d,indent=2)+'\n');print('Saved',len(d),'root records')
