import json,pathlib,copy,gzip
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round30-c-input.json'));old=json.load(open(r/'reviewed.json'));p={}
for i,k in {7:'ef6df18446e8a34e',9:'0270f94e9f580488'}.items():
 row=rows[i];v=copy.deepcopy(old[k]);v['name']+=(' (via Cardinal Point Partners)' if i==9 else '');v['identity_evidence']='Original client label compared with existing individually researched identity. '+v['identity_evidence'];v['notes']+=' Source reference '+k+'.';v['sources']+=row.get('profile',{}).get('sources',[])
 if i==7:v['notes']+=' The filing parenthetical naming The Glover Park Group is not treated as a corporate rename: a lobbying firm is distinct from Cardinal Health.'
 p[row['id']]=v;f=r/f'website-cache/{k}.json'
 if f.exists():
  c=json.load(open(f));c['id']=row['id'];(r/f"website-cache/{row['id']}.json").write_text(json.dumps(c,indent=2))
def add(i,name,desc,web,kind='Company',own='Unknown',sources=[],notes='',legal='',outcome=None,featured=False):
 row=rows[i];filing=json.load(gzip.open('lobbying-map/public/data/reports/'+row['id'][:2]+'.json.gz','rt'))[row['id']][0]
 p[row['id']]=dict(name=name,description=desc,website=web,kind=kind,ownership=own,legal_form=legal,review_outcome=outcome or ('partial' if own=='Unknown' else 'confirmed'),featured=featured,identity_evidence='Disclosed name and activity compared with the cited primary organization evidence. '+notes,notes=notes,sources=[dict(url='https://lda.gov/filings/public/filing/'+filing['id']+'/print/',label='Original lobbying disclosure',claim='Original reported label and filing provenance retained; filing alone does not establish ownership.')]+[dict(url=u,label='Organization evidence',claim=c) for u,c in sources])
add(0,'Carbon to Sea Initiative','Funds and coordinates research evaluating ocean alkalinity enhancement as a potential carbon-removal method.','https://www.carbontosea.org/','Research nonprofit','Nonprofit / tax-exempt',sources=[('https://www.carbontosea.org/about/','Official profile identifies a 501(c)(3) public charity funding ocean alkalinity enhancement research.')],notes='Research initiative, not a claim that this carbon-removal method is already proven safe at scale.')
add(1,'Carbon Upcycling','Develops technology that combines carbon dioxide and industrial byproducts to produce materials for lower-carbon cement.','https://carbonupcycling.com/',own='Private company',sources=[('https://carbonupcycling.com/company/','Official profile describes carbon and waste utilization and a syndicate of strategic investors.')])
add(2,'Carbon Utilization Research Council','Industry coalition promoting research and technology for fossil-energy use, carbon capture, and carbon utilization.','https://curc.net/','Industry coalition','Not applicable',sources=[('https://curc.net/','Official site describes the coalition and its power-generation, labor, research and industry membership.')],notes='Former Coal Utilization Research Council name preserved in filing aliases; coalition is not a government research agency.')
add(3,'Carbonleaf LLC','Lobbying firm appearing as registrant for clients including CHZ Technologies.','','Lobbying firm',sources=[('https://lda.senate.gov/filings/public/filing/8d63f396-6300-4dcc-91df-5b4b9b6b47a4/print/','Official filing identifies Carbonleaf LLC as registrant, with Paul Cicio as contact and CHZ Technologies as client.')],notes='Registrant role and Vienna, Virginia address established by original filing. Contact email domain is not treated as a verified website; current ownership unknown.',legal='LLC')
add(4,'American Bankers Association Card Policy Council','Council within the American Bankers Association advocating for card issuers and payment networks on credit-card policy.','https://www.aba.com/banking-topics/payments/credit-cards','Association council','Not applicable',sources=[('https://lda.senate.gov/filings/public/filing/53989c8b-8abb-4c5e-93bb-970c2bbeb681/print/','Exact client is identified as American Bankers Association’s Card Policy Council.'),('https://www.aba.com/banking-topics/payments/credit-cards','ABA credit-card policy page identifies the council executive director.'),('https://bankingjournal.aba.com/2024/04/rosenkoetter-tapped-to-lead-aba-card-policy-council/','ABA publication describes the council’s card-issuer and payment-network advocacy.')],notes='Internal association council; linked parent page is relevant but parent logo is held.')
add(5,'Carda Health, Inc.','Provides virtual cardiac and pulmonary rehabilitation programs with remote clinician support and monitoring equipment.','https://www.cardahealth.com/',sources=[('https://www.cardahealth.com/','Official site describes at-home cardiopulmonary rehabilitation.')],notes='No treatment-effectiveness claims adopted from marketing; current ownership unknown.')
add(6,'Cardiac RMS','Provides remote monitoring of implanted cardiac devices and virtual care-management services.','https://cardiacrms.com/',own='Subsidiary',sources=[('https://cardiacrms.com/','Official site identifies Cardiac RMS LLC and its monitoring services.'),('https://www.sec.gov/Archives/edgar/data/1822359/000162828026018214/dcgo-20251231.htm','DocGo 2025 annual report describes acquisition of Cardiac RMS LLC.'),('https://cardiacrms.com/our-history/','Current company history describes joining DocGo.')],notes='DocGo subsidiary; no unsupported current ownership percentage stated.',legal='LLC')
add(8,'Hennepin County Regional Railroad Authority (via Cardinal Infrastructure)','Local public authority preserving rail corridors and planning and funding regional transit in Hennepin County, Minnesota.','https://www.hennepincounty.gov/government/leadership/regional-railroad-authority','Regional railroad authority','Government body',sources=[('https://www.hennepincounty.gov/government/leadership/regional-railroad-authority?from=hcrra','County page identifies HCRRA as a separate political subdivision and local government unit established in 1980.')],notes='Distinct authority from the county itself; Cardinal Infrastructure is the intermediary.')
add(10,'Cardiovascular Associates of America','Supports a network of cardiovascular physician practices with capital, shared services, and practice-management resources.','https://cvausa.com/',own='Private company',sources=[('https://cvausa.com/','Official site describes practice support and formation by Webster Equity Partners.'),('https://websterequitypartners.com/portfolio/cvausa/','Investor portfolio identifies CVAUSA as a cardiovascular-services investment.')],notes='Private-equity backed; individual practice legal entities and clinical ownership are not collapsed into this management company.')
add(11,'CardioVascular Coalition','Coalition advocating for patient access to peripheral-artery and coronary-artery disease care.','https://www.cardiovascularcoalition.com/','Health-care coalition','Not applicable',sources=[('https://www.cardiovascularcoalition.com/about-us','Official page describes a coalition of clinicians, patients, and businesses formed in 2014.')])
add(12,'Cardiovascular Institute of the South (CardioVascular Coalition filing)','Provides cardiovascular and peripheral-vascular diagnosis and treatment through a network of clinics.','https://www.cardio.com/',sources=[('https://www.cardio.com/about/mission-values/','Official site describes cardiovascular clinical care.'),('https://www.cardio.com/career-opportunities/','Practice history identifies founder Craig Walker and origins in Houma, Louisiana.')],notes='Filing includes a coalition parenthetical; clinic identity is retained separately from the coalition. Current ownership unknown.')
for i in [13,14]:add(i,'CARE Action' if i==13 else 'CARE Action Now, Inc.','Advocates for US policies and funding addressing global poverty, humanitarian needs, and the rights of women and girls.','https://careaction.org/','Advocacy nonprofit','Nonprofit / tax-exempt',sources=[('https://careaction.org/about/','Official site identifies CARE Action as a separately incorporated 501(c)(4) related to CARE.'),('https://careaction.org/wp-content/uploads/2025/12/2024-CARE-ACTION-NOW%E2%80%94FORM-990.pdf','Official-hosted return identifies CARE Action Now Incorporated.')],notes='Separate advocacy entity from CARE’s 501(c)(3) humanitarian charity; abbreviated and legal filing names remain searchable.')
add(15,'Care Solace','Connects people with mental-health treatment, substance-use treatment, and social-service providers through care coordination.','https://www.caresolace.org/',sources=[('https://www.caresolace.org/','Official site describes provider matching and care-coordination services.')],notes='Care-navigation company, not necessarily the treating clinical provider; .org does not establish nonprofit status. Ownership unknown.')
add(16,'Care Weather Technologies, Inc.','Develops small satellite radar instruments designed to measure ocean-surface winds for weather forecasting.','https://careweather.com/',sources=[('https://www.sbir.gov/portfolio/1546961','Federal SBIR record names Care Weather Technologies Inc and describes its Veery scatterometer and ocean-wind measurement work.'),('https://www.mext.go.jp/content/20230420-mxt_uchukai02-000026968_8.pdf','Japanese government satellite survey lists careweather.com for the company.')],notes='Official website currently exposes limited readable text; federal technology evidence establishes activity, but ownership is unknown.')
add(17,'Career Education Colleges and Universities (CECU)','Membership association representing private postsecondary trade schools and career colleges.','https://career.org/web/web/Home-Page.aspx','Trade association','Not applicable',sources=[('https://career.org/web/web/Home-Page.aspx','Official site identifies CECU and its private career-college membership.'),('https://lda.gov/filings/public/filing/6336ae0e-4f68-4cd0-bd7a-91539ab4d3f1/print/','Original filing connects the former association name and career.org domain.')],notes='Association is separate from its member schools and research foundation; truncated former name remains in original alias.')
add(18,'Career Start (filing label)','Florida-listed lobbying client that describes its business as recruiting software.','','Unknown',sources=[('https://lda.gov/api/v1/clients/72829/?format=json','LDA client record identifies recruiting software and Florida location.')],notes='Generic name; Rochester-based Career Start is a possible candidate but its legal relationship to this Florida client is not established. Website and ownership held.',outcome='unresolved')
add(19,'CareeResilient, LLC','Administers employee benefits for career development and financial security, including education savings and career-interruption programs.','https://www.careeresilient.com/',sources=[('https://www.careeresilient.com/','Official site identifies CareeResilient LLC as a third-party employee-benefits administrator.'),('https://grassociation.org/board-of-directors/','Professional association identifies Alan Knapp as CareeResilient founder and CEO.')],notes='Founder role does not establish current ownership shares.',legal='LLC')
add(20,'CareFirst BlueCross BlueShield','Provides health insurance and related administrative services in Maryland, Washington, DC, and Northern Virginia.','https://www.carefirst.com/business/','Health insurer','Nonprofit / tax-exempt',sources=[('https://www.carefirst.com/business/','Official page describes CareFirst as a not-for-profit healthcare company and its service region.'),('https://www.carefirst.com/assets/pdfs/2022-Our-Mission-in-Action.pdf','Corporate report identifies CareFirst BlueCross BlueShield as a shared business name of multiple licensed entities.')],notes='Shared insurance brand rather than a single legal insurer; exact underlying entity in each filing is not established.',outcome='partial',featured=True)
add(21,'Careforth (Seniorlink Incorporated)','Provides coaching, care-management support, and programs for family caregivers and people receiving care at home.','https://careforth.com/',sources=[('https://careforth.com/about-us/','Official profile describes family-caregiver support.'),('https://careforth.com/terms/','Current terms identify Seniorlink Incorporated doing business as Careforth.')],notes='DBA identity established; current equity ownership remains unknown.')
for i in [22,23]:add(i,'CareQuest Institute for Oral Health, Inc.','Nonprofit supporting oral-health research, policy, philanthropy, and health-system improvements.','https://carequest.org/','Oral-health nonprofit','Nonprofit / tax-exempt',sources=[('https://carequest.org/about/','Official site describes oral-health policy, philanthropy and analytics, and distinguishes its for-profit innovation subsidiary.'),('https://www.ldh.la.gov/assets/HealthyLa/Act212/SFY22/XV_1_DentaQuestAAFinancialStatement.pdf','Government-hosted audited statements identify CareQuest Institute for Oral Health Inc, formerly Catalyst Institute Inc, as a Massachusetts charitable corporation with 501(c)(4) status.')],notes='Former Catalyst Institute name corroborated; separate from CareQuest Innovation Partners. Tax-status evidence reflects the audited reporting period.')
add(24,'careviso Inc.','Develops software for benefits verification, patient cost estimates, and prior-authorization workflows.','https://www.careviso.com/',sources=[('https://www.careviso.com/about','Official site identifies careviso, formerly CMT Solutions, and its seeQer healthcare-administration platform.')],notes='Current ownership unknown; platform is not a clinical care provider.')
add(25,'CARFAX','Provides vehicle-history reports and automotive information services for consumers, dealers, and other businesses.','https://www.carfax.com/',own='Subsidiary',sources=[('https://www.carfax.com/company/about','CARFAX company profile describes vehicle-information services; its older parent description is superseded by the July 2026 separation announcement.'),('https://www.sec.gov/Archives/edgar/data/2090312/000110465926080006/tm2619098d1_ex99-1.htm','SEC-hosted July 2026 announcement confirms Mobility Global completed separation from S&P Global and identifies CARFAX among its brands.')],notes='Part of Mobility Global after the July 2026 separation from S&P Global. CARFAX itself is not assigned the parent’s stock ticker.',featured=True)
add(26,'Caribbean Port Services S.A.','Operates container-terminal handling, storage, and logistics services at Port-au-Prince, Haiti.','https://www.cps.ht/',sources=[('https://www.cps.ht/','Official company site identifies Caribbean Port Services and its Port-au-Prince terminal operations.')],notes='Terminal operator is distinct from Haiti’s public port authority; current ownership not established.',legal='S.A.')
add(27,'Caring Hands Health Center, Inc.','Oklahoma health-center client associated with the Caring Hands clinics serving McAlester and Hartshorne.','https://chhcok.com/',kind='Community health center',sources=[('https://lda.gov/api/v1/clients/56265/?format=json','LDA client record places Caring Hands Health Center Inc in Oklahoma.'),('https://oklahoma.gov/content/dam/ok/en/health/health2/documents/oklahoma-fqhcs-january-2018.pdf','Oklahoma health department lists Caring Hands clinics in McAlester and Hartshorne and chhcok.com as their website.'),('https://chhcok.com/providers/','Current clinic site lists Caring Hands Hartshorne and its providers.')],notes='State and clinical identity align; singular Health Center filing name differs from Healthcare Centers branding, so exact legal-name linkage and ownership remain partial.')
add(28,'Caris Science, Inc.','Caris Life Sciences subsidiary holding and licensing intellectual property used in molecular research and precision-medicine development.','https://www.carislifesciences.com/',own='Subsidiary',sources=[('https://www.sec.gov/Archives/edgar/data/2019410/000201941026000016/cai-20251231.htm','Caris Life Sciences 2025 annual report explicitly identifies subsidiary Caris Science Inc and its research-related patents and licenses.')],notes='Separate subsidiary from the publicly listed Caris Life Sciences issuer and Caris MPI laboratory entity. Group website linked; parent logo held.',legal='Corporation')
add(29,'Carl Zeiss AG','Technology group producing optics, microscopy, industrial measurement systems, medical technology, and semiconductor-manufacturing equipment.','https://www.zeiss.com/','Technology company','Foundation-owned',sources=[('https://www.carl-zeiss-stiftung.de/en/foundation/structure','Carl Zeiss Foundation identifies itself as sole shareholder of Carl Zeiss AG.'),('https://www.zeiss.com/corporate/en/about-zeiss.html','Official group profile describes its optics and technology businesses.')],notes='Foundation-owned group; distinct from its listed subsidiary Carl Zeiss Meditec AG.',legal='AG',featured=True)
for v in p.values():
 if v['ownership']=='Unknown' and v['review_outcome']=='confirmed':v['review_outcome']='partial'
assert len(p)==30
(r/'general-round30c-root-draft.json').write_text(json.dumps(p,indent=2)+'\n');(r/'check_general30c.py').write_text((r/'check_general30b.py').read_text().replace('30b','30c'));print('30 draft profiles')
