import json,pathlib
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round90-input.json'));f=r/'round90-root-incremental-evidence.json';p=json.load(open(f))
def add(i,desc,web,own,src,notes=''):
 row=rows[i];p[row['id']]=dict(name=row['name'],description=desc,website=web,kind='Professional or trade association',ownership=own,notes=notes,sources=[dict(url=u,claim=c) for u,c in src],review_outcome='confirmed' if own!='Unknown' else 'partial',featured=i==21)
add(19,'Represents lenders participating in SBA government-guaranteed lending and provides training, professional resources, and advocacy concerning the SBA 7(a) program.','https://www.naggl.org/','Unknown',[('https://www.pathlms.com/naggl/courses/106022','NAGGL’s own introductory course describes its role in the SBA 7(a) lending community, government relations, and education about lending processes.')])
add(20,'Supports Hispanic real-estate professionals through education, networking, and policy advocacy to advance sustainable homeownership in Hispanic communities.','https://nahrep.org/','Nonprofit / tax-exempt',[('https://nahrep.org/media-center/statements/2022/04/11/nahrep-and-americas-homeowner-alliance-aha-announce-strategic-alliance/','NAHREP identifies itself as a nonprofit section 501(c)(6) trade association advancing Hispanic homeownership.')])
add(21,'Represents home builders and related housing-industry professionals through policy advocacy, business resources, education, and a federation of local and state associations.','https://www.nahb.org/','Unknown',[('https://www.nahb.org/why-nahb/about-nahb','NAHB describes its home-building federation, professional education, business resources, networking and advocacy.')])
add(22,'Represents housing cooperatives and other resident-controlled housing, providing education, resources, and advocacy for cooperative homeownership.','https://coophousing.org/','Nonprofit / tax-exempt',[('https://coophousing.org/who-we-are/','NAHC explicitly identifies itself as a section 501(c)(3) nonprofit incorporated in 1960 and describes its member-governed housing-cooperative mission.')])
add(23,'Voluntary organization of current and former immigration judges advocating for immigration-court independence, professional standards, and court reform through public education and policy advocacy.','https://www.naij-usa.org/','Unknown',[('https://www.naij-usa.org/','NAIJ describes itself as a voluntary organization of current and former U.S. immigration judges and identifies its educational and court-reform advocacy mission.')],notes='Professional organization, not the immigration court or Department of Justice. Current collective-bargaining certification is not asserted.')
add(24,'Represents U.S. industrial banks in banking policy and provides information about industrial-bank charters and regulatory requirements.','https://www.industrialbankers.org/','Unknown',[('https://www.industrialbankers.org/','NAIB describes its representation of industrial banks providing FDIC-insured financial services and its charter and regulatory information.')],notes='Association, not an insured deposit-taking bank itself.')
f.write_text(json.dumps(p,indent=2)+'\n');print('Root saved',len(p))
