import pathlib,json,gzip,copy
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round29-c-input.json'));p={}
def add(i,desc,kind,own,url,claim,source=None,notes='',out=None):
 x=rows[i];v=dict(name=x['name'],description=desc,kind=kind,ownership=own,website=url,sources=copy.deepcopy((x.get('profile') or {}).get('sources',[])),identity_evidence=claim,review_outcome=out or ('partial' if own=='Unknown' else 'confirmed'),notes=notes,as_of='2026-09-05',checked_at='2026-09-05',featured=False)
 if not v['sources']:
  z=json.load(gzip.open(f"lobbying-map/public/data/reports/{x['id'][:2]}.json.gz",'rt'))[x['id']][0];v['sources'].append(dict(label='Original lobbying disclosure',url=f"https://lda.gov/filings/public/filing/{z['id']}/print/",claim='Identifies the disclosed client name.'))
 if source or url:v['sources'].append(dict(url=source or url,label='Organization or primary registry evidence',claim=claim))
 p[x['id']]=v;return v
add(0,'US medical-imaging equipment business supplying and servicing diagnostic systems, including CT, MRI, ultrasound, and X-ray technology.','Business','Subsidiary','https://us.medical.canon/','Canon identifies Canon Medical Systems USA as the US subsidiary of Canon Medical Systems Corporation.','https://global.medical.canon/news/pressrelease/2022/2022-11-28-01/',notes='The bracketed IMAGE SAFELY 360 label is preserved from the disclosure; its exact campaign relationship remains unverified.',out='partial');p[rows[0]['id']]['name']='Canon Medical Systems USA [Image Safely 360]'
add(1,'Develops and manufactures advanced materials, ceramics, and thermal-protection systems for aerospace and defense applications.','Business','Private company','https://www.canopyaerospace.com/','Trive Capital describes forming Canopy Aerospace and Defense from Hera Technologies, MSM Industries, and Canopy Aerospace’s R&D center.','https://www.trivecapital.com/trive-capital-forms-canopy-aerospace-and-defense/',notes='Private-equity-backed platform; the disclosed former Inc. is part of the combined business.');p[rows[1]['id']]['name']='Canopy Aerospace & Defense LLC'
add(2,'Provides behavioral-health treatment, educational programs, and family support services for children and families in Mississippi.','Nonprofit','Nonprofit / tax-exempt','https://mycanopy.org/','Official Canopy site describes its children’s services; published Form990 identifies Mississippi Children’s Home Society operating under the Canopy name.','https://mycanopy.org/wp-content/uploads/2020/12/2019-Form-990-MCHS-Public-Disclosure-Copy-Final.pdf')
for i in [3,4]:add(i,'Manufactures beverage cans, glass bottles, metal closures, and packaging for food and industrial products.','Business','Subsidiary','https://www.canpack.com/','Official investor page identifies Giorgi Global Holdings as parent of CANPACK Group Inc. and Peter Giorgi as its sole shareholder.','https://www.canpack.com/investor-relations/',notes='Group website. Various affiliates in the disclosure are not individually identified here.',out='partial' if i==4 else 'confirmed')
p[rows[3]['id']]['name']='CANPACK Group, Inc.';p[rows[4]['id']]['name']='CANPACK Group, Inc. and affiliates'
add(5,'Manufactures engineered forged metal components for aerospace, power generation, transportation, defense, and other industrial markets.','Business','Subsidiary','https://cantondropforge.com/','Official company update identifies Canton Drop Forge as part of Park-Ohio Holdings.','https://cantondropforge.com/from-safety-to-culture-company-updates-pave-the-way-forward/')
add(6,'Global financial-services partnership providing capital markets, brokerage, investment banking, and investment-related services.','Business','Private company','https://www.cantor.com/','Official company overview describes Cantor’s financial-services business and identifies its private partnership structure.','https://www.cantor.com/our-company/who-we-are/');p[rows[6]['id']]['legal_form']='Limited partnership'
add(7,'Conservation organization disclosed under a new LLC name, associated in the filing with WildLandscapes International’s landscape and habitat conservation work.','Conservation organization','Unknown','','Official disclosure identifies Canvasback Conservation LLC as formerly WildLandscapes International.','https://lda.gov/filings/public/filing/936861bd-4ec8-40a7-8e2d-e5bc76c498cf/print/',notes='Do not transfer WildLandscapes Inc.’s nonprofit status to this LLC. A current standalone website and exact legal continuity remain unverified.');p[rows[7]['id']]['name']='Canvasback Conservation LLC (formerly WildLandscapes International)'
add(8,'Develops US manufacturing projects for battery electrolytes and other chemical materials used in lithium-ion batteries.','Business','Unknown','https://www.capchemusa.com/','Official Capchem USA site identifies its battery-chemical products and planned Ohio and Louisiana projects.',notes='Website describes planned facilities; it does not establish that both projects are already operating.')
add(9,'Designs and integrates tethered aerostats and elevated surveillance systems for defense, border security, and other monitoring missions.','Business','Unknown','https://www.tcomsystems.com/','Official TCOM site describes aerostat platforms, sensors, and surveillance-system integration.',notes='Website and description refer to represented client TCOM, not government-relations firm CAPCVENTURES.');p[rows[9]['id']]['name']='TCOM LP (via CAPCVENTURES)'
add(10,'Mobile-phone carrier offering service designed to limit collection and exposure of customers’ communications and identity data.','Business','Unknown','https://www.cape.co/','Official Cape FAQ identifies its mobile-carrier business and describes its privacy-focused mobile core.','https://www.cape.co/faqs',notes='Privacy and security features are the company’s claims, not an independent security audit.')
add(11,'Represents Cape Cod commercial fishermen through fisheries-policy advocacy, community programs, and work supporting sustainable fishing livelihoods.','Nonprofit','Nonprofit / tax-exempt','https://capecodfishermen.org/','Official history describes its formation as a 501(c)(3) nonprofit and its fishing-community advocacy.','https://capecodfishermen.org/about-us/who-we-are/')
add(12,'Provides cybersecurity consulting, incident response, security architecture, compliance support, and federal-market sales assistance.','Business','Unknown','https://cape-endeavors.com/','Website identifies Cape Endeavors LLC and describes its cybersecurity consulting and federal-compliance services.',notes='Exact LLC website selected; similarly named Cape Endeavors Inc. operates another domain, and their corporate relationship remains unverified.')
add(13,'Alaska Native village corporation managing business and land resources to provide economic and cultural benefits to its shareholders.','Alaska Native corporation','Shareholder-owned Alaska Native corporation','https://www.capefoxcorp.com/','Official history describes formation under ANCSA and management of resources for shareholders.','https://www.capefoxcorp.com/about-us/',notes='Shareholder corporation, distinct from a tribal government or Fox media company.')
for i in [14,15]:add(i,'Builds and operates radar-imaging satellites and supplies Earth-observation imagery and analytics to government and commercial customers.','Business','Subsidiary','https://www.capellaspace.com/','IonQ announced the completed acquisition of Capella Space in July 2025.','https://www.ionq.com/news/ionq-completes-acquisition-of-capella-space-advancing-vision-for-space-based',notes='IonQ subsidiary; not itself a separately listed public issuer.')
p[rows[15]['id']]['name']='Capella Space Corp.'
add(16,'Manages and collects medical receivables, working with patients on outstanding healthcare bills.','Business','Unknown','https://capiopartners.com/','Official site identifies Capio Partners LLC and describes its medical-debt account services.')
add(17,'Think tank researching policies and social conditions affecting children, families, caregiving, and community well-being.','Nonprofit','Nonprofit / tax-exempt','https://capita.org/','Official values page identifies Capita as a US-incorporated 501(c)(3) nonprofit.','https://capita.org/about/our-values/',notes='Not the similarly named outsourcing company Capita plc.')
add(18,'Public district providing water service to Paradise, California, and nearby areas.','Government','Government body','https://www.pidwater.com/','Butte LAFCo identifies Paradise Irrigation District as the special district serving the Paradise area.','https://www.buttelafco.org/paradise-irrigation-district',notes='Website and description belong to represented client Paradise Irrigation District, not Capital Core Group.');p[rows[18]['id']]['name']='Paradise Irrigation District (via Capital Core Group)'
add(19,'Investment-management firm offering actively managed funds and portfolios for individual and institutional investors.','Business','Private company','https://www.capitalgroup.com/','Official company overview identifies Capital Group as privately owned.','https://www.capitalgroup.com/en/pro/about-us.html')
add(20,'New Jersey health system operating hospitals, outpatient facilities, and medical practices in the Trenton and surrounding region.','Healthcare provider','Nonprofit / tax-exempt','https://www.capitalhealth.org/','Audited financial statements identify Capital Health System Inc. as a New Jersey nonprofit corporation.','https://www.capitalhealth.org/sites/default/files/2023-06/2021%20%26%202022%20Audited%20Financial%20Statements.pdf',notes='Distinct from Capital Health Plan, the Florida health insurer.')
add(21,'Investment advisory firm providing retirement-income planning, portfolio management, and wealth-management services.','Business','Private company','https://www.yourwealth.com/','Official homepage identifies Capital Investment Advisors as a family-owned investment advisory firm; Georgia location matches LDA client data.',notes='Other firms share similar names; this profile follows the Georgia wealth-management client.')
add(22,'Ad hoc coalition of Capital Magnet Fund awardees and stakeholders advocating on matters affecting the affordable-housing funding program.','Advocacy coalition','Unknown','','LDA client registration explicitly identifies an ad hoc coalition of fund awardees and stakeholders.','https://lda.gov/api/v1/clients/71587/?format=json',notes='Not the US Treasury’s Capital Magnet Fund itself. No standalone coalition website, complete member list, or legal tax status established.')
add(23,'Public transportation authority providing regional bus, rail, and related transit services in the Austin, Texas, area.','Government','Government body','https://www.capmetro.org/','Official overview identifies CapMetro as Austin’s regional public transportation provider.','https://www.capmetro.org/aboutus/about-capmetro/about');p[rows[23]['id']]['name']='CapMetro (Capital Metropolitan Transportation Authority)'
add(24,'Develops, owns, and operates electricity-generation facilities in North America.','Business','Publicly traded','https://www.capitalpower.com/','Official investor page identifies Capital Power Corporation as TSX: CPX.','https://www.capitalpower.com/investors/')
add(25,'US operating entity within Capital Power’s electricity-generation business.','Business','Subsidiary','https://www.capitalpower.com/','California FPPC letter identifies Capital Power Operations USA Inc. as a wholly owned subsidiary through Capital Power US Holdings.','https://www.fppc.ca.gov/content/dam/fppc/documents/advice-letters/1995-2015/2012/12-034.pdf',notes='Historical ownership chain documented; current exact chain not re-established. Filing’s formerly-known-as phrase does not prove it is the publicly traded parent.',out='partial');p[rows[25]['id']]['name']='Capital Power Operations (USA) Inc.'
add(26,'Public commission that owns and operates Richmond International Airport in Virginia.','Government','Government body','https://flyrichmond.com/','City of Richmond identifies the commission as owner and operator of Richmond International Airport.','https://www.rva.gov/office-city-clerk/boards-and-commissions',notes='Airport website; not the similarly named airport in Lansing, Michigan.')
add(27,'Operates Rivers Casino & Resort Schenectady in New York under the Capital Region Gaming LLC legal name.','Business','Unknown','https://www.riverscasino.com/schenectady/','New York Gaming Commission identifies Capital Region Gaming LLC as the casino licensee.','https://gaming.ny.gov/rivers-casino-resort-schenectady-commercial-casino-license',notes='Operating-brand website; association with Rush Street Gaming does not establish an exact current ownership percentage.')
add(28,'Administers prescription-drug benefits and provides pharmacy-benefit technology and services to employers and health plans.','Business','Unknown','https://www.cap-rx.com/','Official site states Capital Rx is now Judi Rx; New York insurance directory lists Judi Rx Inc. with Capital Rx Inc. in its name history.','https://myportal.dfs.ny.gov/companydirectory/dir_det.jsp?filekey=dir&frst=dir_srch_optiono&search_type=CPAT_NUM&search_value=10629&source=o',notes='Current name Judi Rx retained alongside the historical filing name. Public benefit corporation does not mean publicly traded.');p[rows[28]['id']]['name']='Judi Rx (formerly Capital Rx)'
add(29,'Joint powers authority planning and delivering the Capital SouthEast Connector transportation corridor in the Sacramento region.','Government','Government body','https://www.connectorjpa.com/','Official project overview identifies the JPA formed by five public agencies and describes the regional expressway project.','https://www.connectorjpa.com/project-overview',notes='Planned corridor and construction program; do not imply all segments are complete.')
for i in [0,3,6,10,14,15,19,20,23,24,28]:p[rows[i]['id']]['featured']=True
assert len(p)==30
(r/'general-round29c-root-draft.json').write_text(json.dumps(p,indent=2)+'\n')
