import json,pathlib,copy,gzip
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round30-a-input.json'));old=json.load(open(r/'reviewed.json'));p={}
reuse={3:'5152fe3fff182860',5:'0f4ceb294a8b89a4',6:'780252cbf776eb6a',7:'7937a5bcc9eedf01',8:'5a43e526262a8fe3',9:'212ff28f5e48ee5b',10:'eeaff991a11626f8',11:'1160dac5e5add057',14:'33caf8fc4fc3b1b5',24:'4aab60e062f2670b',29:'03a24c724e30628a'}
for i,k in reuse.items():
 row=rows[i];v=copy.deepcopy(old[k]);v['name']+=' (via '+('Capitol Dome Advocacy' if i==29 else 'Capitol Counsel')+')';v['identity_evidence']='Represented organization explicitly named in this on-behalf-of filing label; its disclosed activity matches the individually researched organization. '+v['identity_evidence'];v['notes']+=' Evidence reused after individual identity comparison; original intermediary filing label remains searchable. Research reference ID '+k+'.';v['sources']+=row['profile'].get('sources',[]);p[row['id']]=v
 # Preserve already inspected logo cache when official website is unchanged.
 f=r/f'website-cache/{k}.json'
 if f.exists():
  c=json.load(open(f));c['id']=row['id'];(r/f"website-cache/{row['id']}.json").write_text(json.dumps(c,indent=2))
def add(i,name,description,website,kind='Company',ownership='Unknown',legal='',sources=[],notes='',outcome=None):
 row=rows[i];p[row['id']]=dict(name=name+' (via Capitol Counsel)',description=description,kind=kind,ownership=ownership,legal_form=legal,website=website,identity_evidence='The filing explicitly names the represented organization; disclosed activity is compared with the cited organization evidence. '+notes,notes=notes,review_outcome=outcome or ('partial' if ownership=='Unknown' else 'confirmed'),featured=False,sources=row['profile'].get('sources',[])+[dict(url=u,label='Organization identity evidence',claim=c) for u,c in sources])
add(0,'Cook Inlet Housing Authority','Develops and operates affordable housing and related housing programs in Southcentral Alaska.','https://www.cookinlethousing.org/','Housing authority','Government body','Alaska public corporation', [('https://www.cookinlethousing.org/wp-content/uploads/2023/07/Appendix-C.pdf','Audited financial statements identify CIHA as an Alaska public corporation created in 1974, governed by commissioners appointed by the Cook Inlet Tribal Council.'),('https://www.cookinlethousing.org/who-we-are/our-story/','Official history describes affordable housing programs in Southcentral Alaska.')], 'Regional housing authority; separate from the shareholder-owned Cook Inlet Region corporation. Public corporation here does not mean stock-market listed.')
add(2,'Cook Inlet Region, Inc. (CIRI)','Alaska Native regional corporation with businesses and investments in aerospace, energy, real estate, government services, and technology.','https://www.ciri.com/','Alaska Native corporation','Alaska Native shareholder-owned','Corporation',[('https://www.ciri.com/','CIRI identifies itself as an Alaska Native regional corporation owned by its shareholders and describes its diversified businesses.')], 'An Alaska Native regional corporation, not a tribal government.')
add(13,'Earth Force Technologies','Builds forestry software and in-cab guidance tools that help equipment operators carry out fuel treatments and report work to land managers.','https://www.earthforce.io/',sources=[('https://www.earthforce.io/','Official site describes Guide operator maps and alerts and the Portal field-reporting application.')],notes='Official business and filing activity match; current ownership is not established.')
add(15,'Intterra Group','Provides map-based software connecting public-safety agency data, operations, and emergency information.','https://www.intterra.io/',sources=[('https://www.intterra.io/','Official site describes the Aware public-safety platform.'),('https://helpdocs.intterragroup.com/knowledge/wildfire-reports-tools?hsLang=en','Intterra Group support domain documents wildfire reporting tools.')],notes='Brand and activity match; exact current legal ownership remains unknown.')
add(16,'Just Right Reader','Publishes phonics curricula and decodable books for early reading instruction, with accompanying teacher and family resources.','https://justrightreader.com/',sources=[('https://justrightreader.com/','Official publisher site describes phonics programs and decodable libraries.'),('https://justrightreader.zendesk.com/hc/en-us/articles/35160870519187-Our-Story','Publisher history identifies founder Sara Rich and its literacy mission.')],notes='Founder identity does not establish current ownership.')
add(17,'Neptune Aviation','Operates aerial firefighting aircraft that deliver retardant and support wildfire suppression.','https://neptuneaviation.com/',sources=[('https://neptuneaviation.com/who-we-are/','Official company page describes aerial firefighting operations and pilot qualifications.')],notes='Operating identity established; current ownership not independently established.')
add(18,'OroraTech GmbH','Develops thermal-infrared satellite technology and wildfire detection and monitoring software.','https://ororatech.com/',ownership='Private company',legal='GmbH',sources=[('https://ororatech.com/terms-and-conditions/imprint','Official imprint identifies OroraTech GmbH in Munich.'),('https://ororatech.com/company/about-us','Company history describes satellite development, wildfire monitoring and Series B financing.')])
add(19,'Overwatch Aero','Provides airborne intelligence, surveillance, reconnaissance, and unmanned-aircraft services.','https://overwatchaero.com/',sources=[('https://overwatchaero.com/','Official site identifies Overwatch Aero as an airborne ISR operator and enabler.')],notes='Official operating identity matches; current ownership remains unknown.')
add(20,'Perimeter Solutions','Manufactures fire-retardant and firefighting-foam products and provides related equipment and services.','https://ir.perimeter-solutions.com/',ownership='Publicly traded',sources=[('https://ir.perimeter-solutions.com/sec-filings/all-sec-filings/content/0001880319-26-000013/prm-20251231.htm','2025 Form 10-K filed February 2026 identifies Perimeter Solutions, Inc., NYSE: PRM, and its fire-safety business.')],notes='The client uses the group business name; the listed issuer is Perimeter Solutions, Inc.')
add(21,'Planned Parenthood for America (filing label)','Filing describes health-care education for a Planned Parenthood client represented through Capitol Counsel.','',kind='Unknown',sources=[('https://lda.senate.gov/filings/public/filing/46eae350-ed5f-47ba-b14d-9256f58c3e5d/print/','Registration uses the exact abbreviated label and describes health-care education.'),('https://lda.gov/filings/public/filing/297fb4c8-6db7-4b2a-9f40-a088e5372b85/print/','Separate Capitol Counsel report names Planned Parenthood Federation of America, Inc.; this is a candidate relationship, not proof that every abbreviated client label is identical.')],notes='Exact represented legal entity remains unresolved between related Planned Parenthood organizations; website and ownership are held pending stronger linkage.')
add(25,'Spatial Informatics Group, LLC','Provides geospatial analysis, environmental research, and software for forests, natural hazards, carbon projects, and other land-management work.','https://sig-gis.com/',legal='LLC',sources=[('https://sig-gis.com/','Official site describes its scientific and geospatial services and distinguishes the separate SIG-NAL nonprofit.'),('https://github.com/sig-gis','Organization-controlled GitHub profile identifies Spatial Informatics Group, LLC.')],notes='Do not transfer the affiliated nonprofit status of SIG-NAL to this LLC.')
add(26,'The Lumber Manufactory','Develops deployable sawmills designed to process timber near its source into lumber for construction.','https://www.lumbermanufactory.com/',sources=[('https://www.lumbermanufactory.com/','Official site describes rapidly deployed local sawmills and domestic lumber production.')],notes='Current ownership not established.')
add(27,'TracPlus','Provides aircraft and asset tracking, satellite communications, and operational data software used in aerial firefighting and other missions.','https://www.tracplus.com/',sources=[('https://www.tracplus.com/','Official site describes tracking, communications, telemetry and TracPlus Cloud.')],notes='Brand identified; exact legal entity behind the abbreviated filing label and current ownership remain unknown.')
add(28,'Vibrant Planet PBC','Builds wildfire-risk monitoring and land-management planning software using environmental data and simulations.','https://vibrantplanet.com/',legal='Public benefit corporation',sources=[('https://vibrantplanet.com/about/our-story','Official history distinguishes the software public benefit corporation from the Vibrant Planet Data Commons nonprofit.')],notes='Public benefit corporation is a legal form, not proof of stock-market listing or nonprofit status; current ownership remains unknown.')
(r/'general-round30a-root-draft.json').write_text(json.dumps(p,indent=2)+'\n');print(len(p))
