import json,pathlib
p=pathlib.Path('work/research-2026');rows=json.load(open(p/'general-round88-input.json'));f=p/'round88-root-incremental-evidence.json';d=json.load(open(f)) if f.exists() else {}
def add(i,description,website,ownership,sources,notes='',featured=False):
 row=rows[i];d[row['id']]={'name':row['name'],'description':description,'website':website,'kind':'Organization','ownership':ownership,'sources':[{'url':u,'claim':c} for u,c in sources],'notes':notes,'review_outcome':'partial' if ownership=='Unknown' else 'confirmed','featured':featured}
add(0,'Mothers Against Drunk Driving advocates against impaired driving and underage drinking and supports people affected by impaired-driving crashes.','https://madd.org/','Nonprofit / tax-exempt',[('https://madd.org/wp-content/uploads/2023/10/MADD_Disclosure_2022_Signed.pdf','MADD public Form 990 documents its charitable impaired-driving prevention and victim-support activities.'),('https://www.irs.gov/pub/irs-soi/eo3.csv','IRS master file lists Mothers Against Drunk Driving, EIN 94-2707273, Irving, Texas, subsection 03.')],featured=True)
for i in [1,2]:
 add(i,'The Motion Picture Association represents film, television and streaming companies on copyright, market access and other industry policies.','https://www.motionpictures.org/','Nonprofit / tax-exempt',[('https://www.motionpictures.org/about/','Official history describes the film, television and streaming trade association and the 2019 unification of its global brand as Motion Picture Association.'),('https://www.irs.gov/pub/irs-soi/eo1.csv','IRS master file lists Motion Picture Association Inc., EIN 13-1068220, Sherman Oaks, California, subsection 06.')],'The former MPAA name and present MPA brand are documented in official history. Retain filing names until legal-ID deduplication is checked.',True)
add(3,'Motiv Space Systems designs space-rated robotic arms, mechanisms and motor controllers used on spacecraft and planetary missions.','https://motivss.com/','Subsidiary',[('https://motivss.com/about/','Official company history describes its robotic systems and work on the Mars 2020 Perseverance rover.'),('https://www.sec.gov/Archives/edgar/data/1819994/000181999426000062/R10.htm','Rocket Lab business-combinations disclosure states that it closed the acquisition of Motiv Space Systems, Inc. on May 26, 2026.')],'Acquisition completed in 2026; do not retain a pre-acquisition independent-company classification.')
add(4,'This lobbying client label combines two law firms, Motley Rice LLC and Ballard Spahr LLP, reporting litigation as their activity.','','Not applicable',[('https://lda.gov/filings/public/filing/92d8bcf3-efa9-442f-968b-3b47c7823210/print/','Registration names both law firms together, with litigation as the business activity and the Mount Pleasant, South Carolina address.')],'Combined disclosure label, not one legal company; preserve both constituent firms.');d[rows[4]['id']]['review_outcome']='partial'
add(5,'MEMA represents manufacturers supplying vehicle components, systems and aftermarket products, and advocates on policies affecting vehicle suppliers.','https://www.mema.org/','Unknown',[('https://www.mema.org/','MEMA official site identifies original-equipment and aftermarket supplier segments and its government-policy advocacy.')],'Association identity established; exact tax category awaits legal evidence.')
add(6,'The Motor Vehicle Protection Products Association represents businesses providing and underwriting products such as tire, wheel, windshield, dent and key-replacement protection.','https://mvppa.org/','Unknown',[('https://mvppa.org/','Official site identifies the association, its members, protection-product categories and regulatory advocacy.')],'Trade-association activity established; tax classification not inferred from the name.')
add(7,'The Motorcycle Industry Council represents the powersports industry through government relations, technical work, research and market-development programs.','https://www.mic.org/','Nonprofit / tax-exempt',[('https://www.mic.org/','Official council site lists government relations, research, technical and market-expansion activities.'),('https://www.irs.gov/pub/irs-soi/eo1.csv','IRS master file lists Motorcycle Industry Council Inc., EIN 31-4394320, Irvine, California, subsection 06.')])
add(8,'The Motorcycle Riders Foundation advocates for motorcyclists on federal transportation and motorcycle policy.','https://mrf.org/','Nonprofit / tax-exempt',[('https://www.irs.gov/pub/irs-soi/eo2.csv','IRS master file lists Motorcycle Riders Foundation Inc., EIN 52-1588092, Peoria, Illinois, subsection 04.')],'Website content still requires verification.');d[rows[8]['id']]['review_outcome']='partial'
add(10,'Mott Corporation manufactures porous-material filters and precision flow-control components for applications including semiconductors, healthcare, energy and aerospace.','https://mottcorp.com/','Subsidiary',[('https://idexcorp.com/news/news-item/idex-corporation-completes-acquisition-of-mott-corporation','IDEX states that its acquisition of Mott Corporation and subsidiaries completed September 5, 2024, and describes porous materials and flow-control products.')],'Part of IDEX Health & Science Technologies following the completed acquisition.')
f.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');print('Saved',len(d),'root entries')
