import json,pathlib,gzip
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round33-c-input.json'));p={};s=(r/'research30c_root.py').read_text();helper=s[s.index('def add('):s.index("add(0,'Carbon")];exec((r/'filing_evidence.py').read_text());helper=helper.replace("filing=json.load(gzip.open('lobbying-map/public/data/reports/'+row['id'][:2]+'.json.gz','rt'))[row['id']][0]","filing,filing_member=latest_filing(row)");exec(helper)
add(10,'Cheese Importers Association of America','Trade association representing businesses importing cheese and other dairy products into the United States.','https://theciaa.org/',kind='Dairy import trade association',own='Not applicable',sources=[('https://theciaa.org/','Official association site identifies its dairy-import mission and member services.')],notes='Membership association; specific tax-exemption classification not established.',outcome='partial')
for i in [11,12]:
 add(i,'Chelan County Public Utility District','Locally governed public utility providing electricity, water, wastewater and fiber services in Chelan County, Washington.','https://www.chelanpud.org/',kind='Public utility district',own='Government body',sources=[('https://www.chelanpud.org/about-us/mission-vision-values','Official district site describes local public control and customer ownership.'),('https://www.chelanpud.org/about-us/news/media-fact-sheet','Official facts identify Chelan County PUD as a state nonprofit corporation governed by municipal-corporation rules.')],notes='PUD is the abbreviation of public utility district; both directory labels describe the same district. Original filing labels retained for traceability; no filing counts combined here.')
add(13,'Chelan Douglas Regional Port Authority','Joint port authority supporting regional economic development and operating Pangborn Memorial Airport in Washington.','https://www.cdrpa.org/',kind='Regional port authority',own='Government body',sources=[('https://www.cdrpa.org/get-to-know-us','Official authority history explains functional consolidation of Chelan and Douglas ports effective January 1 2020 and independent government status.'),('https://portal.sao.wa.gov/ReportSearch/Home/ViewReportFile?arn=1034170&isFinding=false&sp=false','Washington State Auditor report describes the joint authority and airport ownership and operation.')],notes='Functional consolidation did not establish that the two original port districts ceased to exist.')
add(14,'Chemlock Nutrition','Develops and supplies feed ingredients and nutritional products for livestock and other animals.','https://chemlocknutrition.com/',kind='Animal nutrition company',sources=[('https://chemlocknutrition.com/about/','Official history describes animal nutrition ingredient development, founders and outside capital raised in 2021.'),('https://chemlocknutrition.com/products/','Official product catalog identifies feed ingredients and nutritional products.')],notes='Founded by a father and son; that does not establish current family control after external investment. Exact ownership remains unknown.')
add(15,'Chemo Mouthpiece','Medical-device business offering an oral cooling mouthpiece intended for use during chemotherapy care.','https://chemomouthpiece.com/',kind='Medical device business',sources=[('https://chemomouthpiece.com/about/','Official profile describes the oral cooling device and founder David Yoskowitz.'),('https://chemomouthpiece.com/hcp/','Official professional page describes the prescribed device and distribution workflow.')],notes='Filing uses a product brand; exact legal registrant and ownership not independently established. Description does not adopt treatment-effectiveness claims.')
add(16,'Chemonics International','International development and professional-services company working in health, agriculture, supply chains, governance and infrastructure.','https://www.chemonics.com/',kind='International development company',own='Employee-owned',sources=[('https://www.chemonics.com/','Official company site describes international development and professional-services activities.'),('https://chemonics.com/wp-content/uploads/2023/05/IESOP_Fact_Sheet_2023-DRAFT-updated-042623.pdf','Company 2023 employee-stock-ownership fact sheet states it became 100 percent employee owned in 2011.')],notes='Employee-ownership evidence is historical. Current exact ownership percentage not independently re-established; source file is labeled draft.',outcome='partial',featured=True)
add(17,'Chemring Sensors and Electronic Systems, Inc.','Develops biological-threat detection sensors and related equipment for defense and security customers.','https://www.chemring.com/about-us/our-business/chemring-sensors-and-electronics',kind='Defense sensing subsidiary',own='Subsidiary',sources=[('https://www.chemring.com/media/press-releases/2026/01-07-2026','July 2026 parent announcement explicitly identifies CSES as a US subsidiary and describes biological detection systems.')],notes='Subsidiary of Chemring Group; parent stock-market listing is not assigned to this operating client.')
add(18,'Chenega Corporation','Alaska Native village corporation operating government-services businesses and managing assets for its shareholders.','https://www.chenega.com/',kind='Alaska Native village corporation',own='Alaska Native shareholder-owned',sources=[('https://www.chenega.com/','Official corporate site describes ANCSA establishment, shareholder mission and government-services businesses.'),('https://www.chenega.com/wp-content/uploads/2026/03/Chenega-Corporation-Responds-to-False-Allegations.pdf','Corporate statement describes Alaska Native ownership and shareholder purpose.')],notes='Alaska Native corporation, distinct from a tribal government. Corporate statement used for ownership context, not to endorse disputed claims.',featured=True)
add(19,'Chenega Corporation — MIOS Strategic Business Unit','Chenega shared-services division supporting military, intelligence and operations businesses serving government and commercial customers.','https://chenegamios.com/',kind='Government-services business division',own='Division',sources=[('https://chenegamios.com/about/','Official MIOS profile explicitly identifies a shared-services division of Chenega Corporation serving its wholly owned companies.')],notes='A strategic business unit rather than independently established separate legal company. Parent is Alaska Native shareholder-owned; original filing label preserved.')
(r/'general-round33c-root-draft.json').write_text(json.dumps(p,indent=2)+'\n');print(len(p),'root drafts saved')
