import json,pathlib
r=pathlib.Path('work/research-2026');v=json.load(open(r/'irs-round4-c-rewritten.json'));p={x['id']:x for x in v}
changes={
'c7f495e7dbdd7f2c':'Farm membership organization representing South Carolina agriculture through policy advocacy, education, and member services.',
'dace0d3b40c66cba':'Tribal nonprofit health consortium providing medical and community health services in Southeast Alaska.',
'ec153c67c4a19e4f':'Labor organization representing Southwest Airlines pilots in employment, contract, and aviation-policy matters.',
'6945f14d42065556':'Nonprofit organizing sports training and competition, health programs, and inclusive education for people with intellectual disabilities.',
'f619cf3c6dde7acf':'Trade association representing businesses that transport, lift, and erect oversized or overweight equipment and loads.',
'c7465ecbedf5fd04':'Trade association representing manufacturers, distributors, and retailers of specialty automotive equipment and aftermarket products.',
'bded49328eac172f':'Industry alliance representing legal online and retail sports-betting companies in public-policy advocacy.',
'f3bcddfe875cf4b1':'Early-childhood nonprofit providing learning programs, professional training, and policy advocacy for young children and families.',
'cd8744bd7b39fe91':'Nonprofit supporting first responders, military veterans, and their families through housing and related assistance.',
'849b7620af089854':'Outdoor art museum exhibiting and conserving large-scale modern and contemporary sculpture in a landscaped setting.',
'68c76011e5d2edfe':'Nonprofit recording, preserving, and sharing personal oral histories and conversations.',
'e74689bd327208bb':'Education foundation funding and developing programs that connect postsecondary education and training with employment opportunities.',
'7641ac245025f30a':'Nonprofit working to prevent commercial sexual exploitation of children through education, survivor protection, policy advocacy, and collaboration.',
'cc5eb7fadc8380ad':'Nonprofit health system providing hospital, clinic, and home-health services.',
'c7644d7d56a8dc8f':'Community health provider offering medical and related patient-care services.',
'd3be2c2173e4e361':'Conservation research organization studying land management, wildlife, and natural ecosystems.',
'efbffb4adcb9d9ca':'Graduate institution affiliated with Columbia University, providing education and research in education, psychology, and health.',
'98386a4d7230eac4':'Nonprofit helping people with ALS and other neuromuscular conditions obtain assistive technology, equipment, and services.',
'8db77c1b26826a22':'Trade association representing information and communications technology companies through industry standards and policy advocacy.',
'70ff037edff09c6c':'Nonprofit academic health system providing hospital and clinical care associated with Temple University.',
'bad2b9879cb4a918':'Association representing Tennessee hospitals and health systems through advocacy, information, and member services.',
'c0aae876b7461907':'Trade association representing Texas banks through public-policy advocacy, education, and industry information.',
'862df8933bc2d069':'Trade association representing cattle feeders in Texas, Oklahoma, and New Mexico through education and policy advocacy.',
'b59de5d48a169bb4':'Nonprofit hospital organization based in Houston, Texas, providing pediatric and women’s healthcare, research, and medical education.',
'caaed2ce2e38288d':'Grower association supporting citrus production through research, industry education, marketing assistance, and pest and disease control.',
'b6feb0e2077faf32':'Advocacy and education organization working on Medicaid policy affecting Texas hospitals.',
'33130293fb87045a':'Association representing Texas long-term-care providers and professionals through advocacy and industry support.',
'79ba887010672d4b':'Trade association representing Texas hospitals and health systems in public policy, education, and industry matters.',
'4a7cfb96cb99daa6':'Fundraising foundation supporting Texas Southern University, including scholarships, research, and community engagement.',
'f43e32426262f92f':'Coalition advocating for the Low-Income Housing Tax Credit and related affordable-housing programs.',
'b359bd1418cb58d9':'Hospital organization providing medical care, education, and research for Brooklyn and the wider New York area.',
'5131ee0bfede7fd1':'Pediatric hospital organization providing children’s medical care, research, and medical education in Philadelphia.',
'f0eaf668bac51100':'Technology-policy nonprofit connecting researchers, technologists, and policymakers through research and policy work.',
'f406f6a10251a668':'Nonprofit academic hospital organization providing medical care, teaching, and research in New York.',
'bf98f2e729e66504':'Social-services nonprofit supporting children, young people, adults, and families through child-welfare and community programs.',
'f680f8a65ea3d527':'Nonprofit pediatric healthcare organization providing children’s medical services, research, and education.',
'c0dc753b123e721e':'Policy coalition advocating changes to pharmacy benefit management, prescription-drug pricing, and the pharmacy supply chain.',
'a8c0a347865b6946':'Transportation research and testing organization helping clients evaluate vehicles, technologies, and mobility systems.',
'ada07b2b71a6b91b':'Senior-citizen advocacy organization educating members and advocating for retirement benefits and related policy.',
'c5174f8b0749b32b':'Trade association representing businesses that rent and lease trucks and trailers in legislative and regulatory policy.',
'e8508552f99d9496':'Trade association representing truckload carriers and supporting trucking-industry education, operations, and policy advocacy.',
'7543612a18d08a38':'Philanthropic partner supporting restoration, preservation, educational programs, and volunteer work on the National Mall.',
'd5c828ff213e8908':'Nonprofit university organization providing higher education, research, and public-service programs through the University of Pennsylvania.',
'a84a224362b30ddf':'Healthcare organization serving residents of the western Navajo reservation through medical and related health services.',
'8c1bc5b9110674bd':'Trade association representing U.S. mortgage insurers in housing-finance policy and industry matters.',
'c7a36913909a1bf7':'Nonprofit providing immigration legal services and advocating for farmworkers and immigrant communities.',
'9752ba1f21114151':'Nonprofit healthcare education organization providing online and blended career-training programs.',
'ce2f8f81aec2a18e':'Business association representing U.S. companies operating in China and advocating on U.S.–China commercial relations.',
'cbb0a31fac1ab949':'Trade association representing the U.S. travel industry and advocating policies affecting travel to and within the United States.',
'55f30682d425ea4e':'Wine-industry coalition representing importers, distributors, and producers and opposing tariffs on wine.',
'a5252f786da1475e':'Youth and family-services nonprofit providing healing, education, and support for young people, including those involved in child welfare.',
'9c5027f4b959dbf8':'Professional association representing U.S. Postal Service postmasters and managers in employment and postal-policy matters.',
'b9e4f1cf5a173a6d':'Trade association representing U.S. cutting-tool manufacturers and supporting industry information and advocacy.',
'a9fda42d550dae93':'National Olympic and Paralympic organization supporting Team USA athletes and participation in international sporting competition.',
'c0689dc5d8c935ea':'Trade association representing broadband and telecommunications providers in public policy and industry matters.',
'b36b4c80d1268598':'Nonprofit supporting the worldwide United Way network of community fundraising and social-service organizations.',
'db5a26e4767080da':'University consortium coordinating atmospheric and related research, scientific facilities, and education, including management of the National Center for Atmospheric Research.',
'f60a47571f8648af':'Coalition of University of California students and student governments advocating on higher-education and student issues.',
'c62887c8ff511f9b':'University-affiliated healthcare organization supporting patient care, health-professions education, and biomedical research through UF Health.',
'8e15851d1e31f065':'Healthcare accreditation organization evaluating healthcare programs and organizations against quality standards.',
'bba533fe04aa2740':'Membership organization supporting public-library systems through collaboration, research, and library-policy work.',
'f733d3b910c774d8':'Advocacy nonprofit organizing and campaigning on reproductive justice and gender equity.',
'6ee0e062adca7af1':'Advocacy nonprofit working on Alzheimer’s disease research, prevention, treatment, and support for affected families.',
'b09950c0087e48c0':'Nonprofit pediatric healthcare organization serving Central California through children’s medical care, research, and education.',
'f9d49574c6e89ac8':'Research and policy nonprofit working with communities and governments on criminal-justice and immigration-system reform.',
'9db8958fc09ef10a':'Nonprofit blood-health organization providing blood-related medical services, research, and diagnostic support.',
'd17f174124599365':'Nonprofit providing maternity housing and support services for people facing unplanned pregnancies.',
'f66be8a413aa8fad':'Association representing Virginia hospitals and healthcare organizations through policy advocacy and industry collaboration.',
'96c1e40193764ca4':'Conservation nonprofit working to restore Walker Lake and protect agricultural, environmental, and recreational interests in the Walker Basin.',
'8a20388a401677e4':'Membership association representing Washington hospitals and supporting hospital policy and industry collaboration.',
'7ccd2f618e2c7ace':'Association representing Washington public-transit systems through advocacy, public education, and professional development.',
'e60196c0f600afb5':'Integrated nonprofit health system providing hospital, clinical, and community healthcare services in Pennsylvania.',
'87c320bb87910f70':'Nonprofit health system providing hospital, clinic, and related healthcare services.',
'68f3ca4da4fd1172':'Association of local governments supporting municipal services and intergovernmental cooperation in western Cook County, Illinois.'}
for k,d in changes.items():p[k]['description']=d
(r/'irs-round4-c-root-rewrite.json').write_text(json.dumps(p,indent=2)+'\n');print('root rewrote',len(changes),'of',len(p))
