import json,pathlib,re
r=pathlib.Path('work/research-2026');rows=json.load(open(r/'general-round94-input.json'));p={}
for k in 'bcd':p.update(json.load(open(r/f'round94-{k}-evidence.json')))
assert set(p)=={x['id'] for x in rows}
def v(i):return p[rows[i]['id']]
def source(url,claim):return {'url':url,'claim':claim}
v(0).update(ownership='Public company',review_outcome='confirmed',notes='Neogen Corporation is listed on Nasdaq under NEOG, as stated in its July30,2026 financial release.',sources=[source('https://investors.neogen.com/overview/default.aspx','Neogen identifies its food and animal safety business.'),source('https://s21.q4cdn.com/672210836/files/doc_financials/2026/q4/Neogen-Reports-Fourth-Quarter-and-Full-Fiscal-Year-2026-Financial-Results-2026.pdf','Neogen July30,2026 release identifies Nasdaq NEOG and describes food-safety diagnostics, genomics and animal-care products.')])
v(4).update(ownership='Unknown',review_outcome='partial');v(4)['sources']=[s for s in v(4)['sources'] if 'nsca.com' not in s['url']]
v(5).update(name='NEPA Wholesale',website='https://www.nepawholesale.com/',description='Wholesaler distributing tobacco and vape products, food, beverages, convenience-store goods and related supplies to retailers.',ownership='Unknown',review_outcome='partial',notes='Official Florida wholesaler website and product lines match the disclosed distribution and vapor/tobacco business; ownership remains unverified.',sources=[source('https://www.nepawholesale.com/','NEPA Wholesale lists its West Palm Beach address, wholesale distribution services and tobacco, vape, food, beverage and other retailer product categories.')])
v(6).update(website='https://nephdocs.com/',notes='Official NANI site identifies the regional nephrology practice; original DVAC reference remains in disclosed aliases. Ownership remains unverified.',sources=[source('https://nephdocs.com/practice','NANI lists nephrology practice locations in Illinois, Indiana and New Jersey and kidney-care, transplant, clinical-research and vascular-access services.')])
for i in [7,8,9,13,16,28,32,36,59]:
 v(i).update(ownership='Unknown',review_outcome='partial')
 if i in [7,8,9]:v(i)['notes']+=' The brand-to-LLC relationship does not independently establish ownership of Nephron Nitrile itself.'
v(18).update(website='https://nestidd.com/',description='Real-estate company purchasing, adapting, leasing and maintaining homes for care agencies serving people with intellectual and developmental disabilities.',ownership='Unknown',review_outcome='partial',notes='Official property model matches the client’s disclosed disability-housing business. Current ownership remains unverified.',sources=[source('https://nestidd.com/','Nestidd describes disability-focused property acquisition, leasing and maintenance for licensed care agencies and lists its Chicago office.')])
v(24).update(website='https://www.njasap.com/',notes='Correct official site is NJASAP; the union represents NetJets pilots and is distinct from the airline.',sources=[source('https://www.njasap.com/','NetJets Association of Shared Aircraft Pilots describes independent labor representation, collective-bargaining enforcement and pilot safety work.')])
v(29)['sources'].append(source('https://networklobby.org/','NETWORK distinguishes its 501(c)(4) lobbying organization from its separate 501(c)(3) educational affiliate.'))
v(31).update(website='https://www.networkforhope.org/',ownership='Nonprofit / tax-exempt',review_outcome='confirmed',description='Nonprofit organ-procurement organization coordinating organ and tissue donation and supporting donor families, formed in2024 from Kentucky Organ Donor Affiliates and LifeCenter.',notes='CMS issued an August5,2026 notice scheduling decertification for November3,2026. The notice discusses appeals and possible temporary extension; the scheduled action is not described here as already completed.',sources=[source('https://www.networkforhope.org/about-us/','Network for Hope identifies itself as an independent nonprofit formed from KODA and LifeCenter in October2024 and describes donation and family services.'),source('https://www.cms.gov/files/document/network-hope-pdf.pdf','CMS August5,2026 notice schedules termination and decertification for November3,2026, with appeal and possible temporary-transition-extension provisions.')])
v(39)['name']='Neurofibromatosis Northeast';v(39)['sources'][0]['claim']='The official Neurofibromatosis Northeast site describes regional support, education and resources for people affected by neurofibromatosis.'
v(43)['description']='Medical-device company developing and supplying the Altius nerve-treatment system for chronic post-amputation pain.'
v(56)['sources']=[source('https://www.miamilakes-fl.gov/','The official Town of Miami Lakes site verifies the local-government beneficiary of this separately preserved intermediary/client disclosure.')]
for x in p.values():
 x['sources']=[s for s in x['sources'] if s['url'] not in ['https://www.irs.gov/','https://www.sec.gov/edgar/search/']]
 if x['ownership']=='Unknown' and x['review_outcome']=='confirmed':x['review_outcome']='partial'
 x['name']=x['name'].replace('NEW ','New ').replace(' TO ',' to ').replace(' AIR ',' Air ')
for i in [0,12,14,15,19,23,53,59,79,81,91]:v(i)['featured']=True
(r/'round94-root-incremental-evidence.json').write_text(json.dumps(p,indent=2)+'\n')
