import json,pathlib
r=pathlib.Path('work/research-2026');p={}
def add(k,name,desc,website,own,sources,notes=''):
 p[k]=dict(name=name,description=desc,website=website,kind='Trade association',ownership=own,sources=[dict(url=u,claim=c) for u,c in sources],notes=notes,review_outcome='partial',featured=False)
add('423aad277a2785d5','National Office Products Alliance','Historical office-products dealer association name. Its successor, Workplace Solutions Association under ISSA, supports workplace-products dealers, manufacturers and wholesalers through policy advocacy, professional education and member services.','https://wsa.issa.com/','Unknown',[
('https://wsa.issa.com/about/','Official successor history identifies National Office Products Alliance and Office Furniture Dealers Association as predecessors to IOPFDA and describes current Workplace Solutions Association services.'),
('https://www.issa.com/industry-news/iopfda-rebrands-as-workplace-solutions-association/','ISSA explains the NOPA/OFDA convergence as IOPFDA in 2018, merger with ISSA in 2020, and subsequent WSA rebranding.')], 'Historical filing name retained; website and branding belong to documented successor WSA. Not National Oilseed Processors Association, which shares the NOPA acronym.')
add('46d7101bc83354e7','National Organization to Insure a Sound Controlled Environment','Community aviation-noise advocacy organization representing locally elected officials and communities affected by aircraft noise, with policy work on airport operations and environmental standards.','https://www.aviation-noise.org/','Nonprofit / tax-exempt',[
('https://ascent.aero/participant/national-organization-to-insure-a-sound-controlled-environment-noise/','FAA-supported university research center identifies the exact organization, links aviation-noise.org, and lists its noise-research and environmental-standard interests.'),
('https://www.govinfo.gov/content/pkg/CHRG-110hhrg38567/pdf/CHRG-110hhrg38567.pdf','2007 congressional testimony identifies NOISE as a national association of local elected officials addressing aviation noise, with Washington DC office.'),
('https://www.irs.gov/pub/irs-soi/eo2.csv','IRS master record EIN52-0983418 identifies exact National Organization to Insure a Sound Controlled Environment, Washington DC, care of Emily Tranter, subsection04 and status01.')], 'Website connection established by the university/FAA center. Historical mission supported by congressional testimony; live website fetch may be unavailable.')
(r/'round92-root-overrides.json').write_text(json.dumps(p,indent=2)+'\n')
