import json
from pathlib import Path
p=Path('work/research-2026');r=json.load(open(p/'general-round85-input.json'));f=p/'round85-root-incremental-evidence.json';d=json.load(open(f)) if f.exists() else {}
def a(i,name,desc,site,kind,own,notes,sources,out='confirmed',featured=False):
 d[r[i]['id']]=dict(name=name,description=desc,website=site,kind=kind,ownership=own,notes=notes,sources=[dict(url=u,claim=c) for u,c in sources],review_outcome=out,featured=featured)
a(0,'Metropolitan Museum of Art','The Metropolitan Museum of Art collects, preserves, studies and exhibits art from across cultures and historical periods, with museum sites in New York City.','https://www.metmuseum.org/','Art museum','Nonprofit / tax-exempt','Museum financial statements identify 501(c)(3) nonprofit status.',[('https://www.metmuseum.org/about-the-met','Official overview describes museum mission and collections.'),('https://www.metmuseum.org/-/media/Files/About%20The%20Met/Annual%20Reports/2016-2017/Annual%20Report%202016-17.pdf','Museum financial statements identify nonprofit status under Section 501(c)(3).')],featured=True)
a(1,'Great Rivers Greenway District','Great Rivers Greenway develops and maintains a regional network of greenways, trails and connected public spaces in the St. Louis region.','https://greatriversgreenway.org/','Regional parks and greenway agency','Government body','Official site identifies a voter-created public agency serving St. Louis City, St. Louis County and St. Charles County.',[('https://greatriversgreenway.org/about/','Official page explains public agency status, regional purpose and appointed board.')])
a(2,'Metropolitan Pier and Exposition Authority','The Metropolitan Pier and Exposition Authority owns Chicago convention and event properties, including McCormick Place and Wintrust Arena, and promotes conventions and exhibitions.','https://www.mpea.com/','Convention and exposition authority','Government body','Official authority page explicitly identifies a municipal corporation created by Illinois legislation.',[('https://www.mpea.com/about/','Official authority page identifies legal public status, board appointments and properties.')])
a(3,'Metropolitan Transit Authority of Harris County (METRO)','METRO provides public transportation in the Houston region, including bus, rail and other transit services for Harris County and surrounding communities.','https://www.ridemetro.org/','Public transit authority','Government body','Official authority governance page identifies appointments by Houston, Harris County and member cities.',[('https://www.ridemetro.org/about/who-we-are','Official METRO page explains regional services and government-appointed board.')])
a(4,'Metropolitan Transportation Authority (New York)','The Metropolitan Transportation Authority oversees public transportation in the New York metropolitan region, including subway, bus and commuter railroad services.','https://www.mta.info/','Public transportation authority','Government body','MTA is a public benefit corporation under New York law; this is a governmental authority, not a privately owned benefit corporation.',[('https://new.mta.info/sites/default/files/2021-09/TRB_Series_2017A_Climate_Bond_Certified_Official_Statement.pdf','MTA bond statement describes public benefit corporation status and regional transportation responsibilities.'),('https://www.osc.ny.gov/state-agencies/gfo/chapter-xvi/xvi3f-public-benefit-corporations','New York Comptroller explains MTA and related public benefit corporations.')],featured=True)
a(5,'Metropolitan Water District of Southern California','The Metropolitan Water District of Southern California supplies wholesale water to member public agencies serving communities across Southern California.','https://www.mwdh2o.com/','Regional water wholesaler','Government body','Official member page identifies a public agency and cooperative of 26 member agencies.',[('https://www.mwdh2o.com/member-agencies/','Official page states public-agency status, wholesale water role and member governance.')])
a(6,'Mewbourne Oil Company','Mewbourne Oil Company explores for, develops and produces oil and natural gas, with operations in the Permian and Anadarko basins.','https://www.mewbourne.com/','Oil and gas producer','Private company','Official news page describes continued private ownership and carries a statement that the founding family owns the company.',[('https://www.mewbourne.com/','Official company site describes oil and gas exploration and production.'),('https://www.mewbourne.com/blog/','Official anniversary summary and company-published ownership statement identify private family ownership.')])
a(7,'Mexia Economic Development Corporation','The Mexia Economic Development Corporation supports business recruitment, local expansion and community economic development in Mexia, Texas.','https://www.mexiaedc.com/','Local economic development corporation','Unknown','Official site verifies identity and activities. Exact statutory and nonprofit classification still requires primary governance records.',[('https://www.mexiaedc.com/','Official corporation site describes business development services and Mexia office.')],'partial')
a(8,'Mexichem Fluor (Orbia Fluor & Energy Materials)','Mexichem Fluor manufactures fluorine-based chemicals and materials, including refrigerants, within the business now branded Orbia Fluor & Energy Materials.','https://www.orbia-fem.com/','Fluorochemical manufacturer','Subsidiary','Official rebranding notice says Koura brand changed while Mexichem legal names remain. Exact US versus Mexican legal entity for this short filing name needs checking.',[('https://www.orbia-fem.com/media-center/brand-transition-koura-to-orbia-fluor-energy-materials','Official business notice documents Koura to Orbia brand change and unchanged legal entity name.'),('https://downloads.regulations.gov/EPA-HQ-OAR-2022-0430-0043/attachment_1.pdf','Company regulatory submission identifies Mexichem Fluor Inc. DBA Koura and US refrigerant production.')],'partial')
a(9,'Mexico Pacific','Mexico Pacific develops liquefied natural gas export infrastructure, including the Saguaro Energia facility and associated Sierra Madre Pipeline in Mexico.','https://mexicopacific.com/','Energy infrastructure developer','Unknown','Official site establishes project developer identity. Current equity ownership is not established by references to private project investment.',[('https://mexicopacific.com/','Official developer site describes the LNG facility and pipeline projects.')],'partial')
t=f.with_suffix('.tmp');t.write_text(json.dumps(d,indent=2)+'\n');t.replace(f);print(len(d),'root drafts saved')
