import json,pathlib
p=pathlib.Path('work/research-2026');r=json.load(open(p/'general-round86-input.json'));f=p/'round86-root-incremental-evidence.json';d=json.load(open(f)) if f.exists() else {}
def a(i,name,desc,site,kind,own,notes,sources,out='confirmed',featured=False):
 d[r[i]['id']]=dict(name=name,description=desc,website=site,kind=kind,ownership=own,notes=notes,sources=[dict(url=u,claim=c) for u,c in sources],review_outcome=out,featured=featured)
a(0,'Mille Lacs Band of Ojibwe','The Mille Lacs Band of Ojibwe is a sovereign tribal government providing public administration, education, health, community and natural-resource services for its members.','https://millelacsband.com/','Tribal government','Government body','Official government page identifies a federally recognized self-governing tribe, distinct from the corporate entities operating its businesses.',[('https://millelacsband.com/government/government','Official page establishes sovereign tribal government and separate governmental branches.')])
a(1,'Millenium Natural Systems LLC','Lobbying filings describe Millenium Natural Systems LLC as a nutritional supplements business.','','Nutritional supplements business','Unknown','Florida annual report establishes exact LLC name. Websites found for Colombian and Costa Rican natural-supplement businesses have not been conclusively linked to this US legal entity.',[('https://lda.gov/api/v1/clients/67233/?format=json','LDA client self-reports nutritional supplements activity.'),('https://search.sunbiz.org/Inquiry/CorporationSearch/GetDocument?aggregateId=flal-l14000052038-1cc7db3c-e44d-462e-870b-5e4c54d951d8&formatType=PDF&transactionId=l14000052038-20161978-5988-417a-9734-26f7240513e8','Florida annual report identifies exact LLC; historical record alone does not establish current ownership.')],'partial')
a(2,'Millennium Corporation','Millennium Corporation provides cybersecurity and other technical services for defense, intelligence and national-security customers.','https://millgroupinc.com/','Defense cybersecurity contractor','Unknown','Official company identity and Arlington location support match to disclosed national-security cybersecurity business. Current ownership not established.',[('https://millgroupinc.com/','Official company site describes government and defense technical services.'),('https://millgroupinc.com/intelligence-community/','Official intelligence-community page describes cyber protection and Arlington office.')],'partial')
a(3,'Millennium Health','Millennium Health operates a specialty laboratory providing medication monitoring and drug testing, with data analysis to help clinicians understand patterns of substance use.','https://www.millenniumhealth.com/','Clinical laboratory','Unknown','Official laboratory page establishes activities. Current corporate ownership requires additional evidence.',[('https://www.millenniumhealth.com/about-us/','Official overview identifies specialty laboratory, medication monitoring and drug testing.')],'partial')
a(4,'Millennium Management LLC','Millennium Management is an alternative investment firm managing investment strategies across asset classes, industries and geographic markets.','https://www.mlp.com/','Investment management firm','Unknown','Official privacy policy names Millennium Management LLC. Current equity ownership not established by private-fund management alone.',[('https://www.mlp.com/','Official site identifies alternative investment firm.'),('https://www.mlp.com/privacy-policy/','Official privacy policy identifies Millennium Management LLC and controlled entities.')],'partial',True)
a(5,'Milliken & Company','Milliken & Company manufactures materials and chemicals used in textiles, flooring, healthcare products, coatings and other industrial applications.','https://www.milliken.com/','Diversified materials manufacturer','Private company','Official leadership page explicitly identifies private ownership.',[('https://www.milliken.com/en-us/about-us/leadership','Official company leadership page identifies privately owned company and main manufacturing businesses.')])
a(6,'MilliporeSigma','MilliporeSigma supplies laboratory and life-science products and services, operating as the US and Canadian name for the life-science business of Merck KGaA of Darmstadt, Germany.','https://www.sigmaaldrich.com/US/en','Life-science business brand','Not applicable','Business brand rather than a separately established legal issuer; distinguish German Merck KGaA from US Merck & Co.',[('https://www.merckmillipore.com/KR/ko/20150908_205416','Official About page identifies MilliporeSigma as the US and Canada name of German Merck life-science business.'),('https://b2b.sigmaaldrich.com/US/en/life-science/legal/product-licenses/cell-line-restricted-use-agreement','Official product terms explicitly identify MilliporeSigma as life-science business of Merck KGaA.')])
a(7,'Millsapps, Ballinger & Associates','Millsapps, Ballinger & Associates develops software and technology services that help organizations collect and use data, including Salesforce-based applications.','https://mbaoutcome.com/','Software and technology services','Unknown','Official site names current legal entity as Inc.; original lobbying label is LLC. Business match is supported, but legal conversion or relationship requires verification.',[('https://mbaoutcome.com/about/','Official About page describes technology company and names current legal entity as Inc.'),('https://mbaoutcome.com/capesheet/','Official capability sheet describes software-as-a-service products.')],'partial')
a(8,"Milo's Tea Company", "Milo's Tea Company manufactures and distributes ready-to-drink iced teas, lemonades and other beverages.",'https://drinkmilos.com/','Beverage manufacturer','Private company','Official company history identifies family ownership and certified women-owned business status.',[('https://drinkmilos.com/our-sweet-story/','Official company history establishes family-owned beverage company.'),('https://drinkmilos.com/milos-opens-fourth-site/','Official announcement names exact Milo\'s Tea Company Inc and manufacturing business.')],featured=True)
a(9,'Milwaukee County','Milwaukee County provides local government services in Wisconsin, including county roads, parks, public administration and other county programs.','https://county.milwaukee.gov/','County government','Government body','County is distinct from the City of Milwaukee.',[('https://county.milwaukee.gov/EN/About-Us','Official county page describes local government status and county services.')])
a(10,'Milwaukee Metropolitan Sewerage District','The Milwaukee Metropolitan Sewerage District provides wastewater reclamation, water-quality protection and flood-management services in the Greater Milwaukee region.','https://www.mmsd.com/','Regional wastewater and flood-management agency','Government body','Official page explicitly identifies a regional government agency established by state law.',[('https://www.mmsd.com/about-us','Official district page establishes governmental status, water services and commissioner governance.')])
a(11,'MIMEDX Group, Inc.','MIMEDX develops and supplies placental tissue-based products for wound care and surgical applications.','https://www.mimedx.com/','Wound-care biologics company','Public company','Official investor FAQ identifies Nasdaq ticker MDXG. Historical delisting material is not current listing evidence.',[('https://www.mimedx.com/','Official company website describes placental biologics and wound-care products.'),('https://investors.mimedx.com/investor-faqs','Official investor FAQ identifies MIMEDX Group Inc common stock on Nasdaq as MDXG.')])
f.write_text(json.dumps(d,indent=2)+'\n');print(len(d),'root drafts saved')
