import json,pathlib,gzip
r=pathlib.Path('work/research-2026');cs={c['id']:c for c in json.load(open(r/'general-round15-b-input.json'))};f=r/'general-round15-b-root-partial.json';p=json.load(open(f)) if f.exists() else {}
def add(k,desc,kind,own,site,url,claim):
 c=cs[k];v=dict(c.get('profile',{}));v.update(name=c['name'],description=desc,kind=kind,ownership=own,website=site,status='sourced',review_outcome='partial' if own=='Unknown' else 'confirmed',identity_evidence='Official organization source matches disclosed name and activity.',notes='Individually researched using primary organization evidence; filing name retained.'+(' Ownership not established by reviewed sources.' if own=='Unknown' else ''),as_of='2026-09-05',checked_at='2026-09-05',featured=False,legal_form='',logo_url='',logo_kind='',logo_source_url='');v['sources']=v.get('sources',[])
 if not v['sources']:
  rid=json.load(gzip.open(f'lobbying-map/public/data/reports/{k[:2]}.json.gz'))[k][0]['id'];v['sources']=[{'url':f'https://lda.gov/filings/public/filing/{rid}/print/','label':'Lobbying disclosure','claim':'Original disclosed client name.'}]
 v['sources'].append({'url':url,'label':'Official organization evidence','claim':claim});p[k]=v
add('fa208be2f8a52c39','Manufactures aluminum sheet, plate and extrusions and architectural products for aerospace, automotive, packaging, industrial and construction markets.','Company','Private company','https://www.arconic.com/','https://www.arconic.com/-/arconic-completes-transaction-with-apollo-funds','Arconic announced completion of its acquisition by Apollo Funds in August 2023 and transition from a publicly traded company. Current company site describes ongoing aluminum-products operations.')
p['fa208be2f8a52c39']['review_outcome']='partial'
p['fa208be2f8a52c39']['notes']='Private classification supported by completed 2023 acquisition; current ownership structure has not been refreshed. Company activity checked against current official about page.'
p['fa208be2f8a52c39']['sources'].append({'url':'https://www.arconic.com/about-us','label':'Current official business description','claim':'Current official page identifies aluminum sheet, plate, extrusions and architectural products for multiple industrial markets.'})
add('345dcada4d62a356','Alaska Native corporation owned by Iñupiaq shareholders, with businesses in government contracting, industrial services, petroleum, energy support and construction, as well as North Slope land and resources.','Alaska Native corporation','Private company','https://www.asrc.com/','https://www.asrc.com/about/','ASRC explicitly identifies itself as a private, for-profit corporation owned by Iñupiaq shareholders and lists its six business areas.')
add('f3e8f8f6717f216c','Manufactures specialty chemicals, polymer technologies, resins and engineered surface materials used in construction, industrial products and other markets.','Company','Unknown','https://www.arclin.com/','https://www.arclin.com/about/','Arclin official company profile describes its materials-science business and specialty manufacturing capabilities.')
add('165341e209155d3d','Provides engineering, building inspections, energy-efficiency compliance, HVAC design and related services for professional homebuilders and developers.','Company','Unknown','https://arcxis.com/','https://arcxis.com/','ARCXIS official site describes residential construction inspection and engineering services, serving builders, contractors and developers.')
add('8cefa8a466f9bcb0','Mills flour and supplies grain-based ingredients and specialty grain products to food manufacturers, bakeries and other food businesses.','Company','Unknown','https://www.ardentmills.com/','https://www.ardentmills.com/','Ardent Mills official site describes flour milling, grain ingredients and food-industry products.')
f.write_text(json.dumps(p,indent=2)+'\n');print(len(p))
