import json,pathlib,gzip
r=pathlib.Path('work/research-2026');cs={c['id']:c for c in json.load(open(r/'general-round16-b-input.json'))};f=r/'general-round16-b-root-partial.json';p=json.load(open(f)) if f.exists() else {}
def add(k,desc,kind,own,site,url,claim):
 c=cs[k];v=dict(c.get('profile',{}));v.update(name=c['name'],description=desc,kind=kind,ownership=own,website=site,status='sourced',review_outcome='partial' if own=='Unknown' else 'confirmed',identity_evidence='Official organization source matches disclosed name and activity.',notes='Individually researched using primary organization evidence; filing name retained.'+(' Ownership not established by reviewed sources.' if own=='Unknown' else ''),as_of='2026-09-05',checked_at='2026-09-05',featured=False,legal_form='',logo_url='',logo_kind='',logo_source_url='');v['sources']=v.get('sources',[])
 if not v['sources']:
  rid=json.load(gzip.open(f'lobbying-map/public/data/reports/{k[:2]}.json.gz'))[k][0]['id'];v['sources']=[{'url':f'https://lda.gov/filings/public/filing/{rid}/print/','label':'Lobbying disclosure','claim':'Original disclosed client name.'}]
 v['sources'].append({'url':url,'label':'Official organization evidence','claim':claim});p[k]=v
add('8513c99ebb94ab0f','Provides clinical diagnostic reference-laboratory testing, pathology expertise and laboratory consulting to hospitals and health systems.','Diagnostic laboratory','Nonprofit / tax-exempt','https://www.aruplab.com/','https://www.aruplab.com/about','ARUP identifies itself as a national academic reference laboratory and nonprofit enterprise of the University of Utah and its Department of Pathology.')
add('6c70e0c0bf9c3c5d','Manages copyright licensing for visual artists and estates, helping museums, publishers, filmmakers and businesses obtain permissions to reproduce artwork.','Copyright licensing organization','Unknown','https://arsny.com/','https://arsny.com/','Artists Rights Society official site lists artwork licensing services, artist representation and rights advocacy.')
add('051885166185cd24','Provides agricultural data, agronomic support and supply-chain programs that help farmers adopt regenerative practices and companies measure environmental outcomes.','Company','Unknown','https://arva.com/','https://arva.com/','Arva Intelligence official site redirects to arva.com and describes farmer programs, agricultural supply chains and environmental measurement services.')
f.write_text(json.dumps(p,indent=2)+'\n');print(len(p))
