import json,pathlib
w=pathlib.Path('work/research-2026');b=w/'confirmed-logo-batch5-sept12';p=w/'reviewed.json';d=json.loads(p.read_text());rr=json.loads((b/'logo-results.json').read_text());ok=[r for r in rr if r['status']=='downloaded'];reviews=json.loads((b/'root-visual-review.json').read_text());assert len(reviews)==len(ok)==326;assert all(r['index']==i and r['id']==ok[i]['id'] for i,r in enumerate(reviews));exclude={r['index'] for r in reviews if r['decision']!='approved'};dark={r['index'] for r in reviews if r['background']=='dark'};before={};approved={};rejected=[]
for n,r in enumerate(ok):
 if n in exclude:
  rejected.append({**r,'review':'Rejected after visual inspection: sponsor, program, award, photo, unreadable or different-entity asset.'});continue
 k=r['id'];v=d[k];assert v.get('logo_kind')!='logo';before[k]=json.loads(json.dumps(v));v.update(logo_url=r['url'],logo_source_url=r['source'],logo_status='official_site_asset',logo_kind='logo',logo_background='dark' if n in dark else 'light',checked_at='2026-09-12');v['sources'].append({'url':r['source'],'label':'Official website logo visually reviewed','claim':'Official website image retrieved and visually inspected September 12, 2026 against organization branding; background selected for readability. Asset: '+r['url']});approved[k]={f:v[f] for f in ['logo_url','logo_source_url','logo_background']}
(b/'approved-before.json').write_text(json.dumps(before,indent=2)+'\n');(b/'approved.json').write_text(json.dumps(approved,indent=2)+'\n');(b/'rejected-candidates.json').write_text(json.dumps(rejected,indent=2)+'\n');p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');pathlib.Path('lobbying-map/research/reviewed-2026.json').write_text(json.dumps(d,ensure_ascii=False)+'\n');pathlib.Path('outputs/2026-research-trial/profiles.json').write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');results=[];lm={r['id']:r for r in rr}
for r in json.loads((b/'website-results.json').read_text()):
 i=r['id'];status='verified_logo_added' if i in approved else 'wrong_or_ambiguous_logo_candidate' if any(z['id']==i for z in rejected) else 'page_retrieval_failed' if r['status']!='fetched' else 'asset_retrieval_failed' if lm.get(i,{}).get('status')=='error' else 'needs_better_asset_extraction';results.append({'id':i,'name':r['name'],'status':status})
(b/'per-organization-results.json').write_text(json.dumps(results,indent=2)+'\n');f=w/'publication.json';z=json.loads(f.read_text());z.update(local_changes_pending=True,pending_change_summary='235 visually verified official logos and 32 registry identity confirmations.');f.write_text(json.dumps(z,indent=2)+'\n');print('Logos saved',len(approved),'outcomes saved',len(results))
